[BE] feat: 관리자 티켓 발급 구현(#116)
woowacourse-teams/2023-festa-go pull request #134
Opened 2023-07-27 08:27 UTC by BGuga

## 📌 관련 이슈

- closed: #117

2023-07-27 08:44 UTC, seokjin8678 requested changes
간단한 리뷰 남겼습니다!

2023-07-27 08:44 UTC, seokjin8678 commented on backend/src/test/java/com/festago/presentation/AdminControllerTest.java
> +            .andExpect(jsonPath("$.totalAmount").value(totalAmount));
jsonPath를 사용하신 이유가 있나요?

2023-07-27 10:38 UTC, BGuga commented on backend/src/test/java/com/festago/presentation/AdminControllerTest.java
> +            .andExpect(jsonPath("$.totalAmount").value(totalAmount));
jsonPath 로 하나의 흐름을 보고 싶다는 취지였는데
변경시 직접 값들을 다 바꿔줘야한다는 점에 objectMapper 를 사용하도록 변경했습니다!

2023-07-27 12:00 UTC, xxeol2 requested changes
수고 많으셨어요 푸우!!!
티켓의 입장시간이 Stage startTime 이후인 경우 / 혹은 너무 이른 경우 (무대 시작 시간은 7/27인데 입장 시간은 7/26이라던가)에 대한 도메인 단의 validate 처리가 필요할 것 같아요.
추가적으로 티켓 수량의 MIN / MAX 도 정해주면 좋을 것 같습니다! (적어도 0장 이하는 절대 안되게)

2023-07-28 02:16 UTC, xxeol2 commented on backend/src/test/java/com/festago/application/TicketServiceTest.java
> +class TicketServiceTest extends ApplicationTest {
Service 테스트 어플리케이션 테스트로 하신 이유가 있나요 ?!
EntryServiceTest는 Mock으로 진행했어서요!

2023-07-28 03:05 UTC, seokjin8678 approved these changes
고생하셨습니다!

2023-07-28 03:06 UTC, xxeol2 approved these changes

2023-07-28 03:06 UTC, xxeol2 commented on backend/src/test/java/com/festago/application/TicketServiceTest.java
> +class TicketServiceTest extends ApplicationTest {
- #139

2023-07-28 03:16 UTC, carsago approved these changes

2023-07-28 03:20 UTC, merged