[BE] fix: 티켓의 입장시간과 요청시간이 일치하는 경우 입장이 불가한 버그 수정 (#136)
woowacourse-teams/2023-festa-go pull request #137
Opened 2023-07-27 13:23 UTC by xxeol2

## 📌 관련 이슈

- closed: #136

2023-07-27 13:35 UTC, seokjin8678 commented on backend/src/main/java/com/festago/domain/Ticket.java
> +            && time.isBefore(entryTime.plusHours(ENTRY_LIMIT_HOUR));
LocalDateTime.plusDays(1)과 LocalDateTime.pluseHours(24)는 동일한 결과를 보장하는데, 시간으로 변경한 이유가 있나요?

2023-07-27 13:36 UTC, seokjin8678 requested changes
간단한 코멘트 남겼습니다!

2023-07-27 13:41 UTC, xxeol2 commented on backend/src/main/java/com/festago/domain/Ticket.java
> +            && time.isBefore(entryTime.plusHours(ENTRY_LIMIT_HOUR));
입장 유효기간을 상수로 정의한 이유중 하나가 "유효기간이 수정될 수 있다"라고 생각하는데요.
유효기간이 일단위로 바뀔 가능성보다 시간단위로 바뀔 가능성이 더 크다고 생각해서 변경했어요! (1일 → 2일 보다 24시간 → 10시간) 
시간단위가 더 자연스러워보이기도 했구요

근데 이건 개인적인 의견이라, 팀원들이 `ENTRY_LIMIT_DAY`로 관리하는게 더 자연스럽다 생각하시면 다시 수정하도록 하겠습니다!!

2023-07-27 13:44 UTC, seokjin8678 commented on backend/src/main/java/com/festago/domain/Ticket.java
> +            && time.isBefore(entryTime.plusHours(ENTRY_LIMIT_HOUR));
저도 시간으로 관리하는게 더 좋다고 생각되네요!

2023-07-27 13:45 UTC, seokjin8678 approved these changes
고생하셨습니다!

2023-07-28 03:20 UTC, carsago approved these changes

2023-07-28 03:20 UTC, carsago commented on backend/src/main/java/com/festago/domain/Ticket.java
> +            && time.isBefore(entryTime.plusHours(ENTRY_LIMIT_HOUR));
애쉬 코멘트처럼 시간으로 관리하는게 더 좋다고 느껴지네요

2023-07-28 03:20 UTC, carsago commented on backend/src/test/java/com/festago/domain/TicketTest.java
> +    @ValueSource(strings = {"2023-07-28T17:59:59", "2023-07-27T18:00:00"})
굿

2023-07-28 03:28 UTC, BGuga approved these changes

2023-07-28 03:28 UTC, BGuga commented on backend/src/main/java/com/festago/domain/Ticket.java
> +            && time.isBefore(entryTime.plusHours(ENTRY_LIMIT_HOUR));
저도 시간으로 관리되는 것이 좋아보여요!
하지만 이 부분이 자주 변경될 것 같진 않아 보이긴합니다!!
수고하셨습니다 👍

2023-07-28 04:25 UTC, merged