[BE] feat: 티켓 목록 조회 API와 예매 목록 조회 API 분리 (#79)
woowacourse-teams/2023-festa-go pull request #173
Opened 2023-08-01 07:50 UTC by xxeol2

## 📌 관련 이슈

- closed: #79 

## ✨ PR 세부 내용

### 🎟️ 티켓 목록 (GET /member-tickets/current)
- 티켓은 입장시간 12시간 이전부터 노출됩니다.
- 티켓은 입장시간 24시간 이후까지 노출됩니다.
- 티켓은 (활성화) -> (비활성화) 순으로 정렬됩니다.
- (활성화) 및 (비활성화) 내에서는 입장시간이 현재 시간과 가까운 순으로 정렬됩니다.
```
현재시간) 5시

[활성화] 4시 입장
[활성화] 3시 입장
[비활성화] 6시 입장
[비활성화] 7시 입장
```
<img src="https://github.com/woowacourse-teams/2023-festa-go/assets/71129059/44197483-9f16-4897-9acf-7a9c6039f56e" width = 300>

<br>

### 🎟️ 예매 목록 (GET /member-tickets)
- 티켓은 무대 시작시간이 최신순으로 정렬됩니다.
<img src="https://github.com/woowacourse-teams/2023-festa-go/assets/71129059/41f6011c-e429-4824-b35b-80e588219c08" width = 300>

---
### 🧨 코드리뷰 부탁

226db9a5d072e809ddbdd7dbf0c2231f6518b7d8 해당 커밋에서 기존에 Map으로 반환하던 메서드를 List를 반환하도록 수정했습니다.
[전자] stream도는 횟수가 적습니다. 하지만 가독성이 좋지 않습니다.
[후자] stream을 2번 더 돕니다. 하지만 가독성이 좋습니다.

한 멤버의 현재 활성화된 티켓 개수(`currentMemberTickets`) 사이즈가 크지 않아, stream을 2번 더 돈다고 큰 성능상의 차이가 없기에 가독성을 챙기는게 좋을 것 같다는 @BGuga 의 의견을 반영했습니다!
해당 부분 코드리뷰 부탁드립니다 🙇🏻‍♀️

2023-08-01 07:57 UTC, seokjin8678 approved these changes
머지, 진행시켜

2023-08-01 08:11 UTC, BGuga reviewed
수고하셨습니다!

2023-08-01 08:11 UTC, BGuga commented on backend/src/main/java/com/festago/application/MemberTicketService.java
> +        return mergedMemberTickets;
```
List<MemberTicket> mergedMemberTickets = new ArrayList<(memberTickets1.size() + memberTickets2.size());
mergedMemberTickets.addAll(memberTickets1);
mergedMemberTickets.addAll(memberTickets2);
return mergedMemberTickets;
```
요거
```
return Stream.concat(memberTickets1.stream(), memberTickets2.stream())
    .toList();
```
요건 어떤가요??

2023-08-01 08:14 UTC, xxeol2 commented on backend/src/main/java/com/festago/application/MemberTicketService.java
> +        return mergedMemberTickets;
후자가 가독성이 더 좋네요!
반영했습니다!

2023-08-01 08:14 UTC, BGuga approved these changes

2023-08-01 12:25 UTC, seokjin8678 commented on backend/src/main/java/com/festago/application/MemberTicketService.java
> +    }
해당 로직은 64번째 라인의 로직이 실행될 때, 여러 번 실행될 것 같은데 `LocalDateTime.now()`를 매번 생성하여 인스턴스를 만드는 것 보다, currentTime 로직을 파라미터로 받아도 좋을 것 같네요!
또한, `toMillis()` 메서드 또한 다음과 같이 코드가 작성되어 있네요!
```java
public long toMillis() {
    long tempSeconds = this.seconds;
    long tempNanos = (long)this.nanos;
    if (tempSeconds < 0L) {
        ++tempSeconds;
        tempNanos -= 1000000000L;
    }

    long millis = Math.multiplyExact(tempSeconds, 1000);
    millis = Math.addExact(millis, tempNanos / 1000000L);
    return millis;
}
```
단순히 시간을 구할 목적이면 `getSeconds()` 메서드를 사용하는 것은 어떠신가요?

2023-08-01 12:34 UTC, seokjin8678 requested changes
사소한 부분에 대해 추가 리뷰 남겼습니다!

2023-08-01 12:39 UTC, seokjin8678 commented on backend/src/main/java/com/festago/application/MemberTicketService.java
> +    }
또한 메서드 위치도 `filterCurrentMemberTickets` 메서드 밑으로 이동시키면 좋을 것 같네요!

2023-08-01 12:47 UTC, seokjin8678 commented on backend/src/main/java/com/festago/application/MemberTicketService.java
> +            .sorted(comparing(memberTicket -> memberTicket.getStage().getStartTime()))
공연을 조회하고, 시작 시간을 조회하는 것 보다, 티켓의 입장 시간을 기준으로 정렬하는 것은 어떤가요?

첫 번째 이유로, 공연을 조회할 때 SELECT 쿼리를 한 번 더 날려야 한다는 이유도 있고 (fetch join을 사용하더라도 join이 발생)

두 번째 이유로, 입장 시간과 무대 시작 시간이 크게 차이가 날 것 같진 않아서요! (정말 특별한 경우가 아니고서 공연의 시작 시간과 입장 시간이 크게 차이 나지 않으니까요!)
```suggestion
            .sorted(comparing(MemberTicket::getEntryTime))
```

2023-08-01 12:50 UTC, carsago commented on backend/src/main/java/com/festago/application/MemberTicketService.java
> +                                                  List<MemberTicket> memberTickets2) {
더 직관적이게 변수명을 ```activateMemberTickets, pendingMemberTickets``` 으로 바꾸는건 어떨까요?

2023-08-01 12:50 UTC, carsago commented on backend/src/main/java/com/festago/application/MemberTicketService.java
> +    }
이거 now 생성안하고 ```filterCurrentMemberTickets``` 메소드에서 인자로 받은거 넘겨서 써도 상관없지않나요 ?? method reference 안되는건 기분 나쁘지만..

2023-08-01 13:33 UTC, seokjin8678 commented
```java
@Transactional(readOnly = true)
public CurrentMemberTicketsResponse findCurrent(Long memberId) {
    List<MemberTicket> memberTickets = memberTicketRepository.findAllByOwnerId(memberId);
    LocalDateTime currentTime = LocalDateTime.now();
    List<MemberTicket> currentMemberTickets = filterCurrentMemberTickets(memberTickets, currentTime);
    return CurrentMemberTicketsResponse.from(currentMemberTickets);
}

private List<MemberTicket> filterCurrentMemberTickets(List<MemberTicket> memberTickets,
                                                      LocalDateTime currentTime) {
    return memberTickets.stream()
        .filter(memberTicket -> memberTicket.isPending(currentTime) || memberTicket.canEntry(currentTime))
        .sorted(getCurrentMemberComparator(currentTime))
        .toList();
}

private Comparator<MemberTicket> getCurrentMemberComparator(LocalDateTime currentTime) {
    return comparing((MemberTicket m) -> m.isPending(currentTime))
        .thenComparing(memberTicket -> memberTicket.calculateTimeGap(currentTime));
}
```

```java
class MemberTicket {
    ...
    public Duration calculateTimeGap(LocalDateTime time) {
        return Duration.between(entryTime, time).abs();
    }
    ...
}
```

MemberTicketService의 findCurrent 메서드를 다음과 같이 줄일 수 있을 것 같네요!
getCurrentMemberComparator를 메서드로 추출한 이유는 `thenComparing` 에서 자바 컴파일러의 한계로 추론을 못해줘서 그렇습니다. 😂

2023-08-02 00:50 UTC, xxeol2 commented on backend/src/main/java/com/festago/application/MemberTicketService.java
> +            .sorted(comparing(memberTicket -> memberTicket.getStage().getStartTime()))
DTO에 축제 및 공연 내용이 함께 조회되어서 이 때 stage SELECT쿼리가 날아가나 DTO 변환시 날아가나 SELECT 횟수는 똑같을 것 같아요!!

2023-08-02 00:52 UTC, xxeol2 commented on backend/src/main/java/com/festago/application/MemberTicketService.java
> +    }
위의 메서드는 currentTime 사용하게 리팩터링해놓고 이친구 빼먹었네요 ..
꼼꼼하게 봐주셔서 감사해용

2023-08-02 01:08 UTC, xxeol2 commented
https://github.com/woowacourse-teams/2023-festa-go/pull/173#issuecomment-1660337793

해당 코멘트 반영했습니다! 확실히 훨씬 더 간단하네요 👍🙇🏻‍♀️
다만, MemberTicket 안에 calculateTimeGap을 두는 대신, Service에 뒀습니다.
calculateTimeGap는 단순히 뷰에서 정렬하기만을 위한 메서드라고 생각해서 그렇게 했어요!
(다른 메서드들과 달리 전혀 도메인 로직처럼 느껴지지 않아서, 도메인에 들어가는게 어색하게 느껴졌어요.)

이에 대해서 어떻게 생각하시는지 궁금합니다~~

2023-08-02 01:21 UTC, seokjin8678 commented on backend/src/main/java/com/festago/application/MemberTicketService.java
> +            .sorted(comparing(memberTicket -> memberTicket.getStage().getStartTime()))
1번, 3번 중 고르면 될 것 같은데.. 입장 시간이 가까운 순서로 해주는게 좋아 보이네요

2023-08-02 01:22 UTC, seokjin8678 commented
훨씬 더 좋아보이네요!

2023-08-02 01:22 UTC, seokjin8678 approved these changes

2023-08-02 01:24 UTC, xxeol2 commented on backend/src/main/java/com/festago/application/MemberTicketService.java
> +            .sorted(comparing(memberTicket -> memberTicket.getStage().getStartTime()))
전 3번에 한표! 영화관같은거 생각해도 예매 내역은 보통 영화상영시간보다 예매시간 기준으로 정렬되는 것 같아요

2023-08-02 01:24 UTC, carsago approved these changes
수정 코드 확인했습니다. 훨씬 깔끔하고 이해하기 쉽네요.

2023-08-02 01:26 UTC, BGuga commented on backend/src/main/java/com/festago/application/MemberTicketService.java
> +            .sorted(comparing(memberTicket -> memberTicket.getStage().getStartTime()))
어차피 무대시간과 입장시간이 큰 차이가 없기 때문에 입장 시간으로 정리해주는 것이 좀 더 좋아보인요!! 1번 하겠습니다.

2023-08-02 01:27 UTC, carsago commented on backend/src/main/java/com/festago/application/MemberTicketService.java
> +            .sorted(comparing(memberTicket -> memberTicket.getStage().getStartTime()))
전 1번에 마음 갑니다. 유사 서비스를 챙겨본 건 아니지만, 예매는 일찍 했지만, 몇주뒤에 열릴 공연이 더 빨리 조회되면 애매할 거 같아요.

2023-08-02 01:41 UTC, merged