[BE] feat: 카카오 인증을 통한 OAuth 회원가입 및 로그인 기능 추가 (#111)
woowacourse-teams/2023-festa-go pull request #175
Opened 2023-08-01 08:44 UTC by carsago

## 📌 관련 이슈

- closed: #111

2023-08-01 08:46 UTC, carsago commented on backend/src/main/java/com/festago/auth/dto/KakaoAccessTokenResponse.java
> +    @JsonProperty("refresh_token_expires_in") Integer refreshTokenExpiresIn
```@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)``` 을 활용하면 코드가 간소화되는데 
레코드 타입에 안먹히는 문제가 있습니다. 다른 팀은 해결한건지.. 추후에 좀 알아봐야 할듯 합니다.

https://github.com/FasterXML/jackson-databind/issues/3102

2023-08-01 11:57 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/infrastructure/KakaoOAuth2Client.java
> +
`@Override` 어노테이션이 누락됐네요!

2023-08-01 11:57 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/infrastructure/KakaoOAuth2Client.java
> +
마찬가지로, `@Override` 어노테이션 누락입니다!

2023-08-01 12:12 UTC, BGuga reviewed
고생 많으셨습니다!!

2023-08-01 12:12 UTC, BGuga commented on backend/src/test/java/com/festago/auth/infrastructure/KakaoOAuth2ClientTest.java
> +
인증 테스트에서 외부 Api 를 mocking 해서 사용하셨네요!! 👍
반영하지 않아도 되지만 해당 부분을 stubing 해서 사용할 수도 있습니다!!

<img width="600" alt="image" src="https://github.com/woowacourse-teams/2023-festa-go/assets/103228463/a4fcdf28-a35f-46c2-ae70-52e485f2fa41">

1. 해당 부분의 requestURI 를 apllication.properties 에서 가져오도록 한다. @Value("festago.kakao.url.access-token")
2. application-test.properties 에 요청 uri 를 localhost:8080/gihub/acessToken 로 설정한다.
3. @Profile("test") 인 GihubTestController 를 구현하여서 Component 로 등록한다.
4. GihubTestController 에 @PostMapping("/github/accessToken") 에 매핑된 메서드를 만든 후 임의의 token Value를 반환한다.

2023-08-01 14:23 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/dto/KakaoUserInfo.java
> +    @JsonProperty(value = "kakao_account") KakaoAccount kakaoAccount
카카오에서 제공하는 JSON 포맷이 다음과 같이 날아옵니다.
```json
"id": 123456,
"kakao_account": {
    "profile" : {
        "nickname": "glen",
        "thumbnail_image_url": "https://image.com/image.png"
    }
}
```
해당 KakaoAccount 클래스를 외부 클래스로 만들어도 되지만, 해당 응답에서만 사용되므로 내부 클래스로 만들었습니다!

2023-08-01 14:25 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/infrastructure/JwtAuthProvider.java
> +            .signWith(key, SignatureAlgorithm.HS256)
상수 클래스로 분리할 지, JWT에서 사용할 시간은 밀리초 단위를 사용할 지 고려를 해봐야겠네요!

2023-08-01 14:30 UTC, seokjin8678 commented on backend/src/test/java/com/festago/auth/infrastructure/KakaoOAuth2ClientTest.java
> +
가짜 컨트롤러를 만들수도 있겠네요!
그렇다면 저희의 OAuth2 클라이언트를 구현하는 걸까요?

2023-08-01 21:24 UTC, xxeol2 reviewed
수고하셨습니다!! 🫡

2023-08-01 21:30 UTC, xxeol2 requested changes
하나만더..!

2023-08-01 21:30 UTC, xxeol2 commented on backend/src/main/java/com/festago/auth/presentation/AuthController.java
> +@RequestMapping("/login")
/auth로 수정하고, login url을 /auth/login 으로 하는거 어떨까요?
AuthController에 로그인말고 다른 메서드들이 추가적으로 등록될수도 있을것같아요!

2023-08-01 21:38 UTC, xxeol2 commented on backend/src/main/java/com/festago/auth/infrastructure/KakaoOAuth2Client.java
> +            return kakaoUserInfo.toUserInfo();
혹시 사용자가 닉네임/프로필사진 제공을 동의하지않는 경우는 없나요?
가입을 위해서는 해당 정보들을 필수적으로 제공해야하나요?

2023-08-01 21:43 UTC, xxeol2 commented on backend/src/main/java/com/festago/auth/application/AuthService.java
> +            .orElseGet(() -> memberRepository.save(userInfo.toMember()));
+) 해당 로직에 대한 테스트코드를 작성해보는게 어떨까요?!

2023-08-01 21:45 UTC, xxeol2 commented on backend/src/main/java/com/festago/auth/dto/LoginResponse.java
> +    String nickname
신규회원인지 여부를 함께 보내주는건 어떨까요?
신규회원과 기존회원 클라쪽에서 띄워주는 문구또는 화면이 다를 수 있을 것 같아요!
ex) "~~님 로그인 완료“, ”~님 회원가입 완료“

2023-08-01 22:08 UTC, xxeol2 commented on backend/src/main/java/com/festago/auth/infrastructure/KakaoOAuth2Client.java
> +            return errorCode.equals("KOE320");
Objects.equals로 비교해주는거 어떤가요?
만약 카카오 서버가 죽는경우나 다른 원인으로 인래 KakaoOauth2Error 형태가 아닌 에러가 터질 경우 errorCode가 null일 것 같네요.
(아니면 아예 e.getResponseBodyAs에서 터지려나요?)

2023-08-01 23:27 UTC, xxeol2 commented on backend/src/main/java/com/festago/auth/application/AuthService.java
> +        UserInfo userInfo = oAuth2Client.getUserInfo(accessToken);
Request로 code와 함께 socialType도 함께 전달받으면 좋을 것 같아요!
SocialType으로 enum을 정의했다는건 여러 소셜 클라이언트를 활용가능하도록 고려했다는 뜻인데
지금은 무조건 KakaoLogin으로 고정하고 있는 느낌이에요
따라서 Request로 SocialType을 받은 후, 해당 소셜타입에 맞는 OAuth2Client 컴포넌트를 활용하는게 어떨까 라는 생각이 드네요

2023-08-02 01:49 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/infrastructure/KakaoOAuth2Client.java
> +                .getBody();
AccessToken을 구할 때는 해당 파라미터 타입에 HttpEntity 타입을 사용하면 401 코드를 반환하고,
UserInfo를 구할 때 해당 파라미터 타입에 HttpEntity 타입을 사용하지 않으면 401 코드를 반환해서 그렇습니다. 😂

2023-08-02 01:49 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/presentation/AuthController.java
> +@RequestMapping("/login")
`/auth/oauth2/kakao` 같이 해도 좋을 것 같네요!

2023-08-02 01:51 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/infrastructure/KakaoOAuth2Client.java
> +            return kakaoUserInfo.toUserInfo();
닉네임은 필수 제공이고, 프로필 사진은 선택 제공입니다!
프로필 사진이 null이 될 수 있으니 이걸 핸들링 해야겠네요!

2023-08-02 01:54 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/dto/LoginResponse.java
> +    String nickname
해당 기능은 새로운 이슈를 만들면 좋을 것 같네요!

2023-08-02 02:11 UTC, xxeol2 commented on backend/src/main/java/com/festago/auth/presentation/AuthController.java
> +@RequestMapping("/login")
저는 개인적으로 아예 url을 분리하는것보다 request로 구분하는게 좋을것같다는 생각이 들어요!
(이유: Service 한 메서드 재활용하기 때문에 Controller 메서드도 하나로 통일하는게 좋지 않을까?)

2023-08-02 11:51 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/domain/OAuth2Clients.java
> +    }
빌더 패턴을 사용하지 않으면 생성자로 Map 구현체를 넣어줘야 하는데, EnumMap 말고 다른 Map 구현체를 넣을 수 있기도 하고, 제약을 만들어 잘못된 설정을 하지 않게 했습니다!

2023-08-02 11:52 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/infrastructure/KakaoOAuth2AccessTokenErrorHandler.java
> +            is5xxError(statusCode);
안그래도 네이밍을 무엇을 해야할까 고민을 했는데, 좋은 네이밍이 있었군요 😂

2023-08-02 12:02 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/infrastructure/KakaoOAuth2AccessTokenErrorHandler.java
> +        if (errorResponse != null && errorResponse.isErrorCodeKOE320()) {
에러 코드는 해당 Response가 가지고 있기 때문에 메시지를 보내는 방법으로 구현해봤습니다!

2023-08-02 12:03 UTC, xxeol2 commented on backend/src/main/java/com/festago/auth/domain/OAuth2Clients.java
> +    }
역시 꼼꼼글렌

2023-08-02 12:04 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/infrastructure/KakaoOAuth2UserInfoErrorHandler.java
> +    }
꼼꼼하게 리뷰해주셨군요 😂
이 부분은 놓친 것 같네요!

2023-08-02 12:30 UTC, xxeol2 approved these changes
수고많으셨습니다!! 🫡🫡🫡

2023-08-05 17:34 UTC, BGuga commented on backend/src/test/java/com/festago/auth/infrastructure/KakaoOAuth2ClientTest.java
> +
테스트 환경에서만 존재하는 소셜 로그인 빈들을 만들어서 값들을 stubbing 하는 방식입니다 ㅎㅎ

2023-08-05 17:35 UTC, BGuga approved these changes
수고하셨습니다!!

2023-08-07 04:23 UTC, merged