[BE] feat: 마이페이지 전용 API 추가
woowacourse-teams/2023-festa-go pull request #269
Opened 2023-08-07 11:23 UTC by carsago

## 📌 관련 이슈

- closed: #267 

## ✨ PR 세부 내용

단순 view라서 별다른 특이사항은 없습니다.
다만 현재 memberTicket에 createAt이 없어 최근 예매 시간 순 정렬이 불가능해, 일단 입장 시간 순 정렬으로 퉁친후, createAt이 생긴 후 수정이 필요한 곳에 TODO 주석을 작성해놓았습니다.

2023-08-07 11:32 UTC, seokjin8678 commented on backend/src/main/java/com/festago/presentation/MyPageController.java
> +    }
MemberTicketController로 이동하면 좋을 것 같습니다!
그리고 해당 기능은 /member-tickets 조회 시 limit을 걸어 조회하는 부분과 같이 사용될 수 있을 것 같네요

2023-08-07 11:33 UTC, seokjin8678 commented on backend/src/main/java/com/festago/presentation/MyPageController.java
> +public class MyPageController {
```suggestion
@RequestMapping("/members")
public class MemberController {
```

2023-08-07 11:33 UTC, seokjin8678 commented on backend/src/main/java/com/festago/presentation/MyPageController.java
> +    @GetMapping("/info")
```suggestion
    @GetMapping("/profile")
```

2023-08-08 04:14 UTC, xxeol2 requested changes
수고하셨습니다! 간단한 코멘트 남겼어요!
변경된 url 적용해주시면 approve하겠습니다!!

2023-08-08 04:14 UTC, xxeol2 commented on backend/src/main/java/com/festago/application/MemberService.java
> +    }
url을 `/members/profile`로 바꿀 때, 이 메서드 네이밍도 findMemberProfile로 바꿔주면 좋을 것 같아요!

2023-08-08 04:14 UTC, xxeol2 commented on backend/src/main/java/com/festago/dto/MemberResponse.java
> +) {
id도 함께 넘겨주는거 어떤가요?!
그리고 MemberProfileResponse라는 네이밍은 어떤가요! (나중에 Auth정보까지 포함된 Response와 구분짓기 위함입니다!)

2023-08-08 04:26 UTC, BGuga reviewed
간단한 질문 남겼습니다 수고하셨습니다!

2023-08-08 04:26 UTC, BGuga commented on backend/src/main/java/com/festago/domain/MemberTicketRepository.java
> +        """)
left join fetch 를 적용안하신 이유가 있을까요??

2023-08-08 07:21 UTC, seokjin8678 commented on backend/src/main/java/com/festago/domain/MemberTicketRepository.java
> +        """)
해당 메소드 삭제되었습니다!

2023-08-08 08:37 UTC, xxeol2 approved these changes

2023-08-08 11:59 UTC, seokjin8678 commented on backend/src/main/java/com/festago/presentation/MemberTicketController.java
> +        Pageable pageRequest = PageRequest.of(page, size, Sort.by("entryTime").descending());
```suggestion
        Pageable pageRequest = PageRequest.of(page, size, Sort.by("id").descending());
```
지금 생각했는데 id가 생성 순으로 됥텐데, createAt 대신 사용해도 좋을 것 같네요!
(성능 생각하면 이게 더 좋을지도)

2023-08-09 04:06 UTC, BGuga approved these changes

2023-08-09 04:39 UTC, merged

2023-08-09 04:39 UTC, BGuga approved these changes
수고하셨습니다!!