[BE] feat: 로그인한 유저 인증/인가 처리 (#262)
woowacourse-teams/2023-festa-go pull request #272
Opened 2023-08-07 13:01 UTC by BGuga

## 📌 관련 이슈

- closed: #262

2023-08-07 17:30 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/presentation/LoginMemberResolver.java
> +        return authService.loginMemberByHeader(header);
JWT 토큰을 사용하는 이유 중 하나가 데이터베이스를 조회하지 않고 유저의 정보를 가져올 수 있다는 장점이 있는데, `AuthService.loginMemberByHeader()` 메소드를 보니, 데이터베이스에서 사용자의 정보를 조회하고 있네요!
데이터베이스를 조회하지 않고, JWT 토큰의 Payload로 LoginMember 객체를 만들면 안 될까요?

2023-08-07 17:32 UTC, seokjin8678 commented on backend/src/main/java/com/festago/presentation/GlobalExceptionHandler.java
> +
```suggestion

```

2023-08-07 17:44 UTC, seokjin8678 commented on backend/src/test/java/com/festago/presentation/ControllerTest.java
> +}
해당 클래스를 상속했을 때 편리함은 동의하지만, 추후 새로운 Controller가 추가되거나 Service가 추가되었을 때 계속 추가가 되는 걸까요? 🤔
내부에 많은 Mock들이 있는데, 해당 클래스를 상속하는 테스트에서 Mocking을 할 때, 많은 클래스들이 있어서 혼란이 생길 것 같아요.

2023-08-07 23:59 UTC, seokjin8678 requested changes
간단한 리뷰 남겼습니다!

2023-08-07 23:59 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/infrastructure/JwtBearerAuthExtractor.java
> +    }
파라미터가 null일 수 있지 않을까요??

2023-08-07 23:59 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/infrastructure/JwtBearerAuthExtractor.java
> +        Long memberId = claims.get(MEMBER_ID_KEY, Long.class);
저희가 만든 JWT 토큰이라, 그럴 일은 없겠지만.. member_id 키가 아니라 다른 키로 바뀐다면 null 값이 반환되지 않을까요?

2023-08-08 01:26 UTC, BGuga commented on backend/src/main/java/com/festago/auth/presentation/LoginMemberResolver.java
> +        return authService.loginMemberByHeader(header);
JWT 가 데이터베이스를 사용하지 않는 장점은 세션 유지용 데이터베이스가 필요없는 부분이라 생각합니다!!
해당 부분에서 데이터베이스를 사용해야한다 생각한 상황은 다음과 같습니다.
1. 만약 유저가 로그인하고 바로 회원탈퇴를 했을 때 토큰은 유효하지만 실 유저가 없을 수 있는 상황이 있다.
2. 서버측에서 memberId 대신 다른 값을 넣어서 토큰을 발급해서 memberId 가 유효하지 않을 수 있다.
는 상황이 있었고
이를 각 Service의 검증으로 넘길 수 있겠지만
각 Service 에서 만약 
```
public void method(Long memberId) {
    ~.save(new Ticket());
    ~.save(new Festival());
    findMemberById(memberid);
}

public Member findMemberByid(Long memberId) {
    ...orElseThrow(...)
}
```
와 같은 서비스들에서 이미 connection 을 통한 Entity insert 작업이 끝나고 rollback 되는 상황이 예상되었습니다.
그래서 memberId의 검증 로직을 중복이지만 조금 앞단인 resolver 에 중복으로 두어서 불필요한 insert 작업등을 최소화하기 위해서 resolver에서 DB를 조회하도록 만들었습니다.

2023-08-08 04:32 UTC, BGuga commented on backend/src/test/java/com/festago/presentation/ControllerTest.java
> +}
[테스트 환경 분리](https://geminikim.medium.com/%EB%8A%90%EB%A0%A4%ED%84%B0%EC%A7%84-spring-rest-docs-test-springcontext-mockbean-%EC%97%86%EC%9D%B4-%EB%B9%A0%EB%A5%B4%EA%B3%A0-%ED%9A%A8%EA%B3%BC%EC%A0%81%EC%9C%BC%EB%A1%9C-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0-dc36861493c9) 해당 글을 참고해서 TestContext 조차 사용하지 않고 테스트가 가능할 것 같아요 그리고 글렌이 말씀 주신 혼란도 덜해질 것 같네요!! 다만 아직까지는 그렇게 많은 서비스와 컨트롤러가 있는 것이 아니라 이대로 유지하고 차후에 해당 글을 참고하여 반영하는 것은 어떨까요??

2023-08-08 04:38 UTC, xxeol2 commented on backend/src/main/java/com/festago/auth/infrastructure/JwtBearerAuthExtractor.java
> +        Long memberId = claims.get(MEMBER_ID_KEY, Long.class);
검증 로직 추가했습니다~!

2023-08-08 04:38 UTC, xxeol2 commented on backend/src/main/java/com/festago/auth/infrastructure/JwtBearerAuthExtractor.java
> +    }
검증 로직 추가했습니다~!

2023-08-08 06:52 UTC, xxeol2 commented on backend/src/test/java/com/festago/presentation/ControllerTest.java
> +}
반영했습니다!!

2023-08-08 08:06 UTC, carsago approved these changes

2023-08-08 08:18 UTC, xxeol2 approved these changes

2023-08-08 08:19 UTC, seokjin8678 approved these changes
고생하셨습니다!

2023-08-08 08:20 UTC, merged