[BE] feat: 회원이 동일한 무대의 티켓을 1장만 예약할 수 있게 변경 (#288)
woowacourse-teams/2023-festa-go pull request #302
Opened 2023-08-09 11:11 UTC by seokjin8678

## 📌 관련 이슈

- closed: #288

2023-08-09 19:42 UTC, xxeol2 requested changes
수고하셨습니다!
간단한 코멘트 남겼어요!!

2023-08-09 19:42 UTC, xxeol2 commented on backend/src/main/java/com/festago/application/TicketService.java
> +        validateAlreadyReserved(member, ticket);
validate문을 최대한 앞에 넣어서, 유효하지 않은 요청일시 빠르게 Exception을 던지는게 어떨까요?!

2023-08-09 19:42 UTC, xxeol2 commented on backend/src/test/java/com/festago/application/integration/TicketServiceIntegrationTest.java
> +    }
👍

2023-08-09 19:43 UTC, xxeol2 approved these changes

2023-08-10 01:45 UTC, xxeol2 commented on backend/src/main/java/com/festago/application/TicketService.java
> +        validateAlreadyReserved(member, ticket);
아하 이미 매진된 상황의 가능성이 더 크기때문에 상대적으로 발생 가능성이 적은 중복예매 검증처리를 뒤로 두셨다는뜻인가요?!
좋네용 👍

2023-08-10 02:02 UTC, seokjin8678 commented on backend/src/main/java/com/festago/application/TicketService.java
> +        validateAlreadyReserved(member, ticket);
우선 해당 요청을 앞으로 넣고, 추후 클라이언트에서 해당 검증이 가능하다면 뒤로 옮기는게 좋겠네요!

2023-08-10 04:24 UTC, seokjin8678 commented on backend/src/main/java/com/festago/application/TicketService.java
> +        validateAlreadyReserved(member, ticket);
@xxeol2 
적용해보니 검증 로직을 앞으로 옮길 수 없네요 😭
Ticket에서 TicketAmount가  양방향 OneToTone 관계의 주인이 아니라서, EAGER로 조회가 됩니다.
이때, FOR UPDATE로 날아가지 않기 때문에 테이블에 락이 걸리지 않아서 동시성 문제가 발생하네요

2023-08-10 05:36 UTC, carsago approved these changes
로직 추가됐지만 이해하기 어려운 부분은 없어서 좋았습니다.

2023-08-10 05:36 UTC, carsago commented on backend/src/test/java/com/festago/application/integration/TicketServiceIntegrationTest.java
> +    }
로직 추가됐지만 더 이해하기 쉬워졌네요.

2023-08-10 05:36 UTC, carsago commented on backend/src/main/java/com/festago/application/TicketService.java
> +        int reservedAmount = reserveTicket(request.ticketId());
이런거 바꿔주신 것도 좋네요

2023-08-10 07:29 UTC, seokjin8678 commented on backend/src/test/java/com/festago/application/integration/TicketServiceIntegrationTest.java
> +    }
해당 부분 다음과 같이 모킹하여 중복된 회원이라도 예매가 가능하게 했습니다!
```java
when(memberTicketRepository.existsByOwnerAndStage(any(Member.class), any(Stage.class)))
    .thenReturn(false);
```

2023-08-10 21:22 UTC, carsago commented on backend/src/main/java/com/festago/application/TicketService.java
> +        validateAlreadyReserved(member, ticket);
찾아보니 OneToOne 양방향 관계일때, 주인(외래키 관리자)이 아니더라도  LAZY가 가능하게 해주는 옵션이 있네요.
```@OneToOne(optional = false)``` 라는 옵션입니다.

```
  @OneToOne(optional = false, mappedBy = "ticket", fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
  private TicketAmount ticketAmount;
```

밑에 주석처럼 반드시 존재할 때, 걸어라고 하고있네요.

```    /** 
     * (Optional) Whether the association is optional. If set 
     * to false then a non-null relationship must always exist.
     */
    boolean optional() default true;
```

OneToOne 양방향일때 항상 LAZY가 가능한건 아니겠지만, 저희는 항상 같이 persist되니까 문제가 없을 것 같아요.
물론 must always exist가 아니더라도 이 조건을 통해 lazy loading이 가능하지만, 아마 null 나면 예상치않게 흘러갈 까봐 존재할 때만 쓰라고 적어논거 같네요.

왜 주인 아니면  LAZY 안되는지 기억안나면 참고 --
https://jeong-pro.tistory.com/249

2023-08-11 01:17 UTC, BGuga reviewed
수고하셨습니다!! 간단한 코멘트 남겼습니다 ㅎㅎ

2023-08-11 01:17 UTC, BGuga commented on backend/src/test/java/com/festago/application/integration/TicketServiceIntegrationTest.java
> +
사용하지 않는 것 같네요!!👍

2023-08-11 01:17 UTC, BGuga commented on backend/src/test/java/com/festago/application/integration/ApplicationIntegrationTest.java
> +@ExtendWith(DatabaseClearExtension.class)
Transactional 을 없앰에 따라 multiThread 테스트가 가능해졌지만 실제로 데이터 삽입 로직을 수행하기 때문에 테스트들의 평균 속도가 조금 느려진 것 같네요!!

2023-08-12 07:01 UTC, seokjin8678 commented on backend/src/main/java/com/festago/application/TicketService.java
> +        validateAlreadyReserved(member, ticket);
생성자에서 new TicketAmount 한 뒤 Persist 시켜주니까 optional=false를 사용해도 좋겠네요!!

2023-08-12 07:05 UTC, seokjin8678 commented on backend/src/test/java/com/festago/application/integration/ApplicationIntegrationTest.java
> +@ExtendWith(DatabaseClearExtension.class)
그렇다고 해도, 많은 쿼리가 날아가는건 아닌지라.. 느끼기 힘든 차이라고 생각합니다. 😄

2023-08-12 07:17 UTC, BGuga commented on backend/src/main/java/com/festago/application/TicketService.java
> +        validateAlreadyReserved(member, ticket);
Lazy 를 적용시켜서 Lock을 걸 수 있다면 validation 을 앞으로 옮겨보는 것은 어떨까용?🤔

2023-08-12 07:18 UTC, BGuga commented on backend/src/test/java/com/festago/application/integration/ApplicationIntegrationTest.java
> +@ExtendWith(DatabaseClearExtension.class)
이 부분에 대한 인지만 해둔 채로 후에 문제가 되는 수준에 도달한다면 개선하는 것도 좋겠네요 ㅎㅎ

2023-08-12 07:29 UTC, BGuga approved these changes

2023-08-12 07:31 UTC, merged