[BE] feat: 어드민 페이지 인증 기능 구현 (#352)
woowacourse-teams/2023-festa-go pull request #354
Opened 2023-08-13 12:42 UTC by seokjin8678

## 📌 관련 이슈

- closed: #352

## ✨ PR 세부 내용

어드민 페이지에 인증 기능을 구현했습니다.
인증 토큰은 JWT 기반이고, 웹에서 사용할 목적으로 쿠키에 토큰을 저장하여 사용합니다.

토큰이 없는 상태에서 어드민 페이지에 접속하면 자동으로 /admin/login URL으로 리다이렉트 됩니다.

요청의 흐름은 `LoginConfig`에 있는 `AdminAuthInterceptor` 인터셉터에 정의된 경로에 접근 시 인증 기능이 수행됩니다.

어플리케이션의 처음 상태에는 관리자 계정이 없으니, 새롭게 생성을 해야하는데 관리자 계정을 생성하려면 관리자 인증이 필요한 난감한 상황이 발생했습니다.
따라서 DB에 INSERT를 날려서 관리자 계정을 생성하게 하는 것 보다는, 초기 관리자를 생성하는 API를 만들어서 해결했습니다.

초기 관리자를 생성하는 API에는 하드코딩된 "admin" username을 생성하도록 하는 로직을 수행합니다.

새로운 관리자를 생성하려면 `/admin/signup`에 접속하면 새로운 관리자 계정을 생성할 수 있습니다.

새롭게 만들어진 관리자도 새로운 관리자를 계속 생성할 수 있으므로, `admin` username만 가진 관리자(마치 root 계정 같은)만 생성할 수 있게 하는 방법이 필요할 것 같습니다.

추후 계정을 새롭게 만드는 방식은 고도화 시켜서, 축제의 관리자(자기의 축제의 티켓을 발급하고 공연을 관리할 수 있는) 역할을 만든 뒤, 어드민이 해당 축제의 관리자 계정을 만들 수 있게 할 수 있을 것 같네요!

2023-08-13 13:57 UTC, seokjin8678 commented
추가적으로 참고해야할 사항이 있습니다.
어드민으로 로그인을 해도 토큰이 발급됩니다.
해당 토큰의 값을 Authorization 헤더에 설정하면, `LoginMemberResolver`에서 LoginMember 객체를 받을 수 있습니다.

2023-08-13 15:05 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/application/AdminAuthService.java
> +        Admin admin = adminRepository.save(new Admin(username, password, member));
새로운 계정을 저장할 때, 지금은 평문을 그대로 저장하고 있어서 추후 암호화된 비밀번호를 저장하는 수단이 필요합니다.

2023-08-13 15:07 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/domain/Admin.java
> +public class Admin {
지금은 관리자가 축제, 연극, 티켓 모두 관리를 하고 있습니다.
추후에 축제의 관리자가 생긴다면 Admin 이라는 도메인의 이름이 좋은 것 같지는 않은 것 같아서 Account 같은 도메인으로 분리를 해야할 것 같습니다.
그렇게된다면 역할의 구분은 Member 엔티티에 Role 이라는 컬럼을 추가하여 구분할 수 있을 것 같은데, 해당 부분에 대해 논의가 있었으면 좋겠네요. (ex: USER, MANAGER, ADMIN)

2023-08-13 15:16 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/application/AuthService.java
> +        return authProvider.provide(new AuthPayload(member.getId(), Role.MEMBER));
Member에 Role 컬럼이 생긴다면 다음과 같이 될 것 같습니다.
```suggestion
        return authProvider.provide(new AuthPayload(member.getId(), member.getRole()));
```

2023-08-13 15:17 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/application/AdminAuthService.java
> +        return new AuthPayload(memberId, Role.ADMIN);
마찬가지로 Member에 Role 컬럼이 생긴다면 다음과 같이 될 것 같네요.
```suggestion
        Role role = admin.getRole(); // admin.getMember().getRole(); or account.getMember().getRole();
        return new AuthPayload(memberId, role);
```

2023-08-14 04:21 UTC, xxeol2 requested changes
수고많으셨습니다 글렌 🥃
코멘트 남겼습니다!!

2023-08-14 04:21 UTC, xxeol2 commented on backend/src/main/java/com/festago/auth/domain/AdminAuthInterceptor.java
> +}
LoginMemberResolverTest을 참고해 Mock 테스트해보는건 어떤가요?!

2023-08-14 04:21 UTC, xxeol2 commented on backend/src/main/java/com/festago/auth/application/AdminAuthService.java
> +    }
다른 service들에서는 findByUsername orElseThrow로 했었는데 이번에는 existsByUsername을 활용하신 이유가 궁금합니다!
Admin 객체가 필요없어서인가요 ?!

2023-08-14 04:21 UTC, xxeol2 commented on backend/src/main/java/com/festago/auth/domain/AdminAuthInterceptor.java
> +                if (Objects.equals("token", cookie.getName())) {
"token"을 상수화하는건 어떤가요?!

2023-08-14 04:21 UTC, xxeol2 commented on backend/src/main/java/com/festago/auth/domain/AdminAuthInterceptor.java
> +    }
if (cookie == null) 인 경우 early return시키는건 어떤가요?!

2023-08-14 04:21 UTC, xxeol2 commented on backend/src/main/java/com/festago/auth/presentation/LoginMemberResolver.java
>  public class LoginMemberResolver implements HandlerMethodArgumentResolver {
LoginMemberResolver에서도 Role을 검증해주는건 어떤가요?!

2023-08-14 04:21 UTC, xxeol2 commented on backend/src/main/java/com/festago/auth/config/LoginConfig.java
> +
👍

2023-08-14 06:36 UTC, carsago commented on backend/src/main/java/com/festago/auth/domain/Admin.java
> +    private Member member;
저도 애쉬 의견에 공감합니다. Admin은 아예 별도로 가는 게 좋을 것 같아요.
이용자 입장에서 아예 별도의 앱 & 웹에서 처리되기 때문에 다른 계정이라도 딱히 어색함이 없고, 기존의 Member를 활용한다면 테스트 코드등에서 member의 변화에 따라 변경이 생길 가능성도 존재하니까요.

2023-08-14 06:41 UTC, BGuga reviewed
수고하셨습니다 글렌 몇가지 코멘트 남겼습니다 ㅎㅎ

2023-08-14 06:41 UTC, BGuga commented on backend/src/main/java/com/festago/auth/domain/AdminAuthInterceptor.java
> +
어드민의 로그인을 Interceptor 로 처리하신 이유가 있으실까요??
이 부분을 ArgumentResolver 에서 처리한 후 만약 로그인 token 이 없을 경우 exception 을 발생시킨 후 exception handler 에서 redirection 요청을 보내는 방법도 있었을 것 같습니다!!

2023-08-14 06:41 UTC, BGuga commented on backend/src/main/java/com/festago/auth/domain/Admin.java
> +    private Member member;
저도 애쉬의 의견에 공감합니다!!
하나의 앱에서 Member의 역할이 구분된 것이 아니기에 따로 분리하는 것이 좋아보이네요 ㅎㅎ

2023-08-14 06:41 UTC, BGuga commented on backend/src/main/java/com/festago/presentation/AdminController.java
>      }
정답!! js 코드 바꾸기 힘들다??

2023-08-14 06:41 UTC, BGuga commented on backend/src/main/java/com/festago/presentation/AdminController.java
> +            .build();
Interceptor로 처리되니 해당 Login 로직이 어디서 처리되고 있는지 파악하는데 조금 더 걸리는 것 같네요!! 또 해당 Controller 에서 어떤 Admin 이 요청했는지에 대한 정보가 추후에 충분히 필요해 보이기 때문에 ArgumentResolver 로 처리하면 어떨까 의견 내봅니다!!

2023-08-14 07:10 UTC, seokjin8678 commented on backend/src/main/java/com/festago/presentation/AdminController.java
>      }
요청 시, 헤더에 Authorization 값을 보내주려면, 웹 어플리케이션 어딘가에 token 값을 저장해둬야 합니다.
보관할 수 있는 곳은 아마 LocalStorage 또는 SessionStorage 둘 중 보관이 가능한데 아무튼..
이렇게 보관한 토큰을 꺼내고 요청의 헤더에 추가를 해줘야 합니다. 😂
```
// const token = localStorage.getItem("token");
const token = sessionStorage.getItem("token");

fetch("/admin/festivals", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": "Bearer " + token <-- 이렇게
        },
        body: JSON.stringify(festivalData)
      })
```
쿠키는 요청을 할때, 자동으로 같이 보내지게 되니 쿠키를 사용하여 토큰을 전송하였습니다!

2023-08-14 07:13 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/domain/Admin.java
> +    private String password;
그렇습니다
지금 어드민 페이지에서의 기능도 저희같은 어드민이 축제, 공연, 티켓을 생성하고 있습니다!
따라서 추후 어드민은 축제를 개설하고, 축제의 관리자(Mananger) 계정을 생성할 수 있는 역할이 되어야 할 것 같네요!

2023-08-14 07:21 UTC, seokjin8678 commented on backend/src/main/java/com/festago/presentation/AdminController.java
> +    }
매니저가 생긴다면 ManagerController 라는 컨트롤러가 생길 수 있겠네요!
Path는 어떻게 하면 좋을까요?
웹은 /admin-web/, API는 /admin-api/ 이렇게 가야할까요?
저희 서버가 웹을 고려한 환경이 아니다 보니 어떻게 해야할지 난감하네요 😂

2023-08-14 07:32 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/application/AdminAuthService.java
> +        validatePassword(admin.getPassword(), request.password());
이 방법을 고려한 이유가.. Spring Security Crypto 모듈에서 제공되는 `BcryptPasswordEncoder` 라는 클래스가 있습니다.
해당 클래스는 평문 문자열을 해시값으로 암호화를 해주는 클래스인데, 내부에 랜덤한 솔트 값을 가지고 있어 같은 문자열이라도 암호화를 할때 해시 값이 바뀝니다.
따라서 암호화된 비밀번호와 평문 비밀번호를 비교하려면, `BcryptPasswordEncoder`의 `matches()` 메소드로 비교를 해야합니다.
```java
encodedPassword1 = bcryptPasswordEncoder.encode("password");
encodedPassword2 = bcryptPasswordEncoder.encode("password");
encodedPassword1.eqauls(encodedPassword2); // false

bcryptPasswordEncoder.matches(encodedPassword1, encodedPassword2); // true
```
물론 지금은 해당 모듈을 사용하지 않으니 객체에 메시지를 전달하여 암호를 비교할 수 있겠지만, 추후 암호화를 적용한다면 다음과 같은 방법이 변화에 유연하게 대응할 수 있을 것 같습니다!

2023-08-14 07:33 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/application/AdminAuthService.java
> +            .orElseThrow(() -> new UnauthorizedException(ErrorCode.INVALID_PASSWORD));
적절한 에러코드가 있으면 추천해주세요. 😄

2023-08-14 07:35 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/application/AdminAuthService.java
> +    }
해당 메서드의 사용은 새로운 관리자 계정을 사용할 때 입니다!
관리자의 계정이 중복될 수 있으니 이름으로 중복을 검사하려고 해당 방법을 사용했습니다!

2023-08-14 07:37 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/domain/AdminAuthInterceptor.java
> +}
HttpServletRequest를 Mock으로 만들어 테스트 할 수 있겠네요!

2023-08-14 07:38 UTC, carsago reviewed
다른 분들이 코멘트를 먼저 달아주셔서 거기에 +@ 느낌으로 만 거의 달게 됐네요.

전 ArgumentResolver는 파싱만 해주는걸 선호하고, 검증이 필요하다면 Interceptor에서 처리하는 걸 선호하긴 합니다 ㅎㅎ, 이건 나중에 같이 이야기 해봐도 좋을 것 같네요.

그리고 별도의 의견인데 admin 관련 기능을 아예 패키지 분리하는 건 어떨까싶네요? 기존의 로직과는 완전 별도의 관심사고 양방향 패키지 참조가 일어날 일도 없을 것 같아서 전 나눴으면 하거든요. 이 부분에 대해서도 이야기 해보고 싶네요.

2023-08-14 07:40 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/domain/AdminAuthInterceptor.java
> +    }
이 부분은 무지성 구현을 했던 것 같네요 😂

2023-08-14 08:22 UTC, xxeol2 commented on backend/src/main/java/com/festago/auth/application/AdminAuthService.java
> +            .orElseThrow(() -> new UnauthorizedException(ErrorCode.INVALID_PASSWORD));
흠.. 비밀번호가 틀린게 아니니까....... NOT_CORRECT_USERNAME?

2023-08-14 17:15 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/application/AdminAuthService.java
> +            .orElseThrow(() -> new UnauthorizedException(ErrorCode.INVALID_PASSWORD));
에러 메시지를 보낼 때, "비밀번호가 틀렸거나, 해당 계정이 없습니다." 이니까, `INCORRECT_PASSWORD_OR_ACCOUNT`는 어떨까요?

2023-08-14 18:15 UTC, seokjin8678 commented
이번에 인증 구조를 새로 바꿔봤습니다!

기존에는 ArgumentResovler에서 Bearer 토큰을 꺼내고, 해당 토큰을 AuthProvider에 요청을 하는 방법이라 Cookie를 사용한 인증을 사용하기가 불가능 했습니다.
또한 ArgumentResolver로 인증 기능을 수행한다면 핸들러 메서드에 `@Login` 이라는 메서드가 붙어야만 인증이 되므로, /resources/static 에 있는 자료들이 인증을 받지 못하는 이슈가 있습니다!
따라서 인증 자체는 Path를 사용하도록 Interceptor를 만들어 인증을 수행하도록 했습니다.

인증을 하는 구조는 다음과 같습니다.

![image](https://github.com/woowacourse-teams/2023-festa-go/assets/116627736/4563e6b0-5e52-422b-b7d0-c7c1d0e848ad)

인증의 흐름은 다음과 같습니다.

Interceptor는 Path에 맞는 요청이 오면, TokenExtractor에 request를 전달하여 토큰을 가져옵니다.
토큰은 Optional 이므로, Interceptor에서 null에 대한 핸들링을 수행합니다.
그리고 토큰을 `AuthExtractor`에 전달하여 AuthPayload를 가져옵니다.
AuthPayload의 Role을 검증하고 `AuthenticateContext`에 `setAuthenticate()`를 호출하여 인증 정보를 세팅합니다.
(`AuthenticateContext`는 Request Scope 빈입니다.)
그리고 인증 정보가 필요한 경우 ArgumentResolver에서 `AuthenticateContext`에 있는 인증 정보를 꺼내 핸들러 메서드의 어노테이션에 맞는  인증 정보를 설정합니다.

추후 Manager가 생긴다면 `ManagerAdminAuthInterceptor`, `ManagerArgumentResolver`를 만들고 적용하면 될 것 같습니다.

또한 이러한 인증 기능으로 인해 `@WebMvcTest`에서 인증에 필요한 Bean을 주입해야 하는 이슈는 `@CustomWebMvcTest` 어노테이션을 적용하여 해결하였습니다.

```java
@CustomWebMvcTest(AdminController.class)
class AdminControllerTest {
@Test

    @WithMockAuth
    void 토큰의_Role이_어드민이_아니면_로그인_페이지로_리다이렉트() throws Exception {
        ...
    }

    @Test
    @WithMockAuth(role = Role.ADMIN)
    void 축제_생성() throws Exception {
        ...
    }
}
```

다음과 같이 인증이 필요한 테스트의 경우 `@WithMockAuth` 어노테이션으로 간단하게 인증 정보를 부여할 수 있습니다.

2023-08-14 18:46 UTC, seokjin8678 commented on backend/src/main/java/com/festago/presentation/AdminController.java
> +            .build();
ArgumentResolver로 인증을 구현하면 발생하는 이슈에 대해 밑에 코멘트로 남겼습니다!

2023-08-15 09:06 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/presentation/RoleArgumentResolver.java
> +        }
해당 부분이 `AuthInterceptor`에서 검증이 되는데 굳이 여기서도 검증을 할 필요가 있을까? 생각이 드네요.
예외를 던지지 말고 null을 반환하는 방법도 있을 것 같긴한데.. NPE가 생길 것 같기도 하고...
여러분 생각은 어떠신가요?

2023-08-16 02:42 UTC, xxeol2 commented on backend/src/main/java/com/festago/presentation/AdminController.java
>      }
아하 이런 스토리가 있었네요 ㅋㅋㅋ
프론트엔드 개발은 최대한 간단하게 하는게 좋으니 저도 쿠키를 활용하는게 좋아보여요 🍪

2023-08-16 12:33 UTC, xxeol2 approved these changes
변경에 유연한 코드네요! STAFF와 같이 다른 인증이 적용되어도 이 구조에선 손쉽게 추가할 수 있을 것 같아요 👍
수고 많으셨습니다 글렌!!
아래 코멘트들은 단순 궁금증 위주로 남겼습니다

2023-08-16 12:33 UTC, xxeol2 commented on backend/src/main/java/com/festago/auth/domain/Role.java
> +    ADMIN(Admin.class),
Anonymous는 어떤 역할을 하는지 알 수 있을까요?!

2023-08-16 12:33 UTC, xxeol2 commented on backend/src/main/java/com/festago/auth/domain/AuthenticateContext.java
> +@RequestScope
domain인데 org.springframework.web.context 종속성을 가지는 너무 웹에 의존하는 객체인 것 같아요
얘의 패키지 위치가 domain일까?를 함께 고민해보면 좋을 것 같아요
지금 제 생각으로는 presentation layer에 가까울 수도 있을 것 같네용

2023-08-16 12:33 UTC, xxeol2 commented on backend/src/main/java/com/festago/auth/domain/AuthInterceptor.java
> +    private final Role role;
이친구도 AuthenticateContext와 마찬가지로 presentation 레이어에 가깝지않나?라는 생각이 들어요!

근데 또 글렌이 ArgumentResolver는 presentation에 위치시키셔서, Interceptor는 여기 두신데에는 그만한 이유가 있었을 것 같네요 ㅋㅋㅋ

2023-08-16 12:33 UTC, xxeol2 commented on backend/src/main/java/com/festago/presentation/GlobalExceptionHandler.java
> +    }
Http 상태코드로 FORBIDDEN이 아닌 NOT_FOUND를 택하신 이유가 궁금합니다~~

2023-08-16 12:33 UTC, xxeol2 commented on backend/src/test/java/com/festago/support/CustomWebMvcTest.java
> +}
이건 어떤 역할을 하는 클래스인가요?!

2023-08-16 12:34 UTC, xxeol2 commented on backend/src/main/java/com/festago/auth/presentation/RoleArgumentResolver.java
> +        }
비용이 큰 연산이 아니니까.. NPE 위험성을 안고가는 것 보단 이중으로 체크하는게 좋지 않을까 싶네용

2023-08-16 15:02 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/domain/Role.java
> +    ADMIN(Admin.class),
AuthenticateContext에 인증 정보가 세팅되지 않았을 때, Role의 기본 값은 null 입니다.
하지만 null으로 두는 것 보다, 인증이 되지 않은 Role을 `ANONYMOUS`으로 정의하였고, 기본 값으로 사용합니다!
또한 `RoleArgumentResolver`에서 resolveArgument를 수행할 때, 핸들러 메서드의 파라미터에 붙은 특정 어노테이션을 기반으로 값을 주입하도록 했는데, 해당 값은 `Role`의 `getAnnotaion()` 메서드를 통해 `Class<? extends Annotation>` 타입입니다. (Admin, Member)
해당 타입은 Role에 1:1 매칭이 되는 어노테이션입니다.
하지만 `ANONYMOUS`의 경우 인증 어노테이션이 필요없지만, `Class<? extends Annotation>` 타입의 필드를 null로 설정하는건 NPE 가능성이 있다고 판단하여 사용하지 않더라도 스펙에 맞추기 위해서 해당 Anonymous 어노테이션을 세팅해주었습니다!

2023-08-16 15:03 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/domain/AuthInterceptor.java
> +    private final Role role;
ㅋㅋㅋ 위의 AuthenticateContext와 함께 presentation 계층에 두는 것이 맞아 보이네요!

2023-08-16 15:05 UTC, seokjin8678 commented on backend/src/main/java/com/festago/presentation/GlobalExceptionHandler.java
> +    }
보안상의 이유로 의도적으로 NOT_FOUND를 던져주었습니다!
403 FORBIDDEN으로 에러 코드를 던져준다면, 해당 리소스가 보안적으로 중요한 자료이다 라고 판단할 수 있기에 일부러 모호한 결과를 주려고 NOT_FOUND를 택했습니다!

2023-08-17 02:32 UTC, BGuga approved these changes
수고하셨습니다!

2023-08-17 02:32 UTC, carsago approved these changes

2023-08-17 02:32 UTC, merged