[BE] feat: 학교 목록 조회 기능 구현 (#431)
woowacourse-teams/2023-festa-go pull request #432
Opened 2023-09-08 06:26 UTC by xxeol2

## 📌 관련 이슈

- closed: #431 

## ✨ PR 세부 내용

학생 인증을 위한 학교 목록 조회 기능을 구현했습니다.

2023-09-08 16:37 UTC, seokjin8678 requested changes
누락된 사항에 대해 리뷰 남겼습니다!

2023-09-08 16:37 UTC, seokjin8678 commented on backend/src/main/java/com/festago/application/SchoolService.java
> +    }
readOnly를 붙이는건 어떨까요?

2023-09-09 13:41 UTC, carsago approved these changes
간결하네요. 하 가위바위보 잘 할 걸

2023-09-10 16:36 UTC, seokjin8678 approved these changes
리뷰 반영 확인했습니다!

2023-09-11 08:43 UTC, merged