[BE] 이메일 코드를 통한 학생 인증 기능을 추가
woowacourse-teams/2023-festa-go pull request #434
Opened 2023-09-08 07:00 UTC by carsago

## 📌 관련 이슈

- closed: #430 

## ✨ PR 세부 내용

1. 학생 인증 기능을 추가하였습니다.

2. 기존 코드 변경 사항

학생 인증 완료후 Student 객체를 생성할 때 메일 요청시 요청했던, username이 필요합니다.

그런데 저희는 username을 어느 곳에서도 저장하지 않아서, Student 객체에 username을 넣어주지 못합니다.

따라서 메일 인증 요청때 생성하던 StudentCode 객체에 username 필드를 추가하였습니다.

2023-09-10 05:40 UTC, xxeol2 requested changes
수고하셨습니다!
간단한 코멘트 남겼습니다~

2023-09-10 05:40 UTC, xxeol2 commented on backend/src/main/java/com/festago/application/StudentService.java
> +        studentCodeRepository.deleteByMember(member);
저희 아직 코드 유효기간에 대한 요구사항은 없었죠 ?!

2023-09-10 05:40 UTC, xxeol2 commented on backend/src/main/java/com/festago/application/StudentService.java
> +            .orElseThrow(() -> new BadRequestException(ErrorCode.INVALID_STUDENT_VERIFICATION_CODE));
StudentCode가 해당 회원의 code인지 확인하는 절차도 필요할 것 같아요!

2023-09-10 16:00 UTC, carsago commented on backend/src/main/java/com/festago/application/StudentService.java
> +        studentCodeRepository.deleteByMember(member);
네 그 부분은 없었어요.
현재 상황 새로 인증 코드를 요청할 때 마다 &  인증을 받을때 기존 코드가 지워짐
-> DB에 존재하는 코드의 갯수 : 인증코드를 발급했으나 인증받지 않은 회원들의 코드만 존재 -> 유저수가 많아 지더라도극히 적은 갯수만 DB에 존재

그렇기때문에 전 큰 문제 없다고 봅니다.

다만 그래도 DB에 남아있는게 마음에 안든다면
1. Redis로 수행한다. -> studentCode에 다양한 값이 존재해서 java 객체로 저장해야할듯 (지원해주지만 귀찮을수도?, redis 못쓸수도? ㅠㅠ)
2. 자바 외부 라이브러리 중에  Collection을 상속받고, 일정 시간이 지나면 자동으로 만료해주는 녀석 존재함, 애를 활용하자
-> 외부 라이브러리 의존성 ㅠㅠ  & 세션 공유 문제(세션 클러스터링 하면 되지만 이것저것 복잡해짐)

그래서 전 이렇게 DB에 남겨두는게 좋을 것 같아요.

2023-09-10 16:04 UTC, carsago commented on backend/src/main/java/com/festago/application/StudentService.java
> +        studentCodeRepository.deleteByMember(member);
넵 따로 없었어요. 전 굳이 없는게 유저 입장에서 편하다고 생각하는데 한 번 이야기 해봐도 괜찮을 것 같네용

2023-09-10 16:05 UTC, carsago commented on backend/src/main/java/com/festago/application/StudentService.java
> +            .orElseThrow(() -> new BadRequestException(ErrorCode.INVALID_STUDENT_VERIFICATION_CODE));
하는게 좋겠네용

2023-09-10 16:10 UTC, carsago commented
---
merge 주의 DB 테이블 변경됨

2023-09-11 08:29 UTC, xxeol2 approved these changes
수고많으셨습니다

2023-09-11 08:42 UTC, BGuga approved these changes
수고하셨습니다!!

2023-09-11 08:42 UTC, merged