[BE] refactor: Oauth2 네트워크 통신을 Transaction 범위 밖으로 분리 (#435)
woowacourse-teams/2023-festa-go pull request #436
Opened 2023-09-10 05:35 UTC by xxeol2

## 📌 관련 이슈

- closed: #435 

## ✨ PR 세부 내용

Oauth2 벤더사에서 UserInfo를 가져오는 로직을 트랜잭션 범위 밖으로 분리했습니다.
상대적으로 비용이 큰 네트워크 통신 과정이기에 트랜잭션 범위 밖으로 분리하는게 좋을 것 같아, 리팩토링 해봤는데 의견이 궁금합니다!

2023-09-10 05:35 UTC, xxeol2 commented on backend/src/main/java/com/festago/auth/application/AuthService.java
>      }
현재 AuthService를 OuterService로 하고, LoginService를 InnerService로 했습니다.
AuthController에서 AuthService로의 의존성만 가지는게 더 깔끔한 것 같아 이렇게 했는데,
이 과정에서 AuthService 최상단의 `@Transactional` 어노테이션을 메서드단으로 이동해야하는 문제가 있었습니다.

LoginService를 OuterClass로 하는게 더 좋을지 고민이네요 .. 이 부분에 대해 의견 부탁드립니다!

2023-09-10 10:57 UTC, carsago commented on backend/src/main/java/com/festago/auth/application/AuthService.java
>      }
저는 이 구조로 가도 좋다고 생각합니다. 여기서 메소드가 뭐가 더 늘어날까 싶기도하고.. 
지금은 모든 service가 트랜잭션 어노테이션을 가지고 있고, 일종의 컨벤션처럼 됐지만 항상 그럴 필요는 없으니까요.(db 통신을 안한다면 필요없으니)

2023-09-10 12:04 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/application/AuthService.java
>      }
LoginService 클래스에서 DTO를 반환하는게 아니라, 바로 LoginResponse를 반환하게 하는건 어떠신가요?
```java
@Service
@Transactional
public class LoginService {

    private final MemberRepository memberRepository;
    private final AuthProvider authProvider;

    public LoginService(MemberRepository memberRepository, AuthProvider authProvider) {
        this.memberRepository = memberRepository;
        this.authProvider = authProvider;
    }

    public LoginResponse login(UserInfo userInfo) {
        return memberRepository.findBySocialIdAndSocialType(userInfo.socialId(), userInfo.socialType())
            .map(member -> LoginResponse.isExists(getAccessToken(member), member.getNickname()))
            .orElseGet(() -> {
                Member member = signUp(userInfo);
                return LoginResponse.isNew(getAccessToken(member), member.getNickname());
            });
    }

    private String getAccessToken(Member member) {
        return authProvider.provide(new AuthPayload(member.getId(), Role.MEMBER));
    }

    private Member signUp(UserInfo userInfo) {
        return memberRepository.save(userInfo.toMember());
    }
}
```

2023-09-10 12:05 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/application/AuthService.java
>      }
AuthService는 다음과 같이 될 것 같네요
```java
@Service
public class AuthService {
    ...
    public LoginResponse login(LoginRequest request) {
        UserInfo userInfo = getUserInfo(request);
        return loginService.login(userInfo);
    }
    ...
}
```

2023-09-10 12:13 UTC, seokjin8678 requested changes
몇 가지 제 생각 남겼습니다!

2023-09-10 12:13 UTC, seokjin8678 commented on backend/src/test/java/com/festago/auth/application/LoginServiceTest.java
> +    }
기존에는 `@BeforeEach`로 Mock을 초기화 시켜줬네요!
다음과 같이 하는건 어떠신가요?
```suggestion
@Mock
MemberRepository memberRepository;

@Mock
AuthProvider authProvider;

@InjectMocks
LoginService loginService;
```

2023-09-10 12:13 UTC, seokjin8678 commented on backend/src/test/java/com/festago/auth/application/AuthServiceTest.java
> +    AuthProvider authProvider;
해당 부분도 `@InjectMocks`를 사용해도 좋을 것 같아요!

2023-09-10 12:28 UTC, xxeol2 commented on backend/src/main/java/com/festago/auth/application/AuthService.java
>      }
> LoginService 클래스에서 DTO를 반환하는게 아니라, 바로 LoginResponse를 반환하게 하는건 어떠신가요?

이 부분 저도 고민했었는데요!
( 0ce300bdabd0d31b57bf361054917b75c1c7b164 이 커밋에는 글렌이 말씀하신 구조로 되어있어요 )

지금 accessToken 생성하는 부분은 트랜잭션에 포함되지 않아도 되는 부분 인 것 같아, 트랜잭션 범위 최소화하는김에 해당 부분도 제외해볼까? 라는 생각에서 제외했어요!
나중에 RefreshToken을 Redis에 저장한다고 했을 때, Redis I/O도 트랜잭션에 포함되지 않아도 될 것 같기도 했구요!

하지만 이렇게 하니 확실히 가독성이 떨어지는 부분이 있네요!
어느것이 좋아보이시나요!!

2023-09-10 13:24 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/application/AuthService.java
>      }
내일 모여서 토론해봅시다!

2023-09-10 16:06 UTC, carsago commented on backend/src/main/java/com/festago/auth/application/AuthService.java
>      }
저는 AuthService에 AuthProvider가 있는게, 더 자연스럽다고 여겨져서 바꾸신게 더 좋았어요. 글렌 말씀대로 월욜에 이야기해보죠

2023-09-11 05:12 UTC, BGuga reviewed
수고하셨습니다 간단한 리뷰 남겼습니다!!

2023-09-11 05:12 UTC, BGuga commented on backend/src/main/java/com/festago/auth/application/AuthFacadeService.java
> +        String accessToken = getAccessToken(member);
매의 눈 @_@ Service 에서 Entity 를 반환해주고 있네요!! 해당 Service 에는 @Transanction 이 없어서 Entity 프록시 에러가 발생할 것 같아요!!
Service 가 반환하는 LoginMemberDto 에 UserDto 를 사용하도록 만들고
getAccessToken 에는 UserDto 기반으로 authProvicer.provide(UserDto userDto)를 전달하도록 만들면 어떨까요?

2023-09-11 05:14 UTC, xxeol2 commented on backend/src/main/java/com/festago/auth/application/AuthFacadeService.java
> +        String accessToken = getAccessToken(member);
@_@

2023-09-11 05:16 UTC, seokjin8678 approved these changes
깔끔하네요!

2023-09-11 05:23 UTC, carsago approved these changes

2023-09-11 08:47 UTC, merged