[BE] feat: 동시 요청 시 발생할 수 있는 중복 회원 생성 문제 해결 (#443)
woowacourse-teams/2023-festa-go pull request #445
Opened 2023-09-15 01:22 UTC by xxeol2

## 📌 관련 이슈

- closed: #443

2023-09-15 01:30 UTC, seokjin8678 requested changes
flyway 관련한 리뷰 남겼습니다!

2023-09-15 01:30 UTC, seokjin8678 commented on backend/src/main/java/com/festago/member/domain/Member.java
> +)
flyway에도 적용이 필요할 것 같은데.. 혹시 해당 제약조건으로 인한 예외는 발생하지 않던가요?

2023-09-15 09:14 UTC, xxeol2 commented on backend/src/main/java/com/festago/member/domain/Member.java
> +)
V3 스크립트 추가완료했습니다 👍
플라이웨이 도입 후 첫 엔티티변경이라 깜빡했네요 😳

2023-09-17 05:32 UTC, carsago approved these changes
단순 제약 조건 추가라 바로 approve 하겠습니다. 
Service 부분에서 로깅 처리도 지금은 중복이 따로 없으니 작성하신 코드처럼 간결하게 하는게 좋겠네요

2023-09-17 13:24 UTC, seokjin8678 approved these changes
flyway 반영 확인했습니다~ 👍
머지 진행시켜

2023-09-18 08:49 UTC, BGuga approved these changes
수고하셨습니다👍
merge 진행시켜

2023-09-18 08:50 UTC, merged