[BE] feat: 스태프 인증 처리시 FCM 을 통해 유저 핸드폰에 입장 처리 완료 메시지를 보낸다(#444)
woowacourse-teams/2023-festa-go pull request #449
Opened 2023-09-15 14:09 UTC by BGuga

## 📌 관련 이슈

- closed: #444 

## ✨ PR 세부 내용

참고한 글을 다음과 같습니다.
[글 1](https://backtony.github.io/spring/2021-08-20-spring-fcm-1/) , [글2](https://kbwplace.tistory.com/179)

구현한 내용은 다음과 같습니다.
1. FirebaseMessaging 을 통해서 Android Client 에게 메시지를 보낼 수 있습니다.
2. Android Client 에 대한 식별자는 fcmToken 이며, 해당 데이터를 가진 MemberFCM Entity 로 설계하였습니다.
3. fcmToken 은 로그인 요청 시  LoginRequest dto 로 넘어옵니다.
4. fcmToken의 만료는 유저가 앱을 지웠거나, 내부 데이터를 지울 때 등 자연적인 상황에서는 발생하지 않습니다. [Reference](https://stackoverflow.com/questions/41982619/when-does-a-fcm-token-expire)

여기서 추가적으로 논의해야할 포인트는
1. 멤버의 모든 FCM 을 지우지 않기 위해서는 멤버의 디바이스에 대한 식별자가 필요합니다. 
유저가 여러 디바이스에서 로그인할 경우 한 유저에 대한 FCM 은 다수가 저장될 수 있습니다.
현재는 로그인 시 넘어오는 FCM 으로 유저의 모든 FCM 을 지우고 새로운 FCM 하나로 대체하는 방식으로 구현해두었습니다.
2. channelId로 이벤트 구분 하는 로직 필요
Token 을 통해 유저를 식별할 수 있었다면 해당 유저에게 어떤 이벤트를 보낼 것인가는 Channel 이란 단위로 구분할 수 있습니다.
해당 개념을 반영한 부분은 [다음]과 같습니다.
추후에 이벤트가 늘어남에 따라서 이벤트에 대한 명세를 맞추면서 개발을 지속해 나가야할 것 같습니다.
현재는 이벤트 하나이기 때문에 이런 구분이 필요없기에 null 을 넣어놨습니다.

2023-09-16 06:22 UTC, xxeol2 requested changes
수고하셨습니다아 !!
멋지네요..

2023-09-16 06:22 UTC, xxeol2 commented on backend/src/main/java/com/festago/auth/application/AuthFacadeService.java
> +        LoginMemberDto loginMember = authService.login(getUserInfo(request), request.fcmToken());
사소한 제안인데 getUesrInfo(request)를 인라인 말고 변수 추출하는건 어떨까요?
Oauth2Clients에게 요청을 하고 -> tx 시작하고 -> 토큰 발급하고
이 흐름에서 첫번째 단계가 눈에 잘 보이지 않는 것 같아요

2023-09-16 06:22 UTC, xxeol2 commented on backend/src/main/java/com/festago/auth/application/AuthService.java
> +
delete해주는건 해당 기기에서의 이전 FCM 토큰을 지워주기 위해서일까요 ?!
꼼꼼한 처리 좋네요 👍

2023-09-16 06:22 UTC, xxeol2 commented on backend/src/main/java/com/festago/entry/application/EntryService.java
> +        publisher.publishEvent(new EntryProcessEvent(memberTicket.getOwner().getId()));
어떤 memberTicket에 대한 fcm인지는 구분해주지 않아도 되나요?!
(fcm 메세지에 memberTicketId는 함께 보내지 않아도 되나요?)

2023-09-16 06:22 UTC, xxeol2 commented on backend/src/main/java/com/festago/fcm/application/FCMNotificationFacade.java
> +    @Async
왜 EventListener가 아닌 TransactionalEventListener를 사용하셨나요 ?!

2023-09-16 06:22 UTC, xxeol2 commented on backend/src/main/java/com/festago/fcm/domain/MemberFCM.java
> +    }
얘는 왜 InternalServerException이 아닌 IllegalArgumentException인가요?

2023-09-16 06:22 UTC, xxeol2 commented on backend/src/main/java/com/festago/fcm/config/FCMConfig.java
> +    }
사용하는 메서드 아래에 위치시키면 좋을 것 같아요!

2023-09-16 06:22 UTC, xxeol2 commented on backend/src/main/resources/db/migration/V3__MembeFCM_Added.sql
> +            references member (id);
#443 PR에 V3가 있는데, merge할 때 주의해야할 것 같네요!!

2023-09-16 06:22 UTC, xxeol2 commented on backend/src/test/java/com/festago/fcm/repository/MemberFCMRepositoryTest.java
> +}
EOF!!
몇몇 파일에 EOF 문구가 떠요!! 전체적으로 확인해주세용

2023-09-17 03:43 UTC, xxeol2 requested changes
코멘트 몇가지 더 남겼어요!

2023-09-17 03:43 UTC, xxeol2 commented on backend/src/main/java/com/festago/entry/dto/EntryProcessEvent.java
> +}
```suggestion
public record EntryProcessEvent(
    Long memberId) {

}
```

2023-09-17 03:43 UTC, xxeol2 commented on backend/src/main/java/com/festago/fcm/application/FCMNotificationFacade.java
> +    private final MemberFCMService memberFCMService;
이친구들 공백 없이 붙여줘도 괜찮을 것 같아요

2023-09-17 03:43 UTC, xxeol2 commented on backend/src/main/java/com/festago/fcm/application/FCMNotificationFacade.java
> +    public void receiveEvent(EntryProcessEvent event) {
receiveEvent보다 의미있는 메서드명을 사용하면 좋을 것 같아요
이벤트 리스너가 여러개로 늘어나면 메서드명으로 해당 리스너가 어떤 일을 하는지 나타내는것이 필요할 것 같기도 하구요!
sendFcmNotification 과 같은 메서드가 있을 것 같네요

2023-09-17 05:43 UTC, BGuga commented on backend/src/main/java/com/festago/auth/application/AuthFacadeService.java
> +        LoginMemberDto loginMember = authService.login(getUserInfo(request), request.fcmToken());
인정인정 무조건 줄 수 줄이는게 좋은건 아닌 것 같아요 👍

2023-09-17 05:44 UTC, BGuga commented on backend/src/main/java/com/festago/auth/application/AuthService.java
> +
안지우면 글x 가 또..ㅋㅋㅋ

2023-09-17 05:46 UTC, BGuga commented on backend/src/main/java/com/festago/entry/application/EntryService.java
> +        publisher.publishEvent(new EntryProcessEvent(memberTicket.getOwner().getId()));
지금은 이벤트가 딱 하나니까 그냥 이벤트가 날라왔다?  -> 다음 화면으로 이동 이렇게 구현되어 있어요!!
애쉬가 말씀 주신 것처럼 memberTicketId 를 같이 보내서 android 에서도 검증을 할 수 있게 만들면 더 좋겠네요 ㅎㅎ
이건 안드로이드 분들과 한번 같이 이야기해보져

2023-09-17 05:51 UTC, BGuga commented on backend/src/main/java/com/festago/fcm/config/FCMConfig.java
> +    }
앗 ㅋㅋ 감사합니다

2023-09-17 05:52 UTC, BGuga commented on backend/src/test/java/com/festago/fcm/repository/MemberFCMRepositoryTest.java
> +}
edu 설정을 빼먹었네요 ㅠㅠ 설정 달아놓고 개행 추가했어요!

2023-09-17 05:52 UTC, BGuga commented on backend/src/main/java/com/festago/fcm/application/FCMNotificationFacade.java
> +    private final MemberFCMService memberFCMService;
앗 싸웠었나봐요 붙혀뒀습니다

2023-09-17 05:53 UTC, BGuga commented on backend/src/main/java/com/festago/fcm/application/FCMNotificationFacade.java
> +    public void receiveEvent(EntryProcessEvent event) {
오 그렇네요 메서드명 감사합니다

2023-09-17 05:53 UTC, xxeol2 commented on backend/src/test/java/com/festago/fcm/repository/MemberFCMRepositoryTest.java
> +}
edu도 이 기능이 지원돼요 ? 😁

2023-09-17 06:04 UTC, BGuga commented on backend/src/main/java/com/festago/fcm/domain/MemberFCM.java
> +    }
도메인 validation 을 잡을 때 이게 BadRequest 인지 InteralServerException 인지 어떻게 결정하면 좋을까 고민이 됐습니다.
또한 도메인 안에서 Http status 가 결정되는 것이 맞나..? 라는 생각을해서 도메인에서 표준 예외를 발생시키도록 만들었습니다.
그 에외에 대한 판단은 Service 에서 해당 도메인의 생성에서 예외가 발생한 것은 InteralServerException 이다, BadRequest 이다. 이렇게 판단하면 좋지 않을까 생각했었습니다!!

2023-09-17 08:14 UTC, carsago reviewed
푸우 테스트도 꼼꼼하게 작성하셨네요!! 고생하셨습니다, 간단한 리뷰 몇개 남겼습니다.

2023-09-17 08:14 UTC, carsago commented on backend/src/main/java/com/festago/fcm/application/FCMNotificationFacade.java
> +    private void checkAllSuccess(BatchResponse batchResponse, Long memberid) {
```suggestion
    private void checkAllSuccess(BatchResponse batchResponse, Long memberId) {
```
발견

2023-09-17 08:56 UTC, xxeol2 commented on backend/src/main/java/com/festago/fcm/application/FCMNotificationFacade.java
> +public class FCMNotificationFacade {
저도 FCMNotificationService 좋은 것 같아요!

2023-09-17 08:56 UTC, xxeol2 commented on backend/src/main/java/com/festago/fcm/application/FCMNotificationFacade.java
> +    private void checkAllSuccess(BatchResponse batchResponse, Long memberid) {
옥상갈뻔했네요

2023-09-17 15:38 UTC, seokjin8678 commented on backend/src/main/java/com/festago/fcm/application/FCMNotificationFacade.java
> +    private void checkAllSuccess(BatchResponse batchResponse, Long memberid) {
옥상 슈우웃

2023-09-17 16:41 UTC, seokjin8678 requested changes
애쉬랑 오리가 대부분 리뷰 남겨주셔서 크게 리뷰 남길 것은 없었네요.
구현체에 많이 의존하는 부분이 보여서, 해당 부분 개선해주시면 좋을 것 같아요.

2023-09-17 16:41 UTC, seokjin8678 commented on backend/src/main/java/com/festago/fcm/application/FCMNotificationFacade.java
> +public class FCMNotificationFacade {
해당 클래스는 이벤트 리스너로 작동하고 있으니, `Serivce`라는 명칭보다는 다른 이름을 갖게 하는 것도 좋아보이네요.
또한 알람을 보내는 것은 비즈니스 로직에 관련된 부분이 아니니까 `@Profile`을 사용해서 프로덕션이나 데브 환경에서만 빈 등록을 하는 것도 좋아보이네요.

2023-09-17 16:41 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/application/AuthService.java
> +    }
`Auth` 도메인에 외부 API 구현체인 `FCMRepository`가 섞여있네요.
해당 부분은 이벤트를 사용해보는 것은 어떤가요?

2023-09-17 16:41 UTC, seokjin8678 commented on backend/src/main/resources/db/migration/V3__MembeFCM_Added.sql
> +            references member (id);
해당 이슈 때문에 버전을 `V202309180138` 이렇게 사용하기도 한다네요

2023-09-17 16:41 UTC, seokjin8678 commented on backend/src/test/java/com/festago/FestaGoApplicationTests.java
> +
DIP를 지켜야 할 것 같네요

2023-09-20 13:12 UTC, BGuga commented on backend/src/main/java/com/festago/fcm/application/FCMNotificationFacade.java
> +        List<Message> messages = createMessages(getMemberFCMToken(event.memberId()), null);
이건 안드로이드 분들이랑 디폴트 값을 뭘로 지정해 놓을지 이야기하고 null 대신 값을 넣겠습니다 👍

2023-09-20 17:22 UTC, BGuga commented on backend/src/main/java/com/festago/fcm/domain/MemberFCM.java
> +    @ManyToOne
✅

2023-09-20 17:23 UTC, BGuga commented on backend/src/main/java/com/festago/auth/application/AuthService.java
>  public class AuthService {
✅

2023-09-20 17:23 UTC, BGuga commented on backend/src/main/java/com/festago/auth/application/AuthService.java
> +    }
✅

2023-09-20 17:24 UTC, BGuga commented on backend/src/test/java/com/festago/FestaGoApplicationTests.java
> +
Profile 로 Test 환경에서 보이지 않도록 했습니다 !!

2023-09-20 17:50 UTC, BGuga commented on backend/src/test/java/com/festago/FestaGoApplicationTests.java
> +
Profile 테스트 환경에서 상관쓰지 않도록 변경했습니다 !!

2023-09-26 04:05 UTC, BGuga commented
로그인 시 FCM 이 생성되거나 갱신해야하는 사례처럼
로그인, 회원 탈퇴와 같이 사용자 계정의 생명주기와 memberFCM 의 생명 주기는 상당히 밀접한 관계를 가집니다.
eventListening 을 쓰는 이유는 의존성 분리를 통해 해당 메서드의 관심사만 처리할 수 있기 때문입니다.
하지만 로그인 과정의 성공 여부를 결론을 짓기위해서는 fcm 의 생성 여부까지 포함되기 때문에 fcm은 로그인이라는 과정의 관심사에 포함됩니다.
그렇기 때문에 다음 두 가지 작업을 추가 진행했습니다.
1. auth 패키지 내에 MemberFCM 을 위치 시켰으며
2. authService 내부에서 FCM 생성 로직을 배치하였습니다.

2023-09-26 07:28 UTC, xxeol2 approved these changes
수고많으셨습니다 푸우 🫡

2023-09-26 07:28 UTC, xxeol2 commented on backend/src/main/java/com/festago/fcm/application/MemberFCMService.java
> +            log.error("member {} 의 FCM 코드가 발급되지 않았습니다.", memberId);
```suggestion
            log.error("member {} 의 FCM 토큰이 발급되지 않았습니다.", memberId);
```
사소한건데 이거 어떤가요 ㅋㅋㅋ

2023-09-26 07:28 UTC, xxeol2 commented on backend/src/main/java/com/festago/common/exception/ErrorCode.java
> +    FCM_NOT_FOUND("유효하지 않은 MemberFCM 이 감지 되었습니다.");
```suggestion
    FAIL_SEND_FCM_MESSAGE("FCM Message 전송에 실패했습니다."),
    FCM_NOT_FOUND("유효하지 않은 MemberFCM 이 감지 되었습니다."),
    ;
```

2023-09-26 07:28 UTC, xxeol2 commented on backend/src/main/java/com/festago/fcm/application/FCMNotificationEventListener.java
> +    private static final Logger logger = LoggerFactory.getLogger(FCMNotificationEventListener.class);
```suggestion
    private static final Logger log = LoggerFactory.getLogger(FCMNotificationEventListener.class);
```

아래 코드와 통일하면 좋을 것 같아요!

2023-09-26 08:47 UTC, seokjin8678 approved these changes
고생하셨습니다!

2023-09-26 08:52 UTC, carsago approved these changes
고생하셨어요.

2023-09-26 10:13 UTC, merged