[BE] 학생 인증이 완료된 사용자만 재학생용 티켓을 발급 (#446)
woowacourse-teams/2023-festa-go pull request #457
Opened 2023-09-21 01:48 UTC by xxeol2

## 📌 관련 이슈

- closed: #446

## ✨ PR 세부 내용

Ticket -> Stage -> Festival -> School 로 가서 학교 정보를 가져오면 depth가 너무 깊어
Ticket에도 School을 가지도록 반정규화 했습니다.

School 등록시 name, domain UNIQUE 조건을 일단 추가하지 않았는데, 의견 부탁드립니다!

2023-09-21 16:24 UTC, seokjin8678 requested changes
많은 일을 해주셨군요 👍
이번에 Ticket의 School에 대한 참조를 간접 참조로 해보는 것은 어떨지 싶네요!

2023-09-21 16:24 UTC, seokjin8678 commented on backend/src/main/java/com/festago/ticket/domain/Ticket.java
> +    private School school;
Ticket 도메인은 School 도메인을 직접 참조하는 것 보다, Long으로 간접 참조하는 것은 어떤가요?

2023-09-26 06:36 UTC, xxeol2 commented on backend/src/main/java/com/festago/school/application/SchoolService.java
> +    }
- #460 

위의 PR에서 작업 진행

2023-09-26 07:15 UTC, seokjin8678 requested changes
고생하셨습니다!
간접 참조를 처음 사용하는데 과연 어떠한 변화가 있을지 기대가 되네요

2023-09-26 07:15 UTC, seokjin8678 commented on backend/src/main/java/com/festago/ticket/repository/TicketRepository.java
>          """)
fetch할때 학교를 제외할 수 있으니 성능이 더 향상 되겠네요 👍

2023-09-26 07:24 UTC, carsago approved these changes
고생하셨습니다.

2023-09-26 09:00 UTC, BGuga approved these changes
수고하셨습니다!!

2023-09-26 09:06 UTC, xxeol2 commented on backend/src/main/resources/db/migration/V4__add_school_fk.sql
> +            references school (id);
선이요

2023-09-26 09:06 UTC, merged