[BE] feat: 어드민 페이지 추가 관리 기능 추가, 개선 (#459)
woowacourse-teams/2023-festa-go pull request #460
Opened 2023-09-26 03:05 UTC by seokjin8678

## 📌 관련 이슈

- closed: #459

## ✨ PR 세부 내용

기존 단일 페이지에서 관리되었던 어드민 기능을 별도의 페이지로 분리하여 편의를 개선했습니다.

추가된 페이지의 URL은 다음과 같습니다.
`admin/schools`: 학교 목록 조회, 학교 추가
`admin/schools/{id}`: 학교 상세 조회
`admin/festivals`: 축제 목록 조회, 추가
`admin/festivals/{id}`: 축제 상세 조회, 축제에 대한 공연 목록, 공연 추가
`admin/stages/{id}`: 공연 상세 조회, 티켓 목록 조회, 티켓 추가

또한 어드민 기능 중 View에 관한 기능을 제외한 API 기능은 `admin/api`로 시작하도록 했습니다.
`api/admin`을 생각할 수 있었지만, 기존의 다른 컨트롤러에서 URL 매핑이 `api`로 시작되지 않았기 때문에 위와 같은 결정을 했습니다.

도메인의 변경 사항도 포함이 되어 있는데, 수정 기능을 만들면서 도메인의 검증 로직을 재사용이 필요하도록 변경하여 `Validator` 클래스를 만들어 사용하였습니다.
지금은 `Stage`, `Festival`, `School`만 적용되어 있고 해당 검증 로직이 좋다면 다른 도메인 로직에도 적용하는게 어떨까 합니다.

또한 수정 로직에서 추가적인 검증 로직이 필요합니다. 예를들어 공연이 등록된 축제가 있을 때, 축제의 날짜를 수정하면 기존의 공연의 날짜는 무시하고 수정이 가능합니다. (8월 20일 축제, 8월 20일 공연에서 7월 20일 또는 9월 20일 축제로 수정이 가능함)
따라서 수정 시 등록된 공연이 있거나 하면 수정이 되지 않거나 다른 방법을 찾아야 할 것 같습니다. (혹은 어드민 기능에서 이러한 정합성을 무시하고 강제로 수정이 되게 하는 것도 오히려 기능이 될 수 있을 것 같습니다.)

추가적인 변경 사항이나 봐야할 부분에 대해서는 코드에 커멘트로 남기겠습니다.

2023-09-26 03:09 UTC, seokjin8678 commented on backend/src/main/java/com/festago/common/util/Validator.java
> +        }
문자열의 길이를 검증하는 로직에서 null 값이 들어오면 NPE가 발생하기 때문에 다음과 같이 조건문을 작성했습니다.
예외를 던지지 않고, return(검증이 true)인 이유는 길이 검증 로직에서 null을 검사하는 것은 한 번에 두 가지 행위를 한다고 판단하여 null 검사는 다른 로직에서 해주는 것이 맞다고 판단했습니다.
혹은 차라리 NPE가 발생하게 두는 것도 좋을 것 같기도 하네요.

2023-09-26 03:12 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/application/FestivalService.java
> +    }
삭제 로직은 다음과 같이 `DataIntegrityViolationException`을 catch 하도록 하여서, 외래키 제약 조건에 걸린 부분을 400 에러로 바꿔주었습니다.
해당 try-catch 문을 사용하지 않으면 500번대 에러가 반환되더군요.
또한 `flush()`를 호출한 이유는 쓰기 지연 때문에 AOP로 인한 해당 메소드 밖에서 예외가 발생하기 때문에 명시적으로 `flush()`를 호출했습니다.

2023-09-26 05:12 UTC, xxeol2 commented
- https://github.com/woowacourse-teams/2023-festa-go/pull/457
해당 PR과 많은 충돌이 날 것으로 예상되네요 🥲

2023-09-26 15:56 UTC, xxeol2 requested changes
정말 많은 변화가 있었네요..
수고 정말 많으셨습니다 👍
프론트까지 마스터해버린 글선생님..

몇가지 자잘자잘한 코멘트 남겼는데, 의견 궁금해서 RC로 남깁니다!!

2023-09-27 01:45 UTC, seokjin8678 commented on backend/src/main/java/com/festago/common/util/Validator.java
> +        }
해당 부분에서 고민을 좀 했는데, Spring에서 제공하는 "Assert" 클래스를 사용하는 검증 로직에서는 `IllegalArgumentException`을 던져서 다음과 같이 예외를 던졌네요!
해당 부분에 대해서는 다 같이 논의를 해봐야 할 것 같아요!

2023-09-27 01:47 UTC, seokjin8678 commented on backend/src/main/java/com/festago/common/util/Validator.java
> +        }
해당 기능은 새로운 이슈를 만들어서 모든 도메인에 대해 한 번에 적용하겠습니다!

2023-09-27 01:48 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/domain/Festival.java
> +        Assert.notNull(name, "name은 null 값이 될 수 없습니다.");
https://github.com/woowacourse-teams/2023-festa-go/pull/460#discussion_r1337942428

2023-09-27 01:52 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/config/LoginConfig.java
> +            .excludePathPatterns("/admin/login", "/admin/api/login", "/admin/api/initialize");
PathPatterns에 `/admin/**`이 포함되어 있으니까 괜찮을 것 같네요!

2023-09-27 09:00 UTC, BGuga requested changes
안녕하세요 js 코드는 잘 몰라서 코드적 피드백 보다는 사용하면서 확인해봤는데 큰 문제는 없어 보입니다👍
몇 가지 리뷰 남겼으니 확인해주세요!!

2023-09-29 07:24 UTC, xxeol2 commented on backend/src/main/java/com/festago/common/util/Validator.java
> +        }
저도 푸우 말씀에 동의합니다! festival을 지워줄 때, 연관 엔티티들도 전부 지워주는 로직이 필요할 것 같아요
다만 이 부분은 조금 복잡할 것 같아서, 이번 PR 머지 후 별도의 PR에서 진행되어도 좋을 것 같아요

2023-09-29 07:25 UTC, xxeol2 commented on backend/src/main/java/com/festago/festival/application/FestivalService.java
> +    }
저도 푸우 말씀에 동의합니다! festival을 지워줄 때, 연관 엔티티들도 전부 지워주는 로직이 필요할 것 같아요
다만 이 부분은 조금 복잡할 것 같아서, 이번 PR 머지 후 별도의 PR에서 진행되어도 좋을 것 같아요

2023-09-30 04:33 UTC, seokjin8678 commented on backend/src/main/java/com/festago/common/util/Validator.java
> +        }
https://github.com/woowacourse-teams/2023-festa-go/issues/482

2023-09-30 04:37 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/application/FestivalService.java
> +        validate(festival);
지금은 수정 같은 경우 단순하게 생성자에 사용하는 검증만 적용하고, 비즈니스 룰에 따른 검증은 적용하지 않았습니다.
제시해주신 썸네일의 변경 같은 경우 비즈니스 룰에 적용될 것 같네요!
이러한 비즈니스 룰은 다 같이 모여서 회의 후 결정해야 할 내용같아서 적용하지 않았습니다!
따라서 지금은 단순히 수정이 가능하다 로 생각하시면 좋을 것 같아요!

2023-09-30 04:51 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/application/FestivalService.java
> +        if (!festival.canCreate(LocalDate.now(clock))) {
https://enterprisecraftsmanship.com/posts/specification-pattern-always-valid-domain-model/
다음과 같이 검증을 생성자에서 하는 것과 별도의 클래스에서 하는 패턴을 봤는데요, 생성의 검증과 생성 후 사용의 검증을 분리한다면 어떨까 싶네요.
`Fesitval` 인스턴스를 생성할 때는 원시적인 값만 검증하고(null, length 등), 해당 인스턴스를 영속할 때 `Specification` 객체를 사용하여 비즈니스 룰에 대한 검증을 수행하는 것도 좋아 보이네요.
```java
public FestivalResponse create(FestivalCreateRequest request) {
    ...
    Festival festival = request.toEntity(school);
    Result result = festivalSpecification.isSatisfiedBy(festival);
    if (result.isFailure()) {
        throw new BadRequestException(result.errorCode());
    }
    return FestivalResponse.from(festivalRepository.save(festival));
}
```

2023-09-30 04:54 UTC, seokjin8678 commented
@BGuga 
https://github.com/woowacourse-teams/2023-festa-go/pull/460#discussion_r1338282803 해당 커멘트에 답글이 달리지 않아서 새로운 커멘트로 남깁니다.

애쉬의 답변처럼 새로운 이슈를 생성하여 적용해도 좋을 것 같네요!
https://github.com/woowacourse-teams/2023-festa-go/pull/460#discussion_r1341005054

2023-09-30 04:55 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/application/FestivalService.java
> +    }
애쉬 답글처럼 새로운 이슈를 만들어서 해야 좋을 것 같아요!
협의해야할 내용이기도 하구요!

2023-09-30 05:41 UTC, BGuga commented on backend/src/main/java/com/festago/festival/application/FestivalService.java
> +        if (!festival.canCreate(LocalDate.now(clock))) {
글을 보면서 이해가 잘 안되는 부분이 있는데..
Specifiacation 을 왜 제일 먼저 호출해주는 것인가요??
글의 예시 중  enroll을 호출하기전 specification 을 먼저 호출하는데 그러면 그 이후에 일어난 변화에 대한 검증 로직은 따로 두는 것인가요??

2023-10-01 02:05 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/application/FestivalService.java
> +        if (!festival.canCreate(LocalDate.now(clock))) {
글의 어떤 번호의 어디 부분인지 알려주실 수 있을까요??

우선 해당 방식을 사용하는 이유는 검증 로직의 재활용도 있지만, 레이어드 아키텍쳐 관점에서 응집도 있는 도메인 로직을 위해 검증 로직을 도메인 계층에 몰아 넣으려고 해당 방법을 사용하는 것 같네요.

지금은 적용했을 때 어떠한 점에서 이점을 누릴 수 있을지는 아직 모르겠지만..
현재로서 application 레이어인 Serivce 클래스에 도메인 검증 규칙이 포함되어 있습니다.

예를들면 `TicketingService` 객체의 `validateStudent`, `validateAlreadyReserved` 메소드가 되겠네요.
이러한 검증 로직은 단순한 값을 검증하는 것을 넘어 저희의 비즈니스 룰에 관련된 검증 로직이기 때문에 도메인 계층에서 관리되어야 합니다.

하지만 검증을 하려면 `Repository` 계층의 의존이 필수적이므로(그렇지 않으려면 연관된 엔티티를 모두 불러오고 검증해야 하는 엄청난 비효율의 극치가..) 어쩔 수 없이 `Service` 계층에서 검증할 수 밖에 없습니다.

따라서 이런 비즈니스 룰이 도메인 계층이 아닌 서비스 계층에 있는 것이죠..

그렇다고 해서 다음과 같이 도메인 계층에 파라미터로 Repository를 넘기는 것은 더 아닌 것 같아 보입니다.
```java
class MemberTicket {
    ...
    public MemberTicket(MemberTicketRepository memberTicketRepository, ...) {
        ...
        if (memberTicketRepository.existsByOwnerAndStage(member, ticket.getStage())) {
            throw new BadRequestException(ErrorCode.RESERVE_TICKET_OVER_AMOUNT);
        }
        ...
    } 
}
```
따라서 이러한 불합리한 선택 속에서 `Specification`이라는 도메인 객체를 만들어 영속성 계층에 의존되는 비즈니스 룰은 여기서 관리가 되게 하는게 어떨까 합니다.

```java
@Service
@Transactional
public class TicketingService {
    ...
    public TicketingResponse ticketing(Long memberId, TicketingRequest request) {
        Member member = findMemberById(memberId);
        Ticket ticket = findTicketById(request.ticketId());
        validateTicketing(member, ticket);
        int reserveSequence = getReserveSequence(request.ticketId());
        MemberTicket memberTicket = ticket.createMemberTicket(member, reserveSequence, LocalDateTime.now(clock));
        memberTicketRepository.save(memberTicket);
        return TicketingResponse.from(memberTicket);
    }
    
    private void validateTicketing(Member member, Ticket ticket) {
        Result result = spec.isSatisfiedBy(member, ticket);
        result.throwIfFailure();
    }
    ...
}

@Component
public class TicketingSpecImpl implements TicketingSpec {
    ...
    @Override
    public Result isSatisfiedBy(Member member, Ticket ticket) {
        Stage stage = ticket.getStage();
        if (ticket.getTicketType() == TicketType.STUDENT
            && !studentRepository.existsByMemberAndSchoolId(member, ticket.getSchoolId())) {
            return Result.failure(ErrorCode.NEED_STUDENT_VERIFICATION);
        }
        if (memberTicketRepository.existsByOwnerAndStage(member, stage)) {
            return Result.failure(ErrorCode.RESERVE_TICKET_OVER_AMOUNT);
        }
        return Result.success();
    }
    ...
}
```
연관된 엔티티가 간접 참조로 관리가 된다면 해당 방법이 거의 무조건 필수일 것 같기도 하네요. (도메인 객체에서 바로 엔티티로 참조할 수 없고 영속성 계층을 무적권 거쳐야 하니까)

Specification에 관한 더 자세한 얘기는 [블로그](https://americanopeople.tistory.com/389) 참고하시면 될 것 같습니다.

2023-10-01 02:09 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/application/FestivalService.java
> +        if (!festival.canCreate(LocalDate.now(clock))) {
물론 영속성 계층을 거치지 않는다면 Specification 객체를 사용하지 않고 도메인 객체에 비즈니스 룰을 포함시키는 것이 제일 좋을 것 같네요.
우선 여기 핵심은 검증을 하려면 외부에서 한 번 더 호출을 해야한다는 점이니... 생성할 때 바로 검증을 할 수 있는 것이 제일 좋다고 생각합니다.

2023-10-01 08:49 UTC, carsago requested changes
넘 늦게했네요.. 간단한거 달았습니다.

2023-10-01 08:49 UTC, carsago commented on backend/src/main/java/com/festago/festival/application/FestivalService.java
> +    }
말씀하신 delete도 그렇고, 실제로 사용한다고 가정하면 festival의 update도 stage, ticket등의 시간 관련 로직에 대한 검증도 필수적으로 필요할테니.. 새로운 이슈에서 논의하고 적용 할 필요가 있다고 생각합니다. 지금은 PR이 너무 커진것 같아서..

2023-10-01 08:49 UTC, carsago commented on backend/src/main/java/com/festago/festival/application/FestivalService.java
> +        if (!festival.canCreate(LocalDate.now(clock))) {
결국 객체 생성의 검증 로직이 커지면 커질 수록 글렌이 링크 주신 방식대로 나누는 것도 유의미하다고 생각합니다.
그렇다면 validation의 영향 없이, 도메인 객체의 다른 로직들을 쉽게 테스트할 수 있을테니까요.

다만 지금은 저희 객체들이 거의 값만 가지고 있고, 별도의 행위는 거의 없어서 체감이 안될거 같긴해요.
이제 수정 작업도 생겼으니까, 언제 정합성이 깨지고, 이런 부분을 어떻게 중복을 적고, 유연한 코드로 보장해줄지에 대한 이야기가 필요할 거 같긴 해요.

2023-10-05 03:16 UTC, BGuga commented on backend/src/main/java/com/festago/festival/application/FestivalService.java
> +        if (!festival.canCreate(LocalDate.now(clock))) {
```
@Component
public class TicketingSpecImpl implements TicketingSpec {
    ...
    @Override
    public Result isSatisfiedBy(Member member, Ticket ticket) {
        Stage stage = ticket.getStage();
        if (ticket.getTicketType() == TicketType.STUDENT
            && !studentRepository.existsByMemberAndSchoolId(member, ticket.getSchoolId())) {
            return Result.failure(ErrorCode.NEED_STUDENT_VERIFICATION);
        }
        if (memberTicketRepository.existsByOwnerAndStage(member, stage)) {
            return Result.failure(ErrorCode.RESERVE_TICKET_OVER_AMOUNT);
        }
        return Result.success();
    }
    ...
}
```
여기서 specification의 인터페이스 메서드가

```
public Result isSatisfy(MemberTicket memberTicket)
```
으로 정의되어야 하는 것 아닌가요??

2023-10-05 06:11 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/application/FestivalService.java
> +        if (!festival.canCreate(LocalDate.now(clock))) {
`MemberTicket` 엔티티를 생성하려면 우선, `reserveSequence`를 알아야 합니다..
`reserveSequence`을 구하려면 `getReserveSequence()` 메소드를 호출해서 락을 걸어야 하기 때문에 `MemberTicket`을 만들고 검증하는 것 보다, `MemberTicket`을 만들 수 있는 상태인지 검증하는게 우선이 되어야 합니다.

2023-10-05 09:24 UTC, BGuga commented on backend/src/main/java/com/festago/festival/application/FestivalService.java
> +        if (!festival.canCreate(LocalDate.now(clock))) {
Specification 사용 예시들을 보면 [참고1](https://en.wikipedia.org/wiki/Specification_pattern#Python) [참고2](https://leejaedoo.github.io/repository_select_jpa/) 
아래와 같이
```
public class Student
{
    public void EnrollIn(Course course)
    {
        bool canEnroll = new QualifiedForNewEnrollmentsSpecification().IsSatisfiedBy(this);
        if (canEnroll == false)
            throw new InvalidOperationException();

        /* Enrollment logic */
    }
}
```
DDD 에서의 specification 사용은 도메인이 해당 spec을 만족하는지 묻는 용도로 사용하는 것이 원래의 의도 같네요!
해당 부분을 응용해서 생성 로직을 spec으로 정의하여 복잡한 검증 로직을 풀어내는게 좋은 것 같네요 👍

2023-10-05 10:11 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/application/FestivalService.java
> +        if (!festival.canCreate(LocalDate.now(clock))) {
`참고2`의 내용은 JPA의 `Specification`에 관한 내용이네요!
우선 지금은 생각만 해본거라 적용을 할지는 아직 모르겠네요. 오히려 복잡도가 상승할 것 같기도 해서...

2023-10-06 06:37 UTC, xxeol2 approved these changes
오랜 기간동안 수고 많으셨습니다 글렌 👍
delete 부분은 별도 이슈로 처리해보죠!!

2023-10-06 06:38 UTC, carsago approved these changes

2023-10-06 06:38 UTC, BGuga approved these changes
수고 많으셨습니다 ㅎㅎ

2023-10-06 06:38 UTC, merged