[AN/USER] feat: 학교 선택 화면 구현(#374)
woowacourse-teams/2023-festa-go pull request #461
Opened 2023-09-26 04:10 UTC by EmilyCh0

## 📌 관련 이슈

- closed: #374 

## ✨ PR 세부 내용

<img width="509" alt="image" src="https://github.com/woowacourse-teams/2023-festa-go/assets/67777523/db28e0a8-7d0a-44d8-b5a5-d280274181be">

2023-09-26 13:04 UTC, SeongHoonC requested changes
선택 화면 고생많으셨어요!
궁금한 점 리뷰 남겼습니다!

2023-09-27 01:46 UTC, EmilyCh0 commented on android/festago/app/src/main/java/com/festago/festago/data/dto/SchoolResponse.kt
> +) {
반영했습니다! 저도 분명 전에 이 문제를 겪었었는데 왜 여기서는 문제없이 돌아가는지 모르겠네요..! 그래도 순서 맞추는 것이 좋을 것 같아 수정했습니다.

2023-09-27 02:09 UTC, EmilyCh0 commented on android/festago/app/src/main/java/com/festago/festago/presentation/ui/selectschool/SelectSchoolActivity.kt
> +    }
가능은 한데 uiState에 있는 schoolSelected 값이 버튼의 enabled 값에 바인딩 되어 있어서 화면 회전 시 버튼 활성화 상태가 초기화 됩니다! 회전 대응을 하지 않거나 회전 시 다시 선택 여부를 찾아서 버튼을 설정해 줄 수 있을 것 같긴한데 뷰의 상태를 uiState가 들고 있도록 하는 것이 더 자연스럽지 않을까합니다.

2023-09-27 02:17 UTC, SeongHoonC approved these changes
LGTM!

2023-09-27 02:17 UTC, SeongHoonC commented on android/festago/app/src/main/java/com/festago/festago/presentation/ui/selectschool/SelectSchoolActivity.kt
> +    }
버튼의 활성화, 비활성화를 위해서는 그게 최선일 수 있겠네요. 이해했습니다.

2023-09-27 02:21 UTC, re4rk approved these changes
고생하셨습니다!
LGTM!

2023-09-27 02:22 UTC, merged