[BE] refactor: equest DTO Validation 추가(#462)
woowacourse-teams/2023-festa-go pull request #463
Opened 2023-09-26 07:57 UTC by xxeol2

## 📌 관련 이슈

- closed: #462

## ✨ PR 세부 내용

2023-09-30 05:18 UTC, seokjin8678 commented
충돌나는거 수정했고, 예외 메시지 일괄적이게 변경했습니다!

2023-09-30 05:20 UTC, seokjin8678 requested changes
고생하셨습니다~
추가적으로 적용해야할 부분에 대해 커멘트 밑에 남기겠습니다!

2023-09-30 05:20 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/dto/FestivalCreateRequest.java
> +    @NotNull(message = "schoolId는 null 일 수 없습니다.") Long schoolId) {
검증 어노테이션이 많아 가독성이 낮아져 컨벤션을 정해야 할 것 같네요!
제 생각에는 해당 방식이 좋아보이는데 어떠신가요?
```java
public record FestivalCreateRequest(
    @NotBlank(message = "name 은 공백일 수 없습니다.")
    String name,

    @NotNull(message = "startDate 는 null 일 수 없습니다.")
    @DateTimeFormat(iso = ISO.DATE)
    LocalDate startDate,

    @NotNull(message = "endDate 는 null 일 수 없습니다.")
    @DateTimeFormat(iso = ISO.DATE)
    LocalDate endDate,

    String thumbnail) {
}
```

2023-09-30 05:24 UTC, seokjin8678 commented
일부 Contorller에 `@Valid` 어노테이션이 빠져 있네요!
```java
public class StudentController {
    ...
    @PostMapping("/send-verification")
    public ResponseEntity<Void> sendEmail(@Member Long memberId,
                                          @RequestBody StudentSendMailRequest request) {
        studentService.sendVerificationMail(memberId, request);
        return ResponseEntity.ok()
            .build();
    }
    ...
}

2023-09-30 05:27 UTC, seokjin8678 commented
지금 `GlobalExceptionHandler` 클래스에서 `MethodArgumentNotValidException` 핸들링을 수행할 때 어떠한 필드에 값이 유효하지 않은지 알려주지 않고 `"잘못된 요청입니다."` 메시지만 반환해주고 있네요!
예외에서 `getFieldErrors()` 메서드를 통해 어떠한 검증이 실패했는지 알려주는게 좋을 것 같아요!
```java
@RestControllerAdvice
public class GlobalExceptionHandler extends ResponseEntityExceptionHandler { 
    ...
    @Override
    protected ResponseEntity<Object> handleMethodArgumentNotValid(MethodArgumentNotValidException e, HttpHeaders headers,
                                                                  HttpStatusCode status, WebRequest request) {
        return ResponseEntity.status(HttpStatus.BAD_REQUEST)
            .body(ErrorResponse.from(ErrorCode.INVALID_REQUEST_ARGUMENT));
    }
    ...
}

```

2023-09-30 06:15 UTC, BGuga commented
> 일부 Contorller에 `@Valid` 어노테이션이 빠져 있네요!
> 
> ```java
> public class StudentController {
>     ...
>     @PostMapping("/send-verification")
>     public ResponseEntity<Void> sendEmail(@Member Long memberId,
>                                           @RequestBody StudentSendMailRequest request) {
>         studentService.sendVerificationMail(memberId, request);
>         return ResponseEntity.ok()
>             .build();
>     }
>     ...
> }
> ```

2023-09-30 06:15 UTC, BGuga commented
죄송합니다 에임 이슈로 잠시 닫았었네요 😅

2023-09-30 06:22 UTC, BGuga commented on backend/src/main/java/com/festago/festival/dto/FestivalCreateRequest.java
> +    @NotNull(message = "schoolId는 null 일 수 없습니다.") Long schoolId) {
동의보감입니다.

2023-10-01 18:30 UTC, xxeol2 commented on backend/src/main/java/com/festago/festival/dto/FestivalCreateRequest.java
> +    @NotNull(message = "schoolId는 null 일 수 없습니다.") Long schoolId) {
진행시켜!

2023-10-06 05:31 UTC, carsago approved these changes
꿋이에요

2023-10-06 05:31 UTC, seokjin8678 approved these changes
고생하셨습니다!

2023-10-06 05:33 UTC, BGuga approved these changes
수고하셨습니다!

2023-10-06 05:33 UTC, merged