[BE] feat: 유저 FCM 로직 변경(#471)
woowacourse-teams/2023-festa-go pull request #472
Opened 2023-09-27 04:33 UTC by BGuga

## 📌 관련 이슈

- closed: #471 

## ✨ PR 세부 내용

1. 로그인 시 중복 FCM 확인
2. 탈퇴 시 유저 FCM 삭제
3. 모든 요청이 성공했을 시 예외를 발생시키지 않도록 변경

작업 완료했습니다.
MemberFCM table 에 (member_id, fcm_token) unique 제약 조건을 걸어주어

기존 쿼리
```
List<MemberFCM> memberFCM = memberFCMRepository.findByMemberId(memberId);
```
새로운 쿼리
```
Optional<MemberFCM> memberFCM = memberFCMRepository.findMemberFCMByMemberIdAndFcmToken(memberId, fcmToken);
```
가 인덱스 기반으로 쿼리를 날릴 수 있도록 변경하였고 unique 제약 조건으로 데이터 정합성도 맞췄습니다.

2023-09-27 06:23 UTC, seokjin8678 requested changes
리뷰 남겼습니다!

2023-09-27 06:23 UTC, seokjin8678 commented on backend/src/main/java/com/festago/fcm/application/MemberFCMService.java
> +        memberFCMRepository.save(new MemberFCM(memberId, fcmToken));
```suggestion
        if (memberFCM.isEmpty()) {
            memberFCMRepository.save(new MemberFCM(memberId, fcmToken));
        }
```
다음과 같이 해도 좋을 것 같아요

2023-09-27 06:23 UTC, seokjin8678 commented on backend/src/main/java/com/festago/fcm/application/FCMNotificationEventListener.java
> +        }
```suggestion
        if (batchResponse.getFailureCount() > 0) {
            List<SendResponse> failSend = batchResponse.getResponses().stream()
                .filter(sendResponse -> !sendResponse.isSuccessful())
                .toList();
            log.warn("member {} 에 대한 다음 요청들이 실패했습니다. {}", memberId, failSend);
        }
```
다음과 같이 최적화 할 수 있을 것 같아요!

2023-09-27 08:20 UTC, xxeol2 approved these changes
깔꼼하네요 👍

2023-09-28 11:00 UTC, carsago requested changes

2023-09-28 11:00 UTC, carsago commented on backend/src/main/java/com/festago/presentation/AuthController.java
> +        memberFCMService.saveOriginMemberFCM(accessToken, fcmToken);
이 부분 isNew 여부 boolean으로 Service에 파라미터로 보내주고 Service에서 분기타는거 어떤가요??

2023-10-05 08:49 UTC, seokjin8678 requested changes
간단하게 리뷰 남겼습니다!
최신 dev 브랜치로 가져와서 롬복만 적용하면 될 것 같아요!
고생하셨습니다!

2023-10-05 08:49 UTC, seokjin8678 commented on backend/src/main/java/com/festago/fcm/application/FCMNotificationEventListener.java
>      private void checkAllSuccess(BatchResponse batchResponse, Long memberId) {
이제 더 이상 check 하는 것이 아니니까 `logFailResponses` 정도로 해도 좋겠네요!

2023-10-05 08:49 UTC, seokjin8678 commented on backend/src/main/java/com/festago/fcm/application/MemberFCMService.java
>      }
추후 사용자의 FCM 등록 요청이 별도 API로 분리되게 된다면 해당 로그는 더 이상 찍을 필요가 없겠네요!

2023-10-05 08:49 UTC, seokjin8678 commented on backend/src/main/java/com/festago/presentation/AuthController.java
> +        memberFCMService.deleteMemberFCM(memberId);
FCM에 관한 의존성 분리를 하더라도 회원이 탈퇴하면 회원의 FCM을 삭제 해야하기 때문에 Auth 도매인이 FCM 도메인을 의존하게 되는 문제는 여전히 발생하겠네요.
이 부분은 DB의 Cascade로 풀어야 하나 고민이 드네요. (회원의 삭제가 Soft-delete라 전파가 될지도 모르겠네요. 😂)

2023-10-05 08:50 UTC, seokjin8678 approved these changes

2023-10-05 11:04 UTC, BGuga commented on backend/src/main/java/com/festago/fcm/application/FCMNotificationEventListener.java
>      private void checkAllSuccess(BatchResponse batchResponse, Long memberId) {
요 부분이 애쉬 PR에 반영돼어서 애쉬 PR을 머지한 후에 conflict 해결하면서 빠진 부분 채워 넣을게요!
```
public void sendMessages(List<Message> messages, FCMChannel channel) {
        try {
            BatchResponse response = firebaseMessaging.sendAll(messages);
            checkAllSuccess(response, channel);
        } catch (FirebaseMessagingException e) {
            log.warn("[FCM: {}] 전송 실패: {}", channel, e.getMessagingErrorCode());
        }
    }
```

2023-10-05 11:09 UTC, BGuga commented on backend/src/main/java/com/festago/presentation/AuthController.java
> +        memberFCMService.deleteMemberFCM(memberId);
로그인 과정에서 분리된 것이지 패키지 의존성으로 보면 그렇네요!!
저희가 eventListener를 사용하지 않았던 것이 결국 authFacadeService에 fcmToken 값이 들어갔기 때문인데 controller 에서 event 를 발행하면 authService에 fcmToken을 넘겨주지 않아도 되고 의존성도 분리되니 해당 방법은 어떠신가요?

2023-10-06 06:28 UTC, carsago approved these changes
굿

2023-10-11 06:41 UTC, merged