[BE] 입장 10분 전 푸시 알림 전송 기능 구현 (#483)
woowacourse-teams/2023-festa-go pull request #484
Opened 2023-10-02 07:17 UTC by xxeol2

## 📌 관련 이슈

- closed: #483

## ✨ PR 세부 내용
즐거운 한가위 보내고 계신가요? 🌕
추석 전에 말씀드린대로 입장 10분 전 알림 전송 기능을 한번 구현해봤어요!!

기존에 얘기나눴던 1분에 한 번씩 cron job 대신, 티켓 생성시 동적으로 Schedule을 등록하는 방법을 택했습니다..!
해당 방법 선택 과정은 PR에 작성하기 너무 길어져서.. 아래 문서를 참고해주세요!! 
https://wooteco-ash.notion.site/10-7a56e61a70d94bb48f5b3ff801d66cea?pvs=4

일단 제 최선을 다해 구현을 해봤는데, 추석 끝나고 캠퍼스에서 다함께 논의할 부분들이 많은 것 같아요!

#472 PR이랑 충돌도 많을거고, 안드분들이랑도 얘기할 부분이 많아서 우선 draft 처리해두겠습니다~!

그럼 남은 추석 잘 보내시고 수요일에 캠퍼스에서 뵙시당! 🙇🏻‍♀️

2023-10-02 07:24 UTC, xxeol2 commented on backend/src/main/java/com/festago/entry_alert/application/EntryAlertService.java
> +    }
FCM이 한 번에 최대 500건까지 발송가능하더라구요?!
<img width="809" alt="image" src="https://github.com/woowacourse-teams/2023-festa-go/assets/71129059/ce080188-98cf-41ba-94fc-91d8422ba064">

그래서 500건씩 보내줬는데, 이는 Async로 비동기로 진행했어요!

이게 X-lock 범위랑도 연관되어있어서, FCM 로직 전송시간동안 계속 connection을 점유한다면 connection 고갈문제로도 이어질 수 있어 Async로 진행하는게 옳다고 생각했어요!

이 때, 메세지 전송에 실패해도 entryAlertRepository.delete()가 호출된다는 점이 문젠데..
현재는 재시도 로직도 없고, 입장시간 지나서 재시도가 되어도 문제라고 생각했어요
그래서 fcm 메세지 실제 전송 성공 여부와 상관없이, EntryAlert는 제거해주는 방식을 택했습니다!!

2023-10-02 07:28 UTC, xxeol2 commented on backend/src/test/java/com/festago/domain/MemberTicketRepositoryTest.java
> +        assertThat(actual).containsExactlyInAnyOrder(member1.getId(), member2.getId());
로컬에선 잘 실행되는데 CI는 터지네요 🤔
원인 파악해보겠습니다

2023-10-02 07:46 UTC, xxeol2 commented on backend/src/main/java/com/festago/entry_alert/application/EntryAlertService.java
> +            .orElseThrow(() -> new ConflictException(ErrorCode.ALREADY_ALERT));
참고 노션에도 언급되어있듯 동시에 2대의 WAS에서 실행할 때, 하나만 실행되고 나머지 하나는 예외처리가 되도록 했습니다!
그런데 이 때, BadRequest는 아닌 것 같고.. (클라이언트의 요청이 없으니)
InternalServerException은 로깅이 찍히고 그래서
아예 별도의 예외 객체가 필요할 것 같아서 따라서 ConflictException으로 처리했어요!
(사실 서버 내부적으로 동작하는거라 클라이언트에까지 응답이 내려갈 일은 없을 것 같아요)

2023-10-02 09:43 UTC, seokjin8678 commented on backend/src/test/java/com/festago/domain/MemberTicketRepositoryTest.java
> +        assertThat(actual).containsExactlyInAnyOrder(member1.getId(), member2.getId());
LocalDateTime.now() 의 타임존이 맞지 않아서 생기는 것 같기도 하네요.

2023-10-02 10:58 UTC, seokjin8678 requested changes
연휴 동안 많은 일을 해주셨군요. 👍👍👍
몇 부분에 대한 최적화가 가능할 것 같아 리뷰 남겼습니다!
고생하셨어요!!

2023-10-02 10:58 UTC, seokjin8678 commented on backend/src/main/java/com/festago/entry_alert/application/EntryAlertEventListener.java
> +    }
해당 이벤트 핸들러는 `ApplicationReadyEvent`를 받아 제일 먼저 실행되는 이벤트 핸들러 같은데 최상단으로 옮기는 것은 어떤가요?

2023-10-02 10:58 UTC, seokjin8678 commented on backend/src/main/java/com/festago/entry_alert/application/EntryAlertEventListener.java
> +    }
```suggestion
    private void addSchedule(EntryAlertResponse entryAlert) {
        Long entryAlertId = entryAlert.id();
        log.info("add entryAlert schedule: {}", entryAlertId);
        Instant alertTime = toInstant(entryAlert.alertTime());
        taskScheduler.schedule(() -> entryAlertService.sendEntryAlert(entryAlertId), alertTime);
    }

    private Instant toInstant(LocalDateTime localDateTime) {
        return localDateTime.atZone(clock.getZone()).toInstant();
    }
```
다음과 같은 방식은 어떤가요?

2023-10-02 10:58 UTC, seokjin8678 commented on backend/src/main/java/com/festago/entry_alert/application/EntryAlertEventListener.java
> +package com.festago.entry_alert.application;
패키지 이름 같은 경우 [구글 스타일 컨벤션](https://google.github.io/styleguide/javaguide.html#s5.2.1-package-names)에서 다음과 같이 명시하고 있어요!
> Package names use only lowercase letters and digits (no underscores). Consecutive words are simply concatenated together. For example, `com.example.deepspace`, not `com.example.deepSpace` or `com.example.deep_space`.

2023-10-02 10:58 UTC, seokjin8678 commented on backend/src/main/java/com/festago/entry_alert/application/EntryAlertService.java
> +            .toList();
```java
class MemberFCMRepository {
    ...
    @Query("SELECT mf.fcmToken FROM MemberFCM mf WHERE mf.memberId in :memberIds")
    List<String> findAllTokenByMemberIdIn(@Param("memberIds") List<Long> memberIds);
    ...
}
```
다음과 같이 사용할 수 있을 것 같네요!

2023-10-02 10:58 UTC, seokjin8678 commented on backend/src/main/java/com/festago/entry_alert/application/EntryAlertService.java
> +    }
해당 부분은 FCM에서의 제약 사항이니 `sendMessages()` 메서드의 for문이 `fcmClient.sendAllAsync()`으로 옮겨야 될 것 같네요!

2023-10-02 10:58 UTC, seokjin8678 commented on backend/src/main/java/com/festago/entry_alert/domain/EntryAlert.java
> +public class EntryAlert {
```suggestion
public class EntryAlert extends BaseTimeEntity {
```

2023-10-02 10:58 UTC, seokjin8678 commented on backend/src/main/java/com/festago/fcm/application/FCMNotificationEventListener.java
> -    }
```java
@Component
public class FCMNotificationEventListener {

    private final FcmClient fcmClient;
    private final MemberFCMService memberFCMService;

    public FCMNotificationEventListener(FcmClient fcmClient, MemberFCMService memberFCMService) {
        this.fcmClient = fcmClient;
        this.memberFCMService = memberFCMService;
    }

    @TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)
    @Async
    public void sendFcmNotification(EntryProcessEvent event) {
        List<String> tokens = memberFCMService.findAllMemberFCMToken(event.memberId());
        fcmClient.sendAll(tokens, FCMChannel.ENTRY_PROCESS, FcmPayload.entryProcess());
    }
}
```

```java
@Service
@Transactional
public class MemberFCMService {
    ...
    @Transactional(readOnly = true)
    public List<String> findAllMemberFCMToken(Long memberId) {
        return memberFCMRepository.findAllTokenByMemberId(memberId);
    }
    ...
}
```

```java
public interface MemberFCMRepository extends JpaRepository<MemberFCM, Long> {
    ...
    @Query("SELECT mf.fcmToken FROM MemberFCM mf WHERE mf.memberId = :memberId")
    List<String> findAllTokenByMemberId(@Param("memberId") Long memberId);
    ...
}
```
다음과 같은 방법은 어떠신가요?

2023-10-02 14:01 UTC, xxeol2 commented on backend/src/main/java/com/festago/entry_alert/application/EntryAlertEventListener.java
> +package com.festago.entry_alert.application;
오.. 새로운 꿀팁 배워갑니다!!

2023-10-03 09:26 UTC, carsago requested changes
애쉬 고생하셨습니다. 코멘트 달아봤어요.

2023-10-03 09:26 UTC, carsago commented on backend/src/main/java/com/festago/config/AsyncConfig.java
> -    }
이 부분은 어떤 맥락에서 추가됐다가 다시 사라진 걸까요 ?_?

2023-10-03 09:26 UTC, carsago commented on backend/src/main/java/com/festago/entry_alert/application/EntryAlertService.java
> +            .orElseThrow(() -> new ConflictException(ErrorCode.ALREADY_ALERT));
여기서 delete 하는 방법도 있지만 처리전, 처리후 같은 식의 상태를 변경시키는 방법은 어떨까요?

그렇게한다면 굳이 throw안하고, early return 하는 방법으로도 처리할 수도 있고
제대로 스케쥴링이 처리됐는지, 명시적으로 확인할 수도 있을 것 같아요.
데이터가 쌓인다는 점이 있지만 수백~수천개 정도의 데이터는 큰 문제가 안되고, 나중에 주기적으로 비워줄 수도 있으니까요.

2023-10-04 07:37 UTC, xxeol2 commented on backend/src/main/java/com/festago/entry_alert/application/EntryAlertEventListener.java
> +    }
좋은데요?

2023-10-04 07:40 UTC, xxeol2 commented on backend/src/main/java/com/festago/fcm/application/FCMNotificationEventListener.java
> -    }
반영완료했습니다~

2023-10-04 07:40 UTC, xxeol2 commented on backend/src/main/java/com/festago/entry_alert/application/EntryAlertEventListener.java
> +    }
반영했습니다!

2023-10-04 14:35 UTC, xxeol2 commented on backend/src/main/java/com/festago/entry_alert/domain/EntryAlert.java
> +public class EntryAlert {
언제 등록되었는지도 추적하면 좋겠네요! 👍

2023-10-04 14:37 UTC, xxeol2 commented on backend/src/main/java/com/festago/entry_alert/application/EntryAlertService.java
> +            .orElseThrow(() -> new ConflictException(ErrorCode.ALREADY_ALERT));
푸시알림 전송 여부를 추적할 수 있다는 점에서 오리가 말씀해주신 방법이 좋아보이네요!
해당 방법으로 수정해보겠습니다!!

2023-10-04 18:27 UTC, xxeol2 commented
아래 리뷰들을 반영하며 많은 변화가 생겼습니다.
https://github.com/woowacourse-teams/2023-festa-go/pull/484#discussion_r1342534509

> 해당 부분은 FCM에서의 제약 사항이니 `sendMessages()` 메서드의 for문이 `fcmClient.sendAll()`으로 옮겨야 될 것 같네요!

https://github.com/woowacourse-teams/2023-festa-go/pull/484#discussion_r1343795761

> 여기서 delete 하는 방법도 있지만 처리전, 처리후 같은 식의 상태를 변경시키는 방법은 어떨까요?

## AlertStatus 정의

알림의 상태를 나타내는 enum `AlertStatus` 을 정의했습니다.
(이후 다른 알림들이 생긴다면 포괄적으로 사용할 수 있을 것 같아 `EntryAlertStatus` 라는 네이밍 대신 `AlertStatus` 을 택했습니다.)

해당 enum은 아래와 같은 4가지 상태를 가지고 있습니다.
1. PENDING(알림 전)
2. REQUESTED(알림 요청)
3. SENT(알림 전송 완료)
4. FAILED(알림 전송 실패)

EntryAlert를 등록할 때, 상태를 PENDING으로 초기화하고
fcm 요청을 보냈을 때 REQUESTD로 설정하고
fcm 전송이 완료되었을 때 성공 여부에 따라 SENT / FAILED로 설정합니다.

REQUESTED와 SENT/FAILED 상태를 분리한 이유는 X-lock 범위 때문입니다.

![image](https://github.com/woowacourse-teams/2023-festa-go/assets/71129059/c9d88a47-ba54-426a-a7d6-b87a40d48aa6)
## CompletableFuture를 이용한 Async + Blocking

fcm 스펙상 동시에 500건씩 요청이 가능하기 때문에, 500건씩 비동기로 전송하도록 했습니다.
이 때 작업 수행 결과에 따라 모든 작업이 성공했을 때 AlertStatus를 SENT로 바꾸고, 하나라도 실패하면 FAILED로 바꾸고 싶었습니다.

즉, 작업들은 **별개의 스레드에서 병렬적으로 진행**(`Async`)하되, 결과적으로 **모든 작업이 성공했는지 여부**를 알고싶었습니다.(`Blocking`)

이를 위해 **CompletableFuture**를 활용했습니다.

### 데드락 문제 발생

`@Async` 메서드에서 fcmClient.sendAll() 메서드를 호출을 하면 데드락이 발생합니다. (`@Async` 메서드에서 CompletableFuture 작업을 기다리면서 발생하는 문제)
`@Async` 메서드에서 CompletableFuture 작업을 수행하려 했는데 더 이상 남은 스레드가 없을 때 무한 대기 상태가 걸립니다.

이를 위해 FCM 전송을 위한 별도의 스레드풀을 정의해줬습니다.

(Async → defaultExecutor 활용 / CompletableFuture → fcmExecutor 활용)

### AsyncBatchExecutor 클래스 분리 (템플릿-콜백 패턴)

해당 로직을 FcmClientImpl에서 수행하니 핵심 로직과 병렬처리를 위한 로직이 섞여있어, 핵심 로직을 한 눈에 파악하기 어려웠습니다. (아래 사진 참고)
![image](https://github.com/woowacourse-teams/2023-festa-go/assets/71129059/e89829a2-8e9b-4f57-b321-80e740fdfcd3)



**템플릿-콜백 패턴을 적용**해 핵심 로직과 병렬처리 로직을 분리했습니다. (AsyncBatchExecutor)

## `@Async`, `@Transacitonal`의 self-invocation 한계

스케줄 시간이 되었을 때, 알림발송을 시작하는 메서드는 Async 메서드입니다. (여러 무대의 알림을 병렬적으로 전송하기 위해서)
위에서도 언급했듯, FCM을 실제로 전송하는 메서드도 Async 메서드입니다.
이 때, FCM 전송 완료 후 AlertStatus를 변경하는 메서드는 Transactional 메서드입니다.

self-invocation의 한계로.. 셋 다 다른 클래스로 분리하였습니다 🥲
이 부분에 대한 좋은 의견이 있으시면 공유부탁드립니다!!

![image](https://github.com/woowacourse-teams/2023-festa-go/assets/71129059/ca671e76-d66f-44f4-840f-c8f79007c054)

2023-10-04 18:29 UTC, xxeol2 commented on backend/src/main/java/com/festago/config/AsyncConfig.java
> +    }
축제 수용 인원이 3000-5000명정도라고 하면, 동시 입장 인원이 2000명인 경우는 흔할 것 같아 corePoolSize를 4로 지정했습니다.

2023-10-05 02:03 UTC, seokjin8678 commented
알람을 보낸 상태를 기록하느라 로직이 복잡해진 것 같네요.
보낸 상태가 정말 중요한가? 라는 생각이 들긴하는데, 이럴 경우 단순히 로그로 출력하는게 어떨지 싶네요.

2023-10-05 04:20 UTC, seokjin8678 requested changes
비동기 Executor 만드느라 고생 많으셨겠군요.. 👍👍

그런데 굳이 이렇게 복잡한 방법으로 풀지 않고, 단순한 방법으로 풀 방법도 있을 것 같아요.
무대 입장 알림 같은 경우, 있어도 그만 없어도 그만인 기능인 것 같습니다. 
저희 서비스의 장점으로 본다면 중요하긴 하겠지만..

사람들이 저희가 보낸 알림을 봐야 입장이 되는게 아니니까, 편의를 위한 리마인드 기능이라 생각합니다.
따라서 알림이 무조건 가야 하는건 아니기 때문에 DB에 보낸 상태를 저장하는 것 보다, 로그로 남겨 어떤 요청이 실패했는지 기록만 해두는게 어떨까 싶네요.

2023-10-05 04:20 UTC, seokjin8678 commented on backend/src/main/java/com/festago/entryalert/application/EntryAlertEventListener.java
> +    }
`entryAlertService`의 `create()` 메서드는 DB에 저장하는 로직이라, 굳이 `@Async`로 등록을 해야할 필요가 있을까 싶네요.

2023-10-05 04:20 UTC, seokjin8678 commented on backend/src/main/java/com/festago/entryalert/application/EntryAlertService.java
> +        EntryAlert entryAlert = entryAlertRepository.findByIdAndStatusForUpdate(id, AlertStatus.PENDING)
X락을 거느라, 서버가 여러 개 생겼을 때 다른 서버들은 여기서 대기를 하겠네요.
해당 방법은 추후에 락을 걸더라도 락이 걸려있으면 바로 빠져나오게 할 방법이 필요하겠네요.

2023-10-05 04:27 UTC, xxeol2 commented on backend/src/main/java/com/festago/entryalert/application/EntryAlertService.java
> +    }
저도 PENDING -> REQUESTED 정도만 기록으로 남기고
실제 전송 성공여부는 굳이 상태로 관리하지 않고 로그로 추적해도 좋을 것 같다는 생각입니다 ㅋㅋㅋ
구현하기전까진 이런 상태도 저장되면 편하지 않을까? 라는 생각이었는데..
막상 구현하고나니 너무 복잡해져서 굳이 없어도 되는 로직이란점 동의합니다 👍

2023-10-05 04:28 UTC, xxeol2 commented on backend/src/main/java/com/festago/entryalert/application/EntryAlertService.java
> +    }
다만 전송 여부를 true/false로 관리하기보다는, 확장을 위해 Enum으로 관리하는건 유지해도 좋을 것 같아요!

2023-10-05 04:30 UTC, carsago commented on backend/src/main/java/com/festago/entryalert/application/EntryAlertService.java
> +    }
저도 간단할줄 알았는데 막상보니 복잡하다는 부분에 동의합니다. ㅠ 생각보다 어려운 부분이 많았네요

2023-10-05 04:35 UTC, xxeol2 commented on backend/src/main/java/com/festago/entryalert/application/EntryAlertService.java
> +    @Async
@Query("SELECT u FROM User u WHERE u.status = :status and u.name = :name")
User findUserByStatusAndNameNamedParams(
  @Param("status") Integer status, 
  @Param("name") String name);

2023-10-05 04:36 UTC, xxeol2 commented on backend/src/main/java/com/festago/entryalert/application/EntryAlertService.java
> +    @Async
네넵 정확합니다!

ScheduleThreadpool이 아닌 AsyncThreadPool에서 해당 메서드가 실행되도록 유도했습니다.
(ScheduleThreadpool corePoolSize: 1 / AsyncThreadPool corePoolSize: 8)

ScheduleThread는 그저 작업들이 대기하다가 특정 시각이 되면 메서드를 실행시키는 역할만 수행하도록 했습니다!

2023-10-05 04:39 UTC, xxeol2 commented on backend/src/main/java/com/festago/entryalert/application/EntryAlertEventListener.java
> +    }
entryAlertService의 create() 메서드가 `@Transactional` 메서드라서 `@Async`로 등록해줬습니다~!
(`@Async`로 등록하지 않으면 기존 트랜잭션이 이미 커밋된 상태라서 insert문이 동작하지 않아요!
propagation=REQUIRES_NEW로 하면 데드락 문제가 일어나고..)

2023-10-05 04:40 UTC, xxeol2 commented on backend/src/main/java/com/festago/entryalert/application/EntryAlertService.java
> +        EntryAlert entryAlert = entryAlertRepository.findByIdAndStatusForUpdate(id, AlertStatus.PENDING)
대기를 하는 것을 의도한게 맞습니다!
여러 서버에서 동시에 실행되면 한 대의 서버에서만 실행됨을 보장해야해 X-lock을 걸어줬습니다!
X-lock 범위를 최소화하기 위해 실제 FCM 전송 로직은 `@Async`로 분리해줬습니다!

2023-10-05 04:52 UTC, carsago commented on backend/src/main/java/com/festago/entryalert/application/EntryAlertService.java
> +        EntryAlert entryAlert = entryAlertRepository.findByIdAndStatusForUpdate(id, AlertStatus.PENDING)
redis를 이용한 분산락, mysql을 통한 분산락(https://techblog.woowahan.com/2631/) 등으로 추후에 변경을 모색해볼 수 있지만
나중에 저희가 정말 필요하다가 판단될 때 도입하는게 좋을 것 같습니당.

2023-10-05 05:06 UTC, seokjin8678 commented on backend/src/main/java/com/festago/entryalert/application/EntryAlertEventListener.java
> +    }
```suggestion
    private void addSchedule(EntryAlertResponse entryAlert) {
        Long entryAlertId = entryAlert.id();
        log.info("EntryAlert 스케쥴링 추가. entryAlertId: {}, alertTime: {}", entryAlertId, entryAlert.alertTime());
        Instant alertTime = toInstant(entryAlert.alertTime());
        taskScheduler.schedule(() -> entryAlertService.sendEntryAlert(entryAlertId), alertTime);
    }
```
다음과 같이 자세히 로그를 적어도 좋겠네요.
`alertTime` 변수를 사용하지 않은 이유는 `Instant` 타입이라, UTC 시간(우리나라 시간 -9시간)으로 찍혀 헷갈릴 수 있겠더라구요.

2023-10-05 05:11 UTC, xxeol2 commented on backend/src/main/java/com/festago/entryalert/application/EntryAlertService.java
> +    }
a42051ad33f5f300c8123c1b35ca8db4a4733c6f
해당 커밋에서 SENT/FAILED 상태를 삭제했습니다 ~!

2023-10-05 05:28 UTC, seokjin8678 commented on backend/src/main/java/com/festago/fcm/infrastructure/FcmClientImpl.java
> +    }
그냥 갑자기 든 생각인데, 공연에 참가자가 아무도 없는 상황에서 알림을 보내면 emptyList가 보내어 질텐데, 이때 예외를 발생시키는 것이 과연 괜찮을까 생각이 드네요.
그냥 빈 토큰이라면 early return 해버리는 것도 좋을 것 같아요.

2023-10-05 05:30 UTC, xxeol2 commented on backend/src/main/java/com/festago/fcm/infrastructure/FcmClientImpl.java
> +    }
사실 해당 메서드가 비동기 기반으로 호출되는 메서드라 예외가 발생해도 사실상 아무 일도 없을거에요
그런데 이 상황은 글렌 말씀처럼 확실히 예외상황이 아닌 것 같네요 ㅎㅎ
early return으로 수정하겠습니다!!

2023-10-05 05:31 UTC, xxeol2 commented on backend/src/main/java/com/festago/fcm/infrastructure/FcmClientImpl.java
> +    }
이게 입장알림이 아니라 QR상태변화용 FCM인 경우
사용자 토큰이 없으면 QR 상태가 변화하지 않아서
푸우가 기존 작성하신 코드에 예외로 처리되어있었을거에요!

2023-10-05 05:33 UTC, seokjin8678 commented on backend/src/main/java/com/festago/entryalert/application/EntryAlertService.java
> +        taskExecutor.execute(() -> fcmClient.sendAll(tokens, FCMChannel.ENTRY_ALERT, FcmPayload.entryAlert()));
`EntryAlertFcmClient` 클래스가 사라졌네요!
`TaskExecutor`의 `execute` 메소드를 호출해서 비동기로 실행하는 것보다 다시 `EntryAlertFcmClient`를 추가해서 비동기로 실행하는 것은 어떤가요?
그렇게 한다면 다음과 같이 실패한 요청을 로그로 남길 수 있을 것 같아요.

```java
@Component
@RequiredArgsConstructor
@Slf4j
public class EntryAlertFcmClient {

    private final FcmClient fcmClient;

    @Async
    public void sendAll(Long entryAlertId, List<String> tokens, FcmPayload payload) {
        boolean isSuccess = fcmClient.sendAll(tokens, FCMChannel.ENTRY_ALERT, payload);
        if (!isSuccess) {
            log.warn("무대 입장 알림 전송이 실패했습니다. entryAlertId: {}", entryAlertId);
        }
    }
}
```

2023-10-05 05:37 UTC, xxeol2 commented on backend/src/main/java/com/festago/entryalert/application/EntryAlertService.java
> +        taskExecutor.execute(() -> fcmClient.sendAll(tokens, FCMChannel.ENTRY_ALERT, FcmPayload.entryAlert()));
sendAll에서 500건 이상이면 내부적으로 Async로 동작해서 isSuccess 여부를 알아오기가 쉽지 않아요 ... ㅠㅠ
그걸 알기 위해선 위의 CompletableFuture 도입이 다시 필요해집니다 🥲

2023-10-05 05:38 UTC, xxeol2 commented on backend/src/main/java/com/festago/entryalert/application/EntryAlertService.java
> +        taskExecutor.execute(() -> fcmClient.sendAll(tokens, FCMChannel.ENTRY_ALERT, FcmPayload.entryAlert()));
EntryAlertFcmClient를 굳이 클래스로 분리하지 않은 이유는
fcmClient.sendAll(tokens, FCMChannel.ENTRY_ALERT, payload); 메서드를 호출하는 역할 뿐이어서
taskExecutor.execute 하는게 더 간단하고 Async로 돌아가는걸 메서드단에서 파악하기 쉬워서 분리하지않았는데
이 부분은 분리하는게 좋을까요?!

2023-10-05 05:39 UTC, xxeol2 commented on backend/src/main/java/com/festago/entryalert/application/EntryAlertService.java
> +        taskExecutor.execute(() -> fcmClient.sendAll(tokens, FCMChannel.ENTRY_ALERT, FcmPayload.entryAlert()));
아니면 500건 이상일때 비동기로 보내지않고 한 스레드에서 순차적으로 보내는 방법도 존재하긴 합니다..!!

2023-10-05 06:04 UTC, seokjin8678 commented on backend/src/main/java/com/festago/entryalert/application/EntryAlertService.java
> +        taskExecutor.execute(() -> fcmClient.sendAll(tokens, FCMChannel.ENTRY_ALERT, FcmPayload.entryAlert()));
500건 이상일때 순차적으로 보내는 것도 좋겠네요. 😂

2023-10-05 06:23 UTC, seokjin8678 commented on backend/src/main/java/com/festago/entryalert/application/EntryAlertService.java
> +    }
```java
public class EntryAlertService {
    ...
    @Async
    public void sendEntryAlert(Long id) {
        entryAlertRepository.findByIdAndStatusForUpdate(id, AlertStatus.PENDING).ifPresent(entryAlert -> {
            List<String> tokens = findFcmTokens(entryAlert);
            log.info("EntryAlert 전송 시작 / entryAlertId: {} / to {} devices", id, tokens.size());
            taskExecutor.execute(() -> fcmClient.sendAll(tokens, FCMChannel.ENTRY_ALERT, FcmPayload.entryAlert()));
            entryAlert.request();
        });
    }
}
```
다음과 같이 예외를 던지지 않는 방법도 사용할 수 있을 것 같네요!

2023-10-05 06:24 UTC, seokjin8678 commented on backend/src/main/java/com/festago/entryalert/domain/EntryAlert.java
> +    }
`changeRequested()` 같은 메소드 명은 어떤가요?

2023-10-05 06:31 UTC, seokjin8678 reviewed
롬복 적용할 수 있는 것에 커멘트 남겼습니다.
일부에도 적용할 수 있을 것 같은데, 471번 이슈가 머지되면 결국 변경해야 하므로 우선 뒀습니다.

2023-10-05 06:31 UTC, seokjin8678 commented on backend/src/main/java/com/festago/entryalert/application/EntryAlertEventListener.java
> +    }
```suggestion
@Component
@Slf4j
@RequiredArgsConstructor
public class EntryAlertEventListener {

    private final EntryAlertService entryAlertService;
    private final TaskScheduler taskScheduler;
    private final Clock clock;
```

2023-10-05 06:31 UTC, seokjin8678 commented on backend/src/main/java/com/festago/entryalert/domain/EntryAlert.java
> +    }
```suggestion
@Entity
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class EntryAlert extends BaseTimeEntity {

    private static final int ENTRY_ALERT_MINUTES_BEFORE = 10;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotNull
    private Long stageId;

    @NotNull
    private LocalDateTime entryTime;

    @NotNull
    @Enumerated(value = EnumType.STRING)
    private AlertStatus status = AlertStatus.PENDING;
```

2023-10-05 06:53 UTC, carsago commented
애쉬 고생하셨습니다. 제가 보기엔 글렌이 말씀해주신 롬복 어노테이션 일부분만 하면 이만 마무리해도 될것같아요.
굳이 하자면 메시지 보내는 FcmPayload인데 애쉬도 생각하셨겠지만 이건 어차피 안드랑 이야기해야하니 내일 이야기해서 커밋 하나정도만 추가되면 되지 않을까 싶습니다.

2023-10-05 12:40 UTC, BGuga reviewed
애쉬 너무 수고 많으셨습니다 👍
이야기할 것은 이미 거의 다 나온 것 같네요!!
@Profile 설정 같은 경우는 현재 dev 로 실행하면 duplicate bean이 뜨니 꼭 확인해 주세요 ㅎㅎ

2023-10-05 12:40 UTC, BGuga commented on backend/src/main/java/com/festago/fcm/infrastructure/FcmClientImpl.java
> +    private final Executor taskExecutor;
```suggestion
    private final TaskExecutor taskExecutor;
```
👍

2023-10-05 12:40 UTC, BGuga commented on backend/src/main/java/com/festago/fcm/application/MockFcmClient.java
> +@Profile({"!prod", "!dev"})
요러면 모든 환경에서 등록되니 
```suggestion
@Profile({"!prod & !dev"})
```
요걸 의도하신 거겠죠?

2023-10-05 12:40 UTC, BGuga commented on backend/src/main/java/com/festago/fcm/application/FCMNotificationEventListener.java
> +    private final FcmClient fcmClient;
FcmClient 를 추상화해준 이유가 추후에 IosFcmClient, webFcmClient를 고려한 것이 맞을까용?

2023-10-05 12:45 UTC, xxeol2 commented on backend/src/main/java/com/festago/fcm/application/FCMNotificationEventListener.java
> +    private final FcmClient fcmClient;
확장을 위한 추상화보다는 DIP를 위한 추상화입니다!!
FirebaseMessaging은 외부 라이브러리라고 판단해 infrastructure 레이어에 두기 위해서 추상화를 진행했습니다..!

2023-10-05 12:50 UTC, xxeol2 commented on backend/src/main/java/com/festago/config/AsyncConfig.java
> -    }
맞아요! 현재는 롤백되었지만.. 2개 이상의 Executor를 Bean으로 등록할때는 "taskExecutor"가 기본적으로 사용됩니다~!
"taskExecutor" 네이밍의 빈이 없을 때는 별도의 Qualifier를 지정하지 않은 경우엔 SimpleAsyncTaskExecutor를 사용하기때문에 주의해야합니다 ㅎㅎ

![image](https://github.com/woowacourse-teams/2023-festa-go/assets/71129059/a7d52a0c-214c-47cd-800f-e7d1cc5ce6d9)
출처: [도둑탈을 쓴 애쉬 ㅋㅋ](https://xxeol.tistory.com/44)

2023-10-05 12:51 UTC, xxeol2 commented on backend/src/main/java/com/festago/entryalert/domain/EntryAlert.java
> +    }
이부분 네이밍이 어색했었는데.. 추천 감사합니다!!

2023-10-05 12:51 UTC, BGuga reviewed
앗 하나더 😅

2023-10-05 12:51 UTC, BGuga commented on backend/src/main/java/com/festago/fcm/application/FcmClient.java
> +    void sendAll(List<String> tokens, FCMChannel channel, FcmPayload fcmPayload);
```suggestion
    @Async
    void sendAll(List<String> tokens, FCMChannel channel, FcmPayload fcmPayload);
```
이렇게 달면 안돼나요? [overflow](https://stackoverflow.com/questions/9109126/spring-async-annotation-on-interface-methods)

2023-10-05 12:52 UTC, xxeol2 commented on backend/src/main/java/com/festago/fcm/application/MockFcmClient.java
> +@Profile({"!prod", "!dev"})
매의 눈 푸우 22 감사합니다

2023-10-05 12:54 UTC, xxeol2 commented on backend/src/main/java/com/festago/fcm/application/FcmClient.java
> +    void sendAll(List<String> tokens, FCMChannel channel, FcmPayload fcmPayload);
저친구 놀랍게도 sendAll은 Async 메서드가 아닙니다..!
그 이유는 QR 상태 변경용 FCM에서는 이미 비동기 메서드에서 해당 메서드를 호출하기때문에
해당 메서드에 `@Async` 달면 두 번 Async 처리가 되더라구요!
그래도 큰 문제는 없지만, 굳이 두 번 Async를 탈 필요는 없어서 저렇게 진행했습니다

2023-10-05 14:46 UTC, BGuga commented on backend/src/main/java/com/festago/fcm/application/FcmClient.java
> +    void sendAll(List<String> tokens, FCMChannel channel, FcmPayload fcmPayload);
그러면
```
@Async
    public void sendEntryAlert(Long id) {
        EntryAlert entryAlert = entryAlertRepository.findByIdAndStatusForUpdate(id, AlertStatus.PENDING)
            .orElseThrow(() -> new ConflictException(ErrorCode.ALREADY_ALERT));
        List<String> tokens = findFcmTokens(entryAlert);
        log.info("EntryAlert 전송 시작 / entryAlertId: {} / to {} devices", id, tokens.size());
        taskExecutor.execute(() -> fcmClient.sendAll(tokens, FCMChannel.ENTRY_ALERT, FcmPayload.entryAlert()));
        entryAlert.request();
    }
```
마찬가지로 요기도
```
@Async
    public void sendEntryAlert(Long id) {
        EntryAlert entryAlert = entryAlertRepository.findByIdAndStatusForUpdate(id, AlertStatus.PENDING)
            .orElseThrow(() -> new ConflictException(ErrorCode.ALREADY_ALERT));
        List<String> tokens = findFcmTokens(entryAlert);
        log.info("EntryAlert 전송 시작 / entryAlertId: {} / to {} devices", id, tokens.size());
        fcmClient.sendAll(tokens, FCMChannel.ENTRY_ALERT, FcmPayload.entryAlert());
        entryAlert.request();
    }
```
이렇게 하면 안되는 것인가용?

2023-10-05 14:50 UTC, BGuga commented on backend/src/main/java/com/festago/fcm/application/FCMNotificationEventListener.java
> +    private final FcmClient fcmClient;
fcm 자체가 외부 라이브러리라 fcm 패키지에서 fcm 을 infrastructure로 봐야하는가 헷갈리네요 ㅠㅠ

2023-10-05 14:52 UTC, seokjin8678 commented on backend/src/main/java/com/festago/fcm/application/MockFcmClient.java
> +@Profile({"!prod", "!dev"})
매눈푸 ㄷㄷㄷ

2023-10-05 14:56 UTC, seokjin8678 commented on backend/src/main/java/com/festago/fcm/application/FcmClient.java
> +    void sendAll(List<String> tokens, FCMChannel channel, FcmPayload fcmPayload);
그래도 되긴 하는데... `entryAlertRepository.findByIdAndStatusForUpdate()` 메서드가 락을 걸기도 하고, 트랜잭션 범위안에 있어서 이건 비동기로 재호출을 한 번 더 해야될 것 같네요

2023-10-05 15:08 UTC, seokjin8678 approved these changes
재택이라 그런지 오늘 애쉬 PR만 팬 것 같네요. 😂
많은 작업 하느라 고생 많으셨습니다.
이만 하산하시죠 ⛰

2023-10-06 00:20 UTC, BGuga commented on backend/src/main/java/com/festago/fcm/application/FcmClient.java
> +    void sendAll(List<String> tokens, FCMChannel channel, FcmPayload fcmPayload);
아아 x 락 범위가 있었네요 굿굿

2023-10-09 12:54 UTC, seokjin8678 commented
잠깐 생각이 나서 간단하게 푸시 알림 전송 결과를 DB에 업데이트 하는 로직을 생각해봤어요

```java
@Service
@Transactional
@RequiredArgsConstructor
@Slf4j
public class EntryAlertService {
    ...
    private final EntryAlertFcmService entryAlertFcmService;
    ...
    @Async
    public void sendEntryAlert(Long id) {
        entryAlertRepository.findByIdAndStatusForUpdate(id, AlertStatus.PENDING)
            .ifPresent(entryAlert -> {
                List<String> tokens = findFcmTokens(entryAlert);
                log.info("EntryAlert 전송 시작 / entryAlertId: {} / to {} devices", id, tokens.size());
                taskExecutor.execute(() -> entryAlertFcmService.send(id, tokens));
                entryAlert.changeRequested();
            });
    }
    ...
}
```
```java
@Service
@RequiredArgsConstructor
@Slf4j
public class EntryAlertFcmService {

    private final EntryAlertRepository entryAlertRepository;
    private final TransactionTemplate transactionTemplate;
    private final FcmClient fcmClient;

    public void send(Long id, List<String> tokens) {
        AlertStatus result = sendEntryAlert(id, tokens);
        transactionTemplate.execute(status -> {
            changeEntryAlertStatus(id, result);
            return null;
        });
    }

    private AlertStatus sendEntryAlert(Long id, List<String> tokens) {
        try {
            fcmClient.sendAll(tokens, FCMChannel.ENTRY_ALERT, FcmPayload.entryAlert());
            log.info("EntryAlert 전송 성공 / entryAlertId: {}", id);
            return AlertStatus.SUCCEED;
        } catch (FirebaseMessagingException e) {
            log.warn("EntryAlert 전송 실패 / entryAlertId: {}", id);
            return AlertStatus.FAILED;
        }
    }

    private void changeEntryAlertStatus(Long id, AlertStatus alertStatus) {
        EntryAlert entryAlert = entryAlertRepository.findByIdAndStatus(id, AlertStatus.REQUESTED)
            .orElseThrow(IllegalArgumentException::new);
        switch (alertStatus) {
            case SUCCEED -> entryAlert.changeSucceed();
            case FAILED -> entryAlert.changeFailed();
            default -> throw new IllegalArgumentException();
        }
    }
}
```
`TransactionTemplate`을 사용하여 self-invocation 문제를 해결하고 메서드의 원하는 부분만 더티리드를 할 수 있게 했어요.
해당 로직을 호출할 때는 X락이 걸려있어 동시성이 보장되므로 `Repository`에서 for update를 사용하지 않고 가져왔어요.
변화가 생긴다면 `FCMClient`의 `sendAll()` 메서드가 `FirebaseMessagingException`을 던지게 하고 500건 이상의 send는 비동기로 처리하는게 아닌 동기로 처리해야해요.
```java
@Component
@Profile({"dev", "prod"})
@RequiredArgsConstructor
@Slf4j
public class FcmClientImpl implements FcmClient {

    private static final int BATCH_ALERT_SIZE = 500;

    private final FirebaseMessaging firebaseMessaging;

    @Override
    public void sendAll(List<String> tokens, FCMChannel channel, FcmPayload payload) throws FirebaseMessagingException {
        if (tokens.isEmpty()) {
            return;
        }
        List<Message> messages = createMessages(tokens, channel, payload);

        if (messages.size() <= BATCH_ALERT_SIZE) {
            sendMessages(messages, channel);
            return;
        }

        for (int i = 0; i < messages.size(); i += BATCH_ALERT_SIZE) {
            List<Message> batchMessages = messages.subList(i, Math.min(i + BATCH_ALERT_SIZE, messages.size()));
            sendMessages(batchMessages, channel);
        }
    }

    private void sendMessages(List<Message> messages, FCMChannel channel) throws FirebaseMessagingException {
        try {
            BatchResponse response = firebaseMessaging.sendAll(messages);
            checkAllSuccess(response, channel);
        } catch (FirebaseMessagingException e) {
            log.warn("[FCM: {}] 전송 실패: {}", channel, e.getMessagingErrorCode());
            throw e;
        }
    }
    ...
}
```

2023-10-09 12:58 UTC, seokjin8678 commented on backend/src/main/resources/application-local.yml
> +
graceful shutdown 👍👍
submodule에도 적용을 해야겠네요!

2023-12-11 05:43 UTC, SeongHoonC commented
불필요 브랜치를 삭제하다가 삭제해버렸네요. 죄송합니다!

2023-12-20 14:46 UTC, closed without merging