[AN/USER] refactor: LiveData to Flow 리팩터링 (티켓 제시, 로그인 화면) (#494)
woowacourse-teams/2023-festa-go pull request #498
Opened 2023-10-05 07:33 UTC by re4rk

## 📌 관련 이슈

- closed: #494 

## ✨ PR 세부 내용

- 티켓 제시 :  uiState를 combine을 이용해서 합쳐지도록 리팩터링
- 로그인 화면 :  SharedFlow로 리팩터링
- 테스트에 터빈 적용, LiveData 를 위한 Rule 제거

2023-10-06 05:30 UTC, EmilyCh0 approved these changes
👍 코멘트 확인해 주세요!

2023-10-06 05:30 UTC, EmilyCh0 commented on android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModel.kt
> +        }
좋네요 👍

2023-10-06 05:30 UTC, EmilyCh0 commented on android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModel.kt
> +    private val ticketCodeFlow = MutableSharedFlow<Result<TicketCode>>()
SharedFlow를 사용하신 이유가 궁금합니다!

2023-10-06 05:30 UTC, EmilyCh0 commented on android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModelTest.kt
> +    }
private으로 수정해주세요~

2023-10-06 05:34 UTC, re4rk commented on android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModelTest.kt
> +    }
반영했습니다!

2023-10-06 05:36 UTC, re4rk commented on android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModel.kt
> +    private val ticketCodeFlow = MutableSharedFlow<Result<TicketCode>>()
StateFlow와 비교할 수 있다고 생각하고 있습니다!
StateFlow는 Default값을 필요로 하고 있으며 하위 클래스 이기 때문에 SharedFlow를 적용하고자 하였습니다!
하지만 단점도 있다고 생각하고 있습니다! 같은 결과 값을 전달 받더라도 SharedFlow는 방출을 하기 때문에 불필요한 combine이 실행될 수 있다고 생각합니다! 하지만 일반적인 경우에서는 크게 문제되지 않을 것이라고 판단이 되어서 적용하게 되었습니다!

2023-10-06 05:38 UTC, re4rk commented on android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModel.kt
> +        viewModelScope.launch {
반영하였습니다!
현재 코드에서 suspend를 적용하여서 viewModelScope안에 viewModelScope를 중복적으로 사용하지 않는 방향으로 했습니다!

2023-10-06 05:39 UTC, re4rk commented on android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryActivity.kt
> +                    }
지금의 저의 의견은 SharedFlow는 collect를 사용해서 모든 이벤트들이 순차적으로 받을 수 있고 StateFlow의 경우에는 collectLatest를 적용하는 것이 어떠한가 생각합니다! 추후에 교차로 사용하게 된다면 그 때 추가 논의하는 것이 어떨까요??

2023-10-06 05:40 UTC, re4rk commented on android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInActivity.kt
> +    private fun handleEvent(it: SignInEvent) = when (it) {
확인했습니다!

2023-10-07 05:54 UTC, SeongHoonC requested changes
테스트 코드 관련 리뷰만 한번 확인해주세요!

2023-10-07 05:54 UTC, SeongHoonC commented on android/festago/app/src/main/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModel.kt
> +    private val ticketCodeFlow = MutableSharedFlow<Result<TicketCode>>()
같은 값이 들어오면 uiState 가 StateFlow 라서 문제없을 것이라 예상되네요

2023-10-07 05:54 UTC, SeongHoonC commented on android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModelTest.kt
> +    private fun `티켓 요쳥 결과는 다음과 같다`(result: Result<Ticket>) {
given 절이라 ~ 다음과 같을 때 라는 네이밍 어떠신가요?

2023-10-07 05:54 UTC, SeongHoonC commented on android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModelTest.kt
>          }
returns 와  answers 를 어떻게 구분해서 사용하시나요?

2023-10-07 06:12 UTC, re4rk commented on android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModelTest.kt
>          }
단순 반환일 때는 returns을 사용하는 것이 좋다고 생각합니다! 반영했습니다!

2023-10-07 06:12 UTC, re4rk commented on android/festago/app/src/test/java/com/festago/festago/presentation/ui/ticketentry/TicketEntryViewModelTest.kt
> +    private fun `티켓 요쳥 결과는 다음과 같다`(result: Result<Ticket>) {
변경했습니다!

2023-10-07 06:26 UTC, SeongHoonC approved these changes
반영 확인했습니다! LGTM!

2023-10-07 06:26 UTC, merged