[BE] 도메인 엔티티의 예외를 정의하고 적용하고 테스트 패키지 구조를 정리한다.
woowacourse-teams/2023-festa-go pull request #515
Opened 2023-10-07 05:06 UTC by seokjin8678

## 📌 관련 이슈

- closed: #482 

## ✨ PR 세부 내용

도메인 엔티티의 예외를 `ValidException`으로 처리하여 일괄적으로 적용했습니다.

해당 예외는 `GlobalExceptionHandler`에서 처리하여 메시지와 함께 400 BadRequest를 반환합니다.

`common` 패키지 안에 `Validator` 클래스를 사용하여 중복을 제거하고 예외 메시지를 적는데 드는 시간과 노력을 최소화 시켰습니다.

이러한 예외의 변경으로 테스트 코드 또한 변경이 많아, 기존 패키지 구조를 바꿨지만, 테스트 패키지 구조는 바뀌지 않아 중복된 테스트를 작성할 위험이 있었는데, 변경이 많은 겸 새롭게 변경된 패키지 구조로 정리를 했습니다. 

때문에 변경된 파일이 많아 중요한 부분에 대해서는 코드에 커멘트로 남기겠습니다.

2023-10-07 05:08 UTC, seokjin8678 commented on backend/src/main/java/com/festago/admin/domain/Admin.java
> +    }
`Validator` 클래스를 사용하여 쉽고 간편하게 예외 메지지를 전송합니다.
단점으로 검증이 많으면 이렇게 중복된 "username" 필드명이 발생하는데 이를 상수 코드로 뽑기엔 뭔가 애매한 부분이 있는 것 같아서 같이 의견을 나눴으면 합니다.

2023-10-07 05:11 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/application/OAuth2Clients.java
>              }
클라이언트 요청은 정상이지만, 서버에 문제가 발생하여 정상적인 응답을 내려주지 못하는 경우가 `InternalServerException`이라고 생각합니다.
하지만 여기 코드에서 나타나는 부분도 같은 맥락으로 생각할 수 있는데 (클라이언트가 개발자 그 자체)
코드에서 잘못된 설정으로 발생하는 문제점이고,  `InternalServerException`은 WARN 로그를 발생시키기에 `InternalServerException`이 맞지 않다고 판단하여 표준 예외인 `IllegalArgumentException`을 사용했습니다.
또한 표준 예외를 사용하므로 에러 코드가 필요 없어졌으므로 문자열을 적었습니다.

2023-10-07 05:13 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/domain/AuthPayload.java
>      }
https://github.com/woowacourse-teams/2023-festa-go/pull/515/files#r1349463380
위와 같은 맥락으로 `IllegalArgumentException`을 던졌습니다.
`AuthPayload`의 생성 주체(클라이언트)는 어플리케이션 사용자가 아닌, 코드를 작성하는 개발자더군요.

2023-10-07 05:14 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/domain/Role.java
>          }
https://github.com/woowacourse-teams/2023-festa-go/pull/515/files#r1349463643
동일합니다.

2023-10-07 05:17 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/infrastructure/JwtAuthExtractor.java
>          }
JWT 토큰을 파싱할 때 발생하는 예외는 다음과 같습니다.
```
UnsupportedJwtException – if the claimsJws argument does not represent an Claims JWS
MalformedJwtException – if the claimsJws string is not a valid JWS
SignatureException – if the claimsJws JWS signature validation fails
ExpiredJwtException – if the specified JWT is a Claims JWT and the Claims has an expiration time before the time this method is invoked.
IllegalArgumentException – if the claimsJws string is null or empty or only whitespace
```
위에서 발생하는 대부분의 예외는 클라이언트의 요청에 의해 발생하는 예외입니다. (잘못된 토큰)
따라서 클라이언트에 의해 발생하는 예외를 모두 잡고, 혹여 클라이언트의 요청 외 발생할 수 있는 서버 측 문제 (라이브러리의 잘못된 버전업, 예측할 수 없는 등)의 예외에는 error 로그와 함께 예외를 반환하도록 하였습니다.

2023-10-07 05:20 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/infrastructure/KakaoOAuth2UserInfoErrorHandler.java
>      }
카카오 OAuth2 요청 중 400 에러도 아니고, 500 에러도 아니면 error 로그를 남기도록 하였습니다.
다만 마지막에 던지는 예외는 `InternalServerException`이라 이것을 또한 `IllegalArgumentException`으로 처리해야 할 지 모르겠네요.

2023-10-07 05:21 UTC, seokjin8678 commented on backend/src/main/java/com/festago/common/aop/LogRequestBodyAspect.java
>      }
`RequestBody`에 대한 로그를 수행할 때 `IOException`을 catch 해야하므로 잡는 예외입니다.
해당 코드는 클라이언트 요청에 반환하는 예외가 아닌, 단순 로그용 코드이므로 예외를 던지는 것이 잘못됬다 판단하여 예외를 먹고 로그를 남겼습니다.

2023-10-07 05:23 UTC, seokjin8678 commented on backend/src/main/java/com/festago/common/exception/ErrorCode.java
> +    ;
`IllegalArgumentException`으로 바꾸면서 사용하지 않게된 ErrorCode들 입니다.

2023-10-07 05:31 UTC, seokjin8678 commented on backend/src/main/java/com/festago/entry/domain/EntryCode.java
>      }
여기서 애매한 부분입니다.
`InternalServerException`은 [위에서](https://github.com/woowacourse-teams/2023-festa-go/pull/515/files#r1349463380) 정의를 내렸습니다.
여기서 WARN 로그와 ERROR 로그를 구분할 필요가 있다고 생각합니다.
[링크](https://jojoldu.tistory.com/712)의 글에서 WARN과 ERROR의 목적을 분류하고 있는데 다음과 같습니다.

### WARN
- 애플리케이션에서 잠재적으로 문제가 될 수 있는 상황일때 남기는 로그 레벨

### ERROR
- 애플리케이션에서 발생한 심각한 오류나 예외 상황을 나타내는 로그 레벨

해당 객체는 사용자가 요청해서 만들어지는게 아닌, 서버에서 비즈니스 룰에 의해 만들어지는 객체입니다.
따라서 잘못 만들어진 코드로 인한 예외로 인해 해당 객체를 생성하지 못한다면 사용자는 `EntryCode`를 발급받지 못하게 됩니다.
이는 심각한 문제 상황 입니다. 
이 경우 `InternalServerException`은 WARN 로그를 발생시키므로 대응이 늦어질 수 있습니다. 
따라서 ERROR 로그를 바로 발생시켜 빠르게 대응을 할 수 있어야 하므로 `IllegalArgumentException`을 발생시켰습니다.

2023-10-07 05:32 UTC, seokjin8678 commented on backend/src/main/java/com/festago/entry/domain/EntryCodePayload.java
>      }
https://github.com/woowacourse-teams/2023-festa-go/pull/515/files#r1349465324
동일합니다.

2023-10-07 05:33 UTC, seokjin8678 commented on backend/src/main/java/com/festago/entry/infrastructure/JwtEntryCodeExtractor.java
>          }
https://github.com/woowacourse-teams/2023-festa-go/pull/515/files#r1349464036
동일합니다.

2023-10-07 05:34 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/domain/Festival.java
>          }
이슈에서 말했듯 시간에 관련된 로직은 `BadRequestException`을 발생시켰습니다.

2023-10-07 05:34 UTC, seokjin8678 commented on backend/src/main/java/com/festago/presentation/GlobalExceptionHandler.java
>      }
WARN 로그도 스택 트레이스를 출력하게 했습니다.

2023-10-07 05:37 UTC, seokjin8678 commented on backend/src/main/java/com/festago/student/domain/VerificationMailPayload.java
>      }
애매한 부분 2
`username`만 `ValidException`을 던지고 있습니다.
왜냐하면 해당 객체의 생성 부분을 보면 `username`이 사용자의 요청에 의해 전달되기 때문입니다.
`Validator` 클래스를 사용을 하기엔 혼자 Validator를 사용하는게 어색하여 분기문으로 작성했습니다.
이 경우 `Validator`를 사용할지 말지 의견이 필요합니다.

2023-10-10 02:09 UTC, BGuga commented on backend/src/main/java/com/festago/admin/domain/Admin.java
> +    }
상수로 뽑는 것은... 좀 애매한 것 같고
```
private void validateUsername(String username) {
        String fieldName = "username";
        Validator.hasBlank(username, fieldName);
        Validator.minLength(username, MIN_USERNAME_LENGTH, fieldName);
        Validator.maxLength(username, MAX_USERNAME_LENGTH, fieldName);
    }
```
이정도 중복제거는 가능하지 않을까요??

2023-10-10 02:23 UTC, BGuga commented on backend/src/main/java/com/festago/auth/application/OAuth2Clients.java
>              }
해당 예외가 발생하는 시점은 Controller 을 타고 들어오는 경우가 아니기 때문에 error가 핸들링되지 않네요.
그래서 표준 예외가 발생해도 좋을 것 같고 log 도 해당 메서드에서 바로 찍어줘도 좋을 것 같습니다

2023-10-10 02:53 UTC, carsago commented on backend/src/main/java/com/festago/admin/domain/Admin.java
> +    }
저도 푸우가 주신 의견 정도가 좋다고 느껴요.
필드를 죄다 상수로 뽑기도 그렇고, 필드명을 별도의 클래스(inner class든 아니든)에서 관리해주는 것도 좀 과하지 않나 싶네요.

2023-10-10 03:55 UTC, BGuga requested changes
수고하셨습니다 글렌!! 우선 간단한 커맨트 남겼습니다 ㅎㅎ

2023-10-10 03:55 UTC, BGuga commented on backend/src/main/java/com/festago/student/domain/VerificationMailPayload.java
>      }
여러 API가 다른 입력 파라미터로 해당 객체를 만들경우 그때마다 해당 부분에 변경이 발생할 것 같아요!
또한 만드는데 있어서도 입력 파라미터들을 검증하는 것이 상당히 번거로우니 동일하게 모두 ValidException 을 사용하는 것은 어떨까요??

2023-10-10 05:17 UTC, seokjin8678 commented on backend/src/main/java/com/festago/entry/domain/EntryCodePayload.java
> +            throw new IllegalArgumentException("memberTicketId는 null이 될 수 없습니다.");
저희만 사용하는 `IllegalArgumentException` 역할의 예외가 필요하긴 하겠군요

2023-10-10 05:18 UTC, seokjin8678 commented on backend/src/main/java/com/festago/admin/domain/Admin.java
> +    }
2개 이상 중복된 필드명이 나오는 것은 반영하겠습니다!

2023-10-10 05:44 UTC, seokjin8678 commented on backend/src/main/java/com/festago/entry/domain/EntryCode.java
>      }
`IllegalArgumentException`을 대체하는 `UnexpectedException`을 만들어야겠네요!

2023-10-10 05:53 UTC, seokjin8678 commented on backend/src/main/java/com/festago/student/domain/VerificationMailPayload.java
>      }
예외를 구분하면 도메인을 볼 때 의도를 나타낼 수 있다고 생각해요.
`ValidException`의 경우 표현 계층의 요청에 의해 생성된다고 생각할 수 있고, `UnexpectedException`의 경우 응용 계층 혹은 도메인 계층에서 생성된다고 파악할 수 있을 것 같아요.

2023-11-16 04:39 UTC, BGuga approved these changes
수고 많으셨어요!!

2023-11-16 04:42 UTC, carsago approved these changes
많은 시간이 걸렸네요..

2023-11-16 06:06 UTC, merged