[BE] feat: 회원의 학생 인증 정보 조회 API 구현 (#496)
woowacourse-teams/2023-festa-go pull request #531
Opened 2023-10-13 05:36 UTC by xxeol2

## 📌 관련 이슈

- closed: #496 

## ✨ PR 세부 내용

마이페이지 및 티케팅시 필요한 회원의 학생 인증 정보 조회 API를 구현하였습니다!

2023-10-14 08:24 UTC, seokjin8678 requested changes
열심히 테스트 코드까지 작성해주셨군요! 👍👍
몇 가지 사항에 대해 리뷰 남겼습니다!

2023-10-14 08:24 UTC, seokjin8678 commented on backend/src/main/java/com/festago/student/dto/StudentResponse.java
> +    }
인증이 되지 않은 사용자는 해당 정적 메서드를 호출하여 응답을 반환하는군요!
하지만 매번 새로운 인스턴스 값을 넘겨줄 필요가 있을 것 같지는 않아요! (record 클래스가 불변하므로)
따라서 다음과 같이 캐싱된 값을 넘겨줘도 좋을 것 같네요!
```suggestion
    private static final StudentResponse NOT_VERIFIED = new StudentResponse(false, null);
    ...
    public static StudentResponse notVerified() {
        return NOT_VERIFIED;
    }
```

2023-10-14 08:24 UTC, seokjin8678 commented on backend/src/main/java/com/festago/student/application/StudentService.java
> +    }
다음과 같이 라인 수를 줄일 수 있을 것 같네요!
물론 선택입니다. 👍
```suggestion
    public StudentResponse findVerification(Long memberId) {
        return studentRepository.findByMemberIdWithFetch(memberId)
            .map(value -> StudentResponse.verified(value.getSchool()))
            .orElseGet(StudentResponse::notVerified);
    }
```

2023-10-14 08:24 UTC, seokjin8678 commented on backend/src/main/java/com/festago/student/application/StudentService.java
> +    }
또한 지금 `StudentService` 클래스의 필드 수를 보고 있는데 의존하고 있는 객체가 어마무시하네요.
이 부분에 대해서는 추후 서비스를 작은 서비스로 분리시켜도 좋을 것 같아요!

2023-10-14 08:24 UTC, seokjin8678 commented on backend/src/main/java/com/festago/student/repository/StudentRepository.java
> +    Optional<Student> findByMemberIdWithFetch(@Param("memberId") Long memberId);
🦅👀
```suggestion
    @Query("""
        SELECT st
        FROM Student st
        LEFT JOIN FETCH st.school sc
        WHERE st.member.id = :memberId
        """)
    Optional<Student> findByMemberIdWithFetch(@Param("memberId") Long memberId);
```

2023-10-14 08:24 UTC, seokjin8678 commented on backend/src/main/java/com/festago/student/repository/StudentRepository.java
> +    Optional<Student> findByMemberIdWithFetch(@Param("memberId") Long memberId);
또한 `School`에 대해 left join을 하기보단 inner join을 해도 괜찮지 않을까요?
학생은 학교가 있어야만 존재하니까..

2023-10-15 11:29 UTC, carsago approved these changes
고생하셨습니다 애쉬

2023-10-15 11:29 UTC, carsago commented on backend/src/main/java/com/festago/student/dto/StudentResponse.java
> +    }
글렌이 제안해주신 방법이 캐싱뿐만 아니라 상수 형식으로 빼놓기에 전 '가독성 측면에서도 더 좋을 수 있겠다' 라는 생각도 드네요

2023-10-18 06:59 UTC, xxeol2 commented on backend/src/main/java/com/festago/student/dto/StudentResponse.java
> +    }
오, 가독성과 캐싱 두가지 이점을 모두 챙길 수 있겠군요! 반영하겠습니다

2023-10-18 07:00 UTC, xxeol2 commented on backend/src/main/java/com/festago/student/repository/StudentRepository.java
> +    Optional<Student> findByMemberIdWithFetch(@Param("memberId") Long memberId);
inner join 좋은 아이디어인 것 같아요!!

2023-10-19 00:32 UTC, seokjin8678 approved these changes
리뷰 반영 확인했습니다!

2023-10-19 02:53 UTC, BGuga approved these changes
깔끔하네요!! 수고하셨습니다!

2023-10-19 02:59 UTC, merged