[AN/USER] feat: fcm 푸시 알림 구현 (#522)
woowacourse-teams/2023-festa-go pull request #537
Opened 2023-10-13 06:52 UTC by EmilyCh0

## 📌 관련 이슈

- closed: #522 

## ✨ PR 세부 내용

- 축제 입장 알림 받을 수 있도록 푸시 알림 구현했습니다.
- 알림 권한 요청은 HomeActivity에서 진행합니다.

2023-10-13 08:53 UTC, re4rk requested changes
고생하셨습니다!
코멘트 몇개 달았습니다! 확인부탁드려요👍

2023-10-13 08:53 UTC, re4rk commented on android/festago/app/src/main/java/com/festago/festago/FestagoApplication.kt
> +        )
```suggestion
        val channel = NotificationChannel(
            FcmMessageType.ENTRY_ALERT.channelId,
            getString(R.string.entry_alert_channel_name),
            NotificationManager.IMPORTANCE_DEFAULT
        )
        val notificationManager =
            getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
```
사용하기 직전에 꺼내오는 것이 어떨까요??

2023-10-13 08:53 UTC, re4rk commented on android/festago/app/src/main/java/com/festago/festago/presentation/fcm/NotificationManager.kt
> +            ) == PackageManager.PERMISSION_GRANTED
이부분도 PermissionUtil안에서 `Activity.Compat.checkPermission`으로 빼내는 것이 어떨까요??

2023-10-13 08:53 UTC, re4rk commented on android/festago/app/src/main/java/com/festago/festago/presentation/fcm/TicketEntryService.kt
> +                    // TODO: 입장완료 로직인지 확인하는 로직 추가 필요
ENTRY_PROCESS.channelId으로 입력받았을 때 이 TODO가 해결 됐다고 생각하는데 어떻게 보시나요??

2023-10-13 08:53 UTC, re4rk commented on android/festago/app/src/main/java/com/festago/festago/presentation/fcm/TicketEntryService.kt
> +            ENTRY_ALERT.channelId -> {
`processEntryAlert`나 `handleEntryAlert`로 빼내는 것은 어떤가요??

2023-10-15 11:57 UTC, re4rk approved these changes
고생하셨습니다!👍

2023-10-16 05:03 UTC, SeongHoonC requested changes
고생많으셨습니다! 코멘트 확인해주세요~

2023-10-16 05:03 UTC, SeongHoonC commented on android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeActivity.kt
> +
이 부분도 함수로 분리할 수 있지 않을까요?

2023-10-16 06:04 UTC, EmilyCh0 commented on android/festago/app/src/main/java/com/festago/festago/FestagoApplication.kt
> +        )
반영완료!

2023-10-16 06:04 UTC, EmilyCh0 commented on android/festago/app/src/main/java/com/festago/festago/presentation/fcm/NotificationManager.kt
> +            ) == PackageManager.PERMISSION_GRANTED
반영완료!

2023-10-16 06:04 UTC, EmilyCh0 commented on android/festago/app/src/main/java/com/festago/festago/presentation/fcm/TicketEntryService.kt
> +                    // TODO: 입장완료 로직인지 확인하는 로직 추가 필요
주석 삭제했습니다

2023-10-16 06:04 UTC, EmilyCh0 commented on android/festago/app/src/main/java/com/festago/festago/presentation/fcm/TicketEntryService.kt
> +            ENTRY_ALERT.channelId -> {
반영완료!

2023-10-16 06:17 UTC, EmilyCh0 commented on android/festago/app/src/main/java/com/festago/festago/presentation/fcm/NotificationManager.kt
> +    )
아까 논의한대로 프로퍼티로 가지고 있을 필요는 없지만 싱글톤으로 관리하기 위해서 이대로 둘게요!

2023-10-16 06:18 UTC, EmilyCh0 commented on android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeActivity.kt
> +
함수로 분리해서 내부 프로퍼티 제거했습니다!

2023-10-17 01:14 UTC, SeongHoonC approved these changes
LGTM!

2023-10-17 01:14 UTC, merged