[AN/USER] 홈 화면 회전시 이전에 선택한 화면을 그대로 보여준다. (#534)
woowacourse-teams/2023-festa-go pull request #544
Opened 2023-10-14 09:13 UTC by SeongHoonC

## 📌 관련 이슈

- closed: #534 

## ✨ PR 세부 내용

홈화면에서 회전에도 이전에 선택한 화면을 기억
로그인하지 않았을 경우 이벤트 발생
마이페이지 ScrollView 적용 필요

2023-10-15 12:13 UTC, re4rk requested changes
고생하셨습니다! 코멘트 확인 부탁드려요!

2023-10-15 12:13 UTC, re4rk commented on android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInActivity.kt
> +                }
handleEvent로 분리 부탁드립니다!

2023-10-15 12:13 UTC, re4rk commented on android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInActivity.kt
> +        val callback = object : OnBackPressedCallback(true) {
백버튼도 커스텀이 가능하군요

2023-10-15 12:13 UTC, re4rk commented on android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeViewModel.kt
> +    private fun selectItemWhenSignIn(homeItemType: HomeItemType) {
함수명이 조금 어색하게 느껴진다고 생각하는데 베르의 의견은 어떤가요??
`selectItemOrSignIn`와 같이 다른 함수들과 비슷하게 진행하는건 어떤가요??

2023-10-15 12:13 UTC, re4rk commented on android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeViewModel.kt
> +                _selectedItem.emit(homeItemType)
```suggestion
            if (authRepository.isSigned) {
                _selectedItem.emit(homeItemType)
            } else {
                _event.emit(HomeEvent.ShowSignIn)
```
흐름상 `!`을 빼도 괜찮을 것같은데 어떻게 생각하시나요??

2023-10-16 03:41 UTC, EmilyCh0 approved these changes
고생하셨습니다 👍 코멘트 확인해주세요!

2023-10-16 03:41 UTC, EmilyCh0 commented on android/festago/app/src/main/java/com/festago/festago/presentation/ui/signin/SignInActivity.kt
> +                }
저는 지금도 충분히 깔끔하다고 생각합니다ㅎㅎ uistate, event 둘다 있다면 모를까 지금은 분리하면 오히려 가독성이 떨어질 것 같아요!

2023-10-16 03:41 UTC, EmilyCh0 commented on android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/HomeViewModelTest.kt
> +    fun `축제 목록을 요청했을 때 토큰이 있으면 축제 목록이 보이고 이벤트가 발생하지 않는다`() = runTest {
축제 목록 요청시에는 사용자 인증 유무 확인이 필요 없는 거 아닌가요?_?

2023-10-16 03:41 UTC, EmilyCh0 commented on android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/HomeViewModelTest.kt
> +            expectNoEvents()
이벤트가 발생하지 않은 것도 확인할 수 있군요 👍

2023-10-16 03:41 UTC, EmilyCh0 commented on android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/HomeViewModelTest.kt
> +    fun `마이페이지를 요청했을 때 토큰이 있으면 마이페이지가 보이고 이벤트가 발생하지 않는다`() = runTest {
테스트 이름과 내용이 일치하지 않아요..! 마이페이지 테스트인데 TICKET_LIST를 테스트하고 있습니다ㅋㅋ

2023-10-16 04:40 UTC, SeongHoonC commented on android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/HomeViewModel.kt
> +    private fun selectItemWhenSignIn(homeItemType: HomeItemType) {
좋아요!

2023-10-16 04:45 UTC, SeongHoonC commented on android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/HomeViewModelTest.kt
> +    fun `축제 목록을 요청했을 때 토큰이 있으면 축제 목록이 보이고 이벤트가 발생하지 않는다`() = runTest {
필요없다는 것도 테스트로 확인하고 싶었어요!

2023-10-16 04:48 UTC, SeongHoonC commented on android/festago/app/src/test/java/com/festago/festago/presentation/ui/home/HomeViewModelTest.kt
> +    fun `마이페이지를 요청했을 때 토큰이 있으면 마이페이지가 보이고 이벤트가 발생하지 않는다`() = runTest {
앗 수정하겠습니다!

2023-10-16 07:56 UTC, re4rk approved these changes
고생하셨습니다!

2023-10-16 08:11 UTC, merged