[BE] feat: 축제 조회 필터링 구현(#602)
woowacourse-teams/2023-festa-go pull request #603
Opened 2023-11-09 08:27 UTC by BGuga

## 📌 관련 이슈

- closed: #602

## ✨ PR 세부 내용

축제 조건별 조회 기능 구현했습니다.

2023-11-09 08:46 UTC, xxeol2 approved these changes
감동적인 작업재개입니다 .. . 👏

2023-11-09 08:46 UTC, xxeol2 commented on backend/src/main/java/com/festago/festival/repository/FestivalSpecification.java
> +    }
인스턴스화 방지 👍 Lombok써도 좋을 것 같아요!

2023-11-09 08:46 UTC, xxeol2 commented on backend/src/main/java/com/festago/festival/repository/FestivalFilter.java
> +    END((currentTime) -> afterEndDate(currentTime));
```suggestion
    ALL(currentTime -> all()),
    PROGRESS(currentTime -> afterStartDate(currentTime)
        .and(beforeEndDate(currentTime))),
    PLANNED(currentTime -> beforeStartDate(currentTime)),
    END(currentTime -> afterEndDate(currentTime));
```

2023-11-09 08:46 UTC, xxeol2 commented on backend/src/main/java/com/festago/festival/repository/FestivalFilter.java
> +    }
이녀석은 왜 접근제어자가 없나요?!

2023-11-09 08:46 UTC, xxeol2 commented on backend/src/main/java/com/festago/festival/repository/FestivalSpecification.java
> +    }
startDate와 endDate 상수화해주는건 어떤가요?

2023-11-09 08:46 UTC, xxeol2 commented on backend/src/main/java/com/festago/presentation/FestivalController.java
> +        FestivalsResponse response = festivalService.findFestivals(FestivalFilter.from(festivalFilter));
default ALL 👍

2023-11-09 08:46 UTC, xxeol2 commented on backend/src/test/java/com/festago/presentation/FestivalControllerTest.java
> +        given(festivalService.findFestivals(any()))
```suggestion
        given(festivalService.findFestivals(any(FestivalFilter.class)))
```
타입 명시해주는건 어떤가요?!

2023-11-09 08:54 UTC, BGuga commented on backend/src/main/java/com/festago/festival/repository/FestivalFilter.java
> +    }
Enum 생성자 접근제어자에 뭘 썼는지 기억이 안나요 이걸 따로 명시해줬나요?

2023-11-09 08:57 UTC, BGuga commented on backend/src/test/java/com/festago/presentation/FestivalControllerTest.java
> +        given(festivalService.findFestivals(any()))
리뷰 다 반영했습니당

2023-11-09 15:59 UTC, seokjin8678 requested changes
고생하셨습니다 푸우!
간만에 코드 리뷰 하니 재밌네요.
당장 13시간 뒤에 면접이라 그런지도 모르겠습니다.
페이지네이션 적용을 추후 고려해보는 것도 좋을 것 같네요.

2023-11-09 15:59 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/repository/FestivalFilter.java
> +    END(currentTime -> afterEndDate(currentTime));
Enum에서 스펙을 조합하여 조건을 맞추기 보단, `FestivalSpecification` 객체가 명시적으로 스펙을 던져주는 것은 어떤가요?
```suggestion
    ALL(FestivalSpecification::all),
    PROGRESS(FestivalSpecification::progress),
    PLANNED(FestivalSpecification::beforeStartDate),
    END(FestivalSpecification::afterEndDate);
```

```java
@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class FestivalSpecification {

    private static final String START_DATE = "startDate";
    private static final String END_DATE = "endDate";

    public static Specification<Festival> all(LocalDate currentTime) { // 메서드 참조를 위해 파라미터 추가
        return (root, query, criteriaBuilder) -> criteriaBuilder.conjunction();
    }

    public static Specification<Festival> progress(LocalDate currentTime) {
        return (root, query, criteriaBuilder) -> criteriaBuilder.and(
            criteriaBuilder.lessThan(root.get(START_DATE), currentTime), // lessThanOrEqualTo 고려할 것
            criteriaBuilder.greaterThan(root.get(END_DATE), currentTime) // greaterThanOrEqualTo 고려할 것
        );
    }

    public static Specification<Festival> beforeStartDate(LocalDate currentTime) {
        return (root, query, criteriaBuilder) -> criteriaBuilder.greaterThan(root.get(START_DATE), currentTime);
    }

    public static Specification<Festival> afterEndDate(LocalDate currentTime) {
        return (root, query, criteriaBuilder) -> criteriaBuilder.lessThan(root.get(END_DATE), currentTime);
    }
}
```

2023-11-09 15:59 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/repository/FestivalFilter.java
> +        .and(beforeEndDate(currentTime))),
진행중인 축제의 스펙이 다음과 같이 되어있네요.
```java
public static Specification<Festival> afterStartDate(LocalDate currentTime) {
    return (root, query, criteriaBuilder) -> criteriaBuilder.lessThan(root.get(START_DATE), currentTime);
}

public static Specification<Festival> beforeEndDate(LocalDate currentTime) {
    return (root, query, criteriaBuilder) -> criteriaBuilder.greaterThan(root.get(END_DATE), currentTime);
}
```
이때 `lessThan`, `greaterThan` 이라면 당일에만 진행하는 축제에 대해 당일에 조회하면 조회가 되지 않을 것 같네요.

2023-11-09 15:59 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/repository/FestivalFilter.java
> +    }
크게 고려해야 할 상황은 아니지만...
스트림을 매번 돌리기 보단 스위치를 사용하는게 좋아 보이네요.
물론 새로운 Filter가 추가되면 해당 코드를 변경해야 합니다.
```suggestion
public static FestivalFilter from(String filterName) {
        return switch (filterName) {
            case "ALL" -> ALL;
            case "PROGRESS" -> PROGRESS;
            case "PLANNED" -> PLANNED;
            case "END" -> END;
            default -> throw new BadRequestException(ErrorCode.INVALID_FESTIVAL_FILTER);
        };
    }
```

2023-11-09 15:59 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/repository/FestivalFilter.java
> +    }
`Clock`을 매개변수로 받는게 좋아 보이네요.

2023-11-09 15:59 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/repository/FestivalSpecification.java
> +    }
위의 커멘트에도 남기긴 했지만...
다음과 같이 메서드가 하는 일을 명확하게 하는것은 어떤가요
```suggestion
    public static Specification<Festival> all(LocalDate currentTime) { // 메서드 참조를 위해 파라미터 추가
        return (root, query, criteriaBuilder) -> criteriaBuilder.conjunction();
    }

    public static Specification<Festival> progress(LocalDate currentTime) {
        return (root, query, criteriaBuilder) -> criteriaBuilder.and(
            criteriaBuilder.lessThan(root.get(START_DATE), currentTime), // lessThanOrEqualTo 고려할 것
            criteriaBuilder.greaterThan(root.get(END_DATE), currentTime) // greaterThanOrEqualTo 고려할 것
        );
    }

    public static Specification<Festival> beforeStartDate(LocalDate currentTime) {
        return (root, query, criteriaBuilder) -> criteriaBuilder.greaterThan(root.get(START_DATE), currentTime);
    }

    public static Specification<Festival> afterEndDate(LocalDate currentTime) {
        return (root, query, criteriaBuilder) -> criteriaBuilder.lessThan(root.get(END_DATE), currentTime);
    }
```

2023-11-09 15:59 UTC, seokjin8678 commented on backend/src/test/java/com/festago/festival/repository/FestivalRepositoryTest.java
> +    }
당일에 해당하는 축제에 대한 테스트 코드도 필요할 것 같네요.

2023-11-09 15:59 UTC, seokjin8678 commented on backend/src/test/java/com/festago/festival/repository/FestivalRepositoryTest.java
> +        festivalRepository.save(new Festival(FUTURE_FESTIVAL, now.plusDays(1L), now.plusDays(3L), school));
시간에 대한 테스트는 "2023-11-10" 과 같이 고정된 값을 사용하는 것은 어떤가요?

2023-11-09 16:01 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/repository/FestivalFilter.java
> +    END(currentTime -> afterEndDate(currentTime));
`beforeStartDate`, `afterEndDate`는 센스있게 넘어가주세요

2023-11-09 16:03 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/repository/FestivalFilter.java
> +    }
Enum은 접근제어자가 필요하지 않습니다..!

2023-11-10 10:26 UTC, xxeol2 commented on backend/src/main/java/com/festago/festival/repository/FestivalFilter.java
> +    }
아이고 이놈 enum이었네

2023-11-10 16:56 UTC, seokjin8678 commented on backend/src/main/java/com/festago/common/exception/ErrorCode.java
> +    INVALID_FESTIVAL_FILTER("유효하지 않은 필터 값입니다."),
축제 라는 단어가 들어가도 좋겠네요.
ex) 올바르지 않은 축제의 필터 값 입니다.

2023-11-11 05:31 UTC, carsago reviewed
푸우 조금 늦었지만 간단한 코멘트를 첨부했습니다.
Specification도 은근 배우기 귀찮던데 고생하셨어요 !
현재 저희 조건에서 queryDsl 같은 기술을 추가 도입하는건 과하니 이렇게 푸는게 가장 간단한 거 같네요.

2023-11-11 05:31 UTC, carsago commented on backend/src/main/java/com/festago/presentation/FestivalController.java
> +        @RequestParam(defaultValue = "ALL") String festivalFilter) {
카톡에서 이야기 했던대로 전체가 없어진다면 default는 PROGRESS로 처리하는게 맞죠?_?

2023-11-11 05:31 UTC, carsago commented on backend/src/main/java/com/festago/festival/repository/FestivalFilter.java
> +        .and(beforeEndDate(currentTime))),
@Test
    void 현재_진행_축제_넘기기_오늘시작_내일끝() {
        // given
                                                                  ...
        festivalRepository.save(new Festival("name", now.minusDays(0), now.plusDays(1), school));

        // when
        int actual = festivalRepository.findAll(FestivalFilter.PROGRESS.getSpecification()).size();

        // then
        assertThat(actual).isEqualTo(1);
    }

    @Test
    void 현재_진행_축제_넘기기_어제시작_오늘끝() {
        // given
                                                                  ...
        festivalRepository.save(new Festival("name", now.minusDays(1), now.plusDays(0), school));

        // when
        int actual = festivalRepository.findAll(FestivalFilter.PROGRESS.getSpecification()).size();

        // then
        assertThat(actual).isEqualTo(1);
    }

글렌이 말씀해준것 처럼 이 테스트 코드들이 통과하기 위해선 eqaulsTo 조건이 들어가야겠네요 !!
오늘이 11월 11일이라면, 11월 11일에 시작하는 축제 및 11월 11일에 끝나는 축제가 조회되어야 할테니까요.

2023-11-11 05:31 UTC, carsago commented on backend/src/main/java/com/festago/festival/repository/FestivalFilter.java
> +    END(currentTime -> afterEndDate(currentTime));
저도 글렌이 말씀하신 부분에 동의합니다. Specification method가 Progress 같은 경우 외부에서 and 조건으로 조합해주는 형식이 아니라 명확하게 완성된 조건을 뱉어주는게 더 이해하기 쉽고, 테스트하기 좋은 코드라고 여겨져요.

2023-11-13 06:20 UTC, BGuga commented on backend/src/main/java/com/festago/festival/repository/FestivalFilter.java
> +    }
라임 디졌다 ;;

2023-11-13 06:24 UTC, BGuga commented on backend/src/main/java/com/festago/festival/repository/FestivalFilter.java
> +    }
저도 연산마다 Stream 이 생성되는 것이 비효율적이라 생각했지만
Java 코드 레벨에서의 비효율이 실질적으로 미치는 영향이 크지 않다 생각했습니다.
하지만 But 한번 적용해보는 것도 좋아보여 반영했습니다!

2023-11-13 08:08 UTC, BGuga commented on backend/src/main/java/com/festago/festival/repository/FestivalFilter.java
> +    END(currentTime -> afterEndDate(currentTime));
반영했습니다!

2023-11-13 08:08 UTC, BGuga commented on backend/src/main/java/com/festago/festival/repository/FestivalFilter.java
> +        .and(beforeEndDate(currentTime))),
헉 수정했습니다

2023-11-13 08:09 UTC, BGuga commented on backend/src/test/java/com/festago/festival/repository/FestivalRepositoryTest.java
> +    }
반영했습니다!

2023-11-13 08:09 UTC, BGuga commented on backend/src/main/java/com/festago/presentation/FestivalController.java
> +        @RequestParam(defaultValue = "ALL") String festivalFilter) {
네네 맞습니다!

2023-11-13 08:46 UTC, carsago approved these changes
고생하셨습니다 푸우.

2023-11-13 08:47 UTC, seokjin8678 approved these changes
고생하셨습니다!!!

2023-11-13 08:47 UTC, merged