[AN/USER] feat: 홈화면 필터링 기능을 제공한다 (#600)
woowacourse-teams/2023-festa-go pull request #606
Opened 2023-11-13 09:56 UTC by SeongHoonC

## 📌 관련 이슈

- closed: #600 

## ✨ PR 세부 내용

<img width="270" alt="image" src="https://github.com/woowacourse-teams/2023-festa-go/assets/108349655/d2d9b3ef-ba26-4876-acda-2a21fb01ca46">

<img width="289" alt="image" src="https://github.com/woowacourse-teams/2023-festa-go/assets/108349655/8b28f928-cd36-41f7-9c55-5b9dafc7c517">

<img width="291" alt="image" src="https://github.com/woowacourse-teams/2023-festa-go/assets/108349655/1d3dfc07-d42c-44d7-9d3c-2f528603cd5e">

2023-11-13 11:30 UTC, re4rk approved these changes
고생하셨습니다! 하나 코멘트 달았습니다! 다크모드가 미적용 된 부분이 있는데 이부분만 수정하고 넘어가면 될 것같습니다!
![image](https://github.com/woowacourse-teams/2023-festa-go/assets/37167652/9f76655c-326c-4551-bd5e-d18e7540f759)

2023-11-13 11:30 UTC, re4rk commented on android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModel.kt
> +    private val _festivalFilter = MutableStateFlow<FestivalFilter>(FestivalFilter.PROGRESS)
이 프로퍼티는 uiState안으로 가는 것이 맞지 않나 생각합니다!

2023-11-13 11:59 UTC, SeongHoonC commented on android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModel.kt
> +    private val _festivalFilter = MutableStateFlow<FestivalFilter>(FestivalFilter.PROGRESS)
처음에 uiState 안으로 포함시켰다가 이 프로퍼티가 UI 상태와 별개로 존재한다고 생각해 뺐습니다. 

1. 로딩 중이거나 실패해도 보여주어야한다.
2. 다른 필터링 조건으로 변경했을 때 요청 결과와 상관 없이 변경된다.

어떻게 생각하시나요?

2023-11-13 17:42 UTC, re4rk commented on android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListViewModel.kt
> +    private val _festivalFilter = MutableStateFlow<FestivalFilter>(FestivalFilter.PROGRESS)
이후의 대화에서 chipGroup에서 자동으로 설정해주는 것으로 해당 코멘트를 닫도록 하겠습니다!

2023-11-14 01:07 UTC, EmilyCh0 requested changes
고생하셨습니다~ 코멘트 확인해 주세요!!

2023-11-14 01:07 UTC, EmilyCh0 commented on android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
> +    }
화면 회전 시 initView(), initFestivalFilters()에서 중복으로 호출되는데 initView에서는 항상 PROGRESS 상태가 호출됩니다. 그래서 지난 축제에서 화면 회전을 하면 PROGRESS, END 중 랜덤으로 나와요 🥲

2023-11-14 01:07 UTC, EmilyCh0 commented on android/festago/domain/src/main/java/com/festago/festago/model/FestivalFilter.kt
> +    ALL, PROGRESS, PLANNED, END
ALL은 사용하지도 않고, 명세에도 없으니 제거해도 되지 않을까요??

2023-11-14 01:27 UTC, SeongHoonC commented on android/festago/domain/src/main/java/com/festago/festago/model/FestivalFilter.kt
> +    ALL, PROGRESS, PLANNED, END
서버 코드를 찾아봤는데 Enum 에 ALL 이 있어서 추가했습니다! 
또한 api 요청 결과 default 가 all 이기도 합니다.

추후 검색기능 등이 생길 때 유용할 것 같은데 어떻게 생각하시나요?

2023-11-14 01:30 UTC, SeongHoonC commented on android/festago/app/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
> +    }
오류 확인했는데 랜덤이라서 알아차리지 못했군요..ㅜ
수정하겠습니다!

2023-11-14 01:32 UTC, EmilyCh0 commented on android/festago/domain/src/main/java/com/festago/festago/model/FestivalFilter.kt
> +    ALL, PROGRESS, PLANNED, END
노션 명세에는 ALL이 없어서 서버쪽에 있는 개념인지 몰랐네요..! 추후 사용도 고려해서 그대로 두는 거 좋습니다 👍

2023-11-14 03:25 UTC, EmilyCh0 approved these changes
LGTM!

2023-11-14 03:30 UTC, merged