[BE] feat: Specification을 Querydsl로 대체한다 (#604)
woowacourse-teams/2023-festa-go pull request #609
Opened 2023-11-14 03:57 UTC by BGuga

## 📌 관련 이슈

- closed: #604

## ✨ PR 세부 내용

Specification 로직을 Querydsl로 변경했습니다

2023-11-14 06:00 UTC, seokjin8678 requested changes
리뷰 남겼습니다!
쿼리DSL 적용하니 확실히 깔끔하네요

2023-11-14 08:19 UTC, BGuga commented on backend/src/main/java/com/festago/common/exception/ErrorCode.java
> +    NOT_DEFINED_FESTIVAL_FESTIVAL("정의되지 않은 축제 필터입니다.");
사용하지 않게 되어 삭제했습니다.

2023-11-14 08:21 UTC, BGuga commented on backend/build.gradle
> +
삭제했고 둘 다 빌드 되는 것 확인했습니다.

2023-11-14 08:26 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/repository/FestivalRepositoryCustomImpl.java
> +    public List<Festival> findFestivalBy(FestivalFilter festivalFilter, LocalDate currentTime) {
`findByFilter` 라는 이름은 어떠신가요?
또한, Clock을 의존하게 해서, `LocalDate.now(clock)`을 내부에서 사용하게 한다면 인자로 들어오는 `currentTime`은 필요 없을 것 같은데 이 부분은 테스트 용이성을 위해 열어두신건가요?

2023-11-14 11:48 UTC, seokjin8678 commented on backend/src/test/java/com/festago/festival/repository/FestivalRepositoryTest.java
> +@Transactional
```suggestion
@RepositoryTest
```

2023-11-16 05:52 UTC, BGuga commented on backend/src/main/java/com/festago/festival/repository/FestivalRepositoryCustomImpl.java
> +    public List<Festival> findFestivalBy(FestivalFilter festivalFilter, LocalDate currentTime) {
That's right 맞습니다

2023-11-16 06:55 UTC, seokjin8678 commented
충돌 해결했습니당

2023-11-16 07:35 UTC, seokjin8678 approved these changes
리뷰 반영 확인했습니다!

2023-11-16 08:51 UTC, carsago approved these changes
멋진 성장입니다 푸우.

2023-11-18 09:45 UTC, xxeol2 approved these changes
Querydsl 멋있네요 👍

2023-11-19 03:39 UTC, merged