[BE] test: SchoolService의 통합테스트를 작성 (#623)
woowacourse-teams/2023-festa-go pull request #624
Opened 2023-11-18 09:54 UTC by carsago

## 📌 관련 이슈

- closed: #623

## ✨ PR 세부 내용

BEFROE
--- 

<img width="478" alt="스크린샷 2023-11-18 오후 4 55 50" src="https://github.com/woowacourse-teams/2023-festa-go/assets/100915276/053e5346-aae8-4982-b5ef-c0bd7de36a9a">

AFTER
---

<img width="485" alt="스크린샷 2023-11-18 오후 6 53 21" src="https://github.com/woowacourse-teams/2023-festa-go/assets/100915276/0ebcd7ab-3d47-4dce-aa42-c67d70773fa5">

2023-11-18 09:55 UTC, carsago commented on backend/src/main/java/com/festago/school/dto/SchoolCreateRequest.java
>  }
이 부분에 parameter 순서를 변경하였습니다.
찾아보니 School domain도 domain - name, response도 domain - name 순서고
심지어 다른 Request Dto를 만드는 다른 테스트들도 인자는 name - domain 순서인데 domain - name으로 입력해놓았더라고요..

2023-11-18 15:00 UTC, seokjin8678 commented on backend/src/main/java/com/festago/school/dto/SchoolCreateRequest.java
>  }
직접 생성자로 생성하는 객체가 아니라 버그가 없었지만, 직접 생성자로 생성했다면 순서가 꼬여서 버그가 생겼겠군요. 😂

2023-11-18 15:09 UTC, seokjin8678 commented on backend/src/test/java/com/festago/school/intergration/SchoolServiceIntegration.java
> +public class SchoolServiceIntegration extends ApplicationIntegrationTest {
테스트 클래스 뒤에 `Test`가 붙으면 좋을 것 같네요.

2023-11-18 15:09 UTC, seokjin8678 commented on backend/src/test/java/com/festago/school/intergration/SchoolServiceIntegration.java
> +                    .isInstanceOf(BadRequestException.class);
어떠한 예외인지 에러 메시지를 검증해도 좋을 것 같아요!

2023-11-18 15:10 UTC, seokjin8678 requested changes
몇 가지 리뷰 남겼습니다!

2023-11-19 05:04 UTC, carsago commented on backend/src/test/java/com/festago/school/intergration/SchoolServiceIntegration.java
> +public class SchoolServiceIntegration extends ApplicationIntegrationTest {
체크 못했었네용 ㅠㅠ

2023-11-19 05:05 UTC, carsago commented on backend/src/test/java/com/festago/school/intergration/SchoolServiceIntegration.java
> +public class SchoolServiceIntegration extends ApplicationIntegrationTest {
체크 못했었네요 ㅠ

2023-11-19 05:05 UTC, carsago commented on backend/src/test/java/com/festago/school/intergration/SchoolServiceIntegration.java
> +                    .isInstanceOf(BadRequestException.class);
이 부분도 다른 테스트코드의 컨벤션 맞게 추가하였습니다.

2023-11-20 14:24 UTC, xxeol2 approved these changes
눈감고 넘어갈 수 있는 작은 부분이었는데, 꼼꼼하게 테스트케이스 채워주셔서 감사해요 🫡

2023-11-20 14:24 UTC, xxeol2 commented on backend/src/main/java/com/festago/school/dto/SchoolCreateRequest.java
>  }
파라미터 순서 통일해준거 좋네요!!
다만 domain - name 순서보다 name - domain 순서가 한 눈에 봤을 때 조금 더 자연스러워보이긴 하네요
어떻게 생각하시나요?

```json
// domain - name
{
    "domain": "snu.ac.kr",
    "name": "서울대학교"
}

// name - domain
{
    "name": "서울대학교",
    "domain": "snu.ac.kr"
}
```

하지만 이 순서때문에 혹시 테스트코드가 영향을 받는다면 ㅎ domain - name도 좋습니다 ^_^

2023-11-20 14:24 UTC, xxeol2 commented on backend/src/test/java/com/festago/school/intergration/SchoolServiceIntegrationTest.java
> +        schoolRepository.save(new School("domain.jp", "name3"));
다른 테스트들에서는 생성자 변경을 대비하여 단순한 객체여도 Fixture를 활용한 형태인데, 이 부분에 대해서도 얘기 나누고가도 좋을 것 같아요!
(근데 또 Request는 전부 생성자로 만들고있긴함..ㅋㅋㅋ)

이런 파라미터가 2개짜리는 그냥 테스트에서 생성자로 객체 생성하자 vs 나중에 생성자 파라미터 변경을 대비하여 Fixture를 활용하는 방식으로 통일하자

2023-11-21 01:03 UTC, carsago commented on backend/src/test/java/com/festago/school/intergration/SchoolServiceIntegrationTest.java
> +        schoolRepository.save(new School("domain.jp", "name3"));
개인적으론 School만 보면 생성자로 만드는게 더 명확하고 가독성이 더 좋다 여기는데 통일할거냐 적당히 섞어 쓰느냐가 문제네용

2023-11-21 01:03 UTC, carsago commented on backend/src/main/java/com/festago/school/dto/SchoolCreateRequest.java
>  }
이 부분도 명확한건 애쉬가 말씀해주신 것 처럼 그렇다고 느끼던데  ```SchoolResponse```나  ```School```과 같은 다른 모든 객체들은 name - domain 순이라 부담스럽더라고요 ㅠ (바꿀려면 바꾸긴 가능)

2023-11-22 14:34 UTC, seokjin8678 approved these changes
리뷰 반영 확인했습니다!

2023-12-11 05:38 UTC, SeongHoonC commented
불필요 브랜치를 삭제하다가 잘못 삭제해버렸네요. 죄송합니다!

2023-12-20 08:46 UTC, BGuga approved these changes
수고하셨습니다 🫡
꼼꼼히 봐주셔서 감사합니다 ㅎㅎ

2023-12-20 08:46 UTC, BGuga commented on backend/src/test/java/com/festago/school/intergration/SchoolServiceIntegrationTest.java
> +        schoolRepository.save(new School("domain.jp", "name3"));
Fixture 를 통한 default 값이 테스트를 편리하게 만들어주는 것 같아요.
파라미터로 전달할 것이 많으면 Fixture 가 절실하겠지만 이런 경우에는 오히려 Fixture 를 만드는 것이 더 귀찮아보여요.
하지만 테스트 코드에서 모든 파라미터를 다 전달한다면  테스트하고자 하는 범위 이상으로 구현에 의존할 수 있다 생각해요. 예를들어 이름은 3글자 이상이다가 있을 것 같네요. 그래서 저는 픽스처가 편리성과 의존성 완화의 장점을 취하기 위해 조금 더 사용해도 좋다는 생각입니다!!

2023-12-21 05:36 UTC, merged