[BE] refactor: JPQL을 사용하는 Repository 메소드를 QueryDsl로 변경
woowacourse-teams/2023-festa-go pull request #628
Opened 2023-11-21 10:28 UTC by carsago

## 📌 관련 이슈

- closed: #627 

## ✨ PR 세부 내용

일단 모든 JPQL을 옮겼는데 사실 클래스가 2개가 늘어나니 이게 맞나? 싶기도 하고 미리 처내는게 좋겠다는 생각도 들더라고요.
컨벤션 같은 부분도 자의적인 부분이 있으니 여러분이 보시기에 합리적이지 않다 싶은 부분, 생각해보면 좋겠다 싶은 부분은 편하게 의견 남겨주세요.
코드단에도 코멘트를 남기겠습니다.

2023-11-21 10:31 UTC, carsago commented on backend/src/main/java/com/festago/stage/repository/StageRepositoryCustomImpl.java
> +                .leftJoin(stage.festival, festival).fetchJoin()
2번째인자인 alias가 없어도 되는데 이 메소드에서는 밑에 festival을 쓰니까 alias를 설정해줬어요.
이것도 필요하면 달지 안달지 정해보는 것도 좋을 것 같아요.

또 ```.fetchJoin()```을 같은 라인에서 했는데 전 이게 가독성이 좋아보이더라고요.

2023-11-21 12:00 UTC, carsago commented on backend/src/main/java/com/festago/student/repository/StudentRepositoryCustomImpl.java
> +                .innerJoin(student.school).fetchJoin()
기존의 코드를 옮겨놓는다고 inner join으로 명시되어 있으면 inner Join하고 아니면 join을 했는데요.
둘다 똑같이 작동합니다. 그냥 하나로 통일하는게 좋다고 느껴져요.

2023-11-22 07:47 UTC, seokjin8678 commented on backend/src/main/java/com/festago/stage/repository/StageRepositoryCustomImpl.java
> +                .fetchOne());
애매하긴 한게, Festival의 School까지 들고오는게 그렇네요. 😂

2023-11-22 07:49 UTC, seokjin8678 commented on backend/src/main/java/com/festago/stage/repository/StageRepositoryCustomImpl.java
> +                .leftJoin(stage.festival, festival).fetchJoin()
QueryDSL 사용할 때 컨벤션을 정해도 좋겠네요.
묵시적인 것 보단, 명시적인게 좋다고 생각합니다!

2023-11-22 14:32 UTC, seokjin8678 requested changes
고생하셨습니다!
innerJoin 키워드에 대한 리뷰 남겼습니다!

2023-11-27 07:31 UTC, BGuga approved these changes
마이그레이션까지 너무 좋습니다 👍

2023-11-28 05:25 UTC, carsago commented
11월 28일

1. Join이 아닌 inner join 활용
2. alias가 필요없어도 명시적으로 표기를 하였습니다.

2023-12-20 12:50 UTC, merged