[BE] feat: 의존성을 정리한다(#643)
woowacourse-teams/2023-festa-go pull request #644
Opened 2023-12-31 13:39 UTC by BGuga

## 📌 관련 이슈

- closed: #643

## ✨ PR 세부 내용

의존성 정리를 진행하였고,
AuthController 에서 evnet 를 발행하고 있는데 이는 AuthServier 에 fcm 을 모르도록 만들기 위함입니다.
추후에 fcm 분리하면 생성 시점에는 해결될 것이고 삭제에는 마찬가지로 event 를 발행해야할 것 같습니다.

2024-01-01 11:58 UTC, seokjin8678 requested changes
고생하셨습니다 푸우!
몇 가지 리뷰 남겼습니다.
조회가 목적인 Query 서비스와 비즈니스 로직이 담긴 명령이 목적인 Command 서비스(이름이 Command가 아니더라도)를 분리하면 좋겠네요.
---
지금 PR의 목적은 의존성의 정리이니, 엔티티의 변경이 생기는 부분은 추후 새로운 이슈를 만들어 해결하면 좋을 것 같습니다!
(MemberTicket의 Ticket 의존성 추가, Stage 의존성 제거)

2024-01-01 11:58 UTC, seokjin8678 commented on backend/src/main/java/com/festago/stage/application/FestivalStageServiceImpl.java
> +    private DetailStageResponse makeResponse(Stage stage) {
make라는 이름보다는 create는 어떤가요?

2024-01-01 11:58 UTC, seokjin8678 commented on backend/src/main/java/com/festago/stage/application/FestivalStageServiceImpl.java
> +    }
return 타입을 `DetailTicketResponse`로 반환하는건 어떤가요?
```java
private DetailTicketResponse createDetailTicketResponse(Ticket ticket) {
    TicketAmount ticketAmount = ticket.getTicketAmount();
    return new DetailTicketResponse(
        ticket.getId(),
        ticket.getTicketType().name(),
        ticketAmount.getTotalAmount(),
        ticketAmount.calculateRemainAmount()
    );
}
```

2024-01-01 11:58 UTC, seokjin8678 commented on backend/src/main/java/com/festago/ticket/domain/ReservationSequence.java
> +}
해당 값 타입 객체를 만들어 사용해주신 이유가 있을까요?

2024-01-01 11:58 UTC, seokjin8678 commented on backend/src/main/java/com/festago/ticket/domain/TicketInfo.java
> +}
해당 클래스는 DTO 용도의 클래스로 보이는데 record로 변환한다면 다음과 같이 변경할 수 있습니다!
compact construtor를 사용하여 코드를 최소화 할 수 있습니다.
자세한 내용은 [링크](https://blog.hexabrain.net/399#%EC%BB%B4%ED%8C%A9%ED%8A%B8-%EC%83%9D%EC%84%B1%EC%9E%90compact-constructor) 참조하시면 좋을 것 같네요.
```java
public record TicketInfo(
    Stage stage,
    ReservationSequence sequence,
    LocalDateTime entryTime,
    TicketType ticketType
) {

    public TicketInfo {
        validate(stage, sequence, entryTime, ticketType);
    }

    private void validate(Stage stage, ReservationSequence sequence, LocalDateTime entryTime, TicketType ticketType) {
        validateStage(stage);
        validateSequence(sequence);
        validateEntryTime(entryTime);
        validateTicketType(ticketType);
    }

    private void validateStage(Stage stage) {
        Validator.notNull(stage, "stage");
    }

    private void validateSequence(ReservationSequence sequence) {
        Validator.notNull(sequence, "sequence");
    }

    private void validateEntryTime(LocalDateTime entryTime) {
        Validator.notNull(entryTime, "entryTime");
    }

    private void validateTicketType(TicketType ticketType) {
        Validator.notNull(ticketType, "ticketType");
    }
}
```

2024-01-01 11:58 UTC, seokjin8678 commented on backend/src/main/java/com/festago/ticket/domain/TicketInfo.java
> +}
또한 이름을 `TicketInfo` 보단, 예매를 위한 정보를 전송하므로 `TicketReserveInfo`와 같이 명확하게 변경해도 좋을 것 같네요.

2024-01-01 11:58 UTC, seokjin8678 commented on backend/src/main/java/com/festago/ticketing/domain/MemberTicket.java
> +    }
해당 메서드가 필요한 이유는 `MemberTicket`을 생성할 때 Ticket의 Stage가 시작되었는지 확인하기 위해서 같네요.
`MemberTicket`의 생성자로 Stage가 아닌 Ticket을 받는게 더 적절하지 않나 싶어요.
왜냐하면 `MemberTicket`가 참조하는 Stage는 단순히 조회에서 사용되더군요. (그것도 식별자만)
그렇게 한다면 `TicketInfo`라는 DTO는 사용하지 않아도 될 것 같네요.

2024-01-04 04:20 UTC, carsago commented on backend/src/main/java/com/festago/festival/application/FestivalStageService.java
> +}
dd

2024-01-04 06:32 UTC, carsago reviewed
간단한 코멘트를 남겨보았습니다.

2024-01-04 06:32 UTC, carsago commented on backend/src/main/java/com/festago/stage/application/FestivalStageServiceImpl.java
> +    }
이 부분을 Festival이랑 List<Stage>를 DetailFestivalResponse 생성자로 받아서 처리하는 것도 괜찮겠네요.

2024-01-04 08:17 UTC, xxeol2 reviewed
글렌과 오리가 자세하게 코멘트 남겨주셨네요 😁
간단한 코멘트 남기고 갑니다!!

2024-01-04 08:17 UTC, xxeol2 commented on backend/src/main/java/com/festago/festival/dto/DetailFestivalResponse.java
> +}
나중에 보면 헷갈릴 수 있다는 글렌의 말씀에 동의합니다!
다만 글렌이 제시해주신 방법처럼 한다면 외부에서 `StageResponse`를 사용할 때, 실제 StageResponse.java 클래스의 응답객체와 DeatilFestivalResponse 내부 StageResponse 둘 다 노출되어 헷갈릴수도 있겠네요..

2024-01-04 08:17 UTC, xxeol2 commented on backend/src/main/java/com/festago/stage/application/FestivalStageServiceImpl.java
> +
이 서비스를 보니까, 조회와 명령 서비스를 분리하는 이유가 더 잘 보이긴하네요..
다른 비즈니스로직을 수행하는 메서드와 얘가 섞여있었다면 비즈니스로직이 눈에 보이지 않을 것 같네요

2024-01-04 08:17 UTC, xxeol2 commented on backend/src/main/java/com/festago/ticket/domain/ReservationSequence.java
> +    private final int value;
상수와 변수 사이 한 칸 공백 넣어주는건 어떨까용

2024-01-04 08:17 UTC, xxeol2 commented on backend/src/test/java/com/festago/acceptance/EntryPoint.java
> +// TODO: Cucumber 어쩔티비냐
🥒

2024-01-04 13:30 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/dto/DetailFestivalResponse.java
> +}
[링크](https://www.inflearn.com/questions/874055/dto%EC%9D%98-%EA%B0%9C%EC%88%98%EA%B0%80-%EB%A7%8E%EC%95%84%EC%A7%88-%EA%B2%BD%EC%9A%B0%EC%97%90%EB%8A%94-%EC%96%B4%EB%96%BB%EA%B2%8C-%EA%B4%80%EB%A6%AC%ED%95%98%EB%8A%94%EA%B2%8C-%EC%A2%8B%EC%9D%84%EA%B9%8C%EC%9A%94)에도 저와 비슷한 고민을 한 흔적이 있네요.
하지만 이건 코틀린의 케이스라서.. 적용할 수는 없지만 상황에 맞춰 사용해야 할 것 같습니다!

2024-01-06 14:21 UTC, BGuga commented on backend/src/main/java/com/festago/fcm/application/MemberRegisterEventListener.java
> +    }
좋습니다 반영했어요!!

2024-01-06 14:47 UTC, BGuga commented on backend/src/main/java/com/festago/fcm/application/MemberRegisterEventListener.java
> +    }
원래는 조회 쿼리 한 번을 줄이자는 생각이었는데 큰 연산이 아니란 생각이드네요!
작성 당시에는 어차피 새로운 멤버 여부를 알 수 있는 데이터가 있으니 주어진 데이터를 활용해서 최적화해보자 라는 생각이었지만
오히려 복잡해보이는 부분이 더 큰 단점으로 다가오네요 반영했습니다!

2024-01-06 14:52 UTC, BGuga commented on backend/src/main/java/com/festago/fcm/application/MemberRegisterEventListener.java
> +    }
```java
@PostMapping("/oauth2")
@Operation(description = "소셜 엑세스 토큰을 기반으로 로그인 요청을 보낸다.", summary = "OAuth2 로그인")
public ResponseEntity<LoginResponse> login(@RequestBody @Valid LoginRequest request) {
    LoginResponse response = authFacadeService.login(request.socialType(), request.accessToken());
    publisher.publishEvent(new MemberRegisterEvent(request.accessToken(), request.fcmToken()));
    return ResponseEntity.ok()
        .body(response);
}
```
여기서
```java
new MemberRegisterEvent(response.accessToken(), request.fcmToken());
```
request -> response 오타 수정해서 반영했어요

2024-01-06 15:04 UTC, BGuga commented on backend/src/main/java/com/festago/festival/application/FestivalStageService.java
> +}
쿼리 서비스 분리는 작업 단위가 커지는 것 같아 별도의 Issue로 처리할게요!

2024-01-06 15:14 UTC, BGuga commented on backend/src/main/java/com/festago/ticket/domain/ReservationSequence.java
> +}
reservation 이란 값을 Service 에서 MemberTicket -> Ticket 의 메서드까지 타고가면서 잘못된 값이 들어갔을 때 검증이 너무 늦게 발생한다는 문제가 발생해서 값 객체로 선언했습니다!

2024-01-06 15:16 UTC, BGuga commented on backend/src/main/java/com/festago/ticket/domain/TicketInfo.java
> +}
record 를 안 썼던 이유가 해당 객체를 domain 간에 주고 받기 때문에 값 객체라 생각하였었습니다.
record 로 선언해도 좋을 것 같네요!

2024-01-06 15:23 UTC, BGuga commented on backend/src/main/java/com/festago/ticketing/domain/MemberTicket.java
> +    }
> 해당 메서드가 필요한 이유는 MemberTicket을 생성할 때 Ticket의 Stage가 시작되었는지 확인하기 위해서 같네요.
MemberTicket의 생성자로 Stage가 아닌 Ticket을 받는게 더 적절하지 않나 싶어요.
왜냐하면 MemberTicket가 참조하는 Stage는 단순히 조회에서 사용되더군요. (그것도 식별자만)
그렇게 한다면 TicketInfo라는 DTO는 사용하지 않아도 될 것 같네요.

맞아요.. 그래서 저희 MemberTicket을 Ticket으로 변경하는 작업을 진행하는 것이 좋을까요??

2024-01-06 15:25 UTC, BGuga commented on backend/src/main/java/com/festago/ticketing/domain/MemberTicket.java
> +    }
> 저는 굳이 이제 이 로직이 static factory method일 필요가 있나 싶어요.
Ticket이 아니라 Stage가 필요한거라 TicketInfo를 받거나 아니면 getter로 하나씩 꺼내줘서 생성자로 만들어주는게 좋다는 생각이 드네요.

그러면 Service 에서 MemberTicket을 만드는 것을 생각하신 건가요??

2024-01-06 15:27 UTC, BGuga commented on backend/src/main/java/com/festago/auth/presentation/AuthController.java
> +    private final ApplicationEventPublisher publisher;
그러면 Auth Service 가 fcm 을 알게되는데 괜찮을까용??

2024-01-06 15:42 UTC, BGuga commented on backend/src/main/java/com/festago/stage/application/FestivalStageServiceImpl.java
> +    }
Festival 로 넘기면 Festival 이 Stage에 대한 의존이 생겨버려서 Stage Service 에서 다 만들었어요!!

2024-01-06 15:52 UTC, BGuga commented on backend/src/main/java/com/festago/festival/dto/DetailFestivalResponse.java
> +}
이렇게 한 번 만들어 봤는데 
```java
private DetailFestivalResponse.StageResponse.TicketResponse createResponse(Ticket ticket) {
        TicketAmount ticketAmount = ticket.getTicketAmount();
        return new DetailFestivalResponse.StageResponse.TicketResponse(
            ticket.getId(),
            ticket.getTicketType().name(),
            ticketAmount.getTotalAmount(),
            ticketAmount.calculateRemainAmount()
        );
    }
```
와 같이 작성되는데 이질적이긴 하네요 ... ㅋㅋ
하지만 응집도가 좋은 것 같습니다.

2024-01-06 15:54 UTC, BGuga commented on backend/src/main/java/com/festago/festival/dto/DetailFestivalResponse.java
> +}
> 나중에 보면 헷갈릴 수 있다는 글렌의 말씀에 동의합니다!
다만 글렌이 제시해주신 방법처럼 한다면 외부에서 StageResponse를 사용할 때, 실제 StageResponse.java 클래스의 응답객체와 DeatilFestivalResponse 내부 StageResponse 둘 다 노출되어 헷갈릴수도 있겠네요..

Detail 이란 prefix 를 붙혀서 우선 구분 가능하도록 만들어 뒀습니다!!
요런 헷갈림을 방지하기 위해서 멀티모듈을 쓰면서 접근 조차 불가능하게 만드는 것 같기도 하네요 !!

2024-01-07 13:46 UTC, seokjin8678 approved these changes
리뷰 반영 모두 확인했습니다!
고생하셨습니다!

2024-01-08 09:48 UTC, carsago commented on backend/src/main/java/com/festago/ticketing/domain/MemberTicket.java
> +    }
d

2024-01-08 09:53 UTC, carsago approved these changes
고생하셨습니다 푸우
코멘트 달아주신 거 덕분에  구현 방식에 관한 부분이 대부분 공감됐습니다.

2024-01-08 09:53 UTC, carsago commented on backend/src/main/java/com/festago/auth/presentation/AuthController.java
> +    private final ApplicationEventPublisher publisher;
신경 쓰이긴한데, 사실 Controller에서 알기 때문에 패키지 의존성은 상관 없지않을까요..?

2024-01-08 09:53 UTC, carsago commented on backend/src/main/java/com/festago/ticketing/domain/MemberTicket.java
> +    }
MemberTicket의 생성자로 만들되 필요한 인자를 꺼내서 넣어주는 걸 생각했었어요!

2024-01-09 13:55 UTC, merged