[BE] feat: 아티스트 CRUD 기능을 새롭게 추가 (#665)
woowacourse-teams/2023-festa-go pull request #666
Opened 2024-01-20 13:55 UTC by carsago

## 📌 관련 이슈

- closed: #665 

## ✨ PR 세부 내용

- admin에서 사용할 아티스트 CRUD 기능을 추가하였습니다.
- 조회도 현재 admin외엔 사용할 부분이 없다보니 admin에 넣어놨습니다.

고민점

아직 이야기를 하지 않아서 전 controller를 제외하곤 클래스들을 artist 패키지에 두었는데요.
만약 Service 클래스에 어드민에서 사용하는 기능과 페스타고 앱에서 사용하는 기능이 함께 존재한다면 나중에 어떤 부분이 앱에서 사용되는 것이고, 어드민에서 사용하는 것인지 분간하기 귀찮을 것 같다는 생각이 듭니다.

제 생각엔 admin에서만 쓸 것 들은 별도 클래스로 분리하고 admin/application 패키지로 가야하지 않을까 싶습니다. (아마 Dto도?)

2024-01-20 14:22 UTC, seokjin8678 commented on backend/src/main/java/com/festago/admin/presentation/AdminArtistV1Controller.java
> +    }
저는 삭제할 때 `200 OK` 응답 대신 `204 No Content` 응답을 내려줬는데요, 오리는 이에 대해 어떻게 생각하시나요?

2024-01-20 14:38 UTC, seokjin8678 requested changes
안녕하세요 오리!
리뷰 남겼으니 확인 부탁드립니다!
이번 기회로 새롭게 컨벤션을 맞추면 좋겠네요!

2024-01-20 14:38 UTC, seokjin8678 commented on backend/src/main/java/com/festago/admin/presentation/AdminArtistV1Controller.java
> +    }
저는 삭제할 때 `200 OK` 응답 대신 `204 No Content` 응답을 내려줬는데요, 오리는 이에 대해 어떻게 생각하시나요?

2024-01-20 14:38 UTC, seokjin8678 commented on backend/src/main/java/com/festago/admin/presentation/AdminArtistV1Controller.java
> +    }
조회 요청의 경우 민감한 정보가 아니라면 admin 패키지에 관리될 필요가 없을 것 같습니다!

2024-01-20 14:38 UTC, seokjin8678 commented on backend/src/main/java/com/festago/admin/presentation/AdminArtistV1Controller.java
> +    }
`ArtistCreateRequest`는 나중에 API 버전이 변경된다면 필드가 바뀔 가능성이 있어보여서, 저는 Request에도 버저닝을 적용했습니다.
오리는 어떻게 생각하시나요?

2024-01-20 14:38 UTC, seokjin8678 commented on backend/src/main/java/com/festago/artist/application/ArtistCommandService.java
> +@Transactional(readOnly = false)
명시적으로 `readOnly = false`를 설정해주신건가요?

2024-01-20 14:38 UTC, seokjin8678 commented on backend/src/main/java/com/festago/artist/application/ArtistCommandService.java
> +    }
위의 `Request` 버저닝에 관한 내용입니다!
만약, `Request`가 요구 사항의 변경으로 인해 필드의 변경이 일어난다면 해당 `Service` 클래스는 변경에 맞춰 수정될텐데, 그렇다면 기존 컨트롤러를 호환하기 위한 `Service`가 생겨야 하지 않을까요?
저는 그것을 막기 위해 `CommandService`는 `Command` 객체를 받도록 하였습니다!
오리의 의견은 어떠신가요?

2024-01-20 14:38 UTC, seokjin8678 commented on backend/src/main/java/com/festago/artist/application/ArtistQueryService.java
> +    }
해당 `Response` 또한 버저닝의 관점에서 오리의 생각이 궁금합니다!

2024-01-20 14:38 UTC, seokjin8678 commented on backend/src/main/java/com/festago/artist/repository/ArtistRepository.java
> +    Long deleteById(Long artistId);
delete 메서드에서 반환 값으로 식별자를 넘겨주신 이유가 있을까요?

2024-01-20 14:38 UTC, seokjin8678 commented on backend/src/test/java/com/festago/admin/presentation/AdminArtistV1ControllerTest.java
> +        ArtistCreateRequest request = new ArtistCreateRequest("윤하", "www.naver.com");
사소한 의견일 수 있지만, `Request`의 ImageUrl의 파라미터는 `https://image.com/image.png`로 해주는게 어떨까요?

2024-01-20 14:38 UTC, seokjin8678 commented on backend/src/test/java/com/festago/artist/application/integration/ArtistCommandServiceIntegrationTest.java
> +        ArtistCreateRequest request = new ArtistCreateRequest("윤하", "www.zonye.com");
사심이 보이네요 😂

2024-01-20 14:38 UTC, seokjin8678 commented on backend/src/test/java/com/festago/artist/application/integration/ArtistCommandServiceIntegrationTest.java
> +        );
해당 서비스 로직의 목적이면 단순히 `assertThat(artistRepository.findById(artistId)).isPresent()` 정도의 assertion으로 충분해 보이네요!

2024-01-20 14:38 UTC, seokjin8678 commented on backend/src/test/java/com/festago/artist/application/integration/ArtistQueryServiceIntegrationTest.java
> +    void 아티스트_정보를_변경한다() {
```suggestion
    void 아티스트_모두_조회한다() {
```
😁

2024-01-21 06:19 UTC, BGuga approved these changes
수고하셨습니다 오리 🦆
admin 관련해서 예전에 근로에서 비슷한 작업을 한 적이 있어요
AdminPage랑 prolog 페이지에서 똑같은 api 를 호출하니 prolog가 사용하는 api를 개선하기가 힘들었어요!!
그래서 admin 패키지를 아예 분리시키고 Service도 똑같이 admin 전용으로 만들어서(복붙) 기존 api를 수정 했었습니다.

2024-01-21 06:19 UTC, BGuga commented on backend/src/main/java/com/festago/common/exception/ErrorCode.java
> +    ARTIST_NOT_FOUND("존재하지 않는 아티스트입니다."),
ErrorCode가 너무 많아지고 있는 것 같아요 개선이 필요할까요??

2024-01-22 12:30 UTC, xxeol2 commented on backend/src/main/java/com/festago/admin/presentation/AdminArtistV1Controller.java
> +    }
차후에 admin에 띄워주는 정보와 일반 사용자에게 공개되는 정보가 달라질 수도 있을 것 같아요!
우선 admin에 띄워주는 용도니까 여기 둬도 괜찮을 것 같다는 의견입니다!

2024-01-22 12:31 UTC, xxeol2 commented on backend/src/main/java/com/festago/artist/application/ArtistCommandService.java
> +    }
Request를 버저닝한다면 확실히 Request 객체는 뷰 의존적이긴 하겠네요..

2024-01-22 12:33 UTC, xxeol2 approved these changes
수고많으셨어요 오리 🦆

2024-01-25 07:44 UTC, carsago commented
컨벤션에 맞게 코드를 변경해보았습니다.

다만 고민 점이 있고 추후 수정할 부분이 있습니다.

```추후 수정할 부분```
- Repository를 조회(버저닝 적용 버전) 과 CRD 적용한 것과 분리할 예정입니다 다만 글렌 PR에 있는 커스텀 Querydsl Repository를 상속받아서 만드는게 좋을 것 같다고 생각이 들고 (어차피 바꿔야 할듯요), 글렌 PR에 있는 것을 들고 오기엔 변경될 수 있어서 해당 PR 머지 이후에 변경하는게 좋을 것 같아요

```고민할 부분```

- 제 코드에 있는 AritstSerivce들은 (command 와 query 불문하고) 모두 admin에서만 사용될 것입니다. dto도 마찬가지고요.
따라서 전 해당 클래스들이 전부 admin으로 가야한다고 생각합니다. 명칭도 AristAdminQueryService 등으로 변경되야 할 것 같다고 느껴지네요. (현재는 변경하진 않았어요.)

2024-01-25 07:44 UTC, carsago commented on backend/src/main/java/com/festago/admin/presentation/AdminArtistV1Controller.java
> +    }
저도 애쉬가 말씀하신 부분으로 생각했고, domain에 있기엔 조금 부담스럽더라고요.

2024-01-25 10:28 UTC, seokjin8678 approved these changes
고생하셨습니다!
우선 축제 조회가 가능하려면 아티스트가 있어야하니, 추후 새로운 PR에서 리팩터링 하면 좋을 것 같네요!

2024-01-25 10:28 UTC, seokjin8678 commented on backend/src/main/java/com/festago/admin/presentation/v1/AdminArtistV1Controller.java
> +    }
PutMapping 과 PatchMapping에 관해서도 얘기를 해야겠군요!

2024-01-25 10:28 UTC, seokjin8678 commented on backend/src/main/java/com/festago/artist/application/ArtistV1CommandService.java
> +    }
사소한 부분이긴 한데, 체이닝을 다음과 같이 바꿔주는건 어떤가요?

```suggestion
    public Long save(ArtistV1CreateRequest request) {
        Artist artist = artistRepository.save(new Artist(request.name(), request.profileImage()))
        return artist.getId();
    }
```

2024-01-25 10:28 UTC, seokjin8678 commented on backend/src/main/java/com/festago/artist/application/ArtistV1CommandService.java
> +public class ArtistV1CommandService {
Command 에는 버저닝을 적용하지 않고, Query에 버저닝을 적용하기로 했는데 반대로 된 것 같아요!

2024-01-28 07:41 UTC, carsago commented on backend/src/main/java/com/festago/artist/application/ArtistV1CommandService.java
> +public class ArtistV1CommandService {
헐 ㅋㅋ 수정완료 ㅠ

2024-01-28 16:01 UTC, merged