feat: 학교 목록 조회 구현 (#658)
woowacourse-teams/2023-festa-go pull request #667
Opened 2024-01-20 18:52 UTC by BGuga

## 📌 관련 이슈

- #657 

## ✨ PR 세부 내용

- 축제 목록 조회 구현하였습니다.
- 기존에 있던 코드도 작동하도록 OldFestivalRepository, V1FestivalRepository 나누어서 로직을 작성했습니다.

Id 값과 시작일 두 값을 기반으로 페이징을 하는 방안이 잘 떠오르지 않았습니다 😢
대안으로 모든 축제를 간단한 필터 조건으로 가져온 후 서버에서 가공하도록 구현하였습니다!!
가져오는 축제의 양이 크지 않아 괜찮다고 생각하지만 쿼리를 분석하면서 개선 방안을 찾아보겠습니다 🔥

객체 참조 관계로 인해서 Query들이 몇번 더 나가는 것을 더욱 역정규화를 진행해서 개선해볼까 고민했지만
차라리 이렇게 역정규화를 계속 진행할 것이라면 NoSql 과 같은 다른 방안으로 해결하는 것이 더 나을 수도 있겠다 생각했습니다.
감사합니다 🫡

2024-01-20 20:37 UTC, BGuga commented on backend/src/main/java/com/festago/festival/repository/V1FestivalRepository.java
> +        return pagingFestival(page, allPlannedFestivals);
만약 딱 원하는 개수만 가져오겠다하면
```java
private FestivalPage plannedFestivals(FestivalPageable page, LocalDate currentTime) {
        int limit = page.getLimit();
        if (page.getLastStartDate().isPresent() && page.getLastFestivalId().isPresent()) {
            LocalDate lastStartDate = page.getLastStartDate().get();
            List<Festival> festivals = queryFactory.selectFrom(festival)
                .leftJoin(festival.school).fetchJoin()
                .where(festival.startDate.gt(lastStartDate)
                    .or(festival.startDate.eq(lastStartDate)
                        .and(festival.id.gt(page.getLastFestivalId().get()))))
                .orderBy(festival.startDate.asc(), festival.id.asc())
                .limit(limit + CHECKING_END_PAGE_VALUE)
                .fetch();
            return makeFestivalPage(limit, festivals);
        }
        List<Festival> festivals = queryFactory.selectFrom(festival)
            .leftJoin(festival.school).fetchJoin()
            .where(festival.startDate.gt(currentTime))
            .orderBy(festival.startDate.asc(), festival.id.asc())
            .limit(limit + CHECKING_END_PAGE_VALUE)
            .fetch();
        return makeFestivalPage(limit, festivals);
    }

    private FestivalPage makeFestivalPage(int limit, List<Festival> festivals) {
        if (festivals.size() > limit) {
            return new FestivalPage(false, festivals.subList(0, limit));
        }
        return new FestivalPage(true, festivals);
    }
```
이런식으로도 작성할 수 있지만 쿼리가 너무 복잡하다 생각해서 모두 가져오는 방식을 선택했습니다.
어떤 방향이 나아보이나요?

2024-01-20 20:51 UTC, BGuga commented on backend/src/main/java/com/festago/festival/repository/V1FestivalRepository.java
> +        return pagingFestival(page, allPlannedFestivals);
제 생각은 어차피 이렇게 복잡한 쿼리면 Festival 테이블에 풀 테이블 스캔을 할 것이니 DB를 많이 쓰는 것이나
차라리 간단한 Festival 쿼리를 날리고 Spring 서버에 연산을 배치해 Spring 서버를 많이쓰는 것이나 비슷하다 생각했습니다.
DB 메모리 쓸 것이냐 Java 메모리 쓸 것이냐 선택인 것 같은데 Redis나 Mongo에 데이터 정합성만 맞춰주면서 두 마리의 토끼를 다 잡는 것이 더 나은 방안이라 생각됩니당

2024-01-21 08:36 UTC, seokjin8678 requested changes
고생하셨습니다 푸우!
V1FestivalRepository 클래스를 보니 고생 많이 하셨겠구나 싶었습니다. 😂
작엽량이 많아 생각보다 리뷰를 많이 남긴 것 같네요. 😂
혼자 고민할 필요는 없는 리뷰니까 다음 회의 때 같이 얘기하면 좋을 것 같습니다!
---
추가로 PR 제목 수정 필요할 것 같네요!

2024-01-21 08:36 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/repository/FestivalPage.java
> +}
`Slice`를 사용해보는 것은 어떨까요?
https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Slice.html

2024-01-21 08:36 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/repository/FestivalPageable.java
> +public class FestivalPageable {
record를 사용해도 좋을 것 같네요!

2024-01-21 08:36 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/repository/V1FestivalRepository.java
> +public class V1FestivalRepository {
확실히 해당 클래스의 로직이 엄청 복잡하네요 😂
QueryDSL에서 `Pageable` 인터페이스를 받아 페이징을 해주는 기능을 사용해보면 될 것 같은데, 해당 기능을 사용해서 리팩터링 해보면 좋겠네요!

2024-01-21 08:36 UTC, seokjin8678 commented on backend/src/test/java/com/festago/festival/presentation/v1/FestivalV1ControllerTest.java
> +    class 페스티벌_아이디와_마지막_축제_시작일 {
`축제의_식별자` 라는 명확한 도메인 언어를 사용하는 것은 어떤가요?

2024-01-21 08:36 UTC, seokjin8678 commented on backend/src/test/java/com/festago/school/repository/SchoolRepositoryTest.java
> +    void 지역으로_학교를_검새한다() {
```suggestion
    void 지역으로_학교를_검색한다() {
```
😁

2024-01-21 08:36 UTC, seokjin8678 commented on backend/src/test/java/com/festago/support/RepositoryBeanConfig.java
> +}
QueryDSL을 사용하는 Repository가 많아진다면 해당 Config도 비대해질 것 같은데, QueryDSL을 사용하는 Repository는`SpringBootTest`를 사용하거나 통합 테스트로 검증하는 것은 어떤가요?
QueryDSL을 사용하는 목적 자체가 API 명세에 강하게 의존적이기도 하구요!

2024-01-21 08:36 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/repository/V1FestivalRepository.java
> +public class V1FestivalRepository {
`V1FestivalRepository`라는 이름 보다는 `FestivalV1QueryDslRepository` 라는 이름은 어떤가요?

2024-01-21 13:11 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/repository/V1FestivalRepository.java
> +        if (page.getLastFestivalId().isPresent() && page.getLastFestivalId().isPresent()) {
```suggestion
        if (page.getLastFestivalId().isPresent() && page.getLastStartDate().isPresent()) {
```
😁

2024-01-21 13:13 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/repository/V1FestivalRepository.java
> +        if (page.getLastFestivalId().isPresent() && page.getLastFestivalId().isPresent()) {
![image](https://github.com/woowacourse-teams/2023-festa-go/assets/116627736/7dc9cb53-bebf-4568-930b-f7a0e30f937c)
https://plugins.jetbrains.com/plugin/7973-sonarlint
해당 플러그인 설치해보시는거 추천드려요!

2024-01-21 13:29 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/dto/v1/FestivalV1Response.java
> +    String imageUris,
`imageUris`로 변수명을 설정한 이유가 있을까요?

2024-01-21 19:59 UTC, seokjin8678 commented
`V1FestivalRepository`를 QueryProjection을 사용한 방법으로 리팩터링 해보는 중에 문제가 발생하여 코멘트 남깁니다!
```java
@Repository
@RequiredArgsConstructor
public class MyFestivalQueryRepository {

    private final JPAQueryFactory queryFactory;

    public Slice<MyFestivalResponse> findAll(MyFestivalsSearchCondition searchCondition) {
        Pageable pageable = searchCondition.pageable();
        FestivalFilter filter = searchCondition.filter();
        LocalDate currentTime = searchCondition.currentTime();
        SchoolRegion region = searchCondition.region();
        Long lastFestivalId = searchCondition.lastFestivalId();
        List<MyFestivalResponse> content = queryFactory.select(new QMyFestivalResponse(
                festival.id,
                festival.name,
                festival.startDate,
                festival.endDate,
                festival.thumbnail,
                new QMySchoolResponse(
                    school.id,
                    school.name
                ),
                festivalInfo.artistInfo)
            )
            .from(festival)
            .innerJoin(school).on(school.id.eq(festival.school.id))
            .innerJoin(festivalInfo).on(festivalInfo.festival.id.eq(school.id))
            .where(dynamicWhere(filter, currentTime, lastFestivalId, region))
            .orderBy(dynamicOrderBy(filter))
            .limit(pageable.getPageSize() + 1)
            .fetch();
        return new SliceImpl<>(content, pageable, hasNextPage(content, pageable.getPageSize()));
    }

    private BooleanExpression dynamicWhere(FestivalFilter filter, LocalDate currentTime, Long lastFestivalId,
                                           SchoolRegion region) {
        BooleanExpression filterResult = switch (filter) {
            case PLANNED -> festival.startDate.gt(currentTime);
            case PROGRESS -> festival.startDate.loe(currentTime).and(festival.endDate.goe(currentTime));
            case END -> festival.endDate.lt(currentTime);
        };
        if (lastFestivalId != null) {
            return filterResult.and(festival.id.gt(lastFestivalId));
        }
        if (region != null) {
            return filterResult.and(school.region.eq(region));
        }
        return filterResult;
    }

    private OrderSpecifier<LocalDate> dynamicOrderBy(FestivalFilter filter) {
        return switch (filter) {
            case PLANNED, PROGRESS -> festival.startDate.asc();
            case END -> festival.endDate.desc();
        };
    }

    private boolean hasNextPage(List<MyFestivalResponse> content, int pageSize) {
        if (content.size() > pageSize) {
            content.remove(pageSize);
            return true;
        }
        return false;
    }
}
```
리팩터링한 코드는 다음과 같은데요, 여기서 커서 기반 페이징을 할 때 문제가 발생합니다.

ID가 1, 시작일이 5일 ~ 5일
ID가 2, 시작일이 4일 ~ 5일
ID가 3, 시작일이 3일 ~ 5일

여기서 당일이 5일이고, 진행 중인 축제를 한 건 조회하면 결과는 당연히 1개가 나오고 시작일 오름차순으로 조회되기에 식별자가 3인 축제가 조회됩니다.

그리고 다음 조회에서 커서 기반 페이징을 위해 lastFestivalId 3으로 조회하면 아무 결과가 조회되지 않습니다.

왜냐하면 식별자(생성시간)와 시작일이 전혀 연관이 없기 때문입니다.

때문에 식별자를 커서로 사용할 수 없습니다.

그렇다고 시작일을 커서로 사용할 수 없는 것이, 시작일은 고유하지 않습니다. (일-월-년)

정렬 기준을 시작일로 사용하기에 커서에는 시작일이 들어가야 하지만, 고유하지 않기 때문에 불가능하고, 식별자를 포함한다 하더라도 식별자가 시작일하고 연관이 없기에 방법이 보이지 않습니다.
> 식별자를 사용해서 커서 기반 페이징이 가능하다면 방법을 찾아주세요.. 😂

해결할 수 있는 극단적인 방법이 있다면 시작일 오름차순으로 정렬하는 기능을 포기하는 것 입니다.
그러면 식별자로 정렬하므로 식별자를 커서로 사용할 수 있게 됩니다.

서비스 특성상 많은 축제는 없겠지만, 사용자 경험 측면에서 시작일이 빠른 순서로 보여주는 것이 가치 있는 서비스라고 생각한다면 이 방법은 사용할 수 없습니다. 😂

시작일을 빠른 순서로 보여주는 것이 저희 서비스에서 가치 있는 기능이라고 생각한다면, 쉬운 방법과 어려운 방법 2가지가 있습니다.

쉬운 방법은 커서 기반 페이징을 포기하고 오프셋 기반 페이징을 사용하는 것 입니다.

오프셋 기반 페이징이 비효율적인 것은 맞지만, 정말 비효율적인지 고민해 봐야 할 것 같습니다.

어려운 방법은 시작일을 고유하게 만드는 것 입니다.

시작일은 LocalDate 이므로 고유하지 못합니다.
따라서 시작일과 연관이 있는 값을 고유하게 만들어야 하는데, 생각이 든 것은 시작일을 기반으로 milliseconds를 생성하고 유니크 인덱스로 사용하는 것 입니다.
- 시작일을 milliseconds로 만들고 거기에 +1 을 추가해서 고유하게 만드는 것이 핵심입니다.
- milliseconds 대신 LocalDateTime 기반으로 하는 방법도 있습니다.

만드는 방법은 다음과 같습니다.
1. 축제를 생성할 때 축제를 조회한다.
2. 시작일을 where 조건으로(시작일00:00:00ms <= 시작일ms && 시작일23:59:59ms >= 시작일ms) 내림차순 1건 조회
3. 찾은 축제의 cursorId + 1 값으로 세팅 
  - 동시성 문제가 발생할 가능성이 있으므로, 락 필요
  - 낙관적 락 + 찾은 축제는 값이 변경되지 않기에 OPTIMISTIC_FORCE_INCREMENT 사용 필요
4. 결과가 없다면 시작일의 milliseconds로 세팅
  - 마찬가지로 동시성 문제가 발생할 수 있기에 cursorId를 유니크 인덱스로 사용해야 합니다.
  - 하지만 유니크 인덱스로 설정한다면 낙관적 락 버전이 올라가기 전에 유니크 제약 조건 위반 예외가 먼저 발생할 것 같습니다. (PK를 알아야 하기에 먼저 INSERT 되므로)
  - 수정 작업에도 같은 작업이 필요합니다.

복잡하긴 하지만 시작일로 정렬하여 축제를 조회하는 기능이 서비스에서 제공해야 할 중요한 비즈니스 로직이라고 생각한다면 감당할 가치가 있을 것 같기도 합니다.

추가로 적용한다면 조회 성능에서 보너스 이점을 누릴 수 있는 것도 있습니다.

cursorId는 카디널리티가 높으므로 LocalDate를 사용했을 때보다 성능이 상대적으로 높아집니다..!

지금은 offset 기반의 페이징을 사용하고, 낮은 성능 때문에 문제가 발생한다면 다른 방법을 선택하는 것이 좋아 보입니다.

2024-01-22 10:03 UTC, BGuga commented on backend/src/main/java/com/festago/festival/domain/FestivalInfo.java
> +    }
저도 그 방향을 고민했으나
@Entity 안에 infrastructure인 objectMappter가 들어오는 것이 pojo와  더 멀어지는 것 같아서 해당 방식으로 구현했습니다. 지금도 pojo 라고 볼 수는 없지만...

2024-01-22 10:08 UTC, BGuga commented on backend/src/main/java/com/festago/festival/domain/FestivalInfo.java
> +public class FestivalInfo {
앗 여기서 FestivalInfo로 네이밍을 지은 것이 
현재 축제 목록에 포함된 데이터인 축제이름, 학교 이름 등등 여러 데이터를 가져오기 위해서 join을 하고 있어요!!
근데 어차피 조회 쿼리 성능 개선을 위해서 역정규화를 했다면 저런 정보들도 결국 해당 FestivalInfo 로 넣을 것 같다는 생각을 해서 선반영? 한 네이밍 입니다!!
만들어보니 그냥 차리라 FestivalInfo 에 관련된 정보를 시원하게 다 넣는 것이 만들기도 더 쉬울 것 같은데 학교 정보, 축제 정보들을 중복으로 저장해둘까요??
그러면 정합성 맞추기 쉽지 않겠죠?? 그래서 그냥 mongo나 redis 같은 noSql을 적용해서 매일매일 데이터를 적재하는 식으로 가는 것이 훨씬 복잡성이 낮아질 것 같습니다

2024-01-22 10:14 UTC, BGuga commented on backend/src/main/java/com/festago/festival/domain/FestivalInfo.java
> +    private Festival festival;
좋아요!! 성능 개선을 위한 객체니까

2024-01-22 10:39 UTC, BGuga commented on backend/src/main/java/com/festago/festival/domain/FestivalInfoConverter.java
> +}
좋습니다 bb
deserialize 는 최종 반환값을 만들때 DB에 저장된 값 그대로 Artists 정보로 넘기는 것(String) 보다는 다시 역직렬화 후에 dto 로 변환해서 보내는 것이 어떤 응답이 나가는지 알기 쉽다 판단해서 추가했습니다!

2024-01-22 11:13 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/domain/FestivalInfo.java
> +    }
static 사용하는 것이 oop를 위배되고, 안티 패턴이긴 한데.. objectMapper가 thread safe 하기도 하고 private 으로 두면 자기 밖에 사용을 안하는 것도 있긴 한데..
다른 좋은 방법이 있나 고민을 해보는게 좋겠네요

2024-01-22 11:15 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/domain/FestivalInfo.java
> +    private Festival festival;
테스트 할 때 해당 엔티티를 영속하려면 영속 상태의 `Festival` 엔티티가 필요하니, 여러 이유도 있긴 합니다. 😂

2024-01-22 11:18 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/domain/FestivalInfoConverter.java
> +}
Query Projection 기능으로 String(JSON) 값 그대로 반환하는게 더 좋지 않을까요?
```java
queryFactory.select(new QMyFestivalResponse(
    festival.id,
    festival.name,
    festival.startDate,
    festival.endDate,
    festival.thumbnail,
    new QMySchoolResponse(
        school.id,
        school.name
    ),
    festivalInfo.artistInfo)
)
.from(festival)
...
```

2024-01-23 10:31 UTC, carsago commented on backend/src/main/java/com/festago/festival/domain/FestivalInfo.java
> +    private String artistInfo;
이거 커스텀 클래스를 통해 하기보다는  ```@Converter```로 객체는 List로  가지는거 어떤가요? 영속화 하기도, 꺼내 오기도 편할 것 같아요.


```
@Entity
class Member{
    @Id @GeneratedValue
    private Integer id;

    @Convert(converter=BooleanToYNConverter.class)
    private boolean useYn;
}

@Converter
class BooleanToYNConverter implements AttributeConverter<Boolean, String>{
    @Override
    public String convertToDatabaseColumn(Boolean attribute){
        return (attribute != null && attribute) ? "Y" : "N";
    }

    @Override
    public Boolean convertToEntityAttribute(String dbData){
        return "Y".eqauls(dbData);
    }
}
```

https://joont92.github.io/jpa/%EC%97%94%ED%8B%B0%ED%8B%B0-%EA%B0%92%EC%9D%84-%EB%B3%80%ED%99%98%ED%95%B4%EC%84%9C-%EC%A0%80%EC%9E%A5%ED%95%98%EA%B8%B0-Converter/

2024-01-23 11:35 UTC, BGuga commented on backend/src/main/java/com/festago/festival/dto/v1/FestivalV1lListRequest.java
> +    }
1. DTO에 로직이 들어간 것은
원래는 request는 record 기반으로 @NotBlank 같은 어노테이션으로 검증을 했었습니다.
근데 해당 방식은 lastStartDate, lastFestivalId가 둘 다 있거나 둘 다 없는 상황에 대한 검증이 불가해서 Dto에 validate 로직을 포함시켰습니다.
lastStartDate, lastFestivalId 두 값에 대한 Request만 따로 분리해서 validate 해주고 나머지 값들은 @RequestParam 으로 갈려했지만 request 를 만든 시점에서 해당 dto에서 기본값, validate 들을 관리해야 한 눈에 파악하기 쉽다 생각했습니다.
2. Pageable을 사용하지 않은 것은
저희는 두 가지 값 lastFestivalId, lastStartDate 로 페이징을 하기 때문에 마지막 offset을 지정해줄 수가 없었습니다.
그렇기 때문에 강제로 커서 기반으로 가야했습니다.
이 상황에서 Pageable을 사용해서 limit을 담을 수는 없지만 offset을 pageable을 지정해줄 수 없기 때문에 페이징의 관련된 값들이 pageable + dto 에 분리되있는 것이 맘에 안들어서 custom Pageable을 제작하였고 페이징에 필요한 limit, lastFestivalId, lastStartDate를 포함시키도록 만들고자 pageable을 사용하지 않았습니다

2024-01-23 11:44 UTC, BGuga commented on backend/src/main/java/com/festago/festival/repository/FestivalPageable.java
> +public class FestivalPageable {
LastFestivalDate가 nullable하기 때문에 Optional을 쓰고 싶어서 class 로 만들었는데
record의 필드에서 반환된 값을 null로 주는 것보다는 Optional이 낫지 않나요??

2024-01-23 11:46 UTC, BGuga commented on backend/src/main/java/com/festago/festival/repository/V1FestivalRepository.java
> +public class V1FestivalRepository {
> 확실히 해당 클래스의 로직이 엄청 복잡하네요 😂
QueryDSL에서 Pageable 인터페이스를 받아 페이징을 해주는 기능을 사용해보면 될 것 같은데, 해당 기능을 사용해서 리팩터링 해보면 좋겠네요!

pageable 만으로는 festivalId, startDate 값으로 paging을 못해서 pageable을 사용하지 못했습니다!!

2024-01-24 07:02 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/domain/FestivalInfo.java
> +public class FestivalInfo {
조회 전용 DB를 분리해서 만드는 것이 베스트 일 것 같은데.. DB 구축 비용, 학습 비용 등 여러 이슈들이 추가로 생기면 배보다 배꼽이 커질 것 같네요.
`FestivalInfo` 보다 아예 쿼리 전용으로 사용하니 `FestivalQueryInfo`와 같은 이름은 어떤가요?

2024-01-24 07:16 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/dto/v1/FestivalV1lListRequest.java
> +    }
1번에서 `lastStartDate`, `lastFestivalId`가 둘 다 있거나, 둘 다 없는 상황에서 검증이 필요한 이유는 커서 기반 페이징을 위해서 때문이라고 이해했습니다.
그렇다면 QueryDSL의 `where()` 메서드의 인자인 BooleanExpression 타입을 넣을때 분기를 타게 하면 되지 않을까요?
```java
private BooleanExpression dynamicWhere(Long lastFestivalId, Long lastStartDate) {
  if lastFestivalId != null && lastStartDate != null {
    return 조건문
  }
  return null; 
}
```

2024-01-24 07:50 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/dto/v1/FestivalV1lListRequest.java
> +    }
2번에서 Pageable 인터페이스를 사용하지 않는다면 각 API 마다 새로운 커스텀 Pageable 클래스가 생성되고, Pageable 관련 로직들 또한 중복으로 생길 것 같은데, 이럴거면 default 값을 설정할 수 있는 Pageable 인터페이스를 적용하는게 좋을 것 같습니다.
추가로 Pageable 인터페이스가 제공해줄 수 없는 size에 관한 검증 로직은 AOP를 사용해서 해결 할 수 있을 것 같네요!

2024-01-24 07:54 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/repository/FestivalPage.java
> +}
아마 그렇게 해야 추후 유지보수 할 때 편해지지 않을까요?

2024-01-24 07:55 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/repository/FestivalPageable.java
> +public class FestivalPageable {
https://github.com/woowacourse-teams/2023-festa-go/pull/667#discussion_r1464418893
해당 리뷰 참고하시면 될 것 같습니다!

2024-01-26 14:49 UTC, BGuga commented on backend/src/main/java/com/festago/festival/dto/v1/FestivalV1lListRequest.java
> +    }
> 1번에서 lastStartDate, lastFestivalId가 둘 다 있거나, 둘 다 없는 상황에서 검증이 필요한 이유는 커서 기반 페이징을 위해서 때문이라고 이해했습니다.
그렇다면 QueryDSL의 where() 메서드의 인자인 BooleanExpression 타입을 넣을때 분기를 타게 하면 되지 않을까요?

두 값 모두 넣지 않았을 경우 적절한 예외 메시지를 던지기 위해서는 예외를 발생시켜야하지 않을까요?

2024-01-26 14:49 UTC, BGuga commented on backend/src/main/java/com/festago/festival/dto/v1/FestivalV1lListRequest.java
> +    }
>2번에서 Pageable 인터페이스를 사용하지 않는다면 각 API 마다 새로운 커스텀 Pageable 클래스가 생성되고, Pageable 관련 로직들 또한 중복으로 생길 것 같은데, 이럴거면 default 값을 설정할 수 있는 Pageable 인터페이스를 적용하는게 좋을 것 같습니다.
추가로 Pageable 인터페이스가 제공해줄 수 없는 size에 관한 검증 로직은 AOP를 사용해서 해결 할 수 있을 것 같네요!

Pageable, Slice Let's go~

2024-01-26 15:22 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/dto/v1/FestivalV1lListRequest.java
> +    }
> > 1번에서 lastStartDate, lastFestivalId가 둘 다 있거나, 둘 다 없는 상황에서 검증이 필요한 이유는 커서 기반 페이징을 위해서 때문이라고 이해했습니다.
> > 그렇다면 QueryDSL의 where() 메서드의 인자인 BooleanExpression 타입을 넣을때 분기를 타게 하면 되지 않을까요?
> 
> 두 값 모두 넣지 않았을 경우 적절한 예외 메시지를 던지기 위해서는 예외를 발생시켜야하지 않을까요?

흠 하긴 페이징 할 때 필수적인 값이니까.. 클라이언트 측 실수로 키 값을 잘못 전달하거나 하는 상황에서 페이징이 되지 않는 문제가 생길 수 있겠네요.
예외를 던져도 좋을 것 같아요.
하지만 BadRequestException을 던지면 많은 ErrorCode가 생길 수 있어서, ValidException으로 사용하는게 어떨까요?

2024-01-26 15:28 UTC, BGuga commented
Page 기반으로 수정했습니다!!
현재 FestivalInfo의 데이터를 String 으로 deserialize 과정 없이 진행하니
<img width="1008" alt="image" src="https://github.com/woowacourse-teams/2023-festa-go/assets/103228463/e0000d22-96b5-4e58-bf51-6e9dd395c009">
이렇게 응답이 오는데 record라 값을 변경할 수도 없는데
다시 역직렬화해서 보내는 것은 어떤지 의견을 여쭙니다

2024-01-26 15:34 UTC, seokjin8678 commented
> Page 기반으로 수정했습니다!! 현재 FestivalInfo의 데이터를 String 으로 deserialize 과정 없이 진행하니 <img alt="image" width="1008" src="https://private-user-images.githubusercontent.com/103228463/300028512-e0000d22-96b5-4e58-bf51-6e9dd395c009.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyODMzOTMsIm5iZiI6MTcwNjI4MzA5MywicGF0aCI6Ii8xMDMyMjg0NjMvMzAwMDI4NTEyLWUwMDAwZDIyLTk2YjUtNGU1OC1iZjUxLTZlOWRkMzk1YzAwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQxNTMxMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYzk3NGM2YjE4ZDFiNGMxNWYzNDcyZTQzMDU0YTQyZjNjMTUwMDRhMjVjNTMwYWZlZTUyMDZhZGFhOTViNTEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N-9ul9_ffThfP8v3cWtl10qZW0-o2WgKV77zZMh-jfg"> 이렇게 응답이 오는데 record라 값을 변경할 수도 없네요 😢😢 다시 역직렬화해서 보내는 것은 어떤지 의견을 여쭙니다

`@JsonRawValue` 사용하면 좋을 것 같네요!
[참고 링크](https://github.com/cheese10yun/blog-sample/blob/master/jackson/README.md#jsonrawvalue-jackson)

2024-01-26 16:36 UTC, seokjin8678 requested changes
고생하셨습니다!
Controller, Service 로직만 약간 다듬으면 좋을 것 같아요!

2024-01-26 16:36 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/presentation/v1/FestivalV1Controller.java
> +    }
해당 예외 핸들러는 이제 없어도 될 것 같네요!

2024-01-26 16:36 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/presentation/v1/FestivalV1Controller.java
> +    }
```suggestion
    @GetMapping
    public ResponseEntity<Slice<FestivalV1Response>> findFestivals(
        @PageableDefault(size = 10) Pageable pageable,
        FestivalV1ListRequest request
    ) {
        return ResponseEntity.ok(festivalV1QueryService.findFestivals(pageable, request));
    }
```
다음과 같이 `Pageable`을 받는건 어떤가요?

```java
public class FestivalV1QueryService {
    ...
    public Slice<FestivalV1Response> findFestivals(Pageable pageable, FestivalV1ListRequest request) {
        return festivalRepository.findBy(
            new FestivalSearchCondition(
                request.filter(),
                request.region(),
                request.lastStartDate(),
                request.lastFestivalId(),
                pageable,
                LocalDate.now(clock)
            )
        );
    }
    ...
}
```
그렇게 된다면 DTO가 조금 덜 똑똑해질 것 같네요!

2024-01-26 16:36 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/dto/FestivalV1ListRequest.java
> +    private final LocalDate lastStartDate;
해당 DTO는 Pageable을 따로 받고, `@PageableDefault` 어노테이션을 사용하면 검증 로직 또한 전부 없앨 수 있을 것 같네요!
#675 해당 PR 까지 적용하면 최대 값 검증을 외부로 이동시킬 수 있을 것 같아요!
그리고 Enum 변환, LocalDate 파싱에서 예외가 발생하면 `MethodArgumentNotValidException` 예외가 발생해서 굳이 예외 처리를 여기서 해주지 않아도 될 것 같아요!

2024-01-26 16:37 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/dto/FestivalV1ListRequest.java
> +    private final LocalDate lastStartDate;
TO-BE
```java
public record FestivalV1ListRequest(
    FestivalFilter filter,
    SchoolRegion region,
    LocalDate lastStartDate,
    Long lastFestivalId
) {

}
```

2024-01-26 16:42 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/dto/FestivalV1ListRequest.java
> +    private final LocalDate lastStartDate;
그리고 정말 사소한거지만.. `FestivalV1QueryRequest`라는 네이밍은 어떤가요? 😂

2024-01-28 07:36 UTC, carsago approved these changes
푸우 고생하셨습니다.

개인적으론 filter case 따라 메소드를 나누고, 해당 메소드에서  where, orderBy를 동시에 볼 수 있으면 좋겠다. 라는 생각이 드는데 where 조건 때문에 너무 어렵네요..

이번 PR이 너무 커져서 제 의견은 TODO 느낌으로 해두는게 좋겠다는 생각에 approve했습니다.

다만 글렌이 언급해주신 NextPage가 있을 때 content가 +1 개 추가적으로 넘어가는 부분은 클라이언트에서  핸들링 해주지 않는다면 기능적으로 문제가 될 수 있어서 해당 부분만 수정되면 괜찮다고 생각합니다.

2024-01-28 07:36 UTC, carsago commented on backend/src/main/java/com/festago/festival/repository/FestivalV1QueryDslRepository.java
> +        return filterResult.and(school.region.eq(region));
이거 ```region == SchoolRegion.기타```는 어떤 경우죠???

2024-01-28 07:36 UTC, carsago commented on backend/src/main/java/com/festago/festival/repository/FestivalV1QueryDslRepository.java
> +    }
부분은 기능적으로 문제가 되니 이번 PR에선 처리해줘야 겠네용

2024-01-28 07:36 UTC, carsago commented on backend/src/main/java/com/festago/festival/application/FestivalV1QueryService.java
> +    }
이부분에서 LastStartDate와 LastFestivalId를 존재 여부 체크해서 null 넘기는 상황인데요.
그렇기 때문에 다시 한번 Repository에서 한번 더 존재여부를 바탕으로 분기문을 타야할 것입니다.(dynamicWhere 메소드)
그렇다면 그냥 Service에선 분기문 안타고 Optional로 넘기고 Repository에서만 분기문 타는거 어떤가요?

2024-01-28 14:14 UTC, BGuga commented on backend/src/main/java/com/festago/festival/presentation/v1/FestivalV1Controller.java
> +    }
이러면 request 명세가 바뀔 것 같아서 우선 현 상태를 유지하겠습니다!!

2024-01-28 14:22 UTC, BGuga commented on backend/src/main/java/com/festago/festival/dto/FestivalV1ListRequest.java
> +    private final LocalDate lastStartDate;
> 해당 DTO는 Pageable을 따로 받고, @PageableDefault 어노테이션을 사용하면 검증 로직 또한 전부 없앨 수 있을 것 같네요!
https://github.com/woowacourse-teams/2023-festa-go/pull/675 해당 PR 까지 적용하면 최대 값 검증을 외부로 이동시킬 수 있을 것 같아요!
그리고 Enum 변환, LocalDate 파싱에서 예외가 발생하면 MethodArgumentNotValidException 예외가 발생해서 굳이 예외 처리를 여기서 해주지 않아도 될 것 같아요!

지금 형태로 가면 예외가 BeanInstantiationException 이 발생합니다!!
그래서 이걸 처리하기 위한 코드를 만드니 BeanInstantiationException 을 처리하거나 getCause를 받아서 처리해줘야합니다..
너무 복잡하고 유지보수를 어렵게 만드는 부분이라 생각해 두 값이 동시에 존재해야한다는 제약 조건을 controller에서 담당하도록 변경하였습니다.

2024-01-28 15:03 UTC, BGuga commented on backend/src/main/java/com/festago/festival/repository/FestivalV1QueryDslRepository.java
> +        return filterResult.and(school.region.eq(region));
지역을 설정하지 않았을 경우를 방어한건데 끝도 없는 null 방어인 것 같아서 제거했습니다!

2024-01-28 15:04 UTC, BGuga commented on backend/src/main/java/com/festago/festival/repository/FestivalV1QueryDslRepository.java
> +        return filterResult.and(school.region.eq(region));
region 을 지정해주지 않는다면 기타 지역으로 들어오고 이 경우 지역 관련 필터링을 제외합니다!!

2024-01-28 15:54 UTC, seokjin8678 approved these changes
일부 수정할 사항이 몇 보여 리뷰 남겼습니다!
우선 머지하고 추후 새로운 이슈로 파서 작업하도록 하죠!!

2024-01-28 15:54 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/repository/FestivalV1QueryDslRepository.java
> +import static com.festago.festival.domain.QFestival.festival;
```suggestion
package com.festago.festival.repository;

import static com.festago.festival.domain.QFestival.festival;
```

2024-01-28 15:54 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/repository/FestivalV1QueryDslRepository.java
> +        }
`sublist()`도 좋지만, `remove()` 메서드로 마지막 인덱스를 제거하는것은 어떤가요?
```suggestion
        if (haveNextPageContent(content, page)) {
            return content.remove(content.size() - 1);
        }
```

2024-01-28 15:54 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/repository/FestivalRepositoryCustom.java
> +    Slice<FestivalV1Response> findBy(FestivalSearchCondition hello);
👋

2024-01-28 15:54 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/infrastructure/FestivalInfoSerializerImpl.java
> +            return objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(artists);
DB에 저장할 목적이면 예쁘게 보일 필요는 없을 것 같네요. 😁
`objectMapper.writeValueAsString(artists);`

2024-01-28 15:55 UTC, merged

2024-01-28 16:17 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/dto/FestivalV1ListRequest.java
> +    private final LocalDate lastStartDate;
`BeanInstantiationException`은 스프링 빈 관련 예외가 아닌가요??
혹시 어디서 해당 예외가 발생하셨나요??

2024-01-28 16:35 UTC, BGuga commented on backend/src/main/java/com/festago/festival/dto/FestivalV1ListRequest.java
> +    private final LocalDate lastStartDate;
request 생성할 때 생성자의 validate 부분에서 BadRequestException을 발생시키면 이게 BeanInstantiationException로 변환되어서 던져집니다

2024-01-28 16:35 UTC, BGuga commented on backend/src/main/java/com/festago/festival/domain/FestivalInfo.java
> +    private String artistInfo;
이걸 적용해보려 했는데 QueryProjection을 적용하는 것에서 실패했습니다 ㅠㅠ

2024-01-28 16:36 UTC, BGuga commented on backend/src/main/java/com/festago/festival/repository/FestivalRepositoryCustom.java
> +    Slice<FestivalV1Response> findBy(FestivalSearchCondition hello);
래픽터링하면서 intellij가 자동으로 바꿨나보네요 수정하겠습니다

2024-01-29 00:03 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/dto/FestivalV1ListRequest.java
> +    private final LocalDate lastStartDate;
직접 validate를 호출해줄 필요가 있겠군요..!