[AN/USER] feat: 안드로이드 메인 화면 하단을 구성한다.  (#668)
woowacourse-teams/2023-festa-go pull request #670
Opened 2024-01-23 10:10 UTC by re4rk

[Screen_recording_20240123_185028.webm](https://github.com/woowacourse-teams/2023-festa-go/assets/37167652/f68142b8-b693-45dc-a250-4dcd0961be4e)

## 📌 관련 이슈

- closed: #issueNum

## ✨ PR 세부 내용
### 1. 변화 내용
FestivalFragment의 메인 뷰를 RecyclerView로 대체하였습니다.

### 2. 기존 popularList를 RecyclerView의 멀티타입중 `FestivalListPopularViewHoler`하나로 분리
MotionLayout으로 스크롤이 되는 것처럼 보이게 만들 수 있지만 MultiType이 적용되어야 추후에 유지보수가 쉽다고 생각하여 진행했습니다.

### 3. DiffUtil 적용
멀티 타입의 DiffUtill은 처음 적용하는 것이라 설명이 필요한 것같아 첨부 합니다.
`FestivalListUiState`는 Popular가 들어가게 됩니다. 이는 리스트에서 싱글톤으로 유지 될 것이기 때문에 언제나 true로 바꿧습니다.
`FestivalTabUiState`도 마찬가지 입니다.
추가로 멀티 타입이기에 3개의 타입을 상속 받아야 하지만 `Any`타입으로 진행되게 하여서 코드를 간결화 시켜서 진행하였습니다.
Any타입으로 진행되어서 기반 타입이 없기 `equalTo()`가 존재하지 않기 때문에 때문에 `oldItem as FestivalListUiState`처럼 해줘야 비교 연산이 가능합니다. 스마트 캐스트도 작동하지 않습니다.
``` Kotlin
        private val diffUtil = object : DiffUtil.ItemCallback<Any>() {
            override fun areItemsTheSame(oldItem: Any, newItem: Any): Boolean = when {
                oldItem is FestivalListUiState && newItem is FestivalListUiState -> true
                oldItem is FestivalItemUiState && newItem is FestivalItemUiState -> oldItem.id == newItem.id
                oldItem is FestivalTabUiState && newItem is FestivalTabUiState -> true
                else -> false
            }

            override fun areContentsTheSame(oldItem: Any, newItem: Any): Boolean = when {
                oldItem is FestivalListUiState && newItem is FestivalListUiState
                -> oldItem as FestivalListUiState == newItem

                oldItem is FestivalItemUiState && newItem is FestivalItemUiState
                -> oldItem as FestivalItemUiState == newItem

                oldItem is FestivalTabUiState && newItem is FestivalTabUiState
                -> oldItem as FestivalTabUiState == newItem

                else -> false
            }
        }
```
### 4. 아티스트 데코레이션
아티스트간의 간격이 마진으로 `8dp` 씩 존재합니다.
Item의 xml 안에서 마진을 준다면 간단히 구현될 것으로 보이지만 이 마진은 RecyclerVIew에서 조작해야하는 영역으로 보고 `ArtistItemDecoration`을 만들어서 사용하였습니다. 

``` Kotlin
    private class ArtistItemDecoration(val context: Context) : ItemDecoration() {
        override fun getItemOffsets(
            outRect: Rect,
            view: View,
            parent: RecyclerView,
            state: RecyclerView.State,
        ) {
            super.getItemOffsets(outRect, view, parent, state)
            outRect.right = 8.dpToPx(context)
        }

        private fun Int.dpToPx(context: Context): Int {
            return TypedValue.applyDimension(
                TypedValue.COMPLEX_UNIT_DIP,
                this.toFloat(),
                context.resources.displayMetrics,
            ).toInt()
        }
    }

```

### 5. 탭기능 TODO
현재  주어진 API가 없기 때문에 연동하지 않은 상태로 이슈 등록 후 나중에 진행해야 할 것같습니다.

### In App

<img src="https://github.com/woowacourse-teams/2023-festa-go/assets/37167652/688753c5-262e-4a92-8007-d0edde575591" width="108" height="268">
<img src="https://github.com/woowacourse-teams/2023-festa-go/assets/37167652/23e4565c-34f9-4069-a8f4-e003dffc0f58" width="108" height="268">

### Design

<img src="https://github.com/woowacourse-teams/2023-festa-go/assets/37167652/3fe8bc83-564c-4df5-bfb2-13077f45e597" width="108" height="337">

2024-01-24 06:37 UTC, SeongHoonC requested changes
미리 전달드린 context 관련 리뷰를 반영해주셔서 특별히 코멘트 남길 내용은 없습니다.
다만 다음 작업에 대해 의문이 조금 있습니다.

1. 축제 리스트 리사이클러뷰 밑에 여백이 없어서 16dp 정도 띄우는게 어떨까요? figma 확인해보니 따로 그려져있진 않은데 현재 바텀네비에 붙어있어서 제안드려봅니다.

2. TabLayout 실행 람다는 API 배포 이후에 작업하실 예정인가요?
   만약 그렇다면 이 PR 을 close 하지 않고 작업을 이어나갈 것인지 궁금합니다.

3. 무한스크롤 구현 작업도 이 PR 에서 하실건지 이슈를 새로 만들 것인지 궁금합니다.

2024-01-24 06:37 UTC, SeongHoonC commented on android/festago/presentation/src/main/res/layout/item_festival_list_festival.xml
> +            tools:text="2021.10.10 ~ 2021.10.12" />
tools 랑 디자인 포멧이 다르네요!

2024-01-24 11:28 UTC, EmilyCh0 approved these changes
고생하셨습니다!! 👍

2024-01-24 14:26 UTC, re4rk commented on android/festago/presentation/src/main/res/layout/item_festival_list_festival.xml
> +            tools:text="2021.10.10 ~ 2021.10.12" />
코멘트 답변을 여기다 작성합니다!
1. 데코레이터를 사용하여 반영하였습니다!
2. API 작업이 끝난 후 따로 작업하는 것으로 예상했습니다!
3. 무한 스크롤 또한 작업을 미리 할 순 있지만 따로 이슈를파는 것이 맞다고 생각합니다!

2024-01-24 14:27 UTC, re4rk commented
PR 마지막에 기간마다 디자인이 다른 것 반영하였습니다!
<img src="https://github.com/woowacourse-teams/2023-festa-go/assets/37167652/09e173eb-c177-44a4-a711-a7f6c6a1d36a" width="108" height="268">

2024-01-25 01:47 UTC, SeongHoonC approved these changes
변경사항 확인했습니다! 고생많으셨습니다ㅎㅎ

2024-01-25 01:47 UTC, SeongHoonC commented on android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/festivallist/FestivalListFragment.kt
> +        })
이 부분은 util 로 빼는걸 고려해봐야겠네요

2024-01-25 01:47 UTC, merged