[AN/USER] feat: 아티스트 상세 페이지 구현 (#699)
woowacourse-teams/2023-festa-go pull request #713
Opened 2024-02-12 11:25 UTC by re4rk

## 📌 관련 이슈

- closed: #699 

## ✨ PR 세부 내용

이번 PR은 내용이 좀 많습니다.

1. 축제 뷰홀더 남은 날짜 계산식 변경
- before: item.startDate.compareTo(LocalDate.now()).toString()
- after :  (LocalDate.now().toEpochDay() - item.startDate.toEpochDay()).toString() 
- 남은 길이가 한달이상 차이나면 day가 아닌 month 차이만큼 반환

2. Home Activity에서 StatusBar까지 화면을 사용하도록 변경 
- 해당 기능 구현하는데 설명이 복잡해서 블로그쓰고 대신 공유합니다.
[BottomNavigationView](https://velog.io/@4rk/BottomNavigationView)
[WindowInsets](https://velog.io/@4rk/WindowInsets-%EB%8F%99%EC%9E%91-%EA%B5%AC%EC%A1%B0)
- ViewUtils 파일 추가 `setOnApplyWindowInsetsCompatListener` 함수
``` kotlin
        binding.root.setOnApplyWindowInsetsCompatListener { view, windowInsets ->
            val navigationInsets = windowInsets.getInsets(WindowInsetsCompat.Type.navigationBars())
            view.setPadding(0, 0, 0, navigationInsets.bottom)
            window.navigationBarColor = Color.TRANSPARENT
            window.statusBarColor = Color.TRANSPARENT
            windowInsets
        }

        binding.nvHome.setOnApplyWindowInsetsCompatListener { _, windowInsets ->
            windowInsets
        }
```

3. ActivityUtil 추가
- Activity.setStatusBarMode 함수로 해당 화면의 StatusBar 색상을 변경할 수 있도록 추가하였습니다.

4. HomeActivity에서 Fragment에따라 StatusBar 색상을 변경합니다.
- Fragment에게 책임을 넘기게 되니 사이드 이펙트가 너무 많이 발생합니다.
- 예시로 중복되는 프래그먼트가 쌓인 경우와 구성변경이 일어날 시 색상에 오류가 발생하여 Activity로 책임을 이동하였습니다.

5. 아티스트 도메인 모델을 추가하였습니다.
- 추가로 데이터 모듈에서 `FakeArtistRepository`를 만들었습니다.

6. 디자인 적용
- 아직까지는 세부 디자인들이 변동이 있을 것으로 예상되는데 먼저 리뷰를 진행한 후에 디자이너분들에게 컨펌받고 머지를 진행하겠습니다.

<img width="176" alt="스크린샷 2024-02-12 오후 7 55 18" src="https://github.com/woowacourse-teams/2023-festa-go/assets/37167652/c61c1d7a-4bb6-45a1-a5ba-f00695ab9647">
<img width="178" alt="스크린샷 2024-02-12 오후 7 56 42" src="https://github.com/woowacourse-teams/2023-festa-go/assets/37167652/b2e47acb-cb80-43b7-9924-c04edaecdeba">
<img width="178" alt="스크린샷 2024-02-12 오후 7 55 43" src="https://github.com/woowacourse-teams/2023-festa-go/assets/37167652/bd07cdec-e4ea-4328-bb90-2cc7b5a98006">
<img width="176" alt="스크린샷 2024-02-12 오후 7 56 10" src="https://github.com/woowacourse-teams/2023-festa-go/assets/37167652/2d27c902-9a01-406e-828b-a29b6883ceed">

2024-02-13 10:14 UTC, SeongHoonC requested changes
아티스트 상세 구현과 상태바 조작까지 작업량이 많았을텐데 고생하셨습니다!
프래그먼트 관리는 네비게이션 도입 후 변경될 것 같아서 따로 남기지 않았습니다.
코멘트 확인해주세요!

2024-02-13 10:14 UTC, SeongHoonC commented on android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/adapter/festival/ArtistDetailFestivalViewHolder.kt
> +                println(item.startDate.compareTo(LocalDate.now()).toString())
print 문은 제거해주세요!

2024-02-13 10:42 UTC, SeongHoonC commented on android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/adapter/festival/ArtistDetailFestivalViewHolder.kt
> +                dDayView.setTextColor(context.getColor(R.color.secondary_pink_01))
다른 부분에 setText 를 안하면 item 재할당시 text 가 핑크색 그대로입니다

```kotlin
dDayView.setTextColor(context.getColor(R.color.background_gray_01))
```

다른 분기문에서 text 를 하얀색으로 지정해야할 것 같아요!

2024-02-17 18:21 UTC, re4rk commented on android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/adapter/festival/ArtistDetailFestivalViewHolder.kt
> +                dDayView.setTextColor(context.getColor(R.color.secondary_pink_01))
모든 분기마다 처리하도록 하였습니다!

2024-02-17 18:22 UTC, re4rk commented on android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/ArtistDetailFragment.kt
> +                                startActivity(intent)
`startBrowser()`로 따로 내부 함수로 빼고 암시적으로 브라우저로 열도록 변경하였습니다!

2024-02-17 18:22 UTC, re4rk commented on android/festago/domain/src/main/java/com/festago/festago/domain/model/artist/Stage.kt
> +)
회의 후에 긴가민가해서 노션 보고 반영 했었는데 업데이트가 안 된 것같네요 ㅠㅠ 반영했습니다!

2024-02-17 18:23 UTC, re4rk commented on android/festago/.editorconfig
> +ktlint_standard_multiline-expression-wrapping = disabled
ktlint와 plugin과 프로젝트 ktlint의 동기화를 위해 추가하였습니다! 원래대로라면 따로 이슈를 파고 진행해야하지만 그래들 빌드가 통과가 안돼 커밋이 안돼서 추가하였습니다!

2024-02-19 08:25 UTC, SeongHoonC approved these changes
리뷰반영 확인했습니다!

2024-02-19 13:01 UTC, EmilyCh0 approved these changes
고생하셨습니다~ 👍

2024-02-20 05:08 UTC, re4rk commented on android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/adapter/festival/ArtistDetailAdapter.kt
> +    }
의견에 동의해서 제거하였습니다!

2024-02-20 05:22 UTC, merged