[BE] feat: 아티스트 상세 조회 API 추가 (#707)
woowacourse-teams/2023-festa-go pull request #716
Opened 2024-02-16 17:42 UTC by BGuga

## 📌 관련 이슈

- closed: #707 

## ✨ PR 세부 내용

아티스트 정보, 아티스트 축제 정보 반환 API 를 구현하였습니다.
구현 때 아티스트에서 축제까지 도달하는 것은 어려움이 없었습니다.

Festival <- Stgae <- StageArtist <- Artist

다한 축제를 특정했을 때 해당 축제에 참여하고 있는 Artist 정보들을 가져오기 위한 과정이 복잡할 뻔했으나
이 정보는 역정규화를 FestivalInfo를 통해 준비되어 있어 해당 데이터를 재활용했습니다.

2024-02-18 06:47 UTC, seokjin8678 requested changes
고생하셨습니다 푸우!
리뷰 남겼으니 확인해주세요!

2024-02-18 06:47 UTC, seokjin8678 commented on backend/src/main/java/com/festago/artist/application/ArtistDetailV1QueryDslRepository.java
> +            .on(socialMedia.ownerId.eq(artist.id).and(socialMedia.ownerType.eq(OwnerType.ARTIST)))
`on` 메서드는 `join`과 연관이 있으니, 한 줄로 표시해주는 게 좋을 것 같아요!

2024-02-18 06:47 UTC, seokjin8678 commented on backend/src/main/java/com/festago/artist/application/ArtistDetailV1QueryDslRepository.java
> +public class ArtistDetailV1QueryDslRepository extends QueryDslRepositorySupport {
조회 전용으로 사용하는 `QueryDslRepository`는 일부 패턴들이 보이네요.
내부에 사용되는 변수명, 메서드명 등에 대해 컨벤션을 맞춰야 할 것 같습니다!

2024-02-18 06:47 UTC, seokjin8678 commented on backend/src/main/java/com/festago/artist/application/ArtistDetailV1QueryDslRepository.java
> +    private static final int NEXT_PAGE_DATA_TEMP_COUNT = 1;
해당 상수명도 컨벤션을 맞추면 좋겠네요!

2024-02-18 06:47 UTC, seokjin8678 commented on backend/src/main/java/com/festago/artist/application/ArtistDetailV1QueryService.java
> +    }
```suggestion
    public Slice<ArtistFestivalDetailV1Response> findArtistFestivals(
        Long artistId,
        ArtistFestivalDetailV1Request request,
        Pageable pageable
    ) {
        return artistDetailV1QueryDslRepository.findArtistFestivals(
            new ArtistFestivalSearchCondition(
                artistId,
                isPastOrDefault(request),
                request.getLastFestivalId(),
                request.getLastStartDate(),
                pageable,
                LocalDate.now(clock)
            )
        );
    }
```
줄바꿈을 다음과 같이 사용하는건 어떤가요?

2024-02-18 06:47 UTC, seokjin8678 commented on backend/src/main/java/com/festago/artist/application/ArtistDetailV1QueryService.java
> +    }
`ArtistFestivalDetailV1Request`의 `isPast` 변수가 primitive 타입이라면 해당 메서드는 필요 없지 않을까요?

2024-02-18 06:47 UTC, seokjin8678 commented on backend/src/main/java/com/festago/artist/presentation/v1/ArtistDetailV1Controller.java
> +    }
예전 회의에서 `@RequestParam`을 사용하는 방식을 택하기로 했습니다!

2024-02-18 06:47 UTC, seokjin8678 commented on backend/src/main/java/com/festago/artist/presentation/v1/ArtistDetailV1Controller.java
> +    @Operation(description = "아티스트가 참석한 축제를 조회한다. isPast 값으로 종료 축제 와 진행, 예정 축제를 구분 가능하", summary = "아티스트 축제 조회")
가능한

2024-02-18 06:47 UTC, seokjin8678 commented on backend/src/main/java/com/festago/artist/presentation/v1/ArtistFestivalDetailV1Request.java
> +}
`@RequestParam`을 사용하면 사라질 클래스지만, 푸우의 의도가 궁금해서 리뷰 남깁니다.
1. `record` 타입을 사용하지 않은 이유가 있을까요? 
2. `isPast`를 reference 타입으로 사용한 이유가 궁금해요!

2024-02-18 06:47 UTC, seokjin8678 commented on backend/src/test/java/com/festago/admin/presentation/v1/AdminArtistV1ControllerTest.java
이슈의 기능에 영향이 없고, 단지 스타일만 변경한다면 새로운 이슈로 만들어 처리하는게 좋을 것 같아요!

2024-02-18 06:47 UTC, seokjin8678 commented on backend/src/test/java/com/festago/artist/application/ArtistDetailV1QueryServiceTest.java
> +            School school3 = schoolRepository.save(new School("domain3", "대구 학교", SchoolRegion.대구));
약간 억까 같지만.. 😂
변수명을 `school1`,`school2` 보다는 명확하게 `서울대학교`, `대구대학교`와 같이 명확한 도메인 언어로 표현하는게 어떨까요?
`Artist` 또한 마찬가지로, 실제 가수의 이름을 표현하는게 좋을 것 같네요!

2024-02-18 06:47 UTC, seokjin8678 commented on backend/src/main/java/com/festago/artist/application/ArtistDetailV1QueryDslRepository.java
> +    }
푸우는 `makeXxx` 라는 네이밍을 주로 사용하시더군요!
저는 `createXxx` 라는 네이밍을 주로 사용하는 편 입니다!
이 부분도 또한 컨벤션을 정했으면 좋겠네요!

2024-02-19 05:54 UTC, BGuga commented on backend/src/main/java/com/festago/artist/application/ArtistDetailV1QueryDslRepository.java
> +    private static final int NEXT_PAGE_DATA_TEMP_COUNT = 1;
의미만 전달되면 이런것 까지 맞출 필요는 없지 않을까요?

2024-02-19 06:01 UTC, BGuga commented on backend/src/main/java/com/festago/artist/application/ArtistDetailV1QueryService.java
> +    }
고민인게
지금 다른 코드들에서는 Service가 아닌 Controller에서 기본값을 설정해 주고 있는데
이런 기본값 설정도 비즈니스 로직이라 본다면 Service에서 하는 것이 맞지 않냐는 생각이 드는데 의견이 궁금합니다!!

2024-02-19 06:36 UTC, BGuga commented on backend/src/main/java/com/festago/artist/presentation/v1/ArtistFestivalDetailV1Request.java
> +}
Service에서 nullable한 값을 처리하는 방향으로 생각했어서
get~를 Optional을 사용하려 했습니다
근데 Optional을 쓰니 모든 레이어에 isPresent -> get 이게 너무 반복되서 그냥 빼버렸는데 그 잔해로 남아버렸네요 ㅠㅠ
커밋을 중간중간에 하지 않으니 이런 잔해가 자주 남는 것 같네요 좀 더 신경쓰겠습니다

2024-02-19 06:36 UTC, BGuga commented on backend/src/test/java/com/festago/artist/application/ArtistDetailV1QueryServiceTest.java
> +            School school3 = schoolRepository.save(new School("domain3", "대구 학교", SchoolRegion.대구));
억까다!!

2024-02-19 06:37 UTC, BGuga commented on backend/src/test/java/com/festago/artist/application/ArtistDetailV1QueryServiceTest.java
> +            School school3 = schoolRepository.save(new School("domain3", "대구 학교", SchoolRegion.대구));
반영 완.

2024-02-19 06:37 UTC, BGuga commented on backend/src/main/java/com/festago/artist/application/ArtistDetailV1QueryDslRepository.java
> +    }
make가 어감이 좋지 않나요

2024-02-19 06:45 UTC, BGuga commented on backend/src/main/java/com/festago/artist/presentation/v1/ArtistDetailV1Controller.java
> +    }
이거 그때 Service용 dto 까지 만들기로 했었나요?

2024-02-19 11:45 UTC, seokjin8678 commented on backend/src/main/java/com/festago/artist/application/ArtistDetailV1QueryService.java
> +    }
primitive 타입은 null 할당이 불가하므로, null 값이 false가 될텐데 애초부터 controller에서 primitive 타입으로 받으면 해당 메서드가 필요 없지 않을까에 대한 내용이었습니다. 😅

2024-02-19 11:46 UTC, seokjin8678 commented on backend/src/main/java/com/festago/artist/presentation/v1/ArtistDetailV1Controller.java
> +    }
Service로 넘겨줄 때는 Request를 사용해야할 것 같네요. (Clock을 사용한 현재 시간을 넘겨주려면)

2024-02-19 15:53 UTC, BGuga commented on backend/src/main/java/com/festago/artist/application/ArtistDetailV1QueryService.java
> +    }
primitive 타입을 받기 위해서는 값을 controller에서 결정해야하는데 이 결정을 Service에서 하면 어떨까 생각했어요!!
Filter같이 primitive 한 값을 지정 못하는 경우도 있기 때문이죠

2024-02-20 05:20 UTC, carsago commented on backend/src/main/java/com/festago/artist/presentation/v1/ArtistDetailV1Controller.java
> +        @RequestParam(required = false) Boolean isPast,
```suggestion
        @RequestParam(required = false) Long lastFestivalId,
        @RequestParam(required = false) LocalDate lastStartDate,
        @RequestParam(required = false, defaultValue = "false") Boolean isPast,
```

이런 로직이 필요할 것 같습니다!

2024-02-20 05:20 UTC, carsago commented on backend/src/test/java/com/festago/artist/application/ArtistDetailV1QueryServiceTest.java
> +        }
푸우의 이유가 있을 수 있지만, 제 의견으론 해당 메소드에서 Repository로 save하는 부분까지 들어가있다면 given절을 읽는 것이 더 수월하지 않을까 싶어요.

2024-02-20 08:54 UTC, seokjin8678 approved these changes
리뷰 반영 확인했습니다!
고생하셨어요!

2024-02-20 10:16 UTC, merged