[BE] feat: 학교 상세 조회 및 학교 별 축제 조회 API 추가 (#707)
woowacourse-teams/2023-festa-go pull request #717
Opened 2024-02-19 03:38 UTC by carsago

## 📌 관련 이슈

- closed: #707 

## ✨ PR 세부 내용

기존에 존재하던 SchoolV1QueryService가 존재했는데, 이건 Admin에서 사용되는거라 admin으로 명칭 및 URL을 변경하였어요.

디테일한 부분은 제가 코멘트를 첨부하겠습니다.

2024-02-19 03:53 UTC, carsago commented on backend/src/main/java/com/festago/school/application/v1/AdminSchoolV1QueryService.java
> +    private final AdminSchoolV1QueryDslRepository schoolQueryDslRepository;
어드민 명칭을 변경하였어요. 
전 admin 패키지로 가능것도 맞다고 생각하는데 너무 제 혼자 주관으로 하는 것 같아 변경하진 않았습니다.

2024-02-19 03:53 UTC, carsago commented on backend/src/main/java/com/festago/school/dto/v1/SliceResponse.java
> +}
일단은 API 명세서랑 맞출려고 이걸 만들어서 넘겼습니다.
다른 페이징 객체를 넘기면 필요없는 필드들도 넘어가다보니..
다만 커스텀 객체를 넘겨주는건 신경쓰이네요.

2024-02-19 03:53 UTC, carsago commented on backend/src/main/java/com/festago/school/presentation/v1/SchoolV1Controller.java
> +        var searchCondition = new SchoolFestivalV1SearchCondition(lastFestivalId, lastStartDate, isPast, size);
clock을 service에서 만들어서 넘기기보단 Service에 대한 테스트를 하는 경우가 많아서 
컨트롤러에서 만들어서 파라미터로 넘겨주었습니다.

컨트롤러 혹은 API에 대한 E2E 테스트가 된다면 컨트롤러에서 clock으로 생성해주면 해결 될 것 같습니다.
현재 시간 생성에 대한 코드를 최대한 바깥으로 밀어내는게 조금이나마 더 테스트하기 쉽다고 느껴져요.
이러면 Service 테스트에서는 mocking이 필요없으니까요.

2024-02-19 03:53 UTC, carsago commented on backend/src/main/java/com/festago/school/repository/v1/SchoolV1QueryDslRepository.java
> +                                                                           SchoolFestivalV1SearchCondition searchCondition) {
진짜 이 로직은 고민 많이해봤는데, 깔끔하게 풀기가 어렵더군요 T_T

2024-02-19 03:53 UTC, carsago commented on backend/src/test/java/com/festago/acceptance/steps/SchoolStepDefinitions.java
> +            .cookie("token", cucumberClient.getToken())
기존 학교 조회를 admin으로 옮기면서 테스트에 인증 설정이 필요했어요.

2024-02-19 18:21 UTC, seokjin8678 requested changes
고생하셨습니다 오리!
리뷰 남겼으니 확인해주세요!

2024-02-19 18:21 UTC, seokjin8678 commented on backend/src/main/java/com/festago/school/dto/v1/SliceResponse.java
> +}
`SchoolV1Controller`에서 `Pageable` 객체를 인자로 받은 뒤, 해당 객체를 사용해서 페이징 처리를 한 뒤 넘겨준다면 해당 객체는 필요 없을 것 같네요!
아마 Silce 객체를 반환하면 불필요한 필드가 추가로 넘어간다는 것이 문제가 되는건지 프론트와 얘기가 필요할 수 있겠네요! (불필요한 필드가 넘어가도 JSON으로 직렬화를 거칠 때 무시되는 것으로 알고 있어요)

2024-02-19 18:21 UTC, seokjin8678 commented on backend/src/main/java/com/festago/school/presentation/v1/SchoolV1Controller.java
> +        @RequestParam(defaultValue = "10") Integer size
`size` 파라미터는 `Pageable`로 받으면 될 것 같네요!
`isPast` 파라미터를 reference 타입으로 받은 이유가 있나요?

2024-02-19 18:21 UTC, seokjin8678 commented on backend/src/main/java/com/festago/school/presentation/v1/SchoolV1Controller.java
> +        var searchCondition = new SchoolFestivalV1SearchCondition(lastFestivalId, lastStartDate, isPast, size);
CQRS 패턴을 적용했으니, Query 관련된 쪽은 컨트롤러에 비즈니스 로직을 추가해도 괜찮을 것 같습니다!

2024-02-19 18:21 UTC, seokjin8678 commented on backend/src/main/java/com/festago/school/application/v1/AdminSchoolV1QueryService.java
> +    private final AdminSchoolV1QueryDslRepository schoolQueryDslRepository;
구현하려는 SchoolQueryController랑 이름이 겹쳐서 어쩔 수 없겠네요. 😂

2024-02-19 18:21 UTC, seokjin8678 commented on backend/src/test/java/com/festago/admin/presentation/v1/AdminSchoolV1ControllerTest.java
> +            }
혹시 CodeStyle 한 번 확인해 주실 수 있나요? 들여쓰기가 2개 들어간 것 같네요!

2024-02-19 18:21 UTC, seokjin8678 commented on backend/src/main/java/com/festago/school/repository/v1/SchoolV1QueryDslRepository.java
> +    }
줄바꿈을 다음과 같이 해주는게 어떨까요? 파리미터랑 지역 변수랑 겹쳐서 가독성이 낮아 보이네요!
```suggestion
    private SliceResponse<SchoolFestivalV1Response> createResponse(
        Integer pageSize,
        List<SchoolFestivalV1Response> content
    ) {
        boolean isLast = true;
        if (content.size() == pageSize + NEXT_PAGE_CHECK_NUMBER) {
            content.remove(content.size() - NEXT_PAGE_CHECK_NUMBER);
            isLast = false;
        }

        return new SliceResponse(isLast, content);
    }
```

2024-02-19 18:21 UTC, seokjin8678 commented on backend/src/main/java/com/festago/school/repository/v1/SchoolV1QueryDslRepository.java
> +                                                                           SchoolFestivalV1SearchCondition searchCondition) {
쿼리는 어쩔 수 없다고 생각합니다. 😂

2024-02-19 18:21 UTC, seokjin8678 commented on backend/src/test/java/com/festago/school/presentation/v1/SchoolV1ControllerTest.java
> +public class SchoolV1ControllerTest {
테스트 코드기 때문에 public을 추가할 필요는 없어 보이네요!

2024-02-19 18:54 UTC, seokjin8678 commented on backend/src/main/java/com/festago/school/repository/v1/SchoolV1QueryDslRepository.java
> +                                                                           SchoolFestivalV1SearchCondition searchCondition) {
그리고 아마 해당 조회 기능이 끝나지 않은 축제를 마지막 까지 보여주다, 마지막 축제가 되면 이제 클라이언트에서 종료된 축제를 조회하도록 얘기를 했던 것 같네요!
하나의 조회 로직에서 isPast로 분기를 타지 않고, 그냥 service 레이어에서 분기를 탄 뒤 별도로 작성된 끝나지 않은 축제와 끝난 축제 로직을 조회하는건 어떤가요?

2024-02-19 18:55 UTC, seokjin8678 commented on backend/src/main/java/com/festago/school/repository/v1/SchoolV1QueryDslRepository.java
> +    }
단 하나의 OrderSpecifier를 사용할거면 배열을 사용할 필요는 없어 보이네요!
```suggestion
    private OrderSpecifier<LocalDate> addOrderOption(boolean isPast) {
        if (isPast) {
            return festival.endDate.desc()
        }

        return festival.startDate.asc();
    }
```

2024-02-19 18:59 UTC, seokjin8678 commented on backend/src/main/java/com/festago/school/repository/v1/SchoolV1QueryDslRepository.java
> +        }
`isLast`가 false인지 확인할 때 로직은 다음과 같이 변경할 수 있을 것 같네요!
```suggestion
        if (content.size() > pageSize) {
            content.remove(content.size() - 1);
            isLast = false;
        }
```
여기서 `content.remove(content.size() - NEXT_PAGE_CHECK_NUMBER);` 라인의 `NEXT_PAGE_CHECK_NUMBER` 상수 사용은 맞지 않은 것 같네요! (remove() 메서드는 인덱스를 지우므로)

2024-02-19 19:05 UTC, seokjin8678 commented on backend/src/main/java/com/festago/school/repository/v1/SchoolV1QueryDslRepository.java
푸우 리뷰에도 남겼지만..
페이징 처리를 위한 Repository 클래스를 구현하는데 있어서 각자의 스타일이 있다보니 같은 결과를 내는 클래스임에도 내부 변수나 메서드 명이 전부 통일이 되지 않고 있더라구요!
새로운 기능이 생기며 페이징 처리할 Repository 클래스들이 더 많아질텐데 이대로 가다간 통제가 되지 않을 것 같네요!
따라서 해당 페이징 처리를 위한 Repository 클래스에 컨벤션이 필요할 것 같습니다!

2024-02-20 02:38 UTC, BGuga approved these changes
수고하셨습니다 오리 !!

2024-02-20 02:38 UTC, BGuga commented on backend/src/main/java/com/festago/school/repository/v1/SchoolV1QueryDslRepository.java
> +                                                                           SchoolFestivalV1SearchCondition searchCondition) {
글렌이 말씀 주신 것 처럼하면 order, where 부분에서 더 가독성이 좋아지겠네요

2024-02-20 02:38 UTC, BGuga commented on backend/src/main/java/com/festago/school/repository/v1/SchoolV1QueryDslRepository.java
> +                .leftJoin(festivalQueryInfo).on(festivalQueryInfo.festivalId.eq(festival.id))
저도 이거 헷갈려서 찾아봤었어요 😂
```
FROM : 각 테이블 확인
ON : 조인 조건 확인
JOIN : 테이블 조인 (병합)
WHERE : 데이터 추출 조건 확인
GROUP BY : 특정 칼럼으로 데이터 그룹화
HAVING : 그룹화 이후 데이터 추출 조건 확인
SELECT : 데이터 추출
DISTINCT : 중복 제거
ORDER BY : 데이터 정렬
```
요 순서로 실행된다고 하네요

2024-02-20 06:04 UTC, carsago commented on backend/src/main/java/com/festago/school/repository/v1/SchoolV1QueryDslRepository.java
> +                                                                           SchoolFestivalV1SearchCondition searchCondition) {
```하나의 조회 로직에서 isPast로 분기를 타지 않고, 그냥 service 레이어에서 분기를 탄 뒤 별도로 작성된 끝나지 않은 축제와 끝난 축제 로직을 조회하는건 어떤가요?```

라는 부분을 글렌이 언급하셨는데요. 이 부분에 대해서 저도 최대한 메소드 추출되는 것을 없애고 쿼리가 하나의 메소드에서 쭉 볼 수 있는게 더 가독성이 좋다고 생각합니다. 그래서 Service에서 분기를 타서 다른 메소드를 호출하는 것을 고민해봤는데요.

다만 이를 구현해보면서 단점이 있었던 것은

해당 쿼리가 
select 
from 
join 
where school.id = ?
까지 동일하고

달라지는 부분은 2가지 where 조건 (페이징과 endDate보다 크냐 작냐)과 orderBy입니다.

그리고 이후 로직에
limit
fetch
및 Response를 만들어주는 과정이 동일 합니다.

즉 쿼리의 앞부분, 뒷부분이 동일하고 중간부분만 다르기때문에 메소드를 분리한다면 어느정도 중복코드가 나타나는 걸 막기 어렵다고 느꼈습니다.

코드 중복 자체는 디자인 패턴등으로 해결이 가능할텐데, 중복을 제거하기 위해 하다보면 가독성을 위한 분리였는데 가독성이 오히려 안좋아지는 느낌?.. 참 애매하더라고요.

2024-02-20 07:27 UTC, BGuga commented on backend/src/main/java/com/festago/school/application/v1/AdminSchoolV1QueryService.java
> +    private final AdminSchoolV1QueryDslRepository schoolQueryDslRepository;
어드민이 사용하는 서비스는 구분이 돼야할 것 같은데 이건 하나의 이슈로 처리하는 것이 좋아보이네요!!

2024-02-20 07:27 UTC, BGuga commented on backend/src/main/java/com/festago/school/dto/v1/SliceResponse.java
> +}
저도 알면서 넘어간 부분인데 오늘 회의에서 짚고 넘어가면 좋을 것 같아요!!

2024-02-20 07:27 UTC, BGuga commented on backend/src/main/java/com/festago/school/repository/v1/SchoolV1QueryDslRepository.java
> +        }
아하 그렇네요 만약에 2로 변경되면 하나만 삭제되겠네요

2024-02-20 08:39 UTC, carsago reviewed
리뷰 바탕으로 코드를 좀 맞췄습니다. 푸우랑 오늘 회의전에 따로 중복코드나 컨벤션에 관한 부분을 이야기해서 맞추어 볼게요.

2024-02-20 08:39 UTC, carsago commented on backend/src/main/java/com/festago/school/presentation/v1/SchoolV1Controller.java
> +        @RequestParam(defaultValue = "10") Integer size
지금은 false가 default라 원시값으로 해도 상관없지만, 그래도 원시값의 기본값이 박히는것보단 null이 박힐 수 있지만 이런식으로 명확하게 해주는게 좋다고 여겼어요.

2024-02-20 08:45 UTC, seokjin8678 commented on backend/src/main/java/com/festago/school/repository/v1/SchoolV1QueryDslRepository.java
> +                                                                           SchoolFestivalV1SearchCondition searchCondition) {
쿼리에 관련된 로직은 이렇게 가독성이 낮고, 복잡한게 당연한듯 합니다. ㅋㅋㅋ
그래서 CQRS 패턴이 등장했고, 저희도 적용했구요.
날아가는 SQL 분석 및 최적화만 해도 좋을 것 같네요.

2024-02-20 08:52 UTC, seokjin8678 approved these changes
리뷰 반영 확인했습니다!
고생하셨어요!

2024-02-20 10:15 UTC, merged