[BE] feat: 관리자 축제 조회 기능 추가 (#745)
woowacourse-teams/2023-festa-go pull request #749
Opened 2024-02-23 08:11 UTC by seokjin8678

## 📌 관련 이슈

- closed: #745

## ✨ PR 세부 내용

관리자 페이지에서 축제 조회를 위한 기능을 추가했습니다. (API는 아직 미완성)

#695 PR에서 `AdminFestivalV1Controller` API를 먼저 구현하고 있기 때문에 해당 PR이 머지되면 API를 추가해야 할 것 같습니다.

중요하게 봐야할 사항은 `AdminFestivalV1QueryDslRepository`가 의존하고 있는 `QueryDslHelper` 클래스인데, 해당 클래스는 기존 상속으로 사용하던 `QueryDslRepositorySupport` 추상 클래스의 Bean 버전입니다.

왜 기존에 잘 만들어둔 `QueryDslRepositorySupport`을 상속하지 않고 `QueryDslHelper`를 의존해서 사용했냐면, 여러 이유가 있는데 그 중 가장 큰 이유는 정렬을 할 때 발생하는 문제 때문입니다.

`applyPagination` 메서드를 사용하면 `orderBy`를 해주지 않아도 정렬이 되는데 이유는 `querydsl.applyPagination()` 메서드를 호출할 때 Pageable 객체만 넘기면 정렬이 자동으로 되기 때문입니다.

자동으로 정렬이 되게 하는 마법같은 일은 `QueryDslRepositorySupport`의 생성자로 받는 도메인 클래스를 분석해서 해당 도메인 클래스가 가진 필드를 기준으로 프로퍼티를 설정함으로 이뤄집니다.

```java
protected QueryDslRepositorySupport(Class<?> domainClass) {
        this.domainClass = domainClass;
    }

@Autowired
protected void setQueryFactory(EntityManager entityManager) {
    Assert.notNull(entityManager, "EntityManager must not be null!");
    JpaEntityInformation<?, ?> entityInformation =
        JpaEntityInformationSupport.getEntityInformation(domainClass, entityManager);
    SimpleEntityPathResolver resolver = SimpleEntityPathResolver.INSTANCE;
    EntityPath<?> path = resolver.createPath(entityInformation.getJavaType());
    this.querydsl = new Querydsl(entityManager, new PathBuilder<>(path.getType(), path.getMetadata()));
    this.queryFactory = new JPAQueryFactory(JPQLTemplates.DEFAULT, entityManager);
}
```

그런데 이 편리한 자동 정렬이 왜 문제가 되냐면, 생성자로 받은 도메인 클래스의 필드에 대해서만 정렬이 됩니다.

즉 축제 목록을 조회할 때, 학교 이름으로 정렬을 하고 싶다면 정렬이 불가능합니다.

또한 잘못된 프로퍼티(name -> naem)를 입력하면 BadRequest가 아닌 InternalServerError가 발생하기 때문에 여러 애로사항이 생깁니다.  (PropertyReferenceException 예외가 발생하는데, 해당 예외를 BadRequest로 처리하는게 과연 맞나 싶네요.)

따라서 결국 수동으로 정렬을 해야하는 상황이 생겼고, `QueryDslRepositorySupport`를 상속하는 방법에서 `QueryDslHelper`를 의존하는 방법을 택하였습니다.

`QueryDslHelper`를 의존하면서 생기는 이점은 아무래도 어떠한 메서드를 사용할 수 있는지 객체를 통해 확인할 수 있다는 점과 생성자로 도메인 클래스를 넣어주지 않아도 된다는 점이 있겠네요.

물론 기존에 제공해주던 자동 정렬 기능은 사용하지 못하게 되므로, 정렬이 필요하다면 정렬 메서드를 직접 구현해야 합니다.

> Spring의 Sort 객체와 QueryDSL의 Sort 객체가 달라 변환용 유틸 클래스를 만들어서 사용했습니다.

2024-02-26 11:43 UTC, carsago approved these changes
고생하셨습니다. 아무래도 정렬 조건이 많다보니 조금 번거로웠을 것 같네요.
groupby로 stage count 처리하고, 쿼리 한번에 해결하니까 깔끔하네요 !!

2024-02-27 07:30 UTC, BGuga requested changes
수고하셨습니다 글렌!!

2024-02-27 07:30 UTC, BGuga commented on backend/src/main/java/com/festago/admin/dto/AdminFestivalV1Response.java
> +    }
근데 문득 궁금한건데 글렌도 QClass 가져올 때 bootJar하고 build/generated 에서 복붙 하시나요?

2024-02-27 07:30 UTC, BGuga commented on backend/src/main/java/com/festago/admin/repository/AdminFestivalV1QueryDslRepository.java
> +            .orElse(OrderSpecifierUtils.NULL);
orElseGet을 사용하는 것이 더 좋지 않을까요?

2024-02-27 08:53 UTC, seokjin8678 commented on backend/src/main/java/com/festago/admin/dto/AdminFestivalV1Response.java
> +    }
음?? 그냥 아무 테스트 실행하거나 해서 자바 컴파일 시키고 바로 코드에서 `QxXX` 입력해서 바로 임포트 해와용

2024-02-27 09:01 UTC, seokjin8678 commented on backend/src/main/java/com/festago/admin/repository/AdminFestivalV1QueryDslRepository.java
> +            .orElse(OrderSpecifierUtils.NULL);
`orElseGet()`의 경우 파라미터로 `Supplier<T>` 타입을 받습니다.
이는 Optional의 값이 없을 때 **게으르게** 처리하기 위함인데, 지금 같은 경우에는 게으르게 처리할 필요가 없습니다!

예를들어 티켓 생성 로직에 `orElse()`를 사용한다면 문제가 발생할 수 있습니다.
```java
public TicketCreateResponse createTicket(TicketCreateRequest request) {  
    Stage stage = stageRepository.findById(request.stageId())  
        .orElseThrow(NoSuchElementException::new);  
  
    Ticket ticket = ticketRepository.findByStage(stage)  
        .orElse(ticketRepository.save(new Ticket(stage)));  // <-- Optional 값이 있던 없던 save() 메소드가 호출됨
  
    ticket.addAmount(request.amount());  
  
    return new TicketCreateResponse(ticket.getId(), ticket.getAmount());  
}
```
즉, 기본값으로 사용될 인스턴스를 가져올 때, 정말 값이 없어야 호출이 되어야 한다면 `orElseGet()`을 사용해야 하지만, 지금 같은 경우 파라미터로 넘어온 값인 `OrderSpecifierUtils.NULL`은 이미 초기화가 된 static 변수입니다.
따라서 `orElse()`를 호출해도 사이드 이펙트가 발생하지 않기에 `orElse()`를 사용하였습니다.

2024-03-05 14:07 UTC, BGuga approved these changes
수고하셨어요!

2024-03-05 14:53 UTC, merged