[BE] feat: Artist 생성, 수정에 누락된 필드를 추가한다.(#732)
woowacourse-teams/2023-festa-go pull request #756
Opened 2024-02-24 11:26 UTC by BGuga

## 📌 관련 이슈

- closed: #732

## ✨ PR 세부 내용

Artist 생성, 수정에서 backgroundImgageUrl 을 함께 보내도록 수정 했습니다.
추가로 Artist 에서 사용하지 않는 생성자를 삭제했습니다.

2024-02-24 11:39 UTC, seokjin8678 requested changes
고생하셨습니다 푸우!1
테스트 코드에 중복된 변수만 제거하면 될 것 같네요!

2024-02-24 11:39 UTC, seokjin8678 commented on backend/src/main/java/com/festago/artist/application/ArtistCommandService.java
>      }
Artist를 수정하면 `StageQueryInfo`, `FestivalQueryInfo` 도메인도 영향을 받아야 할텐데.. 여기서 이벤트를 발행해야 할 것 같네요!
(지금은 PR의 범위가 다르니 별도의 이슈에서 처리하면 좋겠네요!)
또한 이벤트 객체의 필드에는 무엇이 들어갈지 고민해 보면 좋을 것 같습니다!

2024-02-24 11:39 UTC, seokjin8678 commented on backend/src/test/java/com/festago/admin/presentation/v1/AdminArtistV1ControllerTest.java
> +    private static final Cookie COOKIE = new Cookie("token", "token");
둘 중 하나만 사용하면 될 것 같네요!

2024-02-24 11:51 UTC, BGuga commented on backend/src/test/java/com/festago/admin/presentation/v1/AdminArtistV1ControllerTest.java
> +    private static final Cookie COOKIE = new Cookie("token", "token");
이게 왜 들어갔지 ㅋㅋ 제거했어요!!

2024-02-24 11:52 UTC, BGuga commented on backend/src/main/java/com/festago/artist/application/ArtistCommandService.java
>      }
artistId만 넘기면 artist가 어떤 축제, 정보에 포함되었는지 파악하는 로직이 많이 중복될 것 같네요!!

2024-02-24 11:55 UTC, seokjin8678 commented on backend/src/main/java/com/festago/artist/application/ArtistCommandService.java
>      }
트랜잭션 범위(영속 상태, 준영속 상태)도 고려한다면 엔티티를 그대로 넘겨도 괜찮을까요? (해당 엔티티의 변경이 없다면)

2024-02-24 11:55 UTC, seokjin8678 approved these changes
리뷰 반영 확인했습니다!

2024-02-26 05:27 UTC, carsago approved these changes
고생하셨습니다 푸우

2024-02-26 05:27 UTC, carsago commented on backend/src/main/java/com/festago/artist/application/ArtistCommandService.java
>      }
아티스트 변경시, 해당 조회용 테이블들을 업데이트 하기 위해서 아티스트가 포함된 축제 목록들을 조회해야할텐데,
이 부분을 해당 클래스에서 넘긴다면 이벤트를 전달받은 클래스에서 받는다면 각각 2번 조회해야할 필요가 없겠네요.
다만 그걸 이벤트를 발행하는 클래스에서 알아야하나? 라는 부분도 고민되는 포인트이긴 합니다. 
결국 이야기하면서 정해야할듯요.

2024-02-27 07:08 UTC, merged