[BE] feat: 아티스트 검색 구현(#761
woowacourse-teams/2023-festa-go pull request #762
Opened 2024-02-27 07:07 UTC by BGuga

## 📌 관련 이슈

- closed: #761

## ✨ PR 세부 내용

아티스트 검색 구현하였습니다.
쿼리문을 작성하면서 다음과 같은 고민이 있었습니다.
```java
List<ArtistSearchV1Response> response = selectFrom(artist)
            .leftJoin(stageArtist).on(expression.and(stageArtist.artistId.eq(artist.id)))
            .leftJoin(stage).on(stage.id.eq(stageArtist.stageId))
            .leftJoin(festival).on(festival.id.eq(stage.festival.id))
            .leftJoin(festivalQueryInfo).on(festival.id.eq(festivalQueryInfo.festivalId))
            .where(expression)
            .transform(
                groupBy(artist.id).list(
                    new QArtistSearchV1Response(
                        artist.id,
                        artist.name,
                        artist.profileImage,
                        list(new QArtistFestivalDetailV1Response(
                            festival.id,
                            festival.name,
                            festival.startDate,
                            festival.endDate,
                            festival.thumbnail,
                            festivalQueryInfo.artistInfo
                        ).skipNulls())
                    ).skipNulls()
                )
            );
```
현재 구현된 쿼리는 위와 같습니다.
제가 신경 쓰였던 부분은 artist 에 대한 artistStage leftJoin을 하면 모든 artist 이 join 테이블에 올라와서 DB의 메모리 정보를 과도하게 사용하지 않을까 고민했습니다.
고민결과 현재 단일 키워드 조회와 두 글자 이상 키워드 조회를 분리하였기 때문에 많아도 5명 이내로 아티스트가 검색될 것으로 예상했습니다.
이 경우 join 테이블의 크기는 최대
```
검색 아티스트 x 아티스트 무대 참여 갯수 + 그 이외의 아티스트
```
크게 문제가 되지 않을거라 판단하였습니다.

추가로 5명 초과로 아티스트가 검색되었을 경우 너무 보편적인 단어를 통해 검색을한 경우라 생각하여 warn 로그를 띄우도록 하였습니다.
전에 말씀 주신 `대학교` 같은 키워드들을 막는 과정이 추가되어야 할 것 같긴한데 논의가 좀 더 필요하다 생각해서 우선 로그만 띄웠습니다.

2024-02-27 09:53 UTC, seokjin8678 requested changes
고생하셨습니다 푸우!
검색 기능이 생각보다 고려해야 할 것이 많네요. 😂
오늘 회의를 통해 정책을 명확하게 정해야 할 것 같습니다!

2024-02-27 09:53 UTC, seokjin8678 commented on backend/src/main/java/com/festago/artist/dto/ArtistSearchV1Response.java
> +}
아티스트 검색은 아티스트가 속해있는 축제의 목록을 반환해주는 것이 아닌, 그저 아티스트의 목록을 반환해주는 것이 아니었나요?
![image](https://github.com/woowacourse-teams/2023-festa-go/assets/116627736/52064ba5-78d1-418f-b5c8-bea9b8215075)

2024-02-27 09:53 UTC, seokjin8678 commented on backend/src/main/java/com/festago/artist/presentation/v1/ArtistSearchV1Controller.java
> +    }
검색의 결과가 빈 값이라면 `ArtistsSearchV1Response` 클래스로 감싸지 안고 `List<ArtistSearchV1Response>`로 반환해도 좋지 않을까요?
감싸더라도, `results`에 빈 값이 있는게 이상한 결과는 아닐 것 같아요!

2024-02-27 09:53 UTC, seokjin8678 commented on backend/src/main/java/com/festago/common/exception/ErrorCode.java
> +    FESTIVAL_INFO_CONVERT_ERROR("FestivalInfo 를 만들 수 없습니다");
해당 변경은 롤백하는게 좋겠네요!

2024-02-27 09:53 UTC, seokjin8678 commented on backend/src/test/java/com/festago/artist/application/ArtistSearchV1QueryServiceTest.java
> +        void 해당하는_키워드의_아티스트가_없으면_빈_옵셔널을_빤화한다() {
예전에 빤환이 생각나네요

2024-02-27 09:53 UTC, seokjin8678 commented on backend/src/main/java/com/festago/artist/repository/ArtistSearchV1QueryDslRepository.java
> +            log.warn("{} 키워드로 검색시 3개를 초과한 검색 결괄르 반환하였습니다", keyword);
🦅

2024-03-02 05:37 UTC, carsago commented on backend/src/main/java/com/festago/artist/presentation/v1/ArtistSearchV1Controller.java
> +@RequiredArgsConstructor
저희가 화요일날 이야기한 그대로 이게 festival로 바뀌는 것이죠?

2024-03-02 05:37 UTC, carsago commented on backend/src/main/java/com/festago/artist/repository/ArtistSearchV1QueryDslRepository.java
> +        if (response.isEmpty()) {
글렌이 말씀해주신 것처럼 빈 리스트를 반환하면 될 것 같습니당.

2024-03-03 16:23 UTC, BGuga commented on backend/src/main/java/com/festago/artist/dto/ArtistSearchV1Response.java
> +}
해당 화면에 필요한 모든 정보를 반환하는 것으로 생각하고 있었습니다 ㅎㅎ;;

2024-03-03 16:24 UTC, BGuga commented on backend/src/main/java/com/festago/artist/presentation/v1/ArtistSearchV1Controller.java
> +@RequiredArgsConstructor
네 맞습니다!!

2024-03-13 07:19 UTC, carsago approved these changes

2024-03-13 07:19 UTC, carsago commented on backend/src/main/java/com/festago/festival/repository/ArtistFestivalSearchV1QueryDslRepository.java
> +        }
여기서 검증을 할거면 null, blank다 막을 수 있게  그냥 완전 StringUtils.isBlank()로 하는건 어떨까요

2024-03-13 07:19 UTC, carsago commented on backend/src/test/java/com/festago/artist/application/FestivalSearchV1QueryServiceTest.java
> +        }
```suggestion
            }
        }
```

사소하지만..

2024-03-13 07:19 UTC, carsago commented on backend/src/main/java/com/festago/festival/application/FestivalSearchV1QueryService.java
> +    private static final Pattern schoolPattern = Pattern.compile(".*대(학교)?$", Pattern.CANON_EQ);
xx대, xx대학교 뿐만 아니라 xx대학도 해줘야하나?? 라는 고민이 드네요.
필요없을 것같기도하고 했으면 좋겠을 것 같기도하고.

2024-03-14 00:07 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/repository/ArtistFestivalSearchV1QueryDslRepository.java
> +        }
1. 축제 검색이 5개를 초과한 결과가 나오는 경우가 흔할 것 같네요!
2. 로그 레벨이 warn 인 이유가 있을까요?

2024-03-14 00:09 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/repository/ArtistFestivalSearchV1QueryDslRepository.java
> +            .innerJoin(festivalQueryInfo).on(festival.id.eq(festivalQueryInfo.festivalId)).where(expression)
`.where()` 메서드에 줄바꿈을 해주면 좋겠네요!

2024-03-14 00:17 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/application/FestivalSearchV1QueryService.java
> +    private static final Pattern schoolPattern = Pattern.compile(".*대(학교)?$", Pattern.CANON_EQ);
`Pattern.CANON_EQ` 해당 플래그가 필요한 이유가 있을까요?

2024-03-14 00:18 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/presentation/v1/FestivalSearchV1Controller.java
> +    }
`@RequestParam`에 default 값이 없다면 NPE가 발생할 것 같네요!
따라서 default 값 설정하거나, `StringUtils.hasText()` 사용을 해야 할 것 같네요!
혹은 `Validator.notBlank` 사용해도 괜찮을 것 같습니다!

2024-03-14 00:20 UTC, seokjin8678 commented on backend/src/test/java/com/festago/artist/application/FestivalSearchV1QueryServiceTest.java
> +package com.festago.artist.application;
패키지 위치가 잘못된 것 같네요!

2024-03-14 00:22 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/repository/ArtistFestivalSearchV1QueryDslRepository.java
> +            .innerJoin(stageArtist).on(expression.and(stageArtist.artistId.eq(artist.id)))
해당 join 절에 `.on(expression.and(...)))`가 사용될 필요가 있나요?

2024-03-14 00:27 UTC, seokjin8678 commented on backend/src/test/java/com/festago/artist/application/FestivalSearchV1QueryServiceTest.java
> +    FestivalSearchV1QueryService festivalSearchV1QueryService;
몇 변수는 해당 테스트에서 사용되지 않는 것 같네요!

2024-03-14 00:28 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/repository/SchoolFestivalSearchV1QueryDslRepository.java
> +            .fetch();
축제를 검색할 때 축제의 이름이 포함된 검색이 아닌, 학교의 이름이 포함된 검색으로 바뀌어야 할 것 같네요!

2024-03-14 00:31 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/repository/SchoolFestivalSearchV1QueryDslRepository.java
> +            .fetch();
그리고 아티스트 검색에는 검증 로직이 있지만, 학교 검색에서는 검증 로직이 없는 것 같네요!

2024-03-14 00:33 UTC, seokjin8678 commented on backend/src/test/java/com/festago/artist/application/FestivalSearchV1QueryServiceTest.java
> +                assertThat(actual).hasSize(2);
개수만 검증해도 괜찮을까요?
검색 기능을 마무리하기 촉박하다면 우선 진행하고, 새롭게 이슈를 파서 테스트를 재정비하는 것도 좋겠네요!

2024-03-14 05:58 UTC, BGuga commented on backend/src/main/java/com/festago/common/exception/ErrorCode.java
> +    FESTIVAL_INFO_CONVERT_ERROR("FestivalInfo 를 만들 수 없습니다");
반영했는데 또 돌아갔네요 자동 정렬되는 것 같습니다

2024-03-14 08:07 UTC, BGuga commented on backend/src/main/java/com/festago/festival/repository/ArtistFestivalSearchV1QueryDslRepository.java
> +        }
보편적 단어 키워드를 막으려 했는데 해당 검색의 경우 "아이"라는 키워드를 통해 검색한다면
아이유, 아이들, 아이브 등등 여러 가수에 대한 축제를 다 반환하기 때문에 이런 logging이 필요 없겠군요!!
제거했습니다.

2024-03-14 11:12 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/presentation/v1/FestivalSearchV1Controller.java
> +    }
생각해보니, `@RequestParam`은 값이 없으면 기본으로 예외가 발생하는군요. 😂

2024-03-20 08:21 UTC, BGuga commented on backend/src/main/java/com/festago/festival/repository/ArtistFestivalSearchV1QueryDslRepository.java
> +            .innerJoin(stageArtist).on(expression.and(stageArtist.artistId.eq(artist.id)))
요걸 명시하지 않으면 모든 stageArtist에 대해서 join을 해서 결과가 다르게 나옵니다!!

있는 경우
<img width="511" alt="image" src="https://github.com/woowacourse-teams/2023-festa-go/assets/103228463/d3211ae9-9f47-4940-b363-d38937f763f9">

없는 경우
<img width="485" alt="image" src="https://github.com/woowacourse-teams/2023-festa-go/assets/103228463/32b3e57c-d1e5-4fd3-be30-5847981d7209">

2024-03-20 08:29 UTC, BGuga commented on backend/src/main/java/com/festago/festival/repository/SchoolFestivalSearchV1QueryDslRepository.java
> +            .fetch();
그때 축제의 이름에 학교 이름을 명시하기로 해서 이렇게 했는데 join을 학교까지 끌고가서 학교로 검색하는 것이 나을까요?

2024-03-20 08:34 UTC, BGuga commented on backend/src/test/java/com/festago/artist/application/FestivalSearchV1QueryServiceTest.java
> +                assertThat(actual).hasSize(2);
검증 강화 했습니다!

2024-03-21 07:56 UTC, seokjin8678 commented on backend/src/main/java/com/festago/common/exception/ErrorCode.java
>      ;
해당 변경 제가 처리했습니다

2024-03-21 07:59 UTC, seokjin8678 approved these changes
고생하셨습니다!

2024-03-21 07:59 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/repository/SchoolFestivalSearchV1QueryDslRepository.java
> +            .fetch();
어제 말한대로 그냥 이대로 가고, 나중에 문제가 생기면 바꾸면 될 것 같네요!
결과는 똑같으니..

2024-03-21 07:59 UTC, seokjin8678 commented on backend/src/test/java/com/festago/festival/application/integration/FestivalSearchV1QueryServiceTest.java
> +    FestivalSearchV1QueryService festivalSearchV1QueryService;
통합 테스트에서 Repository를 너무 많이 의존하고 있는 것 같네요.
지금은 이렇게 하지만 추후 Service를 의존하는 방법으로 리팩터링이 필요할 것 같습니다.
(너무 많은 세부 구현에 의존하고 있어, 변경에 취약합니다)

2024-03-26 07:45 UTC, merged