[BE] feat: 학교 검색 기능 구현 (#761)
woowacourse-teams/2023-festa-go pull request #769
Opened 2024-03-03 08:08 UTC by seokjin8678

## 📌 관련 이슈

- #761

## ✨ PR 세부 내용

학교 검색 기능은 워낙 간단해서 구현에서 크게 어려운 점은 없었네요. (QueryDSL 덕분에 딸깍하고 끝냈습니다.)

하지만 추후 변경이 될 사항을 고려해야 할 것 같습니다.

![image](https://github.com/woowacourse-teams/2023-festa-go/assets/116627736/d5997d19-dd15-4ee3-8480-27564f0b3336)

아직 확정된 사항은 아니지만, 학교 검색 시 `서울대` 와 같은 줄임말로 검색을 할 수 있습니다.

또한 결과로 `서울대`와 같이 줄임말로 이름을 대신 하게 되는데, 기존 `School` 도메인에 `alias`(별칭) 라는 필드를 추가해야 할 수 있습니다.

혹은 별칭이 여러 개가 될 수 있는 경우 별도의 테이블로 분리하는 경우도 생각해볼 수 있을 것 같네요.

자세한 얘기는 화요일에 하는게 좋을 것 같습니다!

2024-03-03 10:08 UTC, carsago reviewed
말씀하신 대로 확실히 Response를 어떤 값을 줄건지 등을 fix해야 더 이야기를 할 수 있을 것 같습니다. 
제 PR도 마찬가지 일 것이구요

2024-03-06 13:06 UTC, seokjin8678 commented
학교 별로 가장 빠른 축제 기간을 찾는게 쉬울 줄 알았으나 난관에 봉착했습니다.. 😂
단일 학교의 가장 빠른 축제를 구하는 SQL은 다음과 같습니다.
```sql
select id, school_id, start_date, end_date
from festival
where school_id = 1 and start_date >= now()
order by start_date
limit 1;
```
하지만 검색 기능은 여러 학교가 조회될 수 있으므로 위의 쿼리를 다음과 같이 변경해야 합니다.
```sql
select id, school_id, start_date, end_date
from festival
where school_id in (1, 2) and start_date >= now()
order by start_date
limit 2 # schoolIds.size()
```
하지만 해당 쿼리는 잘못된 결과가 반환될 수 있습니다.
school A에서 1일, 2일 축제, school B에서 3일 축제가 있다고 가정할 때, 해당 쿼리를 실행하면 school B의 축제는 조회할 수 없습니다.

school_Id로 group by를 사용하면 해결할 수 있기는 한데, 다른 컬럼(id, start_date, end_date)을 조회해야 하므로 다음과 같이 `any_value()`를 사용하여 해결해야 합니다.
```sql
select school_id, min(start_date), any_value(end_date), any_value(id)
from festival
where school_id in (1, 2) and start_date >= now()
group by school_id
```
하지만 이 경우에도 문제가 발생할 수 있는 것이, 축제의 시작 날짜가 같은 경우 `any_value()`를 사용하기 때문에 순서가 보장되지 않을 수 있습니다.
하지만 학교의 축제 중에서 시작 날짜가 같은 경우가 있나 싶고, 축제 범위에서 또 새로운 축제가 있는 것이 말이 되지 않습니다. 😂
따라서 `any_value()`를 사용해도 될 것 같습니다만, 여러분의 의견이 듣고 싶습니다.

2024-03-06 17:26 UTC, seokjin8678 commented
구현하다가 문득 생각이 들었는데, 추후 캐싱을 사용해보는게 어떨까 싶네요.

지금 구현은 다음과 같이 이뤄질 것 같습니다.
![image](https://github.com/woowacourse-teams/2023-festa-go/assets/116627736/dae666e0-5d0f-45d3-992c-56ac7bb191c8)

2번 쿼리를 나눠 보내는데, 학교 검색 쿼리와, 검색된 학교의 식별자 목록으로 최신 축제를 가져오는 쿼리입니다.

조회된 결과를 조합하여 `List<TotalSchoolSearchResponse>`를 클라이언트에게 반환합니다.
(mergeLogic에 `recentRes`를 `Collectors.groupingBy` 하여 `Map<Long, Response>`로 만들고 지지고 볶으면 될 것 같네요.)

해당 구현에서 발생하는 문제는 검색 요청마다 최근 축제를 가져오기 위해 쿼리가 하나 더 날아간다는 점 입니다.
(두 번째 쿼리 분석 결과 인덱스를 타므로 DB에 부하는 크게 없을 것 같네요)

만약 이 구현에서 2번 발생하는 쿼리 때문에 성능에 악영향을 끼친다 생각된다면 다음과 같이 캐싱을 적용해볼 수 있을 것 같습니다.
![image](https://github.com/woowacourse-teams/2023-festa-go/assets/116627736/46f0017e-1673-4665-a7fb-bbd39ee376f2)

최근 축제는 학교 당 단 하나만 존재하므로, 메모리 부담도 크게 없을 것 같습니다. (학교 자체가 적기도 하구요)

주의해야 할 사항은 축제가 생성, 수정 될 때 캐시를 지워야 합니다.

이 사항은 Festival CUD Service에 이벤트를 발행시켜서, `RecentFestivalCacheEventListener`를 통해 캐시를  지우면 될 것 같습니다.

만약 학교 검색 요청이 빈번하다면 캐시 사용이 효과적일 것 같습니다. (Spring Cache 적용 또는 직접 ConcurrentHashMap으로 구현)

2024-03-07 07:09 UTC, carsago reviewed
이런 쿼리로 해결하면 어떤가요?

```
select school_id, min(start_date)
from festival
where school_id in (...) and end_date >= :today
group by school_id
```

이렇게 조회하고 startDate <= today면 진행중, startdate > today면 그 갭만큼 D-day 해주면 되지않을까용

2024-03-07 07:13 UTC, seokjin8678 commented
> 이런 쿼리로 해결하면 어떤가요?
> 
> ```
> select school_id, min(start_date)
> from festival
> where school_id in (...) and end_date >= :today
> group by school_id
> ```
> 
> 이렇게 조회하고 startDate <= today면 진행중, startdate > today면 그 갭만큼 D-day 해주면 되지않을까용

![image](https://github.com/woowacourse-teams/2023-festa-go/assets/116627736/d5997d19-dd15-4ee3-8480-27564f0b3336)

`end_date`를 같이 보내주지 않으면 이 축제가 언제 끝났는지 모르니, 화면에 `축제 중`으로 모두 띄워야 합니다. 😂

2024-03-07 07:18 UTC, carsago commented
오늘 3월 7일
A학교축제  
3월 5일 ~ 3월 10일
3월 7일 ~ 3월 12일
B학교축제 
3월 8일 ~ 3월 10일
3월 9일 ~ 3월 11일

쿼리 결과

A학교 - 학교ID, 3월 5일
B학교 - 학교ID, 3월 8일

이러면 
A 학교 startDate 3월 5일
B 학교 startDate 3월 8일이니

A학교 진행중, B학교 D-1으로 계산할 수 있지않나요.

2024-03-07 07:22 UTC, seokjin8678 commented
> 오늘 3월 7일 A학교축제 3월 5일 ~ 3월 10일 3월 7일 ~ 3월 12일 B학교축제 3월 8일 ~ 3월 10일 3월 9일 ~ 3월 11일
> 
> 쿼리 결과
> 
> A학교 - 학교ID, 3월 5일 B학교 - 학교ID, 3월 8일
> 
> 이러면 A 학교 startDate 3월 5일 B 학교 startDate 3월 8일이니
> 
> A학교 진행중, B학교 D-1으로 계산할 수 있지않나요.

네 진행 예정인 축제 계산은 문제가 없는데 오늘이 3월 13일이라 가정하면, A학교, B학교 모두 축제가 끝난 상황에서 표시를 모두 `축제 중`이라고 진행을 해야해요. 😂

2024-03-07 07:37 UTC, seokjin8678 commented
> 3월 13일이라 가정하면 조회가 안될거니까( endDate >= '2024-03-13') 예정없음이 나오지않을까요..? Map<Long(schoolId), LocalDate(StratDate)>로 받은 다음에
> 
> 1. `key가 없음` ->  예정 없음
> 2. `startDate <= today` -> 진행중
> 3. `startDate > today` -> D - (today - stratDate)

아 애초에 끝난 축제는 끝났다고 표시할 필요가 없으니, 그냥 WHERE에서 end_date >= now 를 하면 되겠군요!

2024-03-07 09:44 UTC, seokjin8678 commented
@BGuga @carsago 
기능 구현 완료했습니다!
리뷰 부탁드려용

2024-03-09 08:48 UTC, BGuga requested changes
안녕하세요 글렌 수고하셨습니다!!
구현상 쿼리 2번이 발생했고 그에 따른 해결책으로 캐싱도 고려하셨군요!!
고민하다 보니.. 아래와 같은 쿼리면 한번에 해결할 수 있지 않을까요??
```java
@Repository
public class SchoolSearchV1QueryDslRepository extends QueryDslRepositorySupport {

    public SchoolSearchV1QueryDslRepository() {
        super(School.class);
    }

    public List<SchoolTempResponse> searchSchools(String keyword, LocalDate today) {
        return selectFrom(school)
            .where(school.name.contains(keyword))
            .leftJoin(festival).on(festival.school.eq(school).and(festival.endDate.goe(today)))
            .orderBy(school.name.asc())
            .transform(
                groupBy(school.id).list(
                    new QSchoolTempResponse(
                        school.id,
                        school.name,
                        school.logoUrl,
                        list(
                            new QFestivalTempResponse(
                                festival.startDate,
                                school.id
                            )
                        ))
                )
            );
    }
}

```

```java
public record SchoolTempResponse(
    Long id,
    String name,
    String logoUrl,
    List<FestivalTempResponse> festivals
) {

    @QueryProjection
    public SchoolTempResponse {
    }
}
```

```java
public record FestivalTempResponse(
    LocalDate startTime,
    Long schoolId
) {

    @QueryProjection
    public FestivalTempResponse {
    }
}
```
Repository에서 이렇게 응답을 받고 Service에서 SchoolTotalResponse로 변환하면 될 것 같아요

2024-03-09 10:21 UTC, carsago approved these changes
고생하셨습니다 글렌
```SchoolTotalSearchV1QueryService```와 유사한 클래스가 복잡한 조회 로직이 많이 생길수록(여러번 쿼리 땡겨서 합치는 경우) 계속 늘어날텐데, 테스트를 어떻게 할지도 애매하긴 하네요

내부 조회 로직들은 mocking하고 합쳐지는것만 검증해야할지 흠..

2024-03-09 10:21 UTC, carsago commented on backend/src/main/java/com/festago/school/application/v1/SchoolSearchRecentFestivalV1QueryService.java
> +    Map<Long, SchoolSearchRecentFestivalV1Response> searchRecentFestivals(List<Long> schoolIds);
이 부분은 언급해주신 대로 캐싱 확장 가능성 고려해서 interface화 하신거죠?

2024-03-09 10:31 UTC, carsago commented
> 안녕하세요 글렌 수고하셨습니다!! 구현상 쿼리 2번이 발생했고 그에 따른 해결책으로 캐싱도 고려하셨군요!! 고민하다 보니.. 아래와 같은 쿼리면 한번에 해결할 수 있지 않을까요??
> ...
> Repository에서 이렇게 응답을 받고 Service에서 SchoolTotalResponse로 변환하면 될 것 같아요

글렌보다 먼저 제가 답을 달아보면 푸우 방식도 제 생각엔 가능할 것 같아요.

```leftJoin(festival).on(festival.school.eq(school).and(festival.endDate.goe(today)))```

에서 festival이 여러개 걸려도 어차피 조회가 몇개 더 되는건 그냥 부담안되기에 Java code로 School의 Festival의 min(startDate)만을 필터링 해줄 수 있으니까요. (경우에 따라 이 로직이 코드가 더 복잡하다고 느낄 수도 있을 것 같네요.)

다만 이런 방식으로 했을 때 걱정되는건, 학교 검색 로직이 ```school.name.contatin()```에서 school을 oneToMany로 가지는 키워드 테이블에 검색하는 방식으로 조만간 바뀔 것 같은데, 이러면 이후에 학교 검색 로직을 변경하는게 조금 어렵지 않을까? 라는 생각이 들긴합니다.

2024-03-09 11:31 UTC, seokjin8678 commented on backend/src/main/java/com/festago/school/application/v1/SchoolSearchRecentFestivalV1QueryService.java
> +    Map<Long, SchoolSearchRecentFestivalV1Response> searchRecentFestivals(List<Long> schoolIds);
네 맞습니다. 👍 
또 하나의 이유는 해당 인터페이스가 `school` 패키지에 있는 것을 볼 수 있는데, 학교 검색 시 최근 축제의 일자를 알아야 하므로 의존 관계가 양방향이 되어 버립니다. (학교는 축제를 몰라야 하므로)
따라서 해당 문제를 해결하고자 하는 이유도 있습니다.

2024-03-09 11:36 UTC, seokjin8678 commented
> 안녕하세요 글렌 수고하셨습니다!! 구현상 쿼리 2번이 발생했고 그에 따른 해결책으로 캐싱도 고려하셨군요!! 고민하다 보니.. 아래와 같은 쿼리면 한번에 해결할 수 있지 않을까요??
> 
> ```java
> @Repository
> public class SchoolSearchV1QueryDslRepository extends QueryDslRepositorySupport {
> 
>     public SchoolSearchV1QueryDslRepository() {
>         super(School.class);
>     }
> 
>     public List<SchoolTempResponse> searchSchools(String keyword, LocalDate today) {
>         return selectFrom(school)
>             .where(school.name.contains(keyword))
>             .leftJoin(festival).on(festival.school.eq(school).and(festival.endDate.goe(today)))
>             .orderBy(school.name.asc())
>             .transform(
>                 groupBy(school.id).list(
>                     new QSchoolTempResponse(
>                         school.id,
>                         school.name,
>                         school.logoUrl,
>                         list(
>                             new QFestivalTempResponse(
>                                 festival.startDate,
>                                 school.id
>                             )
>                         ))
>                 )
>             );
>     }
> }
> ```
> 
> ```java
> public record SchoolTempResponse(
>     Long id,
>     String name,
>     String logoUrl,
>     List<FestivalTempResponse> festivals
> ) {
> 
>     @QueryProjection
>     public SchoolTempResponse {
>     }
> }
> ```
> 
> ```java
> public record FestivalTempResponse(
>     LocalDate startTime,
>     Long schoolId
> ) {
> 
>     @QueryProjection
>     public FestivalTempResponse {
>     }
> }
> ```
> 
> Repository에서 이렇게 응답을 받고 Service에서 SchoolTotalResponse로 변환하면 될 것 같아요

이 방법을 사용하면 쿼리 한 방으로 해결할 수 있겠군요 👍👍
하지만 조금 문제가 되는건 학교 검색 도메인에 축제가 연관이 되어 있다는 점인데, 화면에 보여줘야 하는 정보 상 해당 검색을 통해 반드시 축제를 조회해야 합니다.

이를 해결할 방법을 고심한 결과, 학교 검색은 학교 검색만 하도록 하고, 그 외 부가적인 정보 조회(가장 빠른 축제의 시작일)은 별도의 도메인에서 처리하도록 하였습니다.

이 때문에 쿼리 한 방이 추가로 날아가는 것이구요..

쿼리 한 방이 날라가는게 성능 문제가 크다고 판단한다면 어쩔 수 없을 것 같습니다.

2024-03-10 02:57 UTC, BGuga approved these changes
>이 방법을 사용하면 쿼리 한 방으로 해결할 수 있겠군요 👍👍
하지만 조금 문제가 되는건 학교 검색 도메인에 축제가 연관이 되어 있다는 점인데, 화면에 보여줘야 하는 정보 상 해당 검색을 통해 반드시 축제를 조회해야 합니다.
이를 해결할 방법을 고심한 결과, 학교 검색은 학교 검색만 하도록 하고, 그 외 부가적인 정보 조회(가장 빠른 축제의 시작일)은 별도의 도메인에서 처리하도록 하였습니다.
이 때문에 쿼리 한 방이 추가로 날아가는 것이구요..
쿼리 한 방이 날라가는게 성능 문제가 크다고 판단한다면 어쩔 수 없을 것 같습니다.

조회를 위한 로직은 querydsl 기반으로 최적화 하고 의존성은 살짝 눈 감는 방향으로 진행했으니 적용하여도 좋고 쿼리 2번 정도면 나둬도 좋을 것 같습니다!!
수고하셨습니다

2024-03-22 11:09 UTC, merged