[BE] feat: 아티스트 검색 기능 구현 (#761)
woowacourse-teams/2023-festa-go pull request #770
Opened 2024-03-03 10:20 UTC by carsago

## 📌 관련 이슈

- closed: #761 

## ✨ PR 세부 내용

아티스트를 id name profileImage만 넘겨준다면 간단한 쿼리라서 별 건 없습니다.
글렌이 PR에서 언급하신 것처럼 어떤 식으로 view에 넘겨줄지 fix된 후에 수정이든 merge든 필요할 것 같네요.

그나마 특이사항으로는 검색어가 1글자면 eq을, 2글자 이상이면 contain으로 했어요.(사전에 이야기한 부분으로 기억합니다.)
eq이라면 비어있거나 1개인 값만 검색되는게 일반적일 건데, 같은 response DTO를 쓰기 위해서 둘다 list로 처리했습니다.

2024-03-10 07:09 UTC, carsago commented on backend/src/main/java/com/festago/artist/application/ArtistSearchStageCountV1QueryService.java
> +    }
Stage의 StartTime을 받아서 오늘인지, 미래(예정)인지 갯수를 세는 코드입니다.
이 부분을 가독성이라도 개선하고 싶었는데, 음.. 메소드 추출해도 더 안좋아지고 애매하더라고요. ㅠㅠ

2024-03-10 07:23 UTC, carsago reviewed
@BGuga @seokjin8678 
하다보니까 좀 오래 걸렸습니다.. 컨벤션은 글렌이랑 맞출려고 노력해봤어요.

2024-03-10 07:23 UTC, carsago commented on backend/src/main/java/com/festago/artist/application/ArtistSearchStageCountV1QueryService.java
> +    }
Stage의 StartTime을 받아서 오늘인지, 미래(예정)인지 갯수를 세는 코드입니다.
이 부분을 가독성이라도 개선하고 싶었는데, 음.. 메소드 추출해도 더 안좋아지고 애매하더라고요. ㅠㅠ

2024-03-10 07:23 UTC, carsago commented on backend/src/main/java/com/festago/artist/application/ArtistTotalSearchV1Service.java
> +    private final ArtistSearchStageCountV1QueryService artistSearchStageCountV1QueryService;
굳이 클래스 더 안만들고 한개의 클래스에서 걍 할려고 했는데 그럴려고 하니 테스트가 너무 어려워지는 문제가 있어서 분리했습니다.
(컨벤션은 글렌이랑 맞출려고 노력했어요.)

```ArtistSearchQueryService``` 에서는 키워드가 1글자면 eq 검색, 2글자 이상이면 like 검색 그리고 반환 결과가 10개 이상이면 예외라는 부분이 테스트 되어야 하고

```ArtistSearchStageCountQueryService```에서는 해당 아티스트들의 공연이 오늘 갯수, 예정 갯수를 반환해야하는데

한번에 다 테스트 할려면 given절이 이해할 수 없는 수준이 될 수밖에 없어서 나누는 방향으로 갔습니다.

2024-03-10 15:05 UTC, seokjin8678 commented on backend/src/main/java/com/festago/artist/presentation/v1/ArtistSearchV1Controller.java
> +        LocalDate today = LocalDate.now();
굳이 Service에서 `Clock`으로 LocalDate를 만들어 사용하지 않고, 컨트롤러에서 LocalDate를 넘겨주는 것도 좋아보이네요!
다만, 나중에 Controller 통합 테스트가 필요할 수 있으니, `Clock`을 의존성 주입 받는 것은 어떤가요?
이렇게 된다면 `Clock`은 지금 `@Component`로 빈에 등록되어 있으니, 컨트롤러 테스트에서 의존성 주입 문제가 발생할 것 같네요.
테스트 패키지에 `com.festago.support.CustomWebMvcTest` 어노테이션의 `@Import`에 추가로 `TestTimeConfig`를 추가해야할 것 같습니다!

2024-03-10 15:21 UTC, seokjin8678 commented on backend/src/main/java/com/festago/artist/repository/ArtistSearchV1QueryDslRepository.java
> +import static com.festago.stage.domain.QStage.stage;
```suggestion
package com.festago.artist.repository;

import static com.festago.artist.domain.QArtist.artist;
import static com.festago.stage.domain.QStage.stage;
```

2024-03-11 06:22 UTC, carsago reviewed
리뷰 바탕으로 조금 개선했습니다.

2024-03-11 11:38 UTC, seokjin8678 approved these changes
고생하셨습니다 오리!
count의 타입에 대해 얘기하고 싶어 리뷰 남겼습니다!
확인하시고 답변 부탁드려요!

2024-03-11 11:38 UTC, seokjin8678 commented on backend/src/test/java/com/festago/artist/application/ArtistTotalSearchV1ServiceTest.java
> +    }
Service 내에서 하는 일이 명확하다면 이와 같이 Mock 사용을 하는게 매우 효과적이네요. 👍👍

2024-03-11 11:38 UTC, seokjin8678 commented on backend/src/main/java/com/festago/artist/application/ArtistSearchStageCountV1QueryService.java
> +        return new ArtistSearchStageCountV1Response(countOfTodayStage, countOfPlannedStage);
궁금한게 두 가지 있어요!
1. `count` 변수에 `int` 타입을 사용하신 이유가 궁금합니다!
2. DTO에 `count` 값이 레퍼런스 타입이던데, 원시 타입을 사용하지 않은 이유가 궁급합니다! (개수에서 0과 null은 같은 의미를 가지므로)

2024-03-12 04:13 UTC, BGuga requested changes
수고하셨습니다 오리!!

2024-03-12 04:13 UTC, BGuga commented on backend/src/main/java/com/festago/artist/application/ArtistSearchStageCountV1QueryService.java
> +            ));
```java
artistSearchStageCountV1QueryService.findArtistsStageCountAfterDateTime(
            artistIds, LocalDate.now(clock).atStartOfDay());
        return artists.stream()
            .map(it -> ArtistTotalSearchV1Response.of(it, artistToStageCount.get(it.id())))
            .toList();
```
저는 해당 부분을 보고 만약 아티스트가 축제가 없으면 null 예외가 발생할 수 있지 않을까 생각했었습니다.
하지만 Stage 쿼리 서비스를 보니 00 값으로 반환해주기 때문에 null 을 피할 수 있다는 것을 이해했습니다!!
즉, 해당 메서드가 입력한 id에 대한 모든 응답을 반환해주는 책임을 이행하고 있고 호출 메서드들은 이 사실에 의존합니다!!
저는 이 책임을 조금 더 명확하게 해주기 위해 validation 을 추가하는 것이 어떨까요??
구현상 입력 받은 id에 대한 모든 응답이 현재 나가고 있지만 이것을 하나의 명확한 validation으로 바라보고 잡아둔다면 추후에 리팩토링에서 더 안전한 구조가 될 수 있을 것 같습니다 ㅎㅎ

2024-03-13 07:35 UTC, carsago commented on backend/src/main/java/com/festago/artist/application/ArtistSearchStageCountV1QueryService.java
> +import static java.util.stream.Collectors.toMap;
d

2024-03-13 07:35 UTC, carsago commented on backend/src/main/java/com/festago/artist/application/ArtistSearchStageCountV1QueryService.java
> +            ));
이건 고민이네요.. 
물론 둘다 큰 차이는 아니지만, 전 오히려 오늘인지 아닌지 여부만을 따지기 때문에 LocalDate로 변환해서 필요한 parameter만 보내주는게 더 명확하지 않나..? 라는 생각이 들어요.

2024-03-13 07:35 UTC, carsago commented on backend/src/main/java/com/festago/artist/application/ArtistSearchStageCountV1QueryService.java
> +            ));
이게  Map을 넘기다보면 어쩔 수 없더라고요.
제가 생각한건 layer를 넘어가기전에 null 체크를 하고, 테스트코드로 방어하기로 하자! 라고 했는데
다른 layer에서는 그걸 모르니까 애매한 부분이 있긴합니다.. 굳이 더블 체크를 해야할지 불안하기에 따로 검증 및 테스트를 해야할지..
좀 번거롭지만 중복 코드를 만드는게 나을까요 고민됩니다.

2024-03-13 07:35 UTC, carsago commented on backend/src/main/java/com/festago/artist/application/ArtistSearchStageCountV1QueryService.java
> +        return new ArtistSearchStageCountV1Response(countOfTodayStage, countOfPlannedStage);
1. long 수준으로 큰 값이 의미없기에 int로 지정했어요.

2. 전 default 값 박히는 것보다 null 넣는게 차라리 나은 것 같다 마인드라 이런 방식을 선호했는데, 생각해보면 default(0) == null 이라면 그냥 원시타입으로 쓰고, 그런 룰이 바뀔때만 객체로 처리해도 되겠다는 생각도 드네요. 특히 가격, 갯수는 웬만하면 변경되지 않을거니까요.

2024-03-13 12:07 UTC, BGuga requested changes
https://www.notion.so/wooteco-ash/1c646ff7aaab462d9b4dd9c262c731e7

API 명세에서 만약 해당하는 값이 없을 경우 404로 보낸다 하셨는데 다른 항목들은 빈 리스트로 보내주기 때문에 이 부분 맞추면 좋을 것 같습니다!!

2024-03-14 02:43 UTC, seokjin8678 commented on backend/src/main/java/com/festago/artist/application/ArtistSearchStageCountV1QueryService.java
> +            ));
테스트 코드로 방어해도 충분하지 않을까요?
결국 validation 로직을 작성해도 validaiton을 검증하는 테스트 코드를 작성해야하니..

2024-03-14 02:50 UTC, seokjin8678 commented on backend/src/main/java/com/festago/artist/application/ArtistSearchStageCountV1QueryService.java
> +        return new ArtistSearchStageCountV1Response(countOfTodayStage, countOfPlannedStage);
stream().count()가 반환 타입이 long이라 int로 형변환이 필요하더라구요!
그런데 그냥 count 변수를 long 타입으로 선언하면 굳이 형변환하는 과정이 필요 없어지지 않을까요?
int와 long 둘 다 숫자를 표현하는데 문제 없고 4바이트 차이 밖에 발생하지 않으니까요!

2024-03-20 05:07 UTC, carsago commented
@BGuga @seokjin8678 
허 제가 며칠전에 변경하고 코멘트를 안달았었네요.

사실 코드상에서는 검색결과가 없을때 빈 list를 반환했었는데요.
API 명세서는 그렇지 않아서 명세서만 수정했습니다.

2024-03-20 07:12 UTC, BGuga approved these changes

2024-03-21 07:53 UTC, seokjin8678 approved these changes

2024-03-22 10:05 UTC, merged