[AN/USER] 안드로이드 네비게이션을 적용한다. (#758)
woowacourse-teams/2023-festa-go pull request #781
Opened 2024-03-09 01:49 UTC by re4rk

## 📌 관련 이슈

- closed: #758 

## ✨ PR 세부 내용

1. 네비게이션 2.7.7 버전으로 적용하였습니다.
2. 팀원들이 navigation이 없어서 설명드립니다.
    - 네비게이션은 res의 navigation을 통해서 작동하게 됩니다.
    - 해당 xml이 있다면 action을 통해서 다음 프래그먼트로 이동할 수 있습니다.
    - 만약에 다음 프래그먼트에 argument 태그가 있다면 `safeargs`을 통해서 인자를 받게 됩니다.
``` kotlin
findNavController().navigate(
    FestivalListFragmentDirections.actionFestivalListFragmentToArtistDetailFragment(
        artistId,
    ),
)
```
``` xml
<?xml version="1.0" encoding="utf-8"?>
<navigation xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/festivalList"
    app:startDestination="@id/festivalListFragment">

    <fragment
        android:id="@+id/festivalListFragment"
        android:name="com.festago.festago.presentation.ui.home.festivallist.FestivalListFragment"
        android:label="FestivalListFragment"
        tools:layout="@layout/fragment_festival_list">
        <action
            android:id="@+id/action_festivalListFragment_to_artistDetailFragment"
            app:destination="@id/artistDetailFragment"
            app:enterAnim="@android:anim/slide_in_left"
            app:popExitAnim="@android:anim/slide_out_right" />
    </fragment>
    <fragment
        android:id="@+id/artistDetailFragment"
        android:name="com.festago.festago.presentation.ui.artistdetail.ArtistDetailFragment"
        android:label="ArtistDetailFragment"
        tools:layout="@layout/fragment_artist_detail">
        <argument
            android:name="artistId"
            app:argType="long" />
    </fragment>
</navigation
```

3. 바텀 네비게이션의 id들이 `festivalList` 처럼 변하게 되었는데 해당 id가 프래그먼트와 같아야지 동작하게 되서 변경하게 되었습니다.
```
       - android:id="@+id/itemFestival"
       + android:id="@+id/festivalList"
```

4. 전에 톡방에서 전달 드렸던 뒤로가기 버튼을 눌렀을 때 전 화면이 리프래시 되는 현상이 있는 것을 공유 드렸습니다.
- 해당 현상이 일어나는 이유는 navigation에서의 fragment의 생명주기가 다음과 같이 생명주기가 다시 실행되기 때문에 저희 코드에서 load를 한번 더하기 때문입니다.

<img width="517" alt="스크린샷 2024-03-09 오전 10 46 44" src="https://github.com/woowacourse-teams/2023-festa-go/assets/37167652/8a5ccdf4-81f0-488b-84fc-78d3677a01cd">
- 따라서 다음 코드들이 추가 되었습니다. 
- 기존 binding이 있으면 기존꺼를 반환합니다.
- 추가로 저희 화면마다 데이터를 호출하는데 refresh 플래그 값이 없으면 refresh 하지 않도록 변경했습니다.

<img width="497" alt="스크린샷 2024-03-09 오전 10 48 07" src="https://github.com/woowacourse-teams/2023-festa-go/assets/37167652/fd4e1d8e-3e83-4bba-b09a-276bbe22ad0a">

2024-03-09 17:03 UTC, SeongHoonC requested changes
상태바가 흰색으로 변경되게 만들었었는데 안되네요. backStack 이 변경되지 않아서 리스터가 동작하지 않네요.

임시로 myPage 에 네비게이션 그래프를 추가해봤는데 스택이 따로 저장되네요! 이러면 fragment manager 4개로 관리할 필요는 없겠군요!

네비게이션이 생각보다 복잡하군요. 코멘트 확인해주세요!

2024-03-10 06:54 UTC, EmilyCh0 approved these changes
고생하셨습니다 👍 코멘트 확인해 주세요!

2024-03-10 06:54 UTC, EmilyCh0 commented on android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/FestivalDetailFragment.kt
> +        }
null이 아닌 게 어떤 경우인가요??

2024-03-10 06:54 UTC, EmilyCh0 commented on android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/FestivalDetailViewModel.kt
> +
넵 initView() 호출될때마다 불필요하게 load 다시하는 거 막으려고 했던거로 기억합니당

2024-03-10 06:54 UTC, EmilyCh0 commented on android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/HomeActivity.kt
> +        bottomNavigationView.setupWithNavController(navController)
NavigationUI 내부적으로 첫번째 destination으로 popup 하게 되어있어서 그런 것 같아요. 
bottom navigation menu item에 menuCategory를 secondary로 두면 탭 이동도 백스택 관리할 수 있어요! 아래 링크 참고
https://hide1202.github.io/android/navigation-backstack/

2024-03-10 06:54 UTC, EmilyCh0 commented on android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SocialMediaView.kt
이 코드 제가 제거했던 것 같은데 다시 살아났네요..?

2024-03-10 06:54 UTC, EmilyCh0 commented on android/festago/presentation/src/main/res/menu/menu_bottom_navigation.xml
> +        android:id="@+id/festivalList"
https://github.com/woowacourse-teams/2023-festa-go/pull/781/files#r1518540321

2024-03-10 13:07 UTC, SeongHoonC commented on android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/HomeActivity.kt
> +        bottomNavigationView.setupWithNavController(navController)
오오 감사합니다!

2024-03-10 13:08 UTC, SeongHoonC commented on android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SocialMediaView.kt
해시가 작업한 커밋이 PR에 포함되어있네요?

2024-03-13 00:32 UTC, re4rk commented on android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/schooldetail/SocialMediaView.kt
병렬 작업을 위해 해시 PR 브랜치로 타겟으로 했어요
분기 후에 코드 제거를해서 그런지 살아있는거 같네요

2024-03-13 00:48 UTC, re4rk commented on android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/artistdetail/ArtistDetailFragment.kt
> +        }
null로 만들어주는게 onDestory인줄 알았는데 착각했네요
찾아보니 네비게이션 action은 무조건 replace로 작동하고
add처럼 동작하려면 dialog태그를 사용해야합니다.

2024-03-13 00:50 UTC, re4rk commented on android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/festivaldetail/FestivalDetailFragment.kt
> +        }
베르가 말해준 생명주기를 보고 롤백했습니다.

2024-03-13 01:16 UTC, re4rk commented on android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/HomeActivity.kt
> +        bottomNavigationView.setupWithNavController(navController)
베르
- 사실 네비게이션 버튼 이동 시에 뒤로가기 누르면 홈에 쌓인 것들이 초기화 되는 것처럼 보이지만 그 상태에서 다시 홈을 누르면 홈의 스택이 다시 올라옵니다!
해시
- 네비게이션 전략은 다양하게 선택될 수 있을 것같은데 해시가 링크해준게 좋다고 생각해서 반영했습니다!

2024-03-13 02:36 UTC, SeongHoonC approved these changes
프래그먼트 정책 변경 및 버그 수정 확인했습니다!
축제 목록 to 축제 상세 
animation 만 추가하고 머지합니다!

2024-03-13 02:36 UTC, SeongHoonC commented on android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/HomeActivity.kt
> +        navController.addOnDestinationChangedListener { _, destination, _ ->
addOnDestinationChangedListener 도 있군요! 또 배워갑니다!

2024-03-13 02:36 UTC, merged