[BE] 축제 북마크 기능 구현 (#788)
woowacourse-teams/2023-festa-go pull request #791
Opened 2024-03-16 11:45 UTC by seokjin8678

## 📌 관련 이슈

- closed: #788

## ✨ PR 세부 내용

축제 북마크 기능을 구현했습니다.

API 경로는 다음과 같습니다.

축제 북마크 등록: `PUT /api/v1/bookmark/festivals/{festivalId}` 
축제 북마크 삭제: `DELETE /api/v1/bookmark/festivals/{festivalId}` 
축제 북마크 축제 식별자 목록 조회: `GET /api/v1/bookmark/festivals/ids`
축제 북마크 축제 목록 조회: `GET /api/v1/bookmark/festivals`
(bookmark를 복수형으로 해야하나 모르겠네요 😂)

어제 얘기했을 때 북마크 등록, 삭제의 경우 bookmark 식별자를 보내주기로 했었는데, 클라이언트 측에서 북마크 식별자가 필요 없어도 되는 것과 등록 API와 삭제 API의 통합을 위해 유니크 인덱스로 등록과 삭제를 구현했습니다.

이유를 설명하자면..

1. 식별자의 생성 시점

북마크의 식별자를 해당 3개의 필드로 조합된 유니크 인덱스로 대신 사용할 수 있습니다. (슈퍼키)

북마크를 삭제할 때 북마크의 식별자가 필요한데, 북마크의 식별자(PK)를 얻으려면 `@GeneratedValue` 유무에 관계 없이 우선 객체가 생성되어야 합니다.

따라서 식별자를 알아내기 위해 서버의 응답을 반드시 기다려야 합니다.

하지만 굳이 식별자를 알아내지 않아도 해당 유니크 인덱스가 있으니 식별자를 클라이언트 레벨에서 관리가 가능해집니다.

2. 등록 URL과 삭제 URL의 통일

위에서 말했듯, 식별자를 클라이언트가 미리 알고 있는 것과 다름이 없기에 등록과 삭제 처리가 간단해집니다.

등록의 경우 반드시 식별자를 반환해줘야 하므로 클라이언트에서 응답을 받아 처리를 해주는 과정이 필요합니다.

삭제의 경우 등록과 다르게 식별자를 넘겨줘야 하므로 같은 URL에 서로 다른 엔티티의 식별자로 받아야 합니다. 
(등록의 경우 `/api/v1/bookmark/festivals/{festivalId}`, 삭제의 경우 `/api/v1/bookmark/festivals/{bookmarkId}`

이러한 이유로 북마크의 식별자를 사용하는 것보다 유니크 인덱스를 통한 사용이 훨씬 좋다고 판단됩니다.

---

추가로 구현하던 중, 북마크한 축제의 식별자를 반환하고, 다시 식별자를 받아, 그걸 다시 축제 목록으로 반환할 필요가 있을까 생각이 들었는데 추후 캐싱을 고려한다면 충분히 괜찮을 것 같더군요.

그리고 북마크 기능은 회원 인증이 반드시 필요한 기능이기에 `LoginConfig`에 `/api/v1/bookmark/**` 경로를 추가해뒀습니다.

이걸 구현하다 나중에 V2가 생기고, 회원 인증이 필요한 API가 생기면 지옥을 맛 볼 것 같아서 #789 이슈를 만들어 구현해두었습니다.

추가로 얘기가 필요한 사항은 코드에 TODO 주석으로 남겨뒀습니다.

2024-03-16 11:50 UTC, seokjin8678 commented on backend/src/main/java/com/festago/bookmark/repository/FestivalBookmarkOrder.java
> +}
![image](https://github.com/woowacourse-teams/2023-festa-go/assets/116627736/4931177b-23af-4db8-b5d9-04a0c7563d2b)
북마크의 최근 저장순과 축제의 최신 축제순 정렬을 위한 Enum 입니다.
이름을 뭘로 해야할지 모르겠네요 😂

2024-03-16 11:51 UTC, seokjin8678 commented on backend/src/main/java/com/festago/bookmark/application/FestivalBookmarkCommandService.java
> +        }
해당 예외 코드 학교, 아티스트에도 사용될 것 같아 우선 TEST_ERROR로 남겨뒀습니다.

2024-03-16 12:07 UTC, seokjin8678 commented on backend/src/main/java/com/festago/bookmark/repository/FestivalBookmarkV1QueryDslRepository.java
> +    }
![image](https://github.com/woowacourse-teams/2023-festa-go/assets/116627736/5ff56e71-0794-4a90-9469-5ef43a780ff9)

화면에 보내줄 정보가 메인에서 띄워줄 축제와 100% 동일하길래 해당 DTO 그대로 가져와 사용했는데, 학교의 정보를 보내줄 필요가 있을까요?

2024-03-16 12:32 UTC, seokjin8678 commented on backend/src/main/java/com/festago/bookmark/presentation/v1/FestivalBookmarkV1Controller.java
> +        @RequestParam List<Long> festivalIds,
Controller 레벨에서 Size 검증이 필요할 것 같은데, 도메인 규칙대로 12개로 제한하는게 좋을까요?

2024-03-16 12:36 UTC, seokjin8678 commented on backend/src/main/java/com/festago/bookmark/presentation/v1/FestivalBookmarkV1Controller.java
> +    @Operation(description = "축제의 식별자로 축제 북마크를 등록한다.")
`등록` 혹은 `저장` 어느게 더 좋을까요?

2024-03-20 06:19 UTC, carsago reviewed
글렌 언급해주신 부분에 코멘트를 달아보았습니다.

북마크를 삭제하는데 있어 ID를 몰라도 처리 가능하기에, 응답을 기다릴 필요가 없게하기 위해서 따로 response를 안준다는 것 이해했습니다.

다만 제가 생각하기엔 API 콜 이후에 에러가 나타나는 경우가 있기 때문에 결국 이러든 저러든 클라이언트에서 response를 기다려야하는거 아닌가? 라는 생각이듭니다.

12개 초과하도록 좋아요를 누르는 경우엔 에러 메시지를 전달하고 클라이언트측에서 유저에게 에러 메시지를 보여줘야하니까요. 클라이언트에서 내부에 북마크를 저장하는 것도, 요청을 확인하고 저장해야할 것이고요.

그리고 ```북마크 삭제 API가 아티스트, 축제, 학교 모두 나뉘어질 필요가 있을까?``` 라는 생각도 듭니다.  저는 하나의 API로 처리가 가능한데, 굳이 3개가 필요할까? 라는 생각도 들어요.

다만 이 부분은 클라이언트측이랑도 이야기해보면 좋겠네요.

2024-03-20 06:19 UTC, carsago commented on backend/src/main/java/com/festago/bookmark/presentation/v1/FestivalBookmarkV1Controller.java
> +    @Operation(description = "축제의 식별자로 축제 북마크를 등록한다.")
Put을 할까 post를 할까도 고민인데요. 이 API로 등록 & 삭제를 같이 처리할 것이 아니라면, POST로 쓰는게 더 괜찮지 않을까요?

2024-03-20 06:19 UTC, carsago commented on backend/src/main/java/com/festago/bookmark/application/FestivalBookmarkCommandService.java
> +            return;
이 부분 ok 보내주기 보다는 validate에서 호출하는 method로 넣고, ```이미 등록된 북마크입니다.```같은 에러를 보내주는건 어떤가요.

2024-03-20 06:19 UTC, carsago commented on backend/src/main/java/com/festago/bookmark/application/FestivalBookmarkCommandService.java
> +    }
delete할 때 찾아서 있으면 수행, 없으면 예외 해야할지, 아니면 그냥 필드값으로 있든 없든 삭제 때려야할지 전 항상 고민이더라고요.

2024-03-20 07:11 UTC, BGuga requested changes
수고하셨읍니다 글렌!!

2024-03-20 07:11 UTC, BGuga commented on backend/src/main/java/com/festago/bookmark/repository/FestivalBookmarkV1QueryDslRepository.java
> +    }
화면이 바뀐다면 두 화면이 같이 바뀔 가능성도 있으니 재활용해도 좋을 것 같습니다!

2024-03-20 07:11 UTC, BGuga commented on backend/src/main/java/com/festago/bookmark/repository/FestivalBookmarkOrder.java
> +}
근데 이게 북마크 화면에 들어간 순간 축제를 보여줘야 하는데 이때는 Order가 결정되지 않은 상태이지 않을까요??
페이징이 처리되어서 일부 데이터를 보내준다면 서버에서 Order를 기반으로 처리해주어야 겠지만
모두 다 보내는 현 상황에서는 기본적인 정렬만 보내주고 front 단에서 데이터를 기반으로 추가 요청 없이 스스로 정렬해주면 되지 않을까요??

2024-03-21 08:03 UTC, seokjin8678 commented on backend/src/main/java/com/festago/bookmark/repository/FestivalBookmarkOrder.java
> +}
어제 회의에서 얘기한대로 그대로 진행하겠습니다1

2024-03-21 08:04 UTC, seokjin8678 commented on backend/src/main/java/com/festago/bookmark/repository/FestivalBookmarkV1QueryDslRepository.java
> +    }
클라이언트 측 요구사항으로 인해 그대로 유지하겠습니다!

2024-03-21 08:23 UTC, seokjin8678 commented on backend/src/main/java/com/festago/bookmark/application/FestivalBookmarkCommandService.java
> +            return;
처음에 저도 에러를 던져줄까 생각을 했는데요, 해당 메서드의 역할을 생각해보면 굳이 에러를 던질 필요가 없더라구요.

사용자가 원하는 것은 해당 북마크 타입과 자원의 식별자로 북마크를 등록하는 것인데, 이미 해당 북마크 타입과 자원의 식별자로 등록된 북마크가 있다면 사용자가 원하는 기능을 완수한 상태라고 보고 예외라고 판단하지 않았습니다.

이를 통해 얻을 수 있는 장점으로 해당 API를 호출했을 때 멱등함을 보장할 수 있습니다!
(물론 따닥 같은 상황으로 인해 발생하는 동시성 문제가 있겠지만, 지금은 유니크 인덱스를 통해 동시성 문제가 발생하지 않습니다)

2024-03-21 08:24 UTC, seokjin8678 commented on backend/src/main/java/com/festago/bookmark/presentation/v1/FestivalBookmarkV1Controller.java
> +    @Operation(description = "축제의 식별자로 축제 북마크를 등록한다.")
멱등함을 보장하기 위해 `PUT`을 사용했습니다!

2024-03-21 08:27 UTC, seokjin8678 commented on backend/src/main/java/com/festago/bookmark/application/FestivalBookmarkCommandService.java
> +    }
클라이언트에서 잘못된 festivalId를 보내더라도 다른 사람의 자원을 삭제하려는게 아니라면 굳이 예외를 발생시킬 필요가 없지 않을까요?
또한 보안의 이유를 생각하더라도, 해당 자원이 없어도 OK 처리를 해주는게 좋을 것 같습니다.

2024-03-21 08:30 UTC, seokjin8678 commented on backend/src/main/java/com/festago/bookmark/presentation/v1/FestivalBookmarkV1Controller.java
> +    }
실 구현을 보시면 아시겠지만, 추가하려는 북마크의 자원의 타입과 식별자가 존재하는지 찾고, 있으면 예외 없이 early return 하는 방식으로 구현되어 있습니다.
즉, 해당 API를 호출하는 것은 멱등함을 보장합니다.

따라서 멱등함을 보장하지 않는 POST 보다 PUT을 사용하였습니다.

2024-03-21 08:44 UTC, seokjin8678 commented
@BGuga @carsago 
클라이언트 DTO 요구사항 반영했습니다!
추가로 리뷰에 답 남겼으니 확인 부탁드립니다!

2024-03-23 11:25 UTC, carsago commented on backend/src/main/java/com/festago/bookmark/application/FestivalBookmarkCommandService.java
> +            return;
> (물론 따닥 같은 상황으로 인해 발생하는 동시성 문제가 있겠지만, 지금은 유니크 인덱스를 통해 동시성 문제가 발생하지 않습니다)

그럼에도 이런 요청은 발생할 수 있고, 내부적으로 명시적인 예외를 던져주는 것이(DB 제약조건 에러가 발생하는 것보다는) 더 좋지않을까요? 물론 그런 상황이 잘 없겠지만, 전 예외를 직접 던져주는 것이 더 좋은 코드라고 느껴져요. 

그리고 이 부분은 모든 북마크 API에서 일관성있게 처리해야 하는 부분이다보니 어느 방향이든 일단 통일이 필요하겠네요.

2024-03-23 11:28 UTC, seokjin8678 commented on backend/src/main/java/com/festago/bookmark/application/FestivalBookmarkCommandService.java
> +            return;
중복된 북마크 일 때 다시 북마크를 하는 것이 클라이언트 입장에서 정보가 될 수 있으니, 예외를 던져도 괜찮을 것 같네요!

2024-03-26 05:58 UTC, BGuga approved these changes

2024-03-28 06:02 UTC, carsago approved these changes

2024-03-29 11:52 UTC, merged