[BE] feat: 아티스트 북마크 구현(#787)
woowacourse-teams/2023-festa-go pull request #816
Opened 2024-03-25 16:19 UTC by BGuga

## 📌 관련 이슈

- #787 

## ✨ PR 세부 내용

아티스트 북마크 조회, 생성, 삭제 구현하였습니다.
조회의 경우 controller 까지 구현하였으며
생성, 삭제의 경우 Service 까지 구현하였습니다.
Fixture를 사용하기위해 dev merge 를 해서 파일 file changed 가 많이 잡혔네요 😂
리뷰 범위는 [다음](https://github.com/woowacourse-teams/2023-festa-go/pull/816/files/abbdbf6d81db8bdd4d4987c6538d974d5254edc7..a2f0f2eea4a083f270776e4946bb13dc31117acc) 과 같습니다

2024-03-26 08:30 UTC, seokjin8678 requested changes
고생하셨습니다 푸우
리뷰 범위 남겨주셔서 코드 리뷰하기 편했네요.
Command 서비스 테스트에 통합 서비스 테스트로 수행하는 부분만 검토해주시면 될 것 같습니다!

2024-03-26 08:30 UTC, seokjin8678 commented on backend/src/main/java/com/festago/bookmark/application/ArtistBookmarkCommandService.java
> +    }
유니크 제약 조건 때문에 지금 등록 로직에서 예외가 발생할 수 있을 것 같네요.
이건 추후 모든 PR이 완료되었을 때 고려해야할 것 같긴 한데..
우선 그렇습니다.

2024-03-26 08:30 UTC, seokjin8678 commented on backend/src/main/java/com/festago/bookmark/application/ArtistBookmarkCommandService.java
> +        }
`artistRepository.existsById()` 사용할 수 있을 것 같네요!

2024-03-26 08:30 UTC, seokjin8678 commented on backend/src/test/java/com/festago/bookmark/application/ArtistBookmarkCommandServiceTest.java
> +    Artist 네오;
보고 싶은 사람들이네요 😂

2024-03-26 08:30 UTC, seokjin8678 commented on backend/src/test/java/com/festago/bookmark/application/ArtistBookmarkCommandServiceTest.java
> +class ArtistBookmarkCommandServiceTest extends ApplicationIntegrationTest {
해당 서비스에 통합 테스트가 필요한 로직이 있을까요? (SQL에 의존적인 로직, 이벤트 발행 등)

2024-03-26 08:30 UTC, seokjin8678 commented on backend/src/main/java/com/festago/bookmark/repository/v1/ArtistBookmarkV1QueryDslRepository.java
> +    }
오리 리뷰에도 남겼지만, 다음과 같은 쿼리 실행 결과가 동일하더군요.
```sql
explain FORMAT = JSON
select *
from school s
         inner join bookmark b
                    on s.id = b.resource_id and b.bookmark_type = 'SCHOOL' and b.member_id = 1;

explain FORMAT = JSON
select *
from bookmark b
         inner join school s on s.id = b.resource_id
where b.bookmark_type = 'SCHOOL'
  and b.member_id = 1;
```
근데 성능을 따지자면, 지금 같이 JOIN절에 모든 조건을 명시해주는게 맞아 보입니다.

2024-03-26 08:30 UTC, seokjin8678 commented on backend/src/main/java/com/festago/bookmark/dto/v1/ArtistBookmarkV1Response.java
> +    ArtistBookmarkInfoV1Response artistInfo,
이것도 필드명을 artist로 할지, artistInfo라고 할지 클라이언트 분들에게 여쭤보면 좋겠네요!

2024-03-26 09:46 UTC, BGuga commented on backend/src/main/java/com/festago/bookmark/application/ArtistBookmarkCommandService.java
> +    }
요거는 응답을 
```
1. 추가, 삭제의 경우 정상이면 200, 204

2. 중복 추가인 경우는 500 (동시성 문제가 발생하면 ex: DB 유니크 제약 위반)

3. 북마크 최대 개수 초과이면 400
```
로 정의해서 예외 그대로 500 내는 것을 방치했는데 처리 해야겠네요

2024-03-26 09:48 UTC, BGuga commented on backend/src/test/java/com/festago/bookmark/application/ArtistBookmarkCommandServiceTest.java
> +    Artist 네오;
저는 최근에 브리 브라운은 봤습니다 ㅋㅋㅋ

2024-03-26 09:49 UTC, BGuga commented on backend/src/test/java/com/festago/bookmark/application/ArtistBookmarkCommandServiceTest.java
> +class ArtistBookmarkCommandServiceTest extends ApplicationIntegrationTest {
굳히 통합이 아니여도 괜찮지만 제일 편한 방법이라 이렇게 사용했습니다
memory로 사용하는게 좋을까요?

2024-03-26 10:27 UTC, seokjin8678 commented on backend/src/test/java/com/festago/bookmark/application/ArtistBookmarkCommandServiceTest.java
> +class ArtistBookmarkCommandServiceTest extends ApplicationIntegrationTest {
둘 다 사용해도 차이는 없지만, 지금 수준에서는 memory를 사용한 단위 테스트가 더 효과적인 선택이 아닌가 싶네요

2024-03-26 19:16 UTC, BGuga commented on backend/src/test/java/com/festago/bookmark/application/ArtistBookmarkCommandServiceTest.java
> +class ArtistBookmarkCommandServiceTest extends ApplicationIntegrationTest {
반영했습니다 속도가 빠르긴 하네요

2024-03-26 22:54 UTC, seokjin8678 approved these changes
리뷰 반영 확인했습니다!
고생하셨습니다!

2024-03-28 04:39 UTC, carsago commented on backend/src/main/java/com/festago/member/repository/MemberRepository.java
> +    long count();
이런거 해주는거 좋네요

2024-03-28 05:31 UTC, carsago approved these changes

2024-03-28 05:31 UTC, carsago commented on backend/src/test/java/com/festago/member/repository/MemoryMemberRepository.java
> +    private final AtomicLong autoIncrement = new AtomicLong();
저도 MemoryDB를 만들면서 느낀게 공통되는 코드를 MemoryRepository(임시 명칭) 같은 클래스를 만들어서 제네릭으로 공통 처리해주는게 이후에 필요할 것 같아요. 만들긴 하겠는데.. 공통으로 쓸 클래스라는 점 + 리플렉션을 활용하다보니 별도의 PR로 같이 이야기하면서 만드는게 좋겠다는 생각이 드네요.

2024-03-28 06:02 UTC, seokjin8678 commented on backend/src/test/java/com/festago/member/repository/MemoryMemberRepository.java
> +    private final AtomicLong autoIncrement = new AtomicLong();
공통으로 사용되는 memory, autoIncrement 필드와 `id: Long -> Optional<T>` 형식의 findById, `entity -> T` -> `T` 형식의 save 메서드를 추상 클래스에 정의하면 중복을 없앨 수 있을 것 같네요!

2024-03-29 09:50 UTC, merged