[BE] feat: 목 데이터 스케쥴러 구현(#725)
woowacourse-teams/2023-festa-go pull request #821
Opened 2024-03-29 04:04 UTC by BGuga

## 📌 관련 이슈

- closed: #725 

## ✨ PR 세부 내용

목 데이터 스케줄러를 구현했습니다.
전체 흐름은
1. application이 켜지는 시점에 School 과 Artist에 대하여 initilaize한다. 

이때 만약 학교가 하나라도 존재한다면 이미 초기화 이후 데이터라 판단하여 초기 학교, 아티스트 데이터를 만들지 않습니다. 
그래서 dev db의 학교들을 다 지워야하는데 이 방법 외에 좋은 아이디어 있으시면 공유 부탁드립니다.

2. initialize 된 시점에서 모든 학교에 대해서 Festival을 만든다.

생성 되는 Festival은 요청 파라미터 이내의 기간 내에서 최대 3일의 기간을 갖는 축제입니다.
각 축제는 기간만큼 Stage를 가지며 이때 Stage 간의 중복 아티스트를 만들지 않기위해 Queue를 Festival 마다 생성해주었습니다.
생성 과정은 QueryInfo 생성과 같은 부가적인 최적화 로직을 자연스럽게 수용할 수 있도록 CommandService를 통해 생성해 주었습니다.

3. 일주일 단위로 모든 학교에 대해서 Festival을 만든다.

2와 동일한 과정을 거칩니다.

2024-03-29 07:31 UTC, seokjin8678 requested changes
고생하셨습니다 푸우!
해당 PR 머지된다면 개발 환경에서 테스트하기 편하겠네요!
다만 몇 가지 신경 써야할 부분에 대해 고려가 필요할 것 같습니다.
리뷰에 남겼으니 확인 부탁드립니다!

2024-03-29 07:31 UTC, seokjin8678 commented on backend/src/main/java/com/festago/mock/MockDataService.java
> +    }
이슈 내용에는 나와있는데, 나중에 코드만 보면 어떤 일을 하는지 알기 힘들 것 같네요.
주석을 남겨주는게 어떤가요?
```suggestion
    /**
    * 설명
    */
    private void makeRegionSchools(SchoolRegion schoolRegion) {
        for (int schoolNumber = 1; schoolNumber <= 3; i++) {
            String schoolName = schoolRegion.name() + schoolNumber;
            schoolCommandService.createSchool(new SchoolCreateCommand(
                    schoolName,
                    schoolName + ".com",
                    schoolRegion,
                    null,
                    null
                )
            );
        }
    }
```

2024-03-29 07:31 UTC, seokjin8678 commented on backend/src/main/java/com/festago/mock/MockDataService.java
> +    }
`availableFestivalDuration` 파라미터를 받지 않고, 여기서 상수로 관리해도 될 것 같은데, 파라미터로 받으신 이유가 있나요?

2024-03-29 07:31 UTC, seokjin8678 commented on backend/src/main/java/com/festago/mock/MockDataService.java
> +    }
또한 Mock으로 세팅된 데이터 말고, 직접 사용자가 추가한 School, Artist에 영향을 받을 수 있을 것 같네요!

2024-03-29 07:31 UTC, seokjin8678 commented on backend/src/main/java/com/festago/mock/MockDataService.java
> +    }
`LocalDate.datesUntil()` 메서드 사용해보는 것도 좋겠네요!

2024-03-29 07:31 UTC, seokjin8678 commented on backend/src/main/java/com/festago/mock/MockDataService.java
> +        LocalDateTime startTime = localDate.atStartOfDay().plusHours(STAGE_START_HOUR);
```suggestion
        LocalDateTime startTime = localDate.atTime(STAGE_START_HOUR, 0);
```

2024-03-29 07:31 UTC, seokjin8678 commented on backend/src/main/java/com/festago/mock/MockDataService.java
> +public class MockDataService {
각 도메인 별로 별도의 서비스를 만들었다면 어땠을까 하는 생각입니다. 😂

2024-03-29 07:31 UTC, seokjin8678 commented on backend/src/main/java/com/festago/mock/MockDataService.java
> +    }
공연에 포함되는 Artist는 반드시 3으로 나눠 떨어져야 하나요?

2024-03-29 07:32 UTC, seokjin8678 commented on backend/src/main/java/com/festago/mock/MockArtist.java
> +        "https://i.namu.wiki/i/yAfAHme6H-HfWWQCvNAje-KInl_XM-xzRHOUmUxvRxh-HLbzk8KbG6zmD9qQXfUAeCenhHM5whZJ2nhQk0lanzT1LVja3BEQCVk1yPWABxy4NygdaLGyNpiRZTwVFkhD_PnCcESdUQ7-oEtK0YptsQ.webp"),
추가로 확장자가 `.webp`, `.svg`와 같이 끝나는데 클라이언트에서 해당 확장자 지원하는지 확인이 필요할 것 같네요!

2024-03-29 07:35 UTC, seokjin8678 reviewed
그 외 스타일에 관한 리뷰는 여기..

2024-03-29 10:00 UTC, BGuga commented on backend/src/main/java/com/festago/mock/MockDataService.java
> +@Profile({"local"})
수정했습니다!!

2024-03-29 10:14 UTC, BGuga commented on backend/src/main/java/com/festago/mock/CommandLineAppStartupRunner.java
> +}
initialize 여부에 따라 초기 scheduler 로직 호출 여부를 다르게 해주었습니다!

2024-03-29 10:31 UTC, BGuga commented on backend/src/main/java/com/festago/mock/MockDataService.java
> +    }
> availableFestivalDuration 파라미터를 받지 않고, 여기서 상수로 관리해도 될 것 같은데, 파라미터로 받으신 이유가 있나요?

스케쥴러 주기를 바꿀 수 있다 생각해서 파라미터로 주기를 받도록 만들었습니다!

> 또한 Mock으로 세팅된 데이터 말고, 직접 사용자가 추가한 School, Artist에 영향을 받을 수 있을 것 같네요!

이 부분은 dev에서 직접 데이터를 만드는 것에 편의를 주기 위해 만든 것이기 때문에 별 상관없다 판단했었습니다!

2024-03-29 10:38 UTC, BGuga commented on backend/src/main/java/com/festago/mock/MockDataService.java
> +public class MockDataService {
Mock 내부에서 서비스를 나누는 방향을 말씀하신 건가?

2024-03-29 10:39 UTC, BGuga commented on backend/src/main/java/com/festago/mock/MockDataService.java
> +    }
그건 아니고 임의로 하나의 공연당 3개의 아티스트를 넣었습니다.

2024-03-29 11:06 UTC, seokjin8678 commented on backend/src/main/java/com/festago/mock/CommandLineAppStartupRunner.java
> +}
서버가 실행되면 `mockScheduler.run();` 해당 로직 호출될텐데.. 이러면 매 서버 시작마다 축제 데이터가 생길 것 같은데.. 문제가 없을까요?

2024-03-29 11:08 UTC, seokjin8678 commented on backend/src/main/java/com/festago/mock/MockDataService.java
> +public class MockDataService {
`MockFestivalDataService`, `MockSchoolDataService`와 같이 도메인 별 데이터를 세팅해주는 서비스에 대한 얘기였어요!

2024-03-29 11:10 UTC, seokjin8678 commented on backend/src/main/java/com/festago/mock/MockDataService.java
> +    }
artists의 size가 `STAGE_ARTIST_COUNT` 개수보다 적다면 `IllegalArgumentException` 예외가 발생할 것 같은데..
size가 그 이하이면 예외를 발생시키지 않고, 그 사이즈 그대로 넣으면 어떤가요?

2024-03-29 11:12 UTC, seokjin8678 commented on backend/src/main/java/com/festago/mock/MockDataService.java
> +    private final FestivalRepository festivalRepository;
해당 리뷰 반영하셨다면 기존 Repository에 있는 `findAll` 메서드 제거할 수 있을 것 같네요!

2024-03-29 13:52 UTC, BGuga commented on backend/src/main/java/com/festago/mock/CommandLineAppStartupRunner.java
> +}
<img width="313" alt="image" src="https://github.com/woowacourse-teams/2023-festa-go/assets/103228463/55a8497c-fb5f-48f4-8cdf-189a54649462">
<img width="326" alt="image" src="https://github.com/woowacourse-teams/2023-festa-go/assets/103228463/1f510582-5a24-46dd-bf57-005cda172c10">

방어 했습니다!

2024-03-29 14:34 UTC, seokjin8678 approved these changes
리뷰 반영 확인했습니다! 고생하셨어요!
기존 기능을 수정하지 않고, 새로운 기능을 추가했으니, 추후 Mock 데이터에 변경이 필요하더라도 편하게 수정할 수 있겠네요!

2024-03-29 14:34 UTC, seokjin8678 commented on backend/src/main/java/com/festago/stage/repository/StageRepository.java
>  }
해당 수정만 없애주면 완벽할 것 같네요!

2024-03-29 15:00 UTC, BGuga reviewed
@seokjin8678 
> artists의 size가 STAGE_ARTIST_COUNT 개수보다 적다면 IllegalArgumentException 예외가 발생할 것 같은데..
size가 그 이하이면 예외를 발생시키지 않고, 그 사이즈 그대로 넣으면 어떤가요?

StageCommandService 에서 Validator 의
```java
public static void notDuplicate(List<?> list, String fieldName) {
        // avoid NPE
        if (list == null || list.isEmpty()) {
            return;
        }
        if (new HashSet<>(list).size() != list.size()) {
            throw new ValidException("%s에 중복된 값이 있습니다.".formatted(fieldName));
        }
    }
```
를 호출하기 때문에 하나의 Stage 에서 중복된 artist들을 넣을 수 없습니다!!
만약 같은 artist로 구성하려면 직접 Stage를 만들고 queryInfo도 생성해야 하는데 이 방식은 유지보수가 상당히 복잡해질 것 같네요 😂
그래서 아티스트가 STAGE_ARTIST_COUNT 이하라면 예외 상황이 맞다 판단하였고
같은 축제 내에서는 아티스트가 중복될 수 있도록 변경했습니다. 
이때 Stage 내에서는 여전히 unique 한 값으로 구성됩니다.

2024-03-29 17:40 UTC, seokjin8678 commented
> @seokjin8678 
> 
> > artists의 size가 STAGE_ARTIST_COUNT 개수보다 적다면 IllegalArgumentException 예외가 발생할 것 같은데..
> 
> size가 그 이하이면 예외를 발생시키지 않고, 그 사이즈 그대로 넣으면 어떤가요?
> 
> 
> 
> StageCommandService 에서 Validator 의
> 
> ```java
> 
> public static void notDuplicate(List<?> list, String fieldName) {
> 
>         // avoid NPE
> 
>         if (list == null || list.isEmpty()) {
> 
>             return;
> 
>         }
> 
>         if (new HashSet<>(list).size() != list.size()) {
> 
>             throw new ValidException("%s에 중복된 값이 있습니다.".formatted(fieldName));
> 
>         }
> 
>     }
> 
> ```
> 
> 를 호출하기 때문에 하나의 Stage 에서 중복된 artist들을 넣을 수 없습니다!!
> 
> 만약 같은 artist로 구성하려면 직접 Stage를 만들고 queryInfo도 생성해야 하는데 이 방식은 유지보수가 상당히 복잡해질 것 같네요 😂
> 
> 그래서 아티스트가 STAGE_ARTIST_COUNT 이하라면 예외 상황이 맞다 판단하였고
> 
> 같은 축제 내에서는 아티스트가 중복될 수 있도록 변경했습니다. 
> 
> 이때 Stage 내에서는 여전히 unique 한 값으로 구성됩니다.

굿굿 고생하셨습니다!

2024-03-30 02:26 UTC, carsago approved these changes
푸우 고생하셨습니다. 꼼꼼한 테스트 코드도 좋네요.

저도 글렌이 코멘트 달아주신 것 처럼 기존에 DB에 존재하는 혹은 테스트용으로 클라이언트에서 직접 넣은 학교, 아티스트 등도 데이터 들어가는 거를 고민해봤는데.. 
푸우가 말씀해주신 것처럼 어차피 데이터 셋팅을 위한거니까 별 상관이 없다고 느껴지네요. 

다만 제 생각엔 코멘트 남긴 것처럼 MockDataService에서 insert 해주는 책임을 조금씩 나누어 가지면 좀 더 보기 편하지 않을까 생각합니다!

2024-03-31 08:30 UTC, merged