[AN/USER] feat: 북마크 화면 구현(#774)
woowacourse-teams/2023-festa-go pull request #859
Opened 2024-04-13 12:51 UTC by re4rk

## 📌 관련 이슈

- closed: #774

## ✨ PR 세부 내용

- PR이 너무 커져서 화면 구성만 진행했습니다.
- Fake 객체를 연동해놨는데 아직 인증이 작업되지 않아서 불가능한 상태입니다.
   - Repository, Service는 구현 완료한 상태입니다.

[Screen_recording_20240413_214148.webm](https://github.com/woowacourse-teams/2023-festa-go/assets/37167652/683927a7-ed0d-4156-95bf-a7ed5fcb0e96)

<img width="176" alt="스크린샷 2024-02-12 오후 7 55 18" src="https://github.com/woowacourse-teams/2023-festa-go/assets/37167652/22417bc8-a5f9-40de-929a-a6760d928a9e">
<img width="176" alt="스크린샷 2024-02-12 오후 7 55 18" src="https://github.com/woowacourse-teams/2023-festa-go/assets/37167652/a0f95676-e15f-4aca-90a0-79da437d2ca4">
<img width="176" alt="스크린샷 2024-02-12 오후 7 55 18" src="https://github.com/woowacourse-teams/2023-festa-go/assets/37167652/004b1c11-e75a-4eed-bdff-5f5b61e147a5">

2024-04-14 05:25 UTC, SeongHoonC requested changes
복잡한 화면인데 정말 고생하셨습니다..!
인메모리 캐싱 부분은 아직 구현되지 않은 것 같아서 코멘트 남기지 않았습니다! 리뷰 확인해주세요!

2024-04-14 05:25 UTC, SeongHoonC commented on android/festago/presentation/src/main/res/layout/fragment_school_bookmark.xml
> +        <androidx.recyclerview.widget.RecyclerView
<img width="294" alt="image" src="https://github.com/woowacourse-teams/2023-festa-go/assets/108349655/eb97bdd2-7fb9-4590-a555-2fd71546968a">

android:layout_marginHorizontal="18dp" 로 간격을 추가해야할 것 같아요!

2024-04-14 05:25 UTC, SeongHoonC commented on android/festago/presentation/src/main/res/navigation/book_mark.xml
> +
불필요한 코드로 보입니다!

2024-04-14 05:25 UTC, SeongHoonC commented on android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/bookmarklist/schoolbookmark/SchoolBookmarkFragment.kt
> +                            BookmarkListFragmentDirections.actionBookmarkListFragmentToFestivalDetailFragment(
SchoolDetail 로 연결해주세요!

2024-04-14 09:30 UTC, EmilyCh0 requested changes
화면 구성만 해도 양이 엄청 많네요..! 고생하셨습니다 👍

2024-04-14 09:30 UTC, EmilyCh0 commented on android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/bookmarklist/schoolbookmark/SchoolBookmarkAdapter.kt
> +            }
id가 아니라 name으로 비교하네요! 캠퍼스가 다르면 이름을 달리하기로 했으니 상관없을지도..?

2024-04-14 09:30 UTC, EmilyCh0 commented on android/festago/presentation/src/main/res/layout/layout_require_login.xml
> +                    android:src="@drawable/ic_refresh" />
`>` 아이콘으로 변경해 주세요!
![image](https://github.com/woowacourse-teams/2023-festa-go/assets/67777523/b8023910-781f-4940-a36c-7b1cecc77865)

2024-04-14 09:30 UTC, EmilyCh0 commented on android/festago/presentation/src/main/res/values/strings.xml
> +    <string name="layout_network_error_not_work">현재 접속이 원할하지 않아요</string>
```suggestion
    <string name="layout_network_error_not_work">현재 접속이 원활하지 않아요</string>
```

2024-04-14 09:30 UTC, EmilyCh0 commented on android/festago/presentation/src/main/res/layout/fragment_school_bookmark.xml
> +            app:layout_constraintTop_toTopOf="parent" />
`관심있는 학교를 북마크 할 수 있어요` 로 변경해 주세요!

2024-04-14 09:30 UTC, EmilyCh0 commented on android/festago/presentation/src/main/res/layout/fragment_festival_bookmark.xml
> +            app:layout_constraintTop_toTopOf="parent" />
`관심있는 축제를 북마크 할 수 있어요`로 변경해 주세요!

2024-04-17 05:45 UTC, re4rk commented on android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/bookmarklist/artistbookmark/ArtistBookmarkAdapter.kt
> +            }
넵!! 백엔드에서 API로 내려주는게 없어서 우선 name으로 비교합니다!

2024-04-17 05:45 UTC, re4rk commented on android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/bookmarklist/artistbookmark/ArtistBookmarkFragment.kt
위에 id가 없는거랑 똑같은 주제입니다!
id가 없어서 showArtistDetail을 처리하지 못했습니다!

2024-04-17 06:04 UTC, re4rk commented on android/festago/presentation/src/main/java/com/festago/festago/presentation/ui/home/bookmarklist/schoolbookmark/SchoolBookmarkAdapter.kt
> +            }
베르하고 공통으로 받은 의견인데 백엔드에서 id를 전달해주고 있지 않아서 name으로 비교했습니다! 백엔드 API가 변경되면 그때 반영 해야할 것같아요!

2024-04-17 06:23 UTC, re4rk commented on android/festago/presentation/src/main/res/navigation/book_mark.xml
> +
삭제 시도해보니 네비게이션의 특성인지 컴파일 단계에서 동작을 하지 않습니다!

2024-04-18 04:52 UTC, SeongHoonC approved these changes
확인했습니다~ 아티스트 id 부분만 추가 작업 해주세요!

2024-04-24 02:49 UTC, merged