[BE] feat: 축제 대학교 검색 기능 보완 및 정렬(#926)
woowacourse-teams/2023-festa-go pull request #927
Opened 2024-05-01 15:38 UTC by BGuga

## 📌 관련 이슈

- closed: #926 

## ✨ PR 세부 내용

검색 로직은 기존에
~ 대학교 혹은 ~대로 끝난다면 축제 이름에 해당 대학교 이름이 적힌 축제를 반환하고 나머지 경우에 아티스트 이름을 기반으로 검색하였습니다.
변경된 로직은
해당 이름에 해당하는 아티스트가 있는지 확인하고 없으면 축제 이름에 해당 키워드가 포함되어 있다면 반환하도록 변경하였습니다.
이로 인해 부경만 쳤을 경우 부경이란 키워드가 포함된 모든 축제를 받을 수 있습니다.
축제 이름에 해당 키워드가 포함되었는지 확인하는 것이기 때문에 만약 "축제"로 검색을 한다면 "축제"가 이름에 포함된 모든 축제가 반환됩니다.
이 부분에 대한 방어 로직을 짜려했으나 앱 초기에는 데이터도 얼마 없을 뿐더러 후에 페이징 적용시에 고려해도 좋을 것이라 판단하여 최대한 검색이 자유롭게 되도록 그대로 두었습니다.

2024-05-02 06:30 UTC, seokjin8678 requested changes
고생하셨습니다 푸우!
코드의 가독성을 조금 개선해 볼 수 있으면 좋겠네요!

2024-05-02 06:30 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/application/FestivalSearchV1QueryService.java
> +    }
`result.addAll()`을 호출하는 순서가 결과에 영향을 미치네요
이렇게 되면 코드의 중복이 발생할 것 같구요. 😂
`FestivalFilter`를 정렬한다면 호출하는 순서에 영향을 주지 않고도 중복을 제거할 수 있을 것 같네요!

2024-05-02 06:30 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/application/FestivalSearchV1QueryService.java
> +    }
인자로 들어오는 `festivals`이 null이 아니라면 null 검사를 할 필요가 없지 않을까요?
Enum 타입에 대해선 switch문이 가독성이 더 높을 것 같네요!

2024-05-02 06:30 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/application/FestivalSearchV1QueryService.java
>      }
`Comparator.comparing()` 메서드를 사용하지 않으신 이유가 있을까요?

2024-05-02 06:30 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/application/FestivalSearchV1QueryService.java
> +            }
진행 중, 진행 예정 축제의 경우 정렬 기준이 시작일 내림차순 일텐데, 이 부분은 의도하신걸까요?

2024-05-02 07:33 UTC, BGuga commented on backend/src/main/java/com/festago/festival/application/FestivalSearchV1QueryService.java
> +            }
앗 아닙니다

2024-05-02 13:12 UTC, seokjin8678 approved these changes
고생하셨습니다 푸우!
덕분에 코드가 보기 쉽게 바뀐것 같네요!
추가 리뷰는 가볍게 생각해주시면 될 것 같습니다.
그리고 제가 작성한 `FestivalSearchV1QueryService` 코드도 첨부할게요.
전 스트림을 사용해서 리팩터링 해봤네요 😁
```java
@Service
@Transactional(readOnly = true)
@RequiredArgsConstructor
public class FestivalSearchV1QueryService {

    private final ArtistFestivalSearchV1QueryDslRepository artistFestivalSearchV1QueryDslRepository;
    private final SchoolFestivalSearchV1QueryDslRepository schoolFestivalSearchV1QueryDslRepository;
    private final Clock clock;

    public List<FestivalSearchV1Response> search(String keyword) {
        List<FestivalSearchV1Response> festivals = findFestivals(keyword);
        Map<FestivalFilter, List<FestivalSearchV1Response>> statusToFestivals = groupByStatus(festivals);
        return sortAndMerge(statusToFestivals);
    }

    private List<FestivalSearchV1Response> findFestivals(String keyword) {
        if (artistFestivalSearchV1QueryDslRepository.existsByName(keyword)) {
            return artistFestivalSearchV1QueryDslRepository.executeSearch(keyword);
        }
        return schoolFestivalSearchV1QueryDslRepository.executeSearch(keyword);
    }

    private Map<FestivalFilter, List<FestivalSearchV1Response>> groupByStatus(
        List<FestivalSearchV1Response> festivals
    ) {
        return festivals.stream()
            .collect(groupingBy(this::determineStatus, () -> new EnumMap<>(FestivalFilter.class), toList()));
    }

    private FestivalFilter determineStatus(FestivalSearchV1Response festival) {
        LocalDate now = LocalDate.now(clock);
        if (now.isAfter(festival.endDate())) {
            return END;
        }
        if (now.isBefore(festival.startDate())) {
            return PLANNED;
        }
        return PROGRESS;
    }

    private List<FestivalSearchV1Response> sortAndMerge(
        Map<FestivalFilter, List<FestivalSearchV1Response>> statusToFestivals
    ) {
        statusToFestivals.forEach((status, festival) -> festival.sort(getFestivalComparatorByStatus(status)));
        return statusToFestivals.entrySet().stream()
            .sorted(comparing(entry -> getStatusOrder(entry.getKey())))
            .flatMap(entry -> entry.getValue().stream())
            .toList();
    }

    private Comparator<FestivalSearchV1Response> getFestivalComparatorByStatus(FestivalFilter status) {
        return switch (status) {
            case PLANNED -> comparing(FestivalSearchV1Response::endDate)
                .thenComparing(FestivalSearchV1Response::id);
            case PROGRESS, END -> comparing(FestivalSearchV1Response::startDate).reversed()
                .thenComparing(FestivalSearchV1Response::id);
        };
    }

    private int getStatusOrder(FestivalFilter status) {
        return switch (status) {
            case PROGRESS -> 0;
            case PLANNED -> 1;
            case END -> 2;
        };
    }
}
```

2024-05-02 13:12 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/application/FestivalSearchV1QueryService.java
>      }
👍👍
추가로 `.thenComparing(FestivalSearchV1Response::id)` 추가해서 일정이 같은 축제의 경우 두 번째 정렬 조건을 추가해줄 수 있을 것 같네요!

2024-05-02 13:12 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/application/FestivalSearchV1QueryService.java
> +    }
해당 함수 대신 `FestivalFilter.values()`를 사용할 수 있을 것 같은데..
사용하지 않으신 이유가 있을까요?
만약, 있으시다면 해당 리스트를 static으로 만들어 사용해도 될 것 같네요!

2024-05-02 13:12 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/application/FestivalSearchV1QueryService.java
> +    }
줄바꿈을 다음과 같이 사용하는건 어떤가요?
```suggestion
    private Map<FestivalFilter, List<FestivalSearchV1Response>> divideByStatus(
        List<FestivalSearchV1Response> festivals
    ) {
        return festivals.stream()
            .collect(Collectors.groupingBy(
                this::determineStatus,
                () -> new EnumMap<>(FestivalFilter.class),
                Collectors.toList()
            ));
    }
```

2024-05-02 13:12 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/application/FestivalSearchV1QueryService.java
> +                new ArrayList<>());
반환되는 리스트에 변경이 없다면 `Collections.emptyList()`를 사용해도 좋을 것 같네요!
```suggestion
            List<FestivalSearchV1Response> festivalsByFilter = festivalByStatus.getOrDefault(festivalFilter,
                Collections.emptyList());
```

2024-05-07 06:17 UTC, BGuga commented on backend/src/main/java/com/festago/festival/application/FestivalSearchV1QueryService.java
> +    }
이거 values를 쓸까 고민했는데 FestivalFilter에서 적힌 순서가 정렬 순서라는게 명시적이지 않은 것이라 생각하여 후에 순서를 변경할 수 있다 생각했습니다!! 그래서 정렬이 필요한 곳에서 정렬 조건을 정의하고자 순서를 명시해줬네요

2024-05-15 06:13 UTC, merged