[BE] feat: AppleOpenIdClient를 추가한다.(#931)
woowacourse-teams/2023-festa-go pull request #962
Opened 2024-05-11 18:21 UTC by BGuga

## 📌 관련 이슈

- closed: #931

## ✨ PR 세부 내용

1. AppleOpenIdClient 구현

구조나 테스트 부분에서 KakaoOpenIdClient 를 참고하여 구현하였습니다.
넘어온 OpenId 이 정상적인 값인지 확인하기 위해서는 다음 단계가 필요합니다. [[출처](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/verifying_a_user)]

```
1. Verify the JWS E256 signature using the server’s public key
2. Verify the nonce for the authentication
3. Verify that the iss field contains https://appleid.apple.com
4. Verify that the aud field is the developer’s client_id
5. Verify that the time is earlier than the exp value of the token
```
1번은 기존에 있던 KakaoOpenIdPublicKeyLocator 와 동일한 구조를 가진 AppleOpenIdPublicKeyLocator 를 정의해였습니다.
2번은 생략하였습니다.
3,5 번은 JwtParser 를 통해 검증합니다.
4번은 저희의 client-Id와 같은지 validateAudience 메서드를 통해 직접 비교하였습니다.

2. 기본 닉네임 정책

OpenId의 payload는 다음과 같은 값들이 들어있습니다.
```
iss
sub
aud
iat
exp
nonce
nonce_supported
email
email_verified
is_private_email
real_user_status
transfer_sub
```
주목할 점은 UserInfo를 만들기 위한 nickname과 profile을 가지고 있지 않습니다.
따라서 UserInfo를 통해 Member를 만드는 과정에서 nickname이 지정되지 않은 상황에 대한 처리가 필요했는데 이는 profile과 동일하게 Member 도메인 내에서 기본 nickname을 생성하게 하였습니다.

3. 그 외
infrastructure 내에 class 가 너무 많은 것 같아서 oauth2 와 openid 패키지를 나눠 구분하였습니다.
UploadFile의 getUploadUri 가 "https://festago.com2077-06-30/aff16d97-089f-4558-b999-9e5fba54ed8b.png" 처럼 "https://festago.com" 뒤에 "/"가 추가 되지 않아 테스트가 실패하여 추가해주었습니다.

2024-05-11 18:42 UTC, seokjin8678 requested changes
고생하셨습니다 푸우!
조금 기간이 늦어진 것 같지만.. 별도의 사정이 있었다고 믿겠습니다. 😂
리뷰에 남긴 `CachedOpenIdKeyProvider` 관련만 수정해주시면 될 것 같습니다.
고생하셨어요!!

2024-05-11 18:42 UTC, seokjin8678 commented on backend/src/main/java/com/festago/member/domain/Member.java
> +    private static final String DEFAULT_NICKNAME = "FestivalLover";
🥰

2024-05-11 18:42 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/infrastructure/openid/CachedAppleOpenIdKeyProvider.java
해당 클래스를 생성해서 사용하지 않고 기존 `CachedOpenIdKeyProvider` 클래스를 사용하는게 어떤가요?
`kid`가 겹칠 일이 없습니다..! (확률적으로 매우 매우 드뭄)

2024-05-11 18:42 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/infrastructure/openid/AppleOpenIdPublicKeyLocator.java
> +    private final CachedAppleOpenIdKeyProvider cachedOpenIdKeyProvider;
마찬가지로 `CachedOpenIdKeyProvider` 사용하면 될 것 같습니다..!

2024-05-11 18:42 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/infrastructure/openid/AppleOpenIdClient.java
> +    }
Apple의 경우 audiece 값이 하나로 쓰일 것 같아, 굳이 추가로 validation 로직을 만들지 않고 `idTokenParser`를 생성할 때 다음과 같이 `requireAudience()`를 사용할 수 있을 것 같네요!
```java
this.idTokenParser = new OpenIdIdTokenParser(Jwts.parser()
    .keyLocator(appleOpenIdPublicKeyLocator)
    .requireAudience(audience)
    .requireIssuer(ISSUER)
    .clock(() -> Date.from(clock.instant()))
    .build());

2024-05-11 18:42 UTC, seokjin8678 commented on backend/src/main/java/com/festago/member/domain/Member.java
> +        this.nickname = (StringUtils.hasText(nickname)) ? nickname : DEFAULT_NICKNAME;
기본 닉네임 정책을 무엇으로 해야할지... 고민이네요 😂

2024-05-11 18:42 UTC, seokjin8678 commented on backend/src/main/java/com/festago/upload/domain/UploadFile.java
>      }
저는 테스트에서 따로 실패한 곳이 없었는데, 어떤 테스트에서 실패하시던가요??

2024-05-11 18:42 UTC, seokjin8678 commented on backend/src/main/java/com/festago/auth/infrastructure/oauth2/FestagoOAuth2Client.java
> +package com.festago.auth.infrastructure.oauth2;
안그래도 해당 이슈 처리되면 패키지를 나눌까 생각하고 있었는데, 알잘딱하게 해주셨네요 👍👍

2024-05-11 18:42 UTC, seokjin8678 commented on backend/src/test/java/com/festago/auth/infrastructure/openid/AppleOpenIdClientTest.java
> +
🦅

2024-05-12 13:18 UTC, seokjin8678 commented
일요일까지 처리했어야 하는 기능이므로, 리뷰 반영 없이 우선 머지 처리 하도록 하겠습니다!
리뷰에 답글은 닫힌 PR에 달아주시고, 새로운 이슈로 파서 PR 재요청 부탁드립니다!

2024-05-12 13:19 UTC, merged

2024-05-16 03:11 UTC, BGuga commented on backend/src/main/java/com/festago/member/domain/Member.java
> +        this.nickname = (StringUtils.hasText(nickname)) ? nickname : DEFAULT_NICKNAME;
회의때 이야기한 내용으로 갈게요!