[BE] feat: 라인업이 공개된 축제가 인기 라인업으로 검색되게 변경 (#971)
woowacourse-teams/2023-festa-go pull request #973
Opened 2024-05-15 14:15 UTC by BGuga

## 📌 관련 이슈

- closed: #971 

## ✨ PR 세부 내용

간단하게 FestivalQueryInfo가 "[]"가 아닌 것으로 반환하도록 변경했습니다

2024-05-15 15:12 UTC, seokjin8678 requested changes
고생하셨습니다!
추가로 끝난 축제가 조회되지 않게 조건을 추가하는게 좋을 것 같네요!

2024-05-15 15:12 UTC, seokjin8678 commented on backend/src/main/java/com/festago/festival/repository/PopularFestivalV1QueryDslRepository.java
> +            .where(festivalQueryInfo.artistInfo.ne("[]"))
끝난 축제가 보인다는 피드백이 있어서, 해당 내용도 반영해야 할 것 같네요!
```java
.where(festival.festivalDuration.endDate.gt(now)
                .and((festivalQueryInfo.artistInfo.ne("[]"))))
```

2024-05-16 02:51 UTC, BGuga commented on backend/src/main/java/com/festago/festival/repository/PopularFestivalV1QueryDslRepository.java
> +            .where(festivalQueryInfo.artistInfo.ne("[]"))
반영했습니다!

2024-05-16 05:49 UTC, seokjin8678 approved these changes
고생하셨습니다!

2024-05-16 06:00 UTC, merged