[BE] feat: AppleOpenId 로직 리팩터링(#975)
woowacourse-teams/2023-festa-go pull request #976
Opened 2024-05-16 03:10 UTC by BGuga

## 📌 관련 이슈

- closed: #975 

## ✨ PR 세부 내용

해당 [PR](https://github.com/woowacourse-teams/2023-festa-go/pull/962) 리뷰 적용하였습니다

2024-05-16 06:07 UTC, seokjin8678 requested changes
고생하셨습니다!
빈 스코프를 `prototype`으로 사용해서, 락 경합이 분리되어 더욱 최적화가 되었네요!
`AppleOpenIdPublicKeyLocatorTest`에 대해 리뷰 남겼으니, 확인 부탁합니다!

2024-05-16 06:07 UTC, seokjin8678 commented on backend/src/test/java/com/festago/auth/infrastructure/openid/AppleOpenIdPublicKeyLocatorTest.java
> +}
비즈니스 로직의 검증이 아닌, 스프링 프레임워크의 동작에 관한 검증에 대한 테스트 같네요!
해당 테스트가 필요하다고 생각하신 이유가 있을까요?

2024-05-16 06:41 UTC, BGuga commented on backend/src/test/java/com/festago/auth/infrastructure/openid/AppleOpenIdPublicKeyLocatorTest.java
> +}
사실 필요없지만 prototype을 직접 사용한건 처음이라 한번 검증차에서 구현해본 것을 남겼습니다!!
검증 됬으니 지우겠습니다!

2024-05-22 14:15 UTC, seokjin8678 approved these changes

2024-05-22 14:19 UTC, merged